Mapping/ClassMetadata.php
Tests/Behat/TestBundle/Entity/Dummy.php
features/collection.feature
features/crud.feature
features/vocab.feature

By looking for getters and setters to determine if a property is readable and/or writable, we're able to easily detect non-writable fields such as entities' `id`.

Guess non writable attributes

---

DependencyInjection/DunglasJsonLdApiExtension.php

When the `framework.serializer.enabled` configuration is not explicitly to `true`, the `serializer` service won't be able and controller will fail trying to get it from container.
To improve DX, this prepend configuration will enable the `serializer` service if configuration is not explicitly defined.

Prepend serializer configuration when not enabled

---

Controller/DocumentationController.php
Controller/ResourceController.php
EventListener/RequestExceptionListener.php
Exception/DeserializationException.php
Resources/config/api.xml
Serializer/ErrorNormalizer.php
Serializer/JsonLdNormalizer.php
features/error.feature

This PR add support of `Exception` serialization into `hydra:Error` objects. 
It also add checks the types of given objects for relations and eventually throw exceptions in case of error.

Exception serialization to `hydra:Error`

---

JsonLd/ContextBuilder.php
Resources/config/api.xml
Serializer/CollectionNormalizer.php
Serializer/DateTimeNormalizer.php
Serializer/JsonLdNormalizer.php
Serializer/ResourceResolver.php
features/relation.feature

This PR fixes #9: it splits the `JsonLdNormalizer` by creating two new normalizers:
- `CollectionNormalizer` that handles collections
- `DateTimeNormalier` that just handle `DateTime` objects
A new `ResourceResolver` class is also created to extract the resource guessing from normalizers and use that resolver in normalizers.

Explode JsonLdNormalizer into smaller ones

---

Doctrine/Orm/Paginator.php
Model/PaginatorInterface.php

The `getMembers` method of `PaginatorInterface` is not used because the interface extends `Traversable`.
This PR simply remove it and its implementation in Doctrine ORM paginator.

Remove `PaginatorInterface::getMembers` since it's not used

---

Resources/config/routing.xml

Right now, short names of resources can't contain a slash and this PR fixes that issue.

Allow shortName to contain a slash

---

Serializer/ItemNormalizer.php
Serializer/ResourceResolver.php
Tests/Behat/TestBundle/Entity/UnknownDummy.php
features/error.feature
features/relation.feature
features/vocab.feature

This add a check on resolved resources: it must match the object type, and resource don't come directly from the normalization context.
That's way we can display an explicit error message instead of having strange "unknown properties" errors.

Check that resolved resource is matching the object type

---

Api/Filter/FilterInterface.php
Controller/ResourceController.php
Doctrine/Orm/DataProvider.php
Doctrine/Orm/Filter.php
Doctrine/Orm/FilterInterface.php
Model/DataProviderChain.php
Model/DataProviderInterface.php
README.md
Resources/config/doctrine_orm.xml
features/fixtures/TestApp/config/config.yml

- Easier way to define multiple filters
- Possibility to enable filter on all fields of an entity
Finally I've abandoned the idea of using LoopBack style URLs because they are too ugly.
As `page` and `itemsPerPage` parameters are now configurable, conflicts can be easily avoided (ex: using an URLs like `?_page=2&_itemsPerPage=3`).
@theofidry @sroze What do you think about that? And what do you think about forwarding `$request` to `DataProvider` and `Filter` class? It's not very clean but it's powerful and useful when creating custom filters.

New filter API

---

Api/Filter/FilterInterface.php
Doctrine/Orm/Filter.php
Hydra/Serializer/CollectionNormalizer.php
features/collection.feature
features/crud.feature
features/relation.feature

This PR add support for the [hydra:search](http://www.hydra-cg.com/spec/latest/core/#hydra:search) property. It adds filters auto-documentation in the Hydra format to the bundle. It also add supports for RFC 6570 and [Hydra Templated Links](http://www.hydra-cg.com/spec/latest/core/#templated-links).

Hydra search support

---

JsonLd/Serializer/ItemNormalizer.php

The nameConverter was used in denormalisation but not in normalisation.
This PR call the nameConverter to normalise attributeName in the normalisation process.

Normalize attributeName

---

Resources/config/json_ld.xml
Resources/doc/serialization-groups-and-relations.md

Actualy, injecting a nameConverter is quite complicated.
- Redefining the service or creating a new one with a higher priority
```
<service id="my_custom.normalizer.item" class="Dunglas\ApiBundle\JsonLd\Serializer\ItemNormalizer" public="false">
<argument type="service" id="api.resource_collection" />
<argument type="service" id="api.iri_converter" />
<argument type="service" id="api.mapping.class_metadata_factory" />
<argument type="service" id="api.json_ld.context_builder" />
<argument type="service" id="property_accessor" />
<argument type="service" id="my_custom.nameConverter" />
<tag name="serializer.normalizer" />
</service>
```
Or creating a CompilerPass
```
public function process(ContainerBuilder $container)
{
if (!$container->hasDefinition('api.json_ld.normalizer.item')) { …
```

Simplify injection of nameConverter

---

Doctrine/Orm/DateFilter.php
Doctrine/Orm/OrderFilter.php
Resources/config/doctrine_orm.xml
Resources/doc/filters.md
Tests/Behat/TestBundle/Entity/Dummy.php
Tests/Doctrine/Orm/DateFilterTest.php
features/bootstrap/FeatureContext.php
features/collection-date-filter.feature
features/collection-order-filter.feature
features/collection.feature
features/context.feature
features/crud.feature
features/fixtures/TestApp/config/config.yml
features/relation.feature
features/vocab.feature

Add date filter support as requested in #46.
`?property[<before|after>]=value`
Where the period `before` or `after` is case insensitive and `value` a valid string for instantiate a `\DateTime()`.
```yaml
services:
ressource.date_filter:
parent:    "api.doctrine.orm.date_filter"
arguments: [ ["dateProperty"] ]
ressource.date_filter:
parent:    "api.doctrine.orm.date_filter"
arguments: [ ["dateProperty"] ]
```
Even if both search filter and date filter are enabled on all properties there is no conflict possible.

Date filter

---

Hydra/Serializer/CollectionNormalizer.php
Tests/Behat/TestBundle/Entity/Dummy.php
features/collection-date-filter.feature
features/collection-order-filter.feature
features/collection.feature
features/context.feature
features/crud.feature
features/relation.feature
features/vocab.feature

I'm not sure, i'm using the right way to do that, but, here is my problem.
I store complexe data in a field typed `json_array`. This data could be string, array, or object (json object == array(key =>value). 
This PR juste reuse the array key in the normalized data.
Tel me if you see an other way to do that.

Use object index in serialized data

---

Resources/doc/getting-started.md

The [`Range`](http://symfony.com/doc/current/reference/constraints/Range.html) constraint only supports `minMessage` and `maxMessage` but no `message` option, so this sample was wrong.

Fix Range constraint in getting-started.md example

---

Doctrine/Orm/DateFilter.php
Tests/Doctrine/Orm/DateFilterTest.php
features/bootstrap/FeatureContext.php
features/collection-date-filterr.feature
features/fixtures/TestApp/config/config.yml

If we do a DQL query like `dummy.dummyDate <= :dateValue`, if `dummyDate` is null it will match this criteria. However a date field at null is often used to define an undetermined future date, i.e. a NULL date is expected to be higher than any date.
However I'm still concerned that some may which to keep a null date value as the lower value possible for a date. @dunglas what do you think? Should we add another parameter to configure this?
Also removed some duplication in code.

Null date are now after any date.

---

Routing/Router.php

Fix issues when using the `app_dev.php` front controller, or any other base url.
For instance, if my project is accessible from the `localhost://my-project/` (when I'm too lazy for a proper vhost),  route generation was wrong.
I get stuck a while trying to get working the HydraConsole with one project, whereas I didn't get any issue on another one previously.
I saw the [commit](https://github.com/dunglas/DunglasApiBundle/commit/6986a4bb27ce0dac3ff48287df785204c8144add) introducing this Router decorator, but actually, I don't understand why is the baseUrl set to an empty string (and what's the purpose of this decorator ?).
As a witness, as I don't know much about Json-ld and Hydra yet, I tried the [Hydra Demo App](https://github.com/lanthaler/sfHydraDemoApp), and the api entrypoint …

Use baseUrl within Router decorator

---

Resources/config/hydra.xml
Resources/config/json_ld.xml
Routing/Router.php

I forgot about this https://github.com/dunglas/DunglasApiBundle/pull/90#issuecomment-108009124 until now, and I indeed tried to replace the decorator by the Symfony router. Tests failed, as predicted.
But, actually, it only fails when trying to match a route, not generating one. So we can rely on the Symfony router and eliminate some unnecessary code.
Also, `match` method is only used within the `IriConverter` service, so it is the only one where we need to inject the decorator for now.
IMO, the decorator name and service name should reflect the issue. But honestly, I was unable to fully understand what is wrong with the Symfony router `match` method in our case (Overriding the method to `GET` in the context isn't sufficient for instance).
Do you have any idea about that, and naming …

Simplify router decorator & use real router where not needed

---

JsonLd/Serializer/ItemNormalizer.php

This PR fix the following bug:
It's impossible to denormalize attributes in groups which are not allowed in normalization..

Fix denormalize allowedAttributes

---

JsonLd/Serializer/ItemNormalizer.php

The same as #118, but for denormalization
(sorry for the double PR)

Keep indexes when deserializing data

---

Resources/doc/the-event-system.md

Just fix a class namespace :
``Dunglas\ApiBundle\Event\DataEvent`` instead of ``use Dunglas\JsonApiBundle\Event\DataEvent``

Fix a doc typo

---

Hydra/Serializer/CollectionNormalizer.php
JsonLd/ContextBuilder.php
JsonLd/Serializer/ItemNormalizer.php
Resources/doc/serialization-groups-and-relations.md

Quoting http://www.w3.org/TR/json-ld/#the-context :
"Contexts can either be directly embedded into the document or be referenced"
This PR add the ability to embed the context.

Provide the ability to embed the context instead of reference it

---

composer.json

To avoid a blocking bug when using the cache (symfony/symfony#15176)

Require Symfony Serializer 2.7.2

---

Controller/HydraController.php
Resources/config/routing/hydra.xml
features/bootstrap/HydraContext.php
features/custom_identifier.feature
features/custom_normalized.feature
features/custom_writable_identifier.feature
features/hydra/doc.feature
features/json-ld/context.feature

As advised by @lanthaler on the Hydra mailing list.
Also fix a typo.

Rename /vocab to /apidoc

---

Resources/doc/content-negotiation.md

Fix typo in content-negociation.md

---

Doctrine/EventListener/ManagerViewListener.php
EventListener/FormatRequestListener.php
EventListener/ResourceTypeRequestListener.php
EventListener/ValidationViewListener.php
Hydra/EventListener/LinkHeaderResponseListener.php
Hydra/EventListener/RequestExceptionListener.php
JsonLd/EventListener/ResponderViewListener.php
Tests/Behat/TestBundle/EventListener/XmlResponderViewListener.php

Should we really limit those listeners to master requests ?
Here is my use case:
We have a BulkRequest system that allows to execute multiple requests at once, through a payload describing requests to execute.
This system directly use the `kernel` and sub requests to handle the described requests and gather their responses to be finally sent in a single one to the client.
This system won't work anymore with the latest version of the api bundle.

Allow listeners execution for subrequests

---

Hydra/ApiDocumentationBuilder.php
JsonLd/EntrypointBuilder.php
Tests/Behat/TestBundle/Entity/NoCollectionDummy.php
features/fixtures/TestApp/config/config.yml
features/hydra/doc.feature
features/json-ld/context.feature

Here is the PR for the #203 issue without introducing BC Breaks
For now, hydra doc is still generated for collection but with empty supportedOperations. I don't know if it is correct.

Fix entry point builder

---

Doctrine/Orm/Filter/SearchFilter.php
Tests/Doctrine/Orm/SearchFilterTest.php

If you have a relation `Product.order` and you want to add a filter on it, the generated DQL will be:
```sql
SELECT p FROM Product p INNER JOIN p.order order WHERE order.id = :order
```
As order is a reserved keyword, I added an `_` after the alias to avoid this case:
```sql
SELECT p FROM Product p INNER JOIN p.order order_ WHERE order_.id = :order
```

Fix error in DQL generation for reserved SQL keywords

---

FosUser/EventListener.php

The `UserManager::deleteUser` does not take a second parameter and do the persist + flush right away so it would not make much sense to no do the flush with the update too.

Remove useless arguments

---

Action/ActionUtilTrait.php

Re-add the default message `Not Found` into the thrown `NotFoundHttpException`, as it was the case previously when using the framework bundle `Controller::createNotFoundException()`.
Otherwise, the generated response in the api looks like : 
```json
{
"@context": "/api/contexts/Error",
"@type": "Error",
"hydra:title": "An error occurred",
"hydra:description": ""
}
```
Instead of:
```json
{
"@context": "/api/contexts/Error",
"@type": "Error",
"hydra:title": "An error occurred",
"hydra:description": "Not Found"
}
```

Re-add default message to NotFoundHttpException

---

Doctrine/Orm/DataProvider.php

This improves query performance by a huge margin, when using eager collections with Doctrine.
This PR should be merged in 1.0, and merged back in the master branch, if possible.
Before patch:
After patch:

Added support for eager-loading associations in collections

---

Doctrine/Orm/DataProvider.php

As mentioned before. If there are no items in the target table of the relation, then these items won't appear in the collection (try disabling the `$fetchJoinCollection` parameter in the Doctrine paginator, and you'll see that the result won't be the expected result).

Fixed issue with join being inner instead of left join

---

composer.json

This prevents people from using `1.0@dev` or `dev-1.0` in order to fetch content from the `1.0` branch.

Increment version for branch-alias

---

DependencyInjection/Compiler/DataProviderPass.php
DependencyInjection/Configuration.php
DependencyInjection/DunglasApiExtension.php
Resources/config/doctrine_orm.xml
Resources/config/mapping.xml
Resources/config/property_info.xml
Tests/DependencyInjection/Compiler/DataProviderPassTest.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/DunglasApiExtensionTest.php
composer.json

For now it's not possible to use Api Platform without doctrine easily as the doctrine service is used to declare several services.

Add an option to totally disable doctrine support

---

Api/IriConverterInterface.php

The DataProvider can return `null`, (specified in [`DataProviderInterface`](https://github.com/dunglas/DunglasApiBundle/blob/master/Model/DataProviderInterface.php#L30)), so it's only logical that the [`IriConverterInterface`](https://github.com/dunglas/DunglasApiBundle/blob/master/Api/IriConverterInterface.php#L30) does the same. Also from the current implementation of [`SearchFilter::getFilterValueFromUrl()`](https://github.com/dunglas/DunglasApiBundle/blob/master/Doctrine/Orm/Filter/SearchFilter.php#L190-L192) rely on this result.
Can also be merged back to the 1.0.

Fix IriConverterInterface return value

---

JsonLd/Serializer/DateTimeNormalizer.php
Tests/Behat/TestBundle/Entity/Dummy.php
features/invalid_data.feature

Need a mention in the doc explaining that you **must** always allow `null` values in `\DateTime` typehints and use a validator assertion if `null` values must thrown an error.

Better DateTime invalid format handling.

---

Api/Resource.php
Api/ResourceInterface.php
EventListener/ValidationViewListener.php
Mapping/Loader/ValidatorMetadataLoader.php
Tests/EventListener/ValidationViewListenerTest.php
Tests/Mock/ValidationGroupsResolverInterface.php

Continuing from #250...
I've found out that [group sequence providers](http://symfony.com/doc/current/book/validation.html#group-sequence-providers) do not handle cascade well:
symfony/symfony#3622
symfony/symfony#9650
symfony/symfony#11880
symfony/symfony#15666
According to [JSR303](http://beanvalidation.org/1.0/spec/#constraintdeclarationvalidationprocess-validationroutine-graphvalidation):
> Note however that the Default group sequence overriding is local to the class it is defined on and is not propagated to the associated objects.
(Also see Example 3.12 under the same section)
So a callback to determine the validation groups seems to be the solution...

Support GroupSequence and callable for validation groups

---

Doctrine/Orm/Paginator.php
Tests/Doctrine/Orm/PaginatorTest.php
Tests/Fixtures/Query.php

When we use paginated data in several places (through events for instance), queries are re-issued every time we iterate on `DataEvent::getData()`.
It would be nice if the iterators were cached.

Cache paginator iterator

---

.travis.yml
composer.json

This PR adds symfony 3.0 support by changing the constraint of ``symfony/proxy-manager-bridge`` and adding a new build to the ``.travis.yml``.

Add Symfony 3.0 support

---

DependencyInjection/Configuration.php

``NumericNodeDefinition::cannotBeEmpty()`` is deprecated since symfony 2.8. See https://github.com/symfony/symfony/pull/15170

Remove the usage of NumericNodeDefinition::cannotBeEmpty()

---

Tests/Behat/TestBundle/EventListener/XmlResponderViewListener.php
features/bootstrap/FeatureContext.php
features/content_negotiation.feature
features/fixtures/TestApp/config/config.yml
features/fixtures/TestApp/config/security.yml

Escape backslashes else it's considered as unicode character

---

Api/IriConverter.php
Api/Operation/OperationFactory.php
Api/Resource.php
Api/RoutedResourceInterface.php
Tests/Api/Operation/OperationFactoryTest.php

Unable  to test because base tests fails, but this is working as expected in my project.
This PR allows to define route requirements to custom operations : 
```yml
resource.person.item_operation.get_me:
class:   "Dunglas\ApiBundle\Api\Operation\Operation"
public:  false
factory: [ "@api.operation_factory", "createItemOperation" ]
arguments:
-    "@resource.person"       # Resource
-    [ "GET" ]                # Methods
-    "/people/{id}"           # Path
-    "AppBundle:Person:getMe" # Controller
-    "api_people_get_me"      # Route name
-    { id: "me|\d" }          # …
```

Ability to set route requirements, and define which route should be used for @id generation

---

Doctrine/Orm/Filter/DateFilter.php
features/doctrine/date-filter.feature

| Bug fix?      | may be
| BC breaks?    | may be
Actually when we use DateFilter, if we send an empty parameter `property[before]=`, doctrine will convert it to current date (`new \Datetime('')`). This is annoying for a filtering behaviour, empty params should be ignored. 
If we want use currentDate in DateFilter, we can use `now` string.

[RFR] Fixing date filter to not consider empty string as a current date

---

JsonLd/Serializer/ItemNormalizer.php
features/invalid_data.feature

| Fixed tickets | #394, #393 
@dylanjacob, can you try if this PR fix your problem? If it's not the case, can you add a failing test because I wasn't able to reproduce for now.

Fix a bug when a JSON key is empty

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/app/config/config.yml

See http://symfony.com/doc/current/best_practices/business-logic.html#services-naming-and-format
Also added `name_converter` in config, instead of using magic hard-coded `api_platform.name_converter` service id (same method as how `DoctrineBundle` handles `naming_strategy`).
Check for `DoctrineBundle` before loading `doctrine_orm.xml`, because the existence of `doctrine/orm` doesn't mean such services are available.

Rename services in test app

---

.travis.yml

As [GitHub removed their hourly API rate limit](https://github.com/composer/composer/issues/4884#issuecomment-195229989), we can remove this now.

Remove Composer authentication

---

composer.json
src/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProvider.php
src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/nelmio_api_doc.xml
src/Bridge/Symfony/Routing/OperationMethodResolver.php
src/Bridge/Symfony/Routing/OperationMethodResolverInterface.php
tests/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProviderTest.php
tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| Fixed tickets | #219
Continuation of #225
Includes fix for nelmio/NelmioApiDocBundle#678

Import AnnotationsProvider & Parser from NelmioApiDocBundle

---

src/Api/CollectionDataProviderInterface.php
src/Api/ItemDataProviderInterface.php

I find the current very restrictive: it only allows an item provider to throw exceptions when it does not support the class or received an incorrect value. As the responsibility of an item provider is to retrieve an item from the persistent layer, it looks to me that there could be all kind of other problems: could not establish a connection with the persistence layer, the item could not be retrieve, etc.
If someone wants to add a custom provider implementing this interface and have to face one of the situation above, he will have little choice but to return `null`. IMO, …

Allow ItemDataProvider to throw more exceptions

---

composer.json
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Bridge/Symfony/Bundle/Resources/config/metadata.xml
src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php
src/Metadata/Property/Factory/CachedPropertyNameCollectionFactory.php
src/Metadata/Resource/Factory/CachedResourceMetadataFactory.php
src/Metadata/Resource/Factory/CachedResourceNameCollectionFactory.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| Fixed tickets | #468
Add PSR6 cached decorators for all metadata factories.
Also provide `symfony/cache` integration in the Symfony bundle.

Add metadata caching

---

src/JsonLd/Serializer/ContextTrait.php

No such keys as `item_operation` and `collection_operation` in the `$context`.
I assume the intended keys to be unset are `item_operation_name` and `collection_operation_name`?

Fix typo in ContextTrait::createRelationContext

---

src/Hydra/Serializer/PartialCollectionViewNormalizer.php
tests/Hydra/Serializer/PartialCollectionViewNormalizerTest.php

Please look at the comment [here](https://github.com/api-platform/core/pull/419#issuecomment-199690736) as I think it makes sense to show `hydra:totalItems` even when filter is applied.

Show hydra:totalItems even filter is applied

---

src/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactory.php

#452 erroneously renamed `AnnotationPropertyNameCollectionFactory` to `AnnotationPropertyCollectionMetadataFactory`. The actual problem was the file not being renamed to match the class name change (introduced by #436)

Fix wrong renaming introduced in #452

---

src/Util/RequestParser.php

`Request::getQueryString` may return `null`.

Fix an issue in RequestParser when the query string is null

---

src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php

Bugs from #410 when porting the parser
- Correct identification of embedded / non-embedded resources
- Handle non-resource objects

Fix data type for NelmioApiDoc

---

features/bootstrap/FeatureContext.php
features/composite.feature
features/json-ld/context.feature
src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
src/Bridge/Doctrine/Orm/Util/QueryChecker.php
tests/Fixtures/TestBundle/Entity/CompositeItem.php
tests/Fixtures/TestBundle/Entity/CompositeLabel.php
tests/Fixtures/TestBundle/Entity/CompositeRelation.php

Adds a behat test on a complex composite identifier case
Fix the collection retrieval of a resource made of composite identifiers

Fix and test composite identifier collection retrieval

---

Resources/config/routing/hydra.xml
Resources/config/routing/json_ld.xml

Minor semantic fix. I suppose these are meant to be GET routes rather than to match ANY.

Routes should be GET only

---

features/hydra/error.feature
src/Bridge/Symfony/Validator/Hydra/Serializer/ConstraintViolationListNormalizer.php

For example, with 1 constraint violation, actual output is:
```json
{
"@context": "/contexts/ConstraintViolationList",
"@type": "ConstraintViolationList",
"hydra:description": "underNameCustomer Company must be the same than meal.restaurant Company.\n"
}
```
With this fix:
```json
{
"@context": "/contexts/ConstraintViolationList",
"@type": "ConstraintViolationList",
"hydra:description": "underNameCustomer Company must be the same than meal.restaurant Company."
}
```

Prevent extra break line at the end of violations list normalization

---

features/json-ld/context.feature

I've modified the test with the other commit this one is to fix the tests

Fix travis test

---

Hydra/Serializer/CollectionNormalizer.php
Util/RequestParser.php
features/doctrine/date-filter.feature

| Fixed tickets | #509
Fix the dots to underscore

[V1] fix #509 - php's parse str does not allow dots

---

features/doctrine/date-filter.feature
src/Hydra/Serializer/PartialCollectionViewNormalizer.php
src/Util/RequestParser.php

| Fixed tickets | #509 
Does not use php's parse_str wich does not allow dots, based on what is using guzzle to parse http query.

[V2.x] fix #509 - php's parse str does not allow dots

---

features/json-ld/context.feature

This adds a workaround for #454 in `context.feature` (which usually fails in some people's local dev environments...)

Add a workaround for #454 in context.feature

---

features/doctrine/order-filter.feature
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml

Fix the priority of Doctrine query extensions (`OrderExtension` must go before `PaginationExtension`, or it will never be run). Also fixed Behat tests for `OrderFilter` (the JSON schema was not testing the right things - *gosh, I really hate JSON Schema*).

Doctrine query extensions priority

---

src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Bridge/Symfony/Bundle/Resources/config/metadata.xml

This allows better control (ordering) of custom decorators, e.g. a custom decorator with the default priority of 0 would fall right after all the built-in decorators but before the `cached` decorator... So that's the expected behaviour out of the box.

Set priority of metadata factories

---

src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
src/Bridge/Doctrine/Orm/Filter/RangeFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php

| Fixed tickets | no
Since the last commit with both boolean and numeric filters, scrutinizer does not like duplicated code.
And a foreach that scrutinizer does not like.

Fix Dupplication code on Filters

---

features/invalid_data.feature
src/JsonLd/Serializer/ItemNormalizer.php

| Fixed tickets | #518
| Doc PR        | 0
According to the normalizer, we could not pass  a string to one relation.
@teohhanhui is it ok like this ? not sure about the message

fix #518 - Add an exception to show that the value is not readable. 

---

features/bootstrap/FeatureContext.php
features/configurable.feature
features/json-ld/context.feature
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/metadata.xml
src/Metadata/Resource/Factory/XmlResourceMetadataFactory.php
src/Metadata/Resource/Factory/XmlResourceNameCollectionFactory.php
src/Metadata/Resource/Factory/YamlResourceMetadataFactory.php
src/Metadata/Resource/Factory/YamlResourceNameCollectionFactory.php
src/schema/metadata.xsd
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Controller/ConfigCustomController.php
tests/Fixtures/TestBundle/Entity/FileConfigDummy.php
tests/Fixtures/TestBundle/Resources/config/resources.yml
tests/Fixtures/app/config/config.yml
tests/Fixtures/resourcenotfound.xml
tests/Fixtures/resourcenotfound.yml
tests/Fixtures/resources.xml
tests/Fixtures/resources.yml
tests/Fixtures/resourcesinvalid.xml
tests/Fixtures/resourcesoptional.xml
tests/Fixtures/resourcesoptional.yml
tests/Metadata/Resource/Factory/FileConfigurationMetadataTest.php

| Fixed tickets | #421
| Doc PR        | https://github.com/api-platform/doc/pull/42
TODO:

File resource configuration (xml,yml) 

---

tests/Metadata/Resource/Factory/FileConfigurationMetadataTest.php

Just saw that travis emits a warning `$resourceMetadata->withShortname(null);` weird that I didn't see it on my local environment.

Fix warning test ResourceMetadata with null values

---

features/bootstrap/FeatureContext.php
features/composite.feature
features/uuid.feature
src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/Bridge/Symfony/Routing/IriConverter.php
tests/Fixtures/TestBundle/Entity/CompositeRelation.php
tests/Fixtures/TestBundle/Entity/UuidIdentifierDummy.php

| Fixed tickets | #530 
This is WIP 
Edit : This is ok for review

#530 ~ Add behat test and change behavior of ItemDataProvider for uuid

---

src/Annotation/ApiResource.php
src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
src/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php
src/Metadata/Resource/Factory/XmlResourceMetadataFactory.php
src/Metadata/Resource/Factory/XmlResourceNameCollectionFactory.php
src/Metadata/Resource/Factory/YamlResourceMetadataFactory.php
src/Metadata/Resource/Factory/YamlResourceNameCollectionFactory.php
tests/Annotation/ApiResourceTest.php
tests/Fixtures/TestBundle/Entity/AbstractDummy.php
tests/Fixtures/TestBundle/Entity/CircularReference.php
tests/Fixtures/TestBundle/Entity/CompositeItem.php
tests/Fixtures/TestBundle/Entity/CompositeLabel.php
tests/Fixtures/TestBundle/Entity/CompositeRelation.php
tests/Fixtures/TestBundle/Entity/ConcreteDummy.php
tests/Fixtures/TestBundle/Entity/CustomIdentifierDummy.php
tests/Fixtures/TestBundle/Entity/CustomNormalizedDummy.php
tests/Fixtures/TestBundle/Entity/CustomWritableIdentifierDummy.php
tests/Fixtures/TestBundle/Entity/Dummy.php
tests/Fixtures/TestBundle/Entity/NoCollectionDummy.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php
tests/Fixtures/TestBundle/Entity/RelationEmbedder.php
tests/Fixtures/TestBundle/Entity/ThirdLevel.php
tests/Fixtures/TestBundle/Entity/User.php
tests/Fixtures/TestBundle/Entity/UuidIdentifierDummy.php

| Fixed tickets | #537
This is resolving the problem of resource being a soft reserved word in php7

hotfix #537: Change @Resource annotation to @ApiResource

---

src/Annotation/ApiProperty.php
src/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php
src/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactory.php
tests/Annotation/PropertyTest.php
tests/Fixtures/TestBundle/Entity/AbstractDummy.php
tests/Fixtures/TestBundle/Entity/CustomNormalizedDummy.php
tests/Fixtures/TestBundle/Entity/Dummy.php

hotfix: Change @Property annotation to @ApiProperty

---

features/bootstrap/FeatureContext.php
features/crud.feature
features/doctrine/date-filter.feature
features/doctrine/search-filter.feature
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
tests/Fixtures/TestBundle/Entity/Dummy.php
tests/Fixtures/app/config/config.yml

| Doc PR        | https://github.com/dunglas/doc/pull/5
I refactored the code a bit by removing nested conditions, hope that's ok.

Case insensitive search filter

---

features/relation.feature
src/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Bridge/Symfony/Routing/IriConverter.php
src/JsonLd/Serializer/ItemNormalizer.php
src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
tests/Fixtures/TestBundle/Entity/DummyFriend.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php
tests/Fixtures/TestBundle/Entity/RelatedToDummyFriend.php

| Fixed tickets | #551 
#550 ref (sorry about multiple PR, github was buggy).

Fix identifiers behavior bugs

---

src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Hydra/ApiDocumentationBuilder.php

Improve the DX by requiring no config at all to install the bundle.

Make title and description config parameters optional

---

features/composite.feature
src/Bridge/Doctrine/Orm/ItemDataProvider.php

| Doc PR        | 	∅
Thought this was effective but in fact it isn't. Now it is.
Enough philosophical sentences, this allows any parameter order when it comes to composite identifiers. We just make sure that the resulting identifiers matches the doctrine index order.

Allow random composite identifier order

---

.travis.yml
appveyor.yml
composer.json
tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
tests/Metadata/Resource/Factory/PhpDocResourceMetadataFactoryTest.php

Unskip tests using Prophecy

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php

| Fixed tickets | n/A
Fix an error when the `Resources/config` directory doesn't exist in the bundle (`[InvalidArgumentException] The "/api-platform/src/AppBundle/Resources/config/" directory does not exist.`).
Improve the code to load XML and YAML files.
ping @soyuka

Fix XML/YAML config loading

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/metadata.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

Use the new builtin cache factory provided by Symfony. It will always create the faster cache adapter available, handle cache invalidation (during deployment) and warm the APCu cache using a file cache when possible.
ping @teohhanhui

Switch to the new Symfony cache infrastructure

---

src/Metadata/Resource/Factory/XmlResourceMetadataFactory.php
src/Metadata/Resource/Factory/XmlResourceNameCollectionFactory.php
src/Metadata/Resource/Factory/YamlResourceMetadataFactory.php
src/Metadata/Resource/Factory/YamlResourceNameCollectionFactory.php
tests/Fixtures/FileConfigurations/single_resource.xml
tests/Fixtures/FileConfigurations/single_resource.yml
tests/Fixtures/TestBundle/Resources/config/api_resources/my_resource.yml
tests/Metadata/Resource/Factory/FileConfigurationMetadataTest.php

https://github.com/api-platform/core/pull/568#issuecomment-225510491
@teohhanhui

"resources" on single resource declarations is optional

---

src/Action/ActionUtilTrait.php
src/Action/GetCollectionAction.php
src/Action/GetItemAction.php
src/Action/PutItemAction.php
src/Api/ResourceClassResolver.php
src/Bridge/Doctrine/Orm/CollectionDataProvider.php
src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/Bridge/Doctrine/Orm/Paginator.php
src/Bridge/Symfony/Bundle/ApiPlatformBundle.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DataProviderPass.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Bundle/Resources/config/data_provider.xml
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Bridge/Symfony/Routing/IriConverter.php
src/DataProvider/ChainCollectionDataProvider.php
src/DataProvider/ChainItemDataProvider.php
src/DataProvider/CollectionDataProviderInterface.php
src/DataProvider/ItemDataProviderInterface.php
src/DataProvider/PaginatorInterface.php
src/Hydra/Serializer/CollectionNormalizer.php
src/Hydra/Serializer/PartialCollectionViewNormalizer.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Routing/IriConverterTest.php
tests/Fixtures/TestBundle/Controller/ConfigCustomController.php
tests/Hydra/Serializer/PartialCollectionViewNormalizerTest.php

| Fixed tickets | #506
Use a chain instead of a decorator for data providers. It allows to register custom data providers in a more intuitive fashion: just add a tag to your service.
ping @soyuka

Use a chain pattern for data providers

---

src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Routing/ApiLoader.php
tests/Bridge/Symfony/Routing/ApiLoaderTest.php
tests/Fixtures/TestBundle/Entity/CustomAttributeDummy.php

We should not use POST in itemOperation (it is not supported) and each unsupported actionName should not be able to be used since it break NelmioApiDoc.
Thanks to @dunglas for the help.

hotfix: add exception when the action is not a builtin action

---

features/relation.feature
src/JsonLd/Serializer/ItemNormalizer.php

| Fixed tickets | #549, #588
ping @Simperfit @teohhanhui

[alternative] hotfix: fix #549 throw an 404 error instead of 500

---

src/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProvider.php
src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
tests/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProviderTest.php
tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php

| Fixed tickets | #582 
I think i'm not bad on this but there is a part of this I don't know how to handle :
Since we are overriding on method, how do I tell the property-info / nelmio that we want this only for the PUT part ?
```php
/**
* @see http://schema.org/Thing
*
* 
* @ApiResource(iri="http://schema.org/Thing", attributes={
*     "normalization_context"={"groups"={"thing_default_output"}},
*     "denormalization_context"={"groups"={"thing_default_input"}}
* }, itemOperations={
*     "get"={"method"="GET", "normalization_context"={"groups"={"thing_default_out_get"}}, …
```

fix #582 itemOperation Normalization/Denormalization in doc 

---

features/swagger/doc.feature
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
src/Swagger/ApiDocumentationBuilder.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Swagger/ApiDocumentationBuilderTest.php

[swagger-v2] feat: add tests and add collection

---

features/bootstrap/SwaggerContext.php
features/swagger/doc.feature
src/Swagger/ApiDocumentationBuilder.php
tests/Fixtures/TestBundle/Entity/OverriddenOperationDummy.php

feat: add custom operation in swagger fix #614

---

src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| Fixed tickets | #538 
| Doc PR        | update doc

feat: deactivate NelmioApiDocBundle by default

---

src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
src/Hydra/ApiDocumentationBuilder.php
tests/Hydra/ApiDocumentationBuilderTest.php
tests/Hydra/Serializer/CollectionNormalizerTest.php
tests/Hydra/Serializer/ItemNormalizerTest.php
tests/Swagger/ApiDocumentationBuilderTest.php

fix: add CollectionNormalizerTest && ItemNormalizerTest && ApiDocumentationBuilderTest

---

.travis.yml
README.md

| Fixed tickets | #564 (partially)
Alternative to #564, waiting for the resolution of the bug in FOSUserBundle.

Remove HHVM support. Simplify Travis config.

---

src/Action/ExceptionAction.php
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Hal/Serializer/ItemNormalizer.php

More quality fixes

---

README.md

The current link leads to a 404,  this makes it point to the "get started" chapter, on the website.

Fix dead link to get started tutorials

---

src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DoctrineQueryExtensionPass.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DoctrineQueryExtensionPassTest.php

The services related to doctrine [aren't loaded in case doctrine is not available](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L112-L115) but the `DoctrineQueryExtensionPass` is executed anyway leading to exceptions such as:
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "api_platform.doctrine.orm.collection_data_provider".
/home/guilhem/github/ApiDocBundle/vendor/symfony/dependency-injection/ContainerBuilder.php:787 …
```

Skip the DoctrineQueryExtensionPass if doctrine is not loaded

---

src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php

It looks like `AnnotationResourceMetadataFactory::createOperations()` was forgotten from a previous version.

Remove AnnotationResourceMetadataFactory::createOperations()

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

It's a bit annoying to have to remove the cache each time you change something in development so I propose to remove or limit to the current process the cache.

Disable the cache in development

---

features/bootstrap/SwaggerContext.php
features/swagger/doc.feature
src/Swagger/DocumentationNormalizer.php
tests/Fixtures/TestBundle/Entity/RelationEmbedder.php
tests/Swagger/DocumentationNormalizerTest.php

Initial post:
> I found two issues in the swagger ``DocumentationNormalizer``.
> The first one, custom operations always made the normalizer creates a standard operation even if it didn't exist.
> The second one, if two or more custom operations had the same path, they conflicted and only the last one was added to the doc.
In fact I do not even understand why some operations are treated as ``custom`` so this PR simplify the `DocumentationNormalizer` by removing this notion and threat all operations at once.

Refactor the management of operations by the swagger DocumentationNormalizer

---

src/Bridge/Doctrine/Orm/Filter/SearchFilter.php

Rename private function SearchFilter::getFilterValueFromUrl to getIdFromValue

Rename getFilterValueFromUrl to getIdFromValue

---

features/doctrine/date_filter.feature
src/Util/RequestParser.php
tests/Util/RequestParserTest.php

This fixes an issue with query strings being urldecoded twice.
| Fixed tickets | #596

Fixed bug with double urldecoding of query string

---

.editorconfig
composer.json

This is consistent with [Composer official documentation](https://getcomposer.org/doc/04-schema.md) and [Symfony](https://github.com/symfony/symfony/blob/master/composer.json).

Change composer.json to use 4 spaces for indentation

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

Some refactoring but also fixed `$operation['swagger_context']` handling by checking for existing values.
/cc @Simperfit

Refactor Swagger paths generation

---

src/Bridge/Doctrine/EventListener/WriteListener.php
tests/Bridge/Doctrine/EventListener/WriteListenerTest.php
tests/Bridge/Doctrine/Util/QueryCheckerTest.php

feat: complete doctrine bridge tests

---

src/Serializer/AbstractItemNormalizer.php
tests/Serializer/AbstractItemNormalizerTest.php

Bug introduced in https://github.com/api-platform/core/commit/e58bd7374fd01df3efa09e58dd58bf81db249ce3

Fix nullable property on denormalization

---

.travis.yml
composer.json
features/bootstrap/CoverageContext.php
features/fos_user.feature
features/hydra/entrypoint.feature
features/jsonld/context.feature
features/nelmio_api_doc.feature
features/swagger/doc.feature
src/Bridge/FosUser/EventListener.php
src/Bridge/Symfony/Routing/OperationMethodResolver.php
src/Hydra/Serializer/CollectionFiltersNormalizer.php
src/JsonLd/ContextBuilder.php
src/Metadata/Resource/Factory/XmlResourceMetadataFactory.php
src/Metadata/Resource/Factory/YamlResourceMetadataFactory.php
src/Metadata/Resource/ResourceMetadata.php
tests/Bridge/FosUser/EventListenerTest.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config.yml
tests/Fixtures/app/config/routing.yml
tests/Fixtures/app/config/security.yml
tests/Hydra/Serializer/CollectionFiltersNormalizerTest.php
tests/Hydra/Serializer/ItemNormalizerTest.php
tests/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactoryTest.php
tests/Metadata/Property/PropertyMetadataTest.php
tests/Metadata/Property/PropertyNameCollectionTest.php
tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php
tests/Metadata/Resource/Factory/FileConfigurationMetadataTest.php
tests/Metadata/Resource/ResourceMetadataTest.php
tests/Metadata/Resource/ResourceNameCollectionTest.php

Increase code coverage

---

src/Bridge/Doctrine/Orm/Util/QueryNameGeneratorInterface.php

This PR is about fixing the bug that has been created on [Scrutinizer](https://scrutinizer-ci.com/g/api-platform/core/issues/master?selectedLabels%5B0%5D=9&orderField=path&order=asc&honorSelectedPaths=0).
I was not respecting the interface directly. Since we don't use the parameter at all. I think it should be empty string by default in the interface too.

hotfix: scrutinizer issue on last PR

---

src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| Fixed tickets | #696 
| Doc PR        | O
This PR give the possibility to limit the number of items that the client can see on the same page.

feature: fix #696 - add an maximum configurable number for client pagination

---

.travis.yml
phpunit.xml.dist

* Use phpdbg instead of xdebug for code coverage
* Speed up npm install
But we need to verify that code coverage is working properly.

Make Travis fast again

---

src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php
src/Hal/Serializer/CollectionNormalizer.php
src/Hal/Serializer/ItemNormalizer.php
src/JsonLd/ContextBuilder.php
src/Metadata/Resource/ResourceMetadata.php
src/Serializer/ItemNormalizer.php
src/Swagger/Serializer/DocumentationNormalizer.php

Fix some quality issues (Scrutinizer)

---

features/security/strong_typing.feature
src/Serializer/AbstractItemNormalizer.php
tests/Serializer/AbstractItemNormalizerTest.php

Allow integers instead of floats for JSON. Fix #37.

---

src/EventListener/AddFormatListener.php
src/EventListener/RespondListener.php
tests/EventListener/RespondListenerTest.php

We must add the "Vary: Accept" response header, since we're varying the response by "Accept" request header. Otherwise, it messes up HTTP caching (Varnish etc.).

Add "Vary: Accept" response header

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
tests/Bridge/Doctrine/Orm/Extension/FilterExtensionTest.php
tests/Bridge/Doctrine/Orm/Filter/BooleanFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/NumericFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php

Updates regarding doctrine performances with associations

---

src/Hydra/Serializer/DocumentationNormalizer.php

Improve the quality and readability of Hydra's DocumentationNormalizer

---

features/security/validate_response_types.feature
src/EventListener/AddFormatListener.php
tests/EventListener/AddFormatListenerTest.php

| Fixed tickets | #733
This is an alternative fix to #733 but I'm not sure that it's the good way to fix the underlying problem. I think that trying to access an URL with an unsupported extension in the URL should throw a 404 (and not a 406).
WDYT @polc @api-platform/core-team?

Handle invalid formats in the URL. Fix #733.

---

src/Bridge/Doctrine/Orm/CollectionDataProvider.php
src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
src/Bridge/Doctrine/Orm/Extension/QueryResultCollectionExtensionInterface.php
src/Bridge/Doctrine/Orm/Extension/QueryResultItemExtensionInterface.php
src/Bridge/Doctrine/Orm/ItemDataProvider.php
tests/Bridge/Doctrine/Orm/CollectionDataProviderTest.php
tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php

| BC breaks?    | yes (think so)
| Doc PR        | https://github.com/api-platform/docs/pull/107 (second example should implement an item extension)

Add QueryResultItemExtensionInterface

---

src/Api/Entrypoint.php
src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Documentation/Documentation.php
src/Hydra/Serializer/DocumentationNormalizer.php

fix function return type style

---

src/Action/ExceptionAction.php
src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
src/Swagger/Serializer/DocumentationNormalizer.php

Improve Swagger's DocumentationNormalizer

---

src/JsonLd/ContextBuilder.php

The parameter referencType is not always respected in the context builder.
In the method getBaseContext the parameter is also not respected but hard coded. When I changed it, I broke your build, so I removed it again.

Fixes parameter referenceType not being respected

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

Small fix when joinColumns does not exist. Also fixes edge cases where the joinTable does not exist (case of a custom association table).

fix eager loading extension with many to many

---

src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig

Avoid the unwanted `#//` at the end of the homepage URL when displaying Swagger UI.

Fix Swagger UI integration

---

src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
src/Bridge/Symfony/Bundle/Resources/config/nelmio_api_doc.xml
src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | #673 
This PR fixes #673 by adding the support of [the name converter system](https://github.com/api-platform/docs/blob/master/core/serialization-groups-and-relations.md#name-conversion) to Swagger and NelmioApiDocBundle.

Fix #673: name converter for Swagger and NelmioApiDocBundle

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

This PR adds the support of the `readOnly` field according to the [Swagger documentation](http://swagger.io/specification/#schemaObject).
It follows the Swagger specification so an exception is thrown when a property is required and read-only at the same time:
> Properties marked as `readOnly` being `true` SHOULD NOT be in the required list of the defined schema.
N.B. `readOnly` is currently [not completely supported](https://github.com/swagger-api/swagger-ui/issues/1231#issuecomment-98460161) by the Swagger-UI.

Add the readOnly field for Swagger

---

tests/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactoryTest.php

Made this because:
1. there was none
2. I needed to test something

test DoctrineOrmPropertyMetadataFactory

---

features/jsonld/context.feature
src/Hydra/Serializer/DocumentationNormalizer.php
src/JsonLd/ContextBuilder.php
tests/Fixtures/TestBundle/Entity/JsonldContextDummy.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php
tests/JsonLd/ContextBuilderTest.php

This pull request is just an implementation proposal, it is not yet ready to be merged. I have not put any effort into fixing the tests.
This pull request wants to add json-ld typed values: https://www.w3.org/TR/json-ld/#typed-values
e.g.
**entity** 
```php
/**
* @var string | array
*
* @ApiProperty(iri="http://xmlns.com/foaf/0.1/firstName");
*
*/
private $firstName;
/**
* @var string | array
*
* @ApiProperty(iri="http://xmlns.com/foaf/0.1/lastName", valueType="literal");
*
*/
private $lastName;
```
**context**
```json
{
"@context": {
"@vocab": …
```

Adds jsonld context, Adds support for jsonld typed values

---

src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

The `api_platform.hydra.action.exception` definition should be removed because it is not used and its `ApiPlatform\Core\Hydra\Action\ExceptionAction` class no longer exists.

Remove a unused service definition

---

src/Bridge/Symfony/Routing/IriConverter.php

Better error checking for relation used as identifier in IriConverter

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

When doing a `LEFT` join, the next association that should be fetched in `EAGER` mode was doing an `INNER` join. As a result, there were things missing from the end results.

fix eager, left join if previous was a left join

---

src/Metadata/Property/PropertyMetadata.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php
tests/Metadata/Property/PropertyMetadataTest.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

Follow up from https://github.com/api-platform/core/pull/764#discussion_r81112046
/cc @dunglas

Mask required when writable false in PropertyMetadata

---

src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig

At the bottom of https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#HTML_entity_encoding
> An alternative to escaping and unescaping JSON directly in JavaScript, is to normalize JSON server-side by converting '<' to '\u003c' before delivering it to the browser.
`{{ ...|escape('js') }}` was unnecessary in the first place because we know we're dealing with well-formed JSON, which has no possibility of causing any harm in a JS context.

Swagger UI template - use minimalist escaping for XSS prevention

---

.travis.yml

Test with PHP 7.1

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

| Fixed tickets | #795 
This fixes a bug where we could not rely on `isReadableLink` because the serializer metadata factory was not getting the correct groups. It was missing the `x_operation_name` [here](https://github.com/api-platform/core/blob/master/src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php#L157).

fix #795 add context for correct metadata on serialization groups

---

src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php

Though doctrine would create a new join part for each new joined entities, in fact they are under the same branch of dql parts. This fixes a second join by the filter, when an eager association has already been joined.

eager associations joins are on the same alias in dql

---

src/Action/ExceptionAction.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
tests/Action/ExceptionActionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/app/config/config.yml

| Fixed tickets | #405 
This PR adds the ability to configure and match exceptions with an HTTP status code and to override default exceptions (i.e., `Symfony\Component\Serializer\Exception\UnexpectedValueException` and `Symfony\Component\Serializer\Exception\ExceptionInterface` to 400 HTTP error).
Example of configuration:
```yaml
api_platform:
exception_to_status:
Foo\Bar\BazException: 400
Baz\Bar\FooException: "HTTP_BAD_REQUEST" # or use a constant defined in the 'Symfony\Component\HttpFoundation\Response' class
```

Add the ability to configure and match exceptions with an HTTP status code

---

src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php

fix: fix nelmio documentation #728

---

src/Api/FilterInterface.php

It took me some time to figure out how to provide a description for a parameter, so I thought it might be useful to add this to the comment.

Extends filter interface description with swagger options

---

features/bootstrap/FeatureContext.php
features/configurable.feature
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/metadata.xml
src/Metadata/Property/Factory/XmlPropertyMetadataFactory.php
src/Metadata/Property/Factory/XmlPropertyNameCollectionFactory.php
src/Metadata/Property/Factory/YamlPropertyMetadataFactory.php
src/Metadata/Property/Factory/YamlPropertyNameCollectionFactory.php
src/Metadata/Resource/Factory/XmlResourceMetadataFactory.php
src/Metadata/Resource/Factory/YamlResourceMetadataFactory.php
src/Metadata/Resource/Factory/YamlResourceNameCollectionFactory.php
src/Metadata/schema/metadata.xsd
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/FileConfigurations/parse_exception.yml
tests/Fixtures/FileConfigurations/propertiesinvalid.yml
tests/Fixtures/FileConfigurations/propertyinvalid.xml
tests/Fixtures/FileConfigurations/propertyinvalid.yml
tests/Fixtures/FileConfigurations/resources.xml
tests/Fixtures/FileConfigurations/resources.yml
tests/Fixtures/FileConfigurations/resourcesinvalid.yml
tests/Fixtures/TestBundle/Entity/FileConfigDummy.php
tests/Fixtures/TestBundle/Resources/config/api_resources.yml
tests/Metadata/Property/Factory/FileConfigurationMetadataFactoryProvider.php
tests/Metadata/Property/Factory/XmlPropertyMetadataFactoryTest.php
tests/Metadata/Property/Factory/XmlPropertyNameCollectionFactoryTest.php
tests/Metadata/Property/Factory/YamlPropertyMetadataFactoryTest.php
tests/Metadata/Property/Factory/YamlPropertyNameCollectionFactoryTest.php
tests/Metadata/Resource/Factory/FileConfigurationMetadataFactoryProvider.php
tests/Metadata/Resource/Factory/YamlResourceMetadataFactoryTest.php
tests/Metadata/Resource/Factory/YamlResourceNameCollectionFactoryTest.php

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #739, api-platform/api-platform#140 |
| License | MIT |
| Doc PR | N/A |
This PR adds support of mapping for properties in XML and YAML.
I followed the recommendations from #421.

Support mapping properties in XML and YAML

---

src/EventListener/EventPriorities.php
tests/EventListener/EventPrioritiesTest.php

Makes it easier for newcomers to use the event system. Example:
```php
<?php
// src/AppBundle/EventSubscriber/BookMailSubscriber.php
namespace AppBundle\EventSubscriber;
use ApiPlatform\Core\EventListener\EventPriorities;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent;
use Symfony\Component\HttpKernel\KernelEvents;
final class BookMailSubscriber implements EventSubscriberInterface
{
private $mailer;
public function __construct(\Swift_Mailer $mailer)
{
$this->mailer = $mailer;
}
public …
```

Add constants for event's priorities

---

src/Metadata/Resource/Factory/CachedResourceNameCollectionFactory.php
tests/Metadata/Resource/Factory/CachedResourceNameCollectionFactoryTest.php

Add tests for the CachedResourceNameCollectionFactory class

---

src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/EventListener/ReadListener.php
src/JsonLd/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php
src/Serializer/ItemNormalizer.php
tests/EventListener/ReadListenerTest.php

Correct me if I'm wrong, but I think we don't need to explicitly fetch data in the denormalizeRelation. I'm not sure about normalization contexts, but if we have the ID, going through the reference should be enough. Is there a reason I don't see that we need to keep those? If there is one, it's not in the behat tests and I'd like to add it, thanks!

No need to explicilty fetch data in normalizers

---

src/Metadata/Property/Factory/AbstractFilePropertyMetadataFactory.php
src/Metadata/Property/Factory/XmlPropertyMetadataFactory.php
src/Metadata/Property/Factory/XmlPropertyNameCollectionFactory.php
src/Metadata/Property/Factory/YamlPropertyMetadataFactory.php
src/Metadata/Property/Factory/YamlPropertyNameCollectionFactory.php

Introduce AbstractFilePropertyMetadatFactory to remove duplicated code.

---

tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php

Fix SwaggerCommandTest

---

src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php
src/Metadata/Property/Factory/CachedPropertyNameCollectionFactory.php
src/Metadata/Resource/Factory/CachedResourceMetadataFactory.php
tests/Metadata/Property/Factory/CachedPropertyMetadataFactoryTest.php
tests/Metadata/Property/Factory/CachedPropertyNameCollectionFactoryTest.php
tests/Metadata/Resource/Factory/CachedResourceMetadataFactoryTest.php

| Fixed tickets | https://github.com/api-platform/core/pull/828#issuecomment-259062771

Add tests for cached metadata classes

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/swagger-ui.xml
src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| Fixed tickets | #804 
| Doc PR        | O
This PR add a parameter to disable swagger ui

fix #804 - add a parameter to disable swagger ui when not needed

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php

Sometime the `nullable` key may not exist.
Btw @soyuka, I've some question regarding the `eager_only`:
* Can't we enable it by default to improve the performance for everybody?
* What do you think about making this feature configurable per resource using attributes?

Make EagerLoadingExtension robuster and less complex

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

This PR removes dead code introduced by https://github.com/api-platform/core/pull/845/commits/8efed0bf3dfe7afd6bbed2d1ca83b60c436c2a60 and makes happy SensioLabs Insight.
My bad, sorry.

Remove dead code to fix SensioLabs Insight

---

src/Metadata/Extractor/YamlExtractor.php
tests/Fixtures/FileConfigurations/bad_declaration.yml
tests/Metadata/Resource/Factory/ExtractorResourceMetadataFactoryTest.php

This was not working:
```yaml
resources:
App\AppBundle\Entity\Foo: ~
```
Should we recommend using single quotes around class declarations in yaml?

Fix consider empty resource declaration as an actual resource

---

src/Metadata/Extractor/XmlExtractor.php

IMO attributes values for the XML extractor should be _phpized_ because some values need to be parsed to boolean, integer, etc.
Ex:
* `force_eager`: currently a string (`"false"` or `"true"`) instead of a boolean
* `pagination_items_per_page`: currently a string instead of an integer

Fix attributes values for the XML extractor

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

Sorry about the bad review on my end but if we remove the `select` part, Doctrine ends up doing joins without selecting the joined tables, and then does lazy join again...
We can remove the `partial` and add instead `$queryBuilder->addSelect($associationAlias);` if you don't want to use partial. However, partial does only fetch the wanted data, and IMO it's better than selecting everything (ie SQL query is more readable).
Changes the way ManyToMany are handled as we can't now for sure that the related data exists, even if the joinTables columns are null.

Revert "Remove partial select"

---

src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/FilterPass.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/FilterPassTest.php
tests/Fixtures/app/config/config.yml

Make filters's ids defaulting to the service name

---

features/main/circular_reference.feature
src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Fixtures/TestBundle/Entity/CircularReference.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/187
In the case of recursive entities, we should only join once those attributes. Indeed, this fix doesn't break joins where you could join the same entity in two different associations but only if the class references itself. So, the `maxJoins` is still valid.
WDYT @teohhanhui ?

Proposal to avoid join recursivity in eager loading

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

This PR introduces an option to define custom paths for the mapping loaders (see. #868). As you can see, it is really simple to implement that feature. What we need to discuss now, how the configuration should look like.
Currently, I added a loader_paths namespace where you can define custom paths for annotation, yaml and xml based mappings. (In the other issue I asked only for annotation based mappings, but I think its better to add customizations for all loaders.) However, this might not be the best structure. Maybe we should introduce some general mapping related namespace for other options at in the future (if there are any).
| Fixed …

Add configuration option to define custom loader paths

---

src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js
src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
tests/Bridge/Symfony/Bundle/Action/SwaggerUiActionTest.php

Hello,
In case you're using API-Platform and have enable Content Security Policy directive for `script-src` that disable inline scripts, the Swagger UI does not work.
This PR solves this issue.

Make swagger UI compatible in a CSP environment

---

src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php

Fix this error when decorating the Swagger normalizer:
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to ApiPlatform\Core\Bridge\Symfony\Bundl
e\Command\SwaggerCommand::__construct() must be an instance of ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer, instance of AppBundle\Swagge
r\SwaggerDecorator given, called in demo/var/cache/dev/appDevDebugProjectContainer.php on line 879 in demo/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php:35
```

Fix an error when decorating the Swagger normalizer

---

src/JsonLd/Serializer/ItemNormalizer.php

| Fixed tickets | #890, #895 
Addition to PR #895. The classMetadataFactory parameter was not passed to the parent of the JsonLd Normalizer, which I fixed here.

Pass classMetadataFactory in jsonld normalizer to parent

---

features/main/relation.feature
src/Bridge/Symfony/Routing/IriConverter.php
src/Exception/ItemNotFoundException.php
src/JsonLd/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php

| Fixed tickets | api-platform/api-platform#198
Maybe this can be done elsewhere, but in the error stack there is no call to ItemDataProvider / CollectionDataProvider.
Should we test the item in here before sending it to the normalizer ?

fix: add test to reproduce && fix the issue using wrong relation IRI

---

features/main/custom_normalized.feature
src/Serializer/ItemNormalizer.php
tests/Fixtures/TestBundle/Entity/DummyFriend.php
tests/Fixtures/TestBundle/Entity/RelatedNormalizedDummy.php
tests/Serializer/ItemNormalizerTest.php

| Fixed tickets | #857 
Add an non-regression test and modify the comportement of itemNormalizer

fix #857 - fix on put when both @id and id are present

---

features/hydra/error.feature
features/security/strong_typing.feature
src/Hydra/Serializer/ErrorNormalizer.php
tests/Hydra/Serializer/ErrorNormalizerTest.php

| BC breaks?    | little
| Fixed tickets | #934

[Hydra] Normalization error in ErrorNormalizer.php for Error type

---

tests/Fixtures/app/config/config.yml

Sync with last changes in FOSUser. Should make tests green again.

Fix the FOSUser config

---

composer.json
features/main/custom_operation.feature
src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
src/EventListener/DeserializeListener.php
src/EventListener/ReadListener.php
src/Util/RequestAttributesExtractor.php
tests/Bridge/Symfony/Validator/EventListener/ValidateListenerTest.php
tests/EventListener/DeserializeListenerTest.php
tests/EventListener/ReadListenerTest.php
tests/Fixtures/TestBundle/Controller/CustomActionController.php
tests/Fixtures/TestBundle/Entity/CustomActionDummy.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/routing.yml
tests/Util/RequestAttributesExtractorTest.php

| Fixed tickets | #880, #781, #782, #805
To disable all API Platform request listeners (read, deserialize and validate), you have to create a new request attribute (for instance by setting the `defaults` key in a route definition) called `api_request` to false.
ping @lyrixx, @kbsali, @gpenverne.

Add a flag to disable all request listeners

---

src/EventListener/AddFormatListener.php
src/Util/ErrorFormatGuesser.php

`each()` is deprecated in PHP 7.2. This PR removes calls to this function.

Remove deprecated calls to each()

---

composer.json
features/authorization/deny.feature
src/Bridge/Doctrine/EventListener/WriteListener.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/EventListener/DenyAccessListener.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/EventListener/DenyAccessListenerTest.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php
tests/Fixtures/app/config/security.yml

| Fixed tickets | api-platform/api-platform#109 (partially), #234
Edit: now with expression language support
This PR allows to setup authorization controls directly from the resource.
In the following exemple, the only logged in admins can access all operations related to the `Secured` resource. However, regular users owning a specific resource can also access to it.
All variables available in [Symfony's access control expressions](http://symfony.com/doc/current/expressions.html#security-complex-access-controls-with-expressions) are available. The `object` variable value is the current resource (or …

Allow to configure auth access from the resource class

---

src/Bridge/FosUser/EventListener.php
src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
src/EventListener/DeserializeListener.php
src/EventListener/ReadListener.php
src/EventListener/SerializeListener.php
src/Serializer/SerializerContextBuilder.php
src/Util/RequestAttributesExtractor.php
tests/Util/RequestAttributesExtractorTest.php

As suggested by @lyrixx [on Twitter](https://twitter.com/lyrixx/status/831900318539640833), throwing an exception on the hot execution path is bad for performance. This PR improves the situation.

Refactor RequestAttributesExtractor to not throw on the hot path

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php

I've found this error using [PHPStan](https://github.com/phpstan/phpstan). What do you think about adding it to the CI?

Add a missing property in EagerLoadingExtension

---

behat.yml
composer.json
features/bootstrap/FeatureContext.php
features/bootstrap/HydraContext.php
features/bootstrap/SwaggerContext.php
features/doctrine/date_filter.feature
features/doctrine/numeric_filter.feature
features/doctrine/order_filter.feature
features/doctrine/range_filter.feature
features/doctrine/search_filter.feature
features/hydra/collection.feature
features/main/relation.feature

I found that the hydra:view schema validation pattern were not correctly checked in the testsuite. Any value would let the tests passing as the schema is malformed.
I've also updated the Behatch namespace as they changed it in 2.6 (call it deprecated) without providing a decent BC version.

hydra:view schema validation 

---

features/bootstrap/FeatureContext.php
features/doctrine/boolean_filter.feature

I've been reading the [boolean filter documentation](https://api-platform.com/docs/core/filters#boolean-filter) and found that using `on|off` as documented was not working. So I've been searching in the code and saw that only `true|false|1|0` was implemented and tested and also figured out that most of integration tests were not working properly.
It seems that it was working at some point and has been removed [here](https://github.com/api-platform/core/commit/e4eca423d32720bc0cba3fd9a0e47675c1fa21c1#diff-31a7356474220b422a684ad542968342) on purpose ?
Should I open a PR to the …

Boolean filter integration tests improvements

---

src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| Fixed tickets | #965 
Add default Order to make it work for users who have postgresql and Mysql 5.7 and who has not defined api_platform_collection_order by default

Add default order in API Platform Configuration

---

src/Bridge/Symfony/Bundle/Resources/config/api.xml

There is a duplicated tag in the definition of ValidationListener service, and so the listener is called twice in the kernel.view event

Fixed duplicated tag in ValidaterListener service definition

---

features/doctrine/date_filter.feature
features/doctrine/exists_filter.feature
features/main/crud.feature
src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Orm/Filter/ExistsFilterTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Entity/Dummy.php
tests/Fixtures/app/config/config.yml

| Tests pass?   | TODO
IS NULL / IS NOT NULL (field / single-valued association)
or
IS EMPTY / IS NOT EMPTY (collection-valued association)

Add ExistsFilter

---

features/bootstrap/FeatureContext.php
features/doctrine/date_filter.feature
features/doctrine/search_filter.feature
features/main/crud.feature
features/main/relation.feature
src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Entity/DummyCar.php
tests/Fixtures/TestBundle/Entity/DummyCarColor.php
tests/Fixtures/TestBundle/Entity/DummyFriend.php
tests/Fixtures/TestBundle/Entity/ParentDummy.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php
tests/Fixtures/TestBundle/Entity/RelatedToDummyFriend.php
tests/Fixtures/app/config/config.yml

| Fixed tickets | #944
/!\ This is probably the worse code I've ever produced here and I hope we can find how to improve it together.
To fix #944 I needed to alter the query generated by the filters and the eager loading extension. To do so, I've added a `FilterEagerLoadingExtension` that patches the Query generated by the `FilterExtension`. 
It runs directly after the `FilterExtension` and transforms the query so that it ends up doing something like:
```
SELECT o, partial bars_a1_p.{id,prop} 
FROM ApiPlatform\Core\Tests\Fixtures\TestBundle\Entity\Foo o 
LEFT JOIN o.bars bars_a1_p 
WHERE o IN(
SELECT …
```

Fix #944 - allows to filter by relation by keeping EagerLoading enabled

---

src/Action/ExceptionAction.php
src/Hydra/Serializer/ErrorNormalizer.php
tests/Action/ExceptionActionTest.php
tests/Hydra/Serializer/ErrorNormalizerTest.php

| Fixed tickets | #973 , #929 
This PR fixes the display of Sensitive information (SQL request displayed, Database information) when the project is in production.
No BC according to me

Do not expose sensitive information

---

features/bootstrap/FeatureContext.php
features/doctrine/multiple_filter.feature
src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php

Fix #1008 multiple filters on eager loading

---

CONTRIBUTING.md

| Fixed tickets | https://github.com/api-platform/core/pull/926
In order to close https://github.com/api-platform/core/pull/926, I'm suggesting this alternative. I added some documentation in the `CONTRIBUTING` file with the test commands and their possible issues/resolutions.

Document api-platform/core testability

---

src/Hydra/Serializer/DocumentationNormalizer.php

`xmls:number` doesn't even exist...

Fix the generated XML Schema type for float

---

src/Hydra/Serializer/ErrorNormalizer.php
src/Problem/Serializer/ErrorNormalizer.php
src/Problem/Serializer/ErrorNormalizerTrait.php
tests/Problem/Serializer/ErrorNormalizerTest.php

| Fixed tickets | https://github.com/api-platform/core/pull/978#issuecomment-290425327
https://github.com/api-platform/core/pull/978#issuecomment-290425327

Do not expose sensitive informations (json format)

---

src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php

Fix #1021 order by hidden eager loading

---

.travis.yml

They disabled logs when nb_lines > 10000, which is our case, this helps
debugging
| New feature?  | yes \o/

Skip colors on travis job

---

src/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactory.php
tests/Fixtures/TestBundle/Entity/UpperCaseIdentifierDummy.php
tests/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactoryTest.php

ReflectionExtractor::getProperties() returns $id instead of $Id. It is bad naming convention, but is possible
```
use Doctrine\ORM\Mapping as ORM;
class Entity {
/**
* @var string The dummy Guid
*
* @ORM\Column(nullable=true)
* @ApiProperty()
*/
protected $Id;
public function getId()
{
return $this->Id;
}
}
```
| Fixed tickets | #1026

Allow Upper Case property names

---

src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Routing/ApiLoader.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Refresh routes when an entity is created

---

src/Bridge/Doctrine/Orm/Util/IdentifierManagerTrait.php
tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php
tests/Bridge/Doctrine/Util/IdentifierManagerTraitTest.php

Improve compatibility with `declare(strict_types=1);`
Should be backported to `2.0`

Normalize identifiers to the correct type

---

src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
tests/Bridge/Symfony/Bundle/Action/SwaggerUiActionTest.php

Allow API Platform to work without the `symfony/templating` component.

Get rid of the dependency to the templating component

---

src/Metadata/Resource/ResourceMetadata.php
tests/Metadata/Resource/ResourceMetadataTest.php

Allow the operation name to be null in ResourceMetadata

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

| Fixed tickets | #1039
ping @bwegrzyn may you try my branch to see if this fixes the issue? 
Could you please also give me an example of your dynamic context so that I can add a proper test for this use case?
Tyvm!

Eager Loading Extension does not use dynamic serialization context

---

features/bootstrap/FeatureContext.php
features/integration/fos_user.feature
src/Bridge/Symfony/Bundle/Resources/config/fos_user.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/app/config/security.yml

| Fixed tickets | #1064
Since #597, the `ApiPlatform\Core\EventListener\SerializerListener` (formerly `SerializerViewListener`) class changed priorty from 10 to 16.
The `ApiPlatform\Core\Bridge\FosUser\EventListener` class has a priority of 11, which means it now runs after the `SerializerListener`. This causes the controller result to be already serialized, which fails the checks in the FOSUser listener.
This PR updates the priority of `ApiPlatform\Core\Bridge\FosUser\EventListener` to 24, so that it can run before the `SerializerListener` class.

Update priority of FosUser\EventListener

---

src/Api/ResourceClassResolver.php
tests/Api/ResourceClassResolverTest.php

This PR allows the `ResourceClassResolver::getResourceClass()` method to return the given resource class when value is a `\Traversable`.
So, `CollectionNormalizer` classes no longer throw an `InvalidArgumentException` exception with `\Traversable` objects during the normalization.

Fix the resource class resolver (and collection normalizers) with Traversable values

---

src/Metadata/schema/metadata.xsd
tests/Fixtures/FileConfigurations/propertyinvalid.xml
tests/Fixtures/FileConfigurations/resourcenotfound.xml
tests/Fixtures/FileConfigurations/resources.xml
tests/Fixtures/FileConfigurations/resourcesinvalid.xml
tests/Fixtures/FileConfigurations/resourcesoptional.xml
tests/Metadata/Property/Factory/ExtractorPropertyMetadataFactoryTest.php
tests/Metadata/Property/Factory/ExtractorPropertyNameCollectionFactoryTest.php

| Doc PR        | TBD
Not a critical thing, but as I tend to prefer XML for configuration files I'm sure other will enjoy the change :
Added attributes allow to validate resources.xml files as developers can do with other Symfony config files (ex: routing, services, ...)
This would ease auto-completion by editors supporting XML structure hints from the XSD (like PHPStorm) by defining the namespace in the XML header, as other XML config files do in Symfony : 
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<resources xmlns="https://api-platform.com/schema/metadata" …
```

Add attributes to metadata XSD file

---

tests/Fixtures/TestBundle/Doctrine/Generator/Uuid.php
tests/Fixtures/TestBundle/Entity/CustomGeneratedIdentifier.php

Better like this. If you don' t implement JsonSerializable, the `id` normalized value will not be what you expect.

Add JsonSerializable on identifier generator test

---

src/Hal/Serializer/ItemNormalizer.php
tests/Hal/Serializer/ItemNormalizerTest.php

The HAL normalizer was failing when the context isn't serializable.

Fix HAL normalizer when the context isn't serializable

---

composer.json
phpstan.neon
src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Util/EagerLoadingTrait.php

See willdurand/Negotiation#94
TODO:

Upgrade the Negotiation library

---

src/DataProvider/CollectionDataProviderInterface.php
src/EventListener/ReadListener.php

```php
PaginatorInterface instanceof \Traversable
```

Remove redundant type declaration of PaginatorInterface

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| Doc PR        | https://github.com/api-platform/docs/pull/195
This PR adds the possibility to customise the name of the folder in which the api resources (as in the classes tagged using the `@ApiResource` annotation) are stored, rather than the hardcoded "Entity" folder.
Such change allows for easier separation between the entities used for persisting the data and the classes used for describing the api resources.

Add support for customizable api resources folder's name.

---

phpstan.neon
src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/Bridge/Doctrine/Orm/Util/IdentifierManagerTrait.php
tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php
tests/Bridge/Doctrine/Util/IdentifierManagerTraitTest.php

Since it's not feasible to backport #1014 without #907, I've included both. Basically just copy-pasted these files from master \o/

Backport #1014 (also includes #907)

---

src/Bridge/Symfony/Bundle/Resources/config/metadata/metadata.xml
src/Bridge/Symfony/Bundle/Resources/config/validator.xml

| Fixed tickets | ø
| Doc PR        | ø
As the validator as a dev dependency, it won't necessary be installed when using ApiPlatform's "pack" and Symfony Flex. Still, the validator is a dependency to get the metadata from its component: moving this definition to the `validator.xml` file that is only included when the validator component exists fixes the problem.

Move the metadata from validator factory to the validator.xml file

---

.php_cs.dist

Add the header_comment rule to the PHP-CS-Fixer's configuration

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Util/EagerLoadingTrait.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Metadata/Property/PropertyMetadata.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Metadata/Property/PropertyMetadataTest.php

| Fixed tickets | #1069 
As discussed in #1069 sometimes you still want to fetch a property, even though it will not be serialized. This new metadata attribute adds a flag that will prevent the eager loader to check the `readable` state. 
ping @bwegrzyn

Disable eager loading partial fetch by default #1069

---

src/Serializer/AbstractItemNormalizer.php
tests/Serializer/AbstractItemNormalizerTest.php

| Fixed tickets | #1120
This PR add the ability to [ignore attributes](http://symfony.com/doc/current/components/serializer.html#ignoring-attributes) for our abstract item normalizer.
This fix originally comes from #1123 but #1120 made me realize that this is a bug and this one has to be fixed in our `2.0` branch.

Fix ignoring attributes for the abstract item normalizer

---

src/Api/CachedIdentifiersExtractor.php
src/Api/IdentifiersExtractor.php
src/Api/IdentifiersExtractorInterface.php
src/Api/OperationType.php
src/Api/OperationTypeDeprecationHelper.php
src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
src/DataProvider/ChainSubresourceDataProvider.php
src/DataProvider/SubresourceDataProviderInterface.php
tests/Api/CachedIdentifiersExtractorTest.php
tests/Api/IdentifiersExtractorTest.php
tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
tests/DataProvider/ChainSubresourcedataProviderTest.php
tests/Fixtures/TestBundle/Entity/Answer.php
tests/Fixtures/TestBundle/Entity/Container.php
tests/Fixtures/TestBundle/Entity/Node.php
tests/Fixtures/TestBundle/Entity/Question.php

Fix CS, make Travis green again

---

features/bootstrap/FeatureContext.php
features/main/subresource.feature
src/Bridge/Symfony/Routing/ApiLoader.php
src/Bridge/Symfony/Routing/CachedRouteNameResolver.php
src/Bridge/Symfony/Routing/IriConverter.php
src/Bridge/Symfony/Routing/RouteNameResolver.php
src/Bridge/Symfony/Routing/RouteNameResolverInterface.php
src/Hydra/Serializer/CollectionNormalizer.php
tests/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php
tests/Bridge/Symfony/Routing/IriConverterTest.php
tests/Bridge/Symfony/Routing/RouteNameResolverTest.php
tests/Fixtures/TestBundle/Entity/DummyAggregateOffer.php
tests/Fixtures/TestBundle/Entity/DummyOffer.php
tests/Fixtures/TestBundle/Entity/DummyProduct.php

Also resolves conflicts with existing subresources on a property having
the same name
| Tests pass?   | behat is okay, unit tests are nogo
| Fixed tickets | #1107 
| Doc PR        | ma
Unit tests don't pass for now, waiting for an answer to the below comment.

Fix route name resolving with subresources

---

features/bootstrap/FeatureContext.php
features/serializer/group_filter.feature
features/serializer/property_filter.feature
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Serializer/AbstractItemNormalizer.php
src/Serializer/Filter/FilterInterface.php
src/Serializer/Filter/GroupFilter.php
src/Serializer/Filter/PropertyFilter.php
src/Serializer/SerializerFilterContextBuilder.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Entity/DummyGroup.php
tests/Fixtures/TestBundle/Entity/DummyProperty.php
tests/Fixtures/app/config/config.yml
tests/Serializer/Filter/GroupFilterTest.php
tests/Serializer/Filter/PropertyFilterTest.php
tests/Serializer/SerializerFilterContextBuilderTest.php

Add a filter for serialization attributes

---

.travis.yml
features/bootstrap/FeatureContext.php

Fix master tests

---

features/bootstrap/FeatureContext.php
features/doctrine/boolean_filter.feature
features/doctrine/date_filter.feature
features/doctrine/order_filter.feature
features/doctrine/search_filter.feature
features/main/crud.feature
features/main/relation.feature
features/main/subresource.feature
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
src/Bridge/Doctrine/Orm/Filter/DateFilter.php
src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php
src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
src/Bridge/Doctrine/Orm/Filter/RangeFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Bridge/Doctrine/Orm/Util/QueryNameGenerator.php
tests/Fixtures/TestBundle/Entity/EmbeddableDummy.php
tests/Fixtures/TestBundle/Entity/EmbeddedDummy.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php
tests/Fixtures/app/config/config.yml

| Fixed tickets | #969 
This PR is to aliment a discussion about how to manage embedded fields in API Platform Filter
This PR works form Boolean Filter Only. It works recursively Entity->Embed Fields -> Embed Fields..
No Tests is developped for the moment

Manage embedded fields for API Platform Filter

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Fixed tickets | #1151
| Doc PR        | https://github.com/api-platform/docs/pull/214

[RFR] Improve autowiring

---

src/HttpCache/VarnishPurger.php
tests/HttpCache/VarnishPurgerTest.php

* Allows non indexed arrays
* Use `request` instead of `requestAsync` to throw an error in the purge doesn't work

Fix the Varnish purger

---

src/Bridge/Symfony/Routing/ApiLoader.php
tests/Bridge/Symfony/Routing/ApiLoaderTest.php

| Fixed tickets | #1161 
@teohhanhui I don't see the point of setting up a complex `visited` array for this task. I mean, I could populate an array like in your example, but if I then want to use it to compute the RouteCollection, won't I do the job twice?

fix #1161 #1144 followup

---

src/Bridge/Symfony/Routing/CachedRouteNameResolver.php
src/Bridge/Symfony/Routing/IriConverter.php
src/Bridge/Symfony/Routing/RouteNameResolver.php

Per [OperationTypeDeprecationHelper.php](https://github.com/api-platform/core/blob/42940e3f48c3450d6c193f6bca6b8c5041821ffa/src/Api/OperationTypeDeprecationHelper.php#L18) comment: `false` should be replaced with `OperationType::ITEM`. 
Per deprecation notice in [RouteNameResolver](https://github.com/api-platform/core/blob/e66ed60aa0ea4065f75cbd8c24ef07d8f2b14abb/src/Bridge/Symfony/Routing/RouteNameResolver.php#L44) third argument also becomes mandatory and is empty array when not in use. 
| Bug fix?      | yes - fix deprecation notice
I've tried, but I cannot figure out how to write a test to cover …

fix deprecation notice from in IriConvertor::getIriFromItem

---

src/Serializer/AbstractItemNormalizer.php

When I directly serialize an entity which is ApiPlatform resource, `$context['operation_type']` isn't set (usually it's set by SerializerContextBuilder::createFromRequest) and it throws and error
```
Undefined index: operation_type in AbstractItemNormalizer
```
For consistency, CollectionNormalizer [has `isset($context['operation_type'])` check](https://github.com/survos/core/blob/e66ed60aa0ea4065f75cbd8c24ef07d8f2b14abb/src/Hydra/Serializer/CollectionNormalizer.php#L78-L78).

Check if operation_type exists in AbstractItemNormalizer

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

Doctrine Embeddables are correctly fetched for item and collection and support was added recently for filters which is awesome but I found that embedded entities in relations where forgotten by the EagerLoadingExtension.
This PR aims to fix that.

[2.1] Fix Eager Loading of Embedded Entities in Relations

---

features/main/composite.feature
src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/Bridge/Doctrine/Orm/Util/IdentifierManagerTrait.php
tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php

This PR fixes a bug when a resource is requested with a wrong composite identifier, like 'ida=1;' instead of 'ida=1;idb=2'.

Fix a problem when a composite identifier is missing

---

src/HttpCache/EventListener/AddHeadersListener.php
tests/HttpCache/EventListener/AddHeadersListenerTest.php

An example would be returning a BinaryFileResponse
| BC breaks?    | maybe

Avoid errors when a request has no content

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Fixed tickets | #1159 
Ping @sroze

Use the Symfony serializer's name converter by default.

---

src/Api/OperationTypeDeprecationHelper.php
src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
src/Bridge/Symfony/Routing/ApiLoader.php
src/Bridge/Symfony/Routing/RouteNameGenerator.php
src/Bridge/Symfony/Routing/RouterOperationPathResolver.php
src/PathResolver/CustomOperationPathResolver.php
src/PathResolver/DashOperationPathResolver.php
src/PathResolver/OperationPathResolverInterface.php
src/PathResolver/UnderscoreOperationPathResolver.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Bridge/Symfony/Bundle/Action/SwaggerUiActionTest.php
tests/Bridge/Symfony/Routing/RouteNameGeneratorTest.php
tests/Bridge/Symfony/Routing/RouterOperationPathResolverTest.php
tests/PathResolver/CustomOperationPathResolverTest.php
tests/PathResolver/DashOperationPathResolverTest.php
tests/PathResolver/UnderscoreOperationPathResolverTest.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/254
A fix while waiting for Swagger 3 which will permit overriding the base path at the path item level.
See:
* https://github.com/OAI/OpenAPI-Specification/issues/562
* https://github.com/OAI/OpenAPI-Specification/pull/604

Fix path for custom operation with Swagger UI

---

features/swagger/docs.feature
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

Since Swagger-UI 3.x, definitions are exposed in the ui. My proposal is to make them more verbose when an operation has defined roles. So instead of a md5 hash, I propose to use a slug.
Slug can be discussed and currently I use `_groups_<group x>_<group y>_<group ...>`.
Before:
After:
WDYT?

[Proposal] Update Swagger's definition keys (more verbose)

---

features/doctrine/order_filter.feature
src/Bridge/Doctrine/Orm/Filter/OrderFilter.php

This PR fixes a bug related to https://github.com/api-platform/admin/issues/25 where wrongly formed order parameters causes the api to crash.

OrderFilter::extractProperties now always return an array

---

src/Hydra/Serializer/DocumentationNormalizer.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | #912
Today it's impossible to know if an Hydra property is a collection of * or not.
I implemented the solution provided on https://lists.w3.org/Archives/Public/public-hydra/2017Jun/0010.html.

[Hydra] add collection flag in documentation properties

---

features/http_cache/headers.feature
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/HttpCache/EventListener/AddHeadersListener.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/app/config/config.yml
tests/HttpCache/EventListener/AddHeadersListenerTest.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/349
Fixes https://github.com/api-platform/api-platform/issues/349. The vary header for varnish was wrong.

fix varnish content negotiation

---

src/Annotation/ApiProperty.php
src/Annotation/ApiSubresource.php
src/Bridge/Symfony/Bundle/Resources/config/metadata/annotation.xml
src/Bridge/Symfony/Routing/ApiLoader.php
src/Metadata/Extractor/XmlExtractor.php
src/Metadata/Extractor/YamlExtractor.php
src/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php
src/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php
src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php
src/Metadata/Property/PropertyMetadata.php
src/Metadata/Property/SubresourceMetadata.php
src/Metadata/schema/metadata.xsd
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Routing/ApiLoaderTest.php
tests/Fixtures/FileConfigurations/resources.xml
tests/Fixtures/FileConfigurations/resources.yml
tests/Fixtures/TestBundle/Entity/Container.php
tests/Fixtures/TestBundle/Entity/Dummy.php
tests/Fixtures/TestBundle/Entity/DummyAggregateOffer.php
tests/Fixtures/TestBundle/Entity/DummyProduct.php
tests/Fixtures/TestBundle/Entity/Question.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php
tests/Metadata/Property/Factory/ExtractorPropertyMetadataFactoryTest.php
tests/Metadata/Property/Factory/FileConfigurationMetadataFactoryProvider.php

For now the @ApiSubresource only does the same thing as `@ApiProperty(subresource=true)`. It'll be better with metadata and an annotation class if we want to add features to it in the future.
Related to https://github.com/api-platform/core/pull/1188. ping @pierredup

Implement subresource metadata and annotation

---

features/main/composite.feature
src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/EventListener/ReadListener.php
tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php

| Fixed tickets | #1191 
Another solution for this would be to catch the Exception in the ReadListener and return null. Lmk wdyt about this.
ping @teohhanhui  @Simperfit

404 instead of 400 for bad identifiers fix #1191

---

composer.json

| Fixed tickets | #1170 
As discussed in #1170, I'm adding composer conflict for symfony/dependency-injection lower than 3.3, since the bundle packed in the repository only works for symfony ^3.3.
There was discussion about adding more conflicts, I'm not sure if this is a good idea. Since api-platform/core is not only a bundle, it could totally be installed with doctrine/orm or any other require-dev package without using the api-platform bundle (in theory).
I would rather add only real conflicts.

Adds conflict on symfony/dependency-injection < 3.3

---

features/bootstrap/HydraContext.php
features/hydra/collection.feature
features/hydra/docs.feature
features/main/relation.feature
src/Hydra/Serializer/DocumentationNormalizer.php
src/JsonLd/ContextBuilderInterface.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php

* Remove old references to the `PagedCollection` class (see https://github.com/HydraCG/Specifications/issues/42)
* Remove old references to the `*ResourceOperation` classes (see https://github.com/HydraCG/Specifications/issues/11)
* Replace predefined operations with the schema.org actions (see https://github.com/HydraCG/Specifications/pull/125)
* Add `ApiDocumentation` class as type of the generated documentation

Fix Hydra documentation

---

src/Bridge/Symfony/Routing/ApiLoader.php
src/Bridge/Symfony/Routing/RouteNameGenerator.php
src/Bridge/Symfony/Routing/RouterOperationPathResolver.php
src/Hydra/Serializer/DocumentationNormalizer.php
src/PathResolver/UnderscoreOperationPathResolver.php
tests/Bridge/Symfony/Routing/RouteNameGeneratorTest.php
tests/Bridge/Symfony/Routing/RouterOperationPathResolverTest.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php

ping @pierredup 
Update of #1188

Add subresources to hydra

---

src/Bridge/Symfony/Bundle/Resources/config/validator.xml
src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
tests/Bridge/Symfony/Validator/EventListener/ValidateListenerTest.php

Usage:
```php
<?php
// src/ValidatorGroupsGenerator.php
class ValidatorGroupsGenerator
{
private $s;
public function __construct(AService $s)
{
$this->s = $s;
}
public function __invoke(): array
{
return $this->s->isSomething() ? ['a', 'b'] : ['a'];
}
}
```
```yaml
services:
App\ValidatorGroupsGenerator: ['@a_service']
```
```php
<?php
// src/Entity/Book.php
use Symfony\Component\Validator\Constraints as Assert;
/**
* @ApiResource(attributes={"validation_groups"="App\ValidatorGroupsGenerator"})
*/
class Book
{
/**
* …
```

Allow to use a service for dynamic validation groups

---

src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
tests/Bridge/Symfony/Validator/EventListener/ValidateListenerTest.php

| Fixed tickets | https://github.com/api-platform/core/pull/1198#issuecomment-314716934
* Fix the bug/BC break introduced by #1198 (see https://github.com/api-platform/core/pull/1198#issuecomment-314716934)
* Allow to use a simple scalar instead of an array as validation group in attributes.

Fix BC break in ValidateListener

---

src/Metadata/Extractor/YamlExtractor.php
tests/Fixtures/FileConfigurations/resources.yml
tests/Fixtures/TestBundle/Entity/FileConfigDummy.php

Allow using PHP constants in YAML resources files

---

src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/app/config/config.yml

Replace the old exception to status config with the new Symfony's YAML extension for PHP constants

---

src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php
src/Metadata/Property/Factory/CachedPropertyNameCollectionFactory.php
src/Metadata/Resource/Factory/CachedResourceMetadataFactory.php
src/Metadata/Resource/Factory/CachedResourceNameCollectionFactory.php
tests/Metadata/Property/Factory/CachedPropertyMetadataFactoryTest.php
tests/Metadata/Property/Factory/CachedPropertyNameCollectionFactoryTest.php
tests/Metadata/Resource/Factory/CachedResourceMetadataFactoryTest.php
tests/Metadata/Resource/Factory/CachedResourceNameCollectionFactoryTest.php

By default, the Symfony's `cache.system` setup uses apcu. Our metadata component relies on this cache, however, as we retrieve the cache many time in a single request `apcu_fetch` is called many times and do a lot of IO. This fix introduce a local memory cache to avoid the IO operations.

Improve performance of the metadata system

---

src/Api/CachedIdentifiersExtractor.php
tests/Api/CachedIdentifiersExtractorTest.php

Improve the performance of CachedIdentifiersExtractor

---

src/Annotation/ApiResource.php
tests/Annotation/AnnotatedClass.php
tests/Annotation/ApiResourceTest.php

Doctrine's DocParser throws an exception if you set a description.
| Fixed tickets | #1050

Removed null description @var in ApiResource

---

src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php
src/Metadata/Property/Factory/CachedPropertyNameCollectionFactory.php
src/Metadata/Resource/Factory/CachedResourceMetadataFactory.php
src/Metadata/Resource/Factory/CachedResourceNameCollectionFactory.php

Rename memoryCache to localCache

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

* Revert/Refactor https://github.com/api-platform/core/pull/869
* Revert https://github.com/api-platform/core/pull/1078
* Allow to configure a mapping paths like `symfony/framework-bundle`

Add a mapping paths

---

src/Security/EventListener/DenyAccessListener.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php
tests/Security/EventListener/DenyAccessListenerTest.php

This expliciter now that we have a `is_granted` function usable in the expression.

Change the is_granted key to access_control

---

features/main/crud.feature
src/EventListener/DeserializeListener.php
tests/EventListener/DeserializeListenerTest.php

| Fixed tickets | no
| Doc PR        | NA
This PR allows to send empty request content for PUT in a custom operation.
Use case : 
I have a custom Action (ex : "reset") associated to an ApiResource "Job". 
I don't have any request content to send when I send a PUT request to `/jobs/1234/reset`.
But I've a SerializerError because the request content is required.

Authorize empty content put in custom operations

---

.travis.yml
phpstan.neon

Ensure PHPStan version stability

---

src/Hydra/Serializer/DocumentationNormalizer.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | #1294
Needs to be ported back in master (may be conflicts)

fix #1294 hydra_context should override operation metadata

---

src/Bridge/Symfony/Routing/IriConverter.php

It could be useful.
| Bug fix?      | not really
| New feature?  | kinda

Preserve previous exception

---

src/EventListener/SerializeListener.php
tests/EventListener/SerializeListenerTest.php

| Fixed tickets | #1303 
Because [getCacheKey](https://github.com/symfony/serializer/blob/master/Normalizer/AbstractObjectNormalizer.php#L361) serializes the `context`, let's avoid serializing the `$context['resources']` that can get pretty big.
Solves the performance issue.

	Avoid serializing "resources" in the normalization context

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

| Fixed tickets | #1290
| Doc PR        | https://github.com/api-platform/docs/pull/233
The following will bypass `readable` and `readableLink`:
```
@ApiProperty(attributes={"fetchEager": true})
```
ping @bendavies could you give this a try?

Allow to fetchEager a non-serializable property fix #1290

---

src/Serializer/AbstractItemNormalizer.php

| Fixed tickets | #1210 
And...... Nothing happened :D.
Though, really unsure on how I could test this to avoid regression. There's no point in unit-testing it because it's not impacting the normalization, instead it may impact features that rely on the same context. Also, we can't test if a feature has been executed (like `force_eager=false`) with behat...

Keep propagating the correct context to relations when (de)normalizing

---

features/bootstrap/FeatureContext.php
features/main/default_order.feature
src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Orm/Extension/OrderExtensionTest.php
tests/Fixtures/TestBundle/Entity/Dummy.php
tests/Fixtures/TestBundle/Entity/Foo.php

| Fixed tickets | #1246
| Doc PR        | api-platform/doc#235

Fix 1246: configure default order on ApiResource annotation

---

features/serializer/property_filter.feature
src/Serializer/Filter/PropertyFilter.php
tests/Fixtures/TestBundle/Entity/DummyProperty.php
tests/Fixtures/app/config/config.yml
tests/Serializer/Filter/PropertyFilterTest.php

Similar to #1333 but for the property filter. Doc PR will follow in the week for both PR

[2.1] Allow to specify a whitelist of properties for Property Filter

---

features/serializer/group_filter.feature
src/Serializer/Filter/GroupFilter.php
tests/Fixtures/TestBundle/Entity/DummyGroup.php
tests/Fixtures/app/config/config.yml
tests/Serializer/Filter/GroupFilterTest.php

This PR aims to give the possibility to restrict the Group Filter application.
The use case would be for example when exposing books with author, to protect calling `/books?goups[]=author_sensitive_data`.
If this PR is welcome, I'll do it for the Property Filter and provide a doc PR

[2.1] Allow to specify a whitelist of serialization groups for Group Filter

---

features/jsonld/context.feature
src/JsonLd/ContextBuilder.php
tests/JsonLd/ContextBuilderTest.php

| Fixed tickets | #1224
According to the specs I think that the `#` character is there to separate the URL from the given element, for example:
```
"@context": {
"name": "http://example.com/organization#name"
},
```
I'm really no json-ld expert, let me know if removing `#` doesn't seem correct to you.

Fix #1224 json-ld context should not be prefixed by #

---

tests/Bridge/Symfony/Validator/EventListener/ValidateListenerTest.php

Avoid `count(): Parameter must be an array or an object that implements Countable`error un PHP7.2

Avoid `count()` error in testsuite for PHP7.2

---

src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | api-platform/api-platform#381
Since api-platform/core#1315, the pagination parameter is added to Swagger.
This PR adds the itemsPerPage (when needed).
It should fix api-platform/api-platform#381

Add itemsPerPage to swagger doc

---

features/doctrine/date_filter.feature
features/main/crud.feature
src/Bridge/Doctrine/Orm/Filter/DateFilter.php
tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php

| Fixed tickets | #1326
| Doc PR        | api-platform/doc#244
The DateFilter `?property[after]=date` should filter on `>`, not on `>=` to have only the items with date after the value

Fix #1326 (DateFilter before/after filters on before or equals/after or equals)

---

src/Bridge/Doctrine/Orm/Util/QueryChecker.php
src/Bridge/Doctrine/Orm/Util/QueryJoinParser.php
tests/Bridge/Doctrine/Orm/Util/QueryCheckerTest.php
tests/Bridge/Doctrine/Orm/Util/QueryJoinParserTest.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/360

fix api-platform/#360 QueryChecker with class join

---

src/Bridge/Doctrine/Orm/Filter/DateFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php

Those types have been added in doctrine/dbal 2.6.0
I didn't added a PHPUnit test because I don't want to bump min requirement.

[2.1] Allow to use Immutable date/time

---

src/Hydra/Serializer/DocumentationNormalizer.php

Denormalization_context is ignored due to unmerged arrays as expected.
If someone have an elegant way to merge those arrays. I tried with array_merge but it add an other level of array :(
ping @dunglas

Hotfix to handle denormalization_context on hydra documentation

---

src/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProvider.php
src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
tests/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProviderTest.php
tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php

NelmioApiDocBundle 3 has native support for API Platform. Deprecating our support for v2.

Deprecate NelmioApiDoc 2 support

---

phpunit.xml.dist
src/Api/OperationTypeDeprecationHelper.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Metadata/Extractor/XmlExtractor.php
src/PathResolver/DashOperationPathResolver.php
src/PathResolver/UnderscoreOperationPathResolver.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php
tests/Bridge/Symfony/Routing/RouteNameGeneratorTest.php
tests/Bridge/Symfony/Routing/RouteNameResolverTest.php
tests/Bridge/Symfony/Routing/RouterOperationPathResolverTest.php
tests/Metadata/Resource/Factory/ExtractorResourceMetadataFactoryTest.php
tests/PathResolver/CustomOperationPathResolverTest.php
tests/PathResolver/DashOperationPathResolverTest.php
tests/PathResolver/UnderscoreOperationPathResolverTest.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

PHPUnit works better with deprecations when the Symfony PHPUnit Bridge is enabled...

Enable the Symfony PHPUnit bridge

---

composer.json
phpunit.xml.dist
src/Serializer/AbstractItemNormalizer.php

> Class "Symfony\Bridge\PhpUnit\SymfonyTestsListener" does not exist
We obtain this message with `deps=low` when we run PHPUnit, but tests are not executed and the command exits with 0.
About the `weak_vendors`, see https://github.com/api-platform/core/pull/1368#issuecomment-329133122.

Fix Travis when deps are low

---

src/DataProvider/ChainSubresourceDataProvider.php
src/DataProvider/SubresourceDataProviderInterface.php

| Fixed tickets | no
operationName can be null in SubresourceDataProviders like the other DataProviders.

operationName parameter should be optional in SubresourceDataProviders

---

features/serializer/property_filter.feature
src/Serializer/Filter/PropertyFilter.php
tests/Fixtures/TestBundle/Entity/DummyProperty.php
tests/Fixtures/app/config/config.yml
tests/Serializer/Filter/PropertyFilterTest.php

| Doc PR        | to come
I'm using the GroupFilter with whitelist since it got merged but never really tried/used the ProprertyFilter whitelist in an application and just relied on the tests I wrote initially. When trying to use it in a real application last week I noticed that the behavior was not the expected one.
An example to reproduce the issue is to whitelist a `foo` property. Then when requesting `/resource?properties[]=bar`, `foo`will be present in the serialized entity.
Another thing I've been trying to fix is the filter declaration and it might be considered as a BC break but given the …

[PropertyFilter] Fix whitelist comparison

---

features/swagger/docs.feature
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Fixtures/TestBundle/Entity/RelatedToDummyFriend.php
tests/Fixtures/app/config/config.yml

I notice that swagger documentation retrieve resourceMetadata instead of subResourceMetadata for filters and serializationContext.
I added a behat test to cover this use case.

Swagger subcollection documentation issue

---

features/security/validate_response_types.feature
src/EventListener/AddFormatListener.php
tests/EventListener/AddFormatListenerTest.php

Getting "Not found" on a route where you are getting an object can get
real confusing.

Provide a better exception message

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Fixed tickets | #1394
When HTTP Cache invalidation is enabled, the `api_platform.doctrine.listener.http_cache.purge` service is created. This service depends on `api_platform.http_cache.purger` which is an alias that is only defined when at least one Varnish URL is defined.
With this PR, the alias is defined even if no Varnish URL is defined, which fixes the dependency issue.

Fix missing service when no Varnish URL is defined

---

composer.json

2.1.x-dev is already taken by the 2.1 branch, and this should represent
the next minor version anyway.
The branch alias was still pointing to the old 2.1 version.

Bump branch alias to 2.2.x-dev

---

src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Hydra/Serializer/ConstraintViolationListNormalizer.php
src/Problem/Serializer/ConstraintViolationListNormalizer.php
src/Serializer/AbstractConstraintViolationListNormalizer.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Hydra/Serializer/ConstraintViolationNormalizerTest.php
tests/Problem/Serializer/ConstraintViolationNormalizerTest.php

Follows #1364.
* Remove code duplication (https://insight.sensiolabs.com/projects/92d78899-946c-4282-89a3-ac92344f9a93/analyses/2123)
* Enforce type safety (now the type is `?array`, if null is passed, it means the whole payload will be serialized)
ping @pierre-H

Improve payload support and remove duplicate code in ConstraintViolationListNormalizer

---

features/bootstrap/FeatureContext.php
features/doctrine/search_filter.feature
src/Annotation/ApiFilter.php
src/Bridge/Symfony/Bundle/ApiPlatformBundle.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php
src/Bridge/Symfony/Bundle/Resources/config/metadata/annotation.xml
src/Metadata/Resource/Factory/AnnotationResourceFilterMetadataFactory.php
src/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php
src/Util/AnnotationFilterExtractorTrait.php
src/Util/ReflectionClassRecursiveIterator.php
tests/Annotation/ApiFilterTest.php
tests/Bridge/Symfony/Bundle/ApiPlatformBundleTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPassTest.php
tests/Fixtures/TestBundle/Doctrine/Orm/Filter/AnotherDummyFilter.php
tests/Fixtures/TestBundle/Entity/DummyCar.php
tests/Fixtures/TestBundle/Util/AnnotationFilterExtractor.php
tests/Fixtures/app/config/config.yml
tests/Metadata/Resource/Factory/AnnotationResourceFilterMetadataFactoryTest.php
tests/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactoryTest.php
tests/Util/AnnotationFilterExtractorTraitTest.php

| Fixed tickets | #1033 
Please, let me know if I'm on the right track or if I should have done some things differently :).
Docs:
```
* @ApiFilter(DateFilter::class, strategy=DateFilter::EXCLUDE_NULL)
* @ApiFilter(BooleanFilter::class)
* @ApiFilter(PropertyFilter::class, arguments={"parameterName"="foobar"})
* @ApiFilter(SearchFilter::class, properties={"colors.prop": "ipartial"})
* @ApiFilter(SearchFilter::class, strategy="partial")
```

Implement Annotation filters @ApiFilter

---

.travis.yml

| Tests pass?   | hopefully
| Doc PR        | n / a
If api-platform uses upstream libs in a deprecated way, we should be aware
of it.

Add job to test upstream libs deprecations

---

features/main/relation.feature
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Serializer/AbstractItemNormalizer.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/app/config/config.yml
tests/Serializer/AbstractItemNormalizerTest.php

| Bug fix?      | yes/no (depends on the POV)
| New feature?  | yes/no (same)
| Fixed tickets | https://github.com/api-platform/api-platform/issues/249 https://github.com/api-platform/core/issues/1363

Allow plain IDs with `allow_plain_identifiers`

---

src/HttpCache/EventListener/AddTagsListener.php
tests/HttpCache/EventListener/AddTagsListenerTest.php

When a collection is empty, the cache tag of the collection itself is missing from the response, which cannot be invalidated later when the collection changes.

Fix missing cache tag on empty collections

---

src/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php

Fix compatibility with PHP7.2: `Warning: get_class() expects parameter 1 to be object, null given`

Fix tags addition with an empty value

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

| Doc PR        | api-platform/docs#315

Add feature to update swagger context for properties

---

src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
src/Hydra/Serializer/DocumentationNormalizer.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php

Fixes the hydra documentation normalization by using the `subresourceOperationFactory`

fix hydra documentation normalizer with subresources

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Related to symfony/symfony#24673. It may be a small BC break, but it's mandatory to support Symfony Flex and it was a bad idea (mine) from the very beginning.

Don't use dynamic values in service keys

---

src/Swagger/Serializer/DocumentationNormalizer.php

I do not know when the type is supposed to be null, but I am using the `YamlExtractor` and it always seems to be the case with that metadata specification method.
Refs #1433

Include swagger context even when type is null

---

src/Bridge/Symfony/Routing/ApiLoader.php
src/Bridge/Symfony/Routing/OperationMethodResolver.php
src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php
tests/Fixtures/TestBundle/Entity/CustomActionDummy.php
tests/Fixtures/TestBundle/Entity/OverriddenOperationDummy.php
tests/Fixtures/TestBundle/Entity/RelationEmbedder.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php
tests/Metadata/Resource/Factory/OperationResourceMetadataFactoryTest.php

Before:
```php
/**
*     collectionOperations={
*         "get"={"method"="GET"},
*         "post"={"method"="POST"}
*     },
*     itemOperations={
*         "get"={"method"="GET"}
*     }
*/
```
Now:
```php
/**
*     collectionOperations={"get", "post"},
*     itemOperations={"get"}
*/
```
Before:
```php
/**
*     attributes={"access_control"="has_role('ROLE_USER')"},
*     collectionOperations={
*         "get"={"method"="GET"},
*         "post"={"method"="POST", "access_control"="has_role('ROLE_ADMIN')"}
*     },
* …
```

Make it easier to configure operations

---

src/DataProvider/PaginatorInterface.php

`count()` could return the number of pages, or the total number of items, or the number of items on the current page. Looking at the doctrine ORM implementation, it looks like it should be the number of items on the current page, so let's document that, maybe it is relied on somewhere?
I'm contributing this on 2.1, but on master the implementation was moved in an abstract class. Here is how it looks: https://github.com/api-platform/core/blob/c7e2cda19a906d9d13d145312fe9ec231a78d45e/src/Bridge/Doctrine/Orm/AbstractPaginator.php#L71-L74

Document what count() is supposed to return

---

src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Util/EagerLoadingTrait.php
src/Bridge/Doctrine/Orm/Util/QueryChecker.php
tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
tests/Bridge/Doctrine/Orm/Util/QueryCheckerTest.php
tests/Bridge/Doctrine/Orm/Util/QueryJoinParserTest.php

| Fixed tickets | #1313 + no ticket see below
1. First commit is a fix on `FilterEagerLoadingExtension` with composite identifiers when one of the composite identifier is not an association. I also improved the testability of `EagerLoadingTrait` by using `ClassMetadataInfo` methods instead of public properties (easier to prophesize).
2. Merges #1449  + add a test + improve comment

Fix filter eager loading & merge #1449 + test

---

src/Bridge/Symfony/Routing/ApiLoader.php
tests/Bridge/Symfony/Routing/ApiLoaderTest.php

| Doc PR        | [#330](https://github.com/api-platform/docs/pull/330)
I was trying to associate a default key/value association to a given route following [this Symfony documentation](https://symfony.com/doc/current/routing/extra_information.html) when I realized there is actually no way to do this as the `defaults` configuration of a Symfony route is not available in operations. This PR tries to fix this.
I don't know much about the new subresources feature yet and couldn't really guess if it was relevant to also cover these routes. 
Please let me know if this PR sounds fine to you and if I …

Add missing Symfony Routing options to operations configuration

---

features/main/serializable_item_data_provider.feature
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DataProviderPass.php
src/Bridge/Symfony/Bundle/Resources/config/data_provider.xml
src/DataProvider/SerializerAwareDataProviderInterface.php
src/DataProvider/SerializerAwareDataProviderTrait.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/DataProvider/SerializableItemDataProvider.php
tests/Fixtures/TestBundle/Entity/SerializableResource.php
tests/Fixtures/TestBundle/Serializer/Denormalizer/SerializableResourceDenormalizer.php
tests/Fixtures/app/config/config.yml

| Fixed tickets | #1165
| Doc PR        | WIP
Calling any external API from a custom ItemDataProvider, it may return a JSON which must be deserialized to my object. To do so, I must inject the `serializer` service in my custom ItemDataProvider, which creates a CircularReferenceException. A solution could be to use [service locators](http://symfony.com/blog/new-in-symfony-3-3-service-locators), but the following solution can manage it more easily for final users.
This PR allows to support `SerializerAwareInterface` on ItemDataProvider to prevent this exception.

[RFR] Add SerializerAwareInterface supports on ItemDataProvider

---

features/bootstrap/FeatureContext.php
features/main/default_order.feature
phpstan.neon
src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Bridge/Doctrine/Orm/Util/QueryBuilderHelper.php
tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
tests/Bridge/Doctrine/Orm/Extension/OrderExtensionTest.php
tests/Fixtures/TestBundle/Entity/Foo.php
tests/Fixtures/TestBundle/Entity/FooDummy.php

| Fixed tickets | #1246, https://github.com/api-platform/core/pull/1323#discussion_r134468290
| Doc PR        | https://github.com/api-platform/docs/pull/269

[RFR] Issues/1246

---

src/Annotation/ApiResource.php
src/Bridge/Symfony/Routing/ApiLoader.php
src/Metadata/Extractor/XmlExtractor.php
src/Metadata/Extractor/YamlExtractor.php
src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
src/Metadata/Resource/Factory/ExtractorResourceMetadataFactory.php
src/Metadata/Resource/ResourceMetadata.php
src/Metadata/schema/metadata.xsd
src/Operation/Factory/SubresourceOperationFactory.php
tests/Fixtures/FileConfigurations/resources.xml
tests/Fixtures/FileConfigurations/resources.yml
tests/Fixtures/FileConfigurations/single_resource.yml
tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php
tests/Metadata/Resource/Factory/FileConfigurationMetadataFactoryProvider.php
tests/Metadata/Resource/ResourceMetadataTest.php
tests/Operation/Factory/SubresourceOperationFactoryTest.php

| Fixed tickets | #1479 
Also backported #1472 to subresources

fix #1479 allow to override SubresourceOperations through metadata

---

src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
src/Util/AnnotationFilterExtractorTrait.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPassTest.php
tests/Fixtures/DummyEntityFilterAnnotated.php
tests/Util/AnnotationFilterExtractorTraitTest.php

| Doc PR        | needed for https://github.com/api-platform/docs/pull/314
Allows:
```
@ApiFilter(OrderFilter::class, properties={"one", "two"}
```
Also removes the required `orderParameterName` argument in the filter.

Fix annotation filters + OrderBy autowiring capabilities

---

.travis.yml
Dockerfile.coverage
brigade.js

| Tests pass?   | I hope
| Fixed tickets | #1489

Use Brigade for coverage

---

src/Bridge/Doctrine/Orm/ItemDataProvider.php
tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php

When building query with custom doctrine type parameter like ```Ramsey\Uuid\Doctrine\UuidType```, it is essential for oci8 extension to get converted value, because apparently it cannot cast it to string. (pdo/mysql doesn't have problem with that)
Also It could be potential problem with other custom doctrine types used as identifiers.
My configuration:
PHP app: docker image 7.1-fpm with latest oci8 extension from pecl
Database: docker image: oracle 12c
Identifier type: ```Ramsey\Uuid\Doctrine\UuidType```
Error from log:
```
[2017-11-20 23:09:20] request.CRITICAL: Uncaught PHP …
```

Fix for custom identifier DBAL Type (oracle)

---

src/Annotation/ApiSubresource.php
src/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php
src/Metadata/Property/SubresourceMetadata.php
src/Metadata/schema/metadata.xsd
src/Operation/Factory/SubresourceOperationFactory.php
tests/Fixtures/FileConfigurations/resources.xml
tests/Fixtures/FileConfigurations/resources.yml
tests/Operation/Factory/SubresourceOperationFactoryTest.php

| Fixed tickets | #1316
| Doc PR        | https://github.com/api-platform/docs/pull/351
Proper PR from original: https://github.com/api-platform/core/pull/1512

Subresource maxDepth

---

.travis.yml
appveyor.yml
behat.yml.dist
features/bootstrap/FeatureContext.php
features/bootstrap/JsonContext.php
features/doctrine/date_filter.feature
features/doctrine/numeric_filter.feature
features/doctrine/search_filter.feature
features/http_cache/tags.feature
features/main/composite.feature
features/main/uuid.feature
features/serializer/property_filter.feature
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/DateFilter.php
src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
tests/Fixtures/TestBundle/Entity/DummyDate.php
tests/Fixtures/TestBundle/Entity/User.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config_mysql.yml
tests/Fixtures/app/config/config_postgres.yml
tests/Fixtures/app/config/config_test.yml
tests/Fixtures/app/config/parameters_mysql.yml
tests/Fixtures/app/config/parameters_postgres.yml
tests/Fixtures/app/console

Stated in [Advanced field value conversion using custom mapping types](http://docs.doctrine-project.org/en/latest/cookbook/advanced-field-value-conversion-using-custom-mapping-types.html):
> When using DQL queries, the convertToPHPValueSQL and convertToDatabaseValueSQL methods only apply to identification variables and path expressions in SELECT clauses. Expressions in WHERE clauses are not wrapped!
We won't see any difference in sqlite for example ([know why here](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/known-vendor-issues.html)) but I'm …

Use database type conversion in Filters (test postgres+mysql)

---

CHANGELOG.md
features/graphql/mutation.feature
src/Bridge/Graphql/Resolver/ItemMutationResolverFactory.php
src/Bridge/Graphql/Resolver/ItemMutationResolverFactoryInterface.php
src/Bridge/Graphql/Type/SchemaBuilder.php
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php
tests/Bridge/Graphql/Resolver/ItemMutationResolverFactoryTest.php
tests/Bridge/Graphql/Type/SchemaBuilderTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

[WIP] GraphQL Mutation support

---

.travis.yml

Restore the Postgres tests

---

features/main/relation.feature
src/Serializer/AbstractItemNormalizer.php

`POST /relation_embedders`
with body:
```json
{
"related": "foo"
}
```
will throw an error:
```Type error: Argument 2 passed to ApiPlatform\Core\Metadata\Property\Factory\CachedPropertyMetadataFactory::create() must be of the type string, integer given, called in src/Serializer/AbstractItemNormalizer.php on line 163 (Behat\Testwork\Call\Exception\FatalThrowableError)```
This is because "related" is marked as a "writable link"

Fix: Passing nor an unknown iri nor an array in an embedded relation throws an error

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

Trigger eager loading when using the attributes serializer option

---

src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
src/Bridge/Doctrine/Orm/Filter/DateFilter.php
src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php
src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
src/Bridge/Doctrine/Orm/Filter/RangeFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/Bridge/Doctrine/Orm/Util/QueryBuilderHelper.php
tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
tests/Bridge/Doctrine/Orm/Extension/OrderExtensionTest.php
tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php

This PR allow creating our own query builder and apply filter to it.
There was a "bug" forcing the main alias to be `o` but it's not necessarily the case when creating our own query builder.

Allow another query builder alias

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

Always skip relations marked as [extra lazy](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/extra-lazy-associations.html), because if using this type, the user will probably want to retrieve only a subset of the collection, and not the entire one.

Always skip eager loading of collections marked as extra lazy

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

Follows #1546. This PR allows API Platform to add useful SQL `JOIN` clauses and to remove the useless ones according to properties selected by the client using the [property filter](https://api-platform.com/docs/core/filters#property-filter).
That's a massive performance improvement when using this filter.
I'll also use this feature later to improve the generated SQL queries when using GraphQL. It will allow to only fetch what is required for a given GraphQL query while to reducing dramatically the number of issued SQL queries for a whole GraphQL request.

Improved joins when using the properties filter

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Some services are autoconfigured in ApiPlatform. Filters are not beside their simplicity.
Add filters in DIC autoconfiguration.

Autoconfigure filters

---

src/Bridge/Doctrine/Orm/Paginator.php

| Fixed tickets | n:a
Follows #1561.

Always return a float in Paginator::getLastPage()

---

src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Bridge/Symfony/Bundle/Resources/config/metadata/metadata.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Add service aliases for autowiring in symfony>3.4

---

src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php

| Tests pass?   | I guess
---
The value of title/description/version should not be empty.
If there are empty, we got the following exception:
```
Type error: Argument 8 passed to ApiPlatform\Core\Bridge\Symfony\Bundle\Action\SwaggerUiAction::__construct() must be of the type string, null given, called in /var/www/server/backend/var/cache/dev/appDevDebugProjectContainer.php on line 1155
```
How to reproduce:
```
#config.yml
api_platform:
title: #nothing explicitly 
```

[SymfonyBundle] Fixed the configuration

---

tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| Fixed tickets | https://github.com/api-platform/core/pull/1563#discussion_r157848790
ping @chalasr @dunglas @lyrixx

Fix null title/description configuration (#1563 followup)

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Introduced by d3b690ecb2944717faeea659f2b14692de20b361

fix error when disabling eager_loading

---

composer.json
features/bootstrap/FeatureContext.php

use doctrine 2.6

---

features/graphql/collection.feature
features/graphql/introspection.feature
features/graphql/query.feature
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Graphql/Resolver/Factory/CollectionResolverFactory.php
src/Graphql/Resolver/Factory/ItemMutationResolverFactory.php
src/Graphql/Resolver/Factory/ResolverFactoryInterface.php
src/Graphql/Resolver/ItemResolver.php
src/Graphql/Resolver/ResourceFieldResolver.php
src/Graphql/Serializer/ItemNormalizer.php
src/Graphql/Type/SchemaBuilder.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Entity/Node.php
tests/Graphql/Resolver/Factory/CollectionResolverFactoryTest.php
tests/Graphql/Resolver/Factory/ItemMutationResolverFactoryTest.php
tests/Graphql/Resolver/ItemResolverTest.php
tests/Graphql/Resolver/ResourceFieldResolverTest.php
tests/Graphql/Serializer/ItemNormalizerTest.php
tests/Graphql/Type/SchemaBuilderTest.php

Implementation of the GraphQL's [Relay Global Object Identification Specification](https://facebook.github.io/relay/graphql/objectidentification.htm) using hypermedia IRIs.
You can now execute this kind of queries on the GraphQL endpoint:
```graphql
{
node(id: "/product/ABC") {
id
... on Product {
name
}
}
}
```
Note: I'll probably extract the GraphQL type builder in a from the `SchemaBuilder` in a following PR.

Implement the Relay Global Object Identification Specification

---

features/graphql/mutation.feature
src/Graphql/Resolver/Factory/ItemMutationResolverFactory.php
src/Graphql/Type/SchemaBuilder.php
tests/Graphql/Resolver/Factory/ItemMutationResolverFactoryTest.php

Implement the [Relay Input Object Mutations Specification](https://facebook.github.io/relay/graphql/mutations.htm).
When this PR will be merged, we'll respect 100% of the Relay spec!

Implement the Relay specification for mutations

---

composer.json

[Composer] Sort packages

---

features/graphql/mutation.feature
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Bridge/Symfony/Bundle/Resources/config/validator.xml
src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
src/Bridge/Symfony/Validator/Exception/ValidationException.php
src/Bridge/Symfony/Validator/Validator.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/Serializer/AbstractConstraintViolationListNormalizer.php
src/Validator/EventListener/ValidateListener.php
src/Validator/Exception/ValidationException.php
src/Validator/ValidatorInterface.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Validator/EventListener/ValidateListenerTest.php
tests/Bridge/Symfony/Validator/Exception/ValidationExceptionTest.php
tests/Bridge/Symfony/Validator/ValidatorTest.php
tests/Validator/EventListener/ValidateListenerTest.php

Validate data during GraphQL mutations. Also includes a refactoring of the validation system.
TODO:

Add validation for GraphQL mutations

---

src/Serializer/SerializerContextBuilder.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Serializer/SerializerContextBuilderTest.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | #1583
| Doc PR        | https://github.com/api-platform/docs/pull/368
---
Hello.
I want to customize the Definition key as state in #1583.
I found this way:
```php
/**
*      collectionOperations={
*          "post"={
*              "method"="POST",
*              "denormalization_context"={"groups"={"v2_user_read"}, "swagger_definition_name": "HERE_WE_GO"},
*          },
*      },
* )
*/
class User
{
```
And in order to reduce the code duplication,
when there are many (de)normalization_context,
we can use this shortcut:
```php
/**
*      collectionOperations={
* …
```

[Swagger] Added support for customizing the Definition key

---

features/main/relation.feature
features/main/subresource.feature
src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
tests/Fixtures/TestBundle/Entity/FourthLevel.php
tests/Fixtures/TestBundle/Entity/ThirdLevel.php

| Fixed tickets | #1442
Fix the build of the Doctrine query for subresources nested in more than 2 levels of depth.
Use a recursive function instead of a while loop.

Fix Doctrine query for nested subresources

---

src/Bridge/Symfony/Routing/Router.php

---
BTW, we could just clone the context, and replace few information:
```php
public function match($pathInfo)
{
$baseContext = $this->router->getContext();
$pathInfo = str_replace($baseContext->getBaseUrl(), '', $pathInfo);
$context = clone $baseContext;
$context->setMethod('GET');
$context->setPathInfo($pathInfo);
$this->router->setContext($context);
try {
return $this->router->match($pathInfo);
} finally {
$this->router->setContext($baseContext);
}
}
```
---
Why do I hit all the bugs :/

[Routing] Also copy the Host in the Router::match

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Bundle/Resources/config/routing/docs.xml
src/Bridge/Symfony/Routing/ApiLoader.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Bridge/Symfony/Routing/ApiLoaderTest.php

| Fixed tickets | #1568
| Doc PR        | api-platform/doc#365

Ability to disable entrypoint and /api/docs

---

features/hydra/error.feature
src/Serializer/AbstractItemNormalizer.php

| Fixed tickets | #1624, #1363, #427
Allow updating nested resource on POST

Allow updating nested resource on POST

---

features/bootstrap/FeatureContext.php
features/hal/always_identifier.feature
features/json/always_identifier.feature
features/jsonld/always_identifier.feature
src/Annotation/ApiProperty.php
src/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php
src/Metadata/Property/PropertyMetadata.php
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/Entity/AlwaysIdentifierDummy.php
tests/Metadata/Property/PropertyMetadataTest.php

| Fixed tickets | #1130 
| Doc PR        | https://github.com/api-platform/docs/pull/373
The goal here is to allow the users to display only the IRI of a nested resource. It's very usefull on trees or on big entities which have multiple links on a same other entity.
As the MaxDepth annotation doesn't allow us to do that I have created a new annotation option :
```php
/**
* @ApiResource(attributes={
*     "normalization_context"={"groups": {"alwaysIdentifierGroup"}, "enable_always_identifier"=true}
* })
* @ORM\Entity
*/
class AlwaysIdentifierDummy 
{
/**
* @var ArrayCollection children dummies
*
* …
```

alwaysIdentifier annotation option implementation

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| New feature?  | yes/no
| Fixed tickets | #1655
| Doc PR        | need to do
It's better for flex.

feat Ability to configure resource_class_directories

---

features/doctrine/date_filter.feature
features/main/crud.feature
src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
tests/Fixtures/app/config/config_test.yml

On 2.2-beta-1 if a order filter and let say a date filter are declared on the same property (`createdAt`), then calling `/dummies?createdAt[before]=2018-01-24` will trigger the date filter and cause a
`Type error: strtoupper() expects parameter 1 to be string, array given in vendor/api-platform/core/src/Bridge/Doctrine/Orm/Filter/OrderFilter.php:134`

Avoid to call OrderFilter on wrong properties

---

src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
tests/Bridge/Doctrine/Orm/Extension/OrderExtensionTest.php

| Fixed tickets | #1670
This PR is related to `2.1` version and would be updated too in master branch.    
To push it to `master` branch, we have to add the code `$queryBuilderProphecy->getRootAliases()->shouldBeCalled()->willReturn(['o']);` in my test.    
Do i need to open a second PR ?

 Fix OrderExtension to provide ordering with embedded fields

---

features/main/configurable.feature
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Entity/FlexConfig.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/api_platform/flex.yaml

| Doc PR        | api-platform#383
Example usage:
```yaml
App\Entity\Greeting: ~
```

Support Flex directory structure for YAML and XML configs

---

src/Metadata/Extractor/XmlExtractor.php
src/Metadata/schema/metadata.xsd
tests/Fixtures/FileConfigurations/empty-operation.xml
tests/Metadata/Extractor/XmlExtractorTest.php

A companion PR of #1470.
Now instead of:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<resources xmlns="https://api-platform.com/schema/metadata"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://api-platform.com/schema/metadata
https://api-platform.com/schema/metadata/metadata-2.0.xsd">
<resource class="App\Entity\Greeting">
<collectionOperations>
<collectionOperation name="get">
<attribute name="method">GET</attribute>
</collectionOperation>
</collectionOperations>
</resource>
</resources>
```
It's possible to write:
```xml
<?xml …
```

Allow empty operations in XML configs

---

src/Bridge/Doctrine/Orm/Extension/FilterExtension.php
tests/Bridge/Doctrine/Orm/Extension/FilterExtensionTest.php

À vous deprecation notice by routing to the new filter system.

Fix deprecation notice on filters applied on collection without params

---

features/graphql/mutation.feature
src/GraphQl/Type/SchemaBuilder.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/535
Nested mutations are not a part of the specification. See:
- https://github.com/webonyx/graphql-php/issues/189
- https://github.com/facebook/graphql/issues/252
- https://github.com/graphql/graphql-js/issues/672
Moreover, it would be laborious to implement it. We would have to change the behavior of the ItemNormalizer and we would have to move the validation/access control of the resolver elsewhere to be reused in the normalizer.
Therefore, it seems a better solution to force IRIs for subresources in mutations.
This PR also fixes …

[GraphQL] Fix type for subresource

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Doc PR        | not needed imho
Noticed my class implementing `SubresourceDataProviderInterface` was not automatically tagged correctly :-)

Autoregister classes implementing SubresourceDataProviderInterface

---

features/doctrine/order_filter.feature
src/EventListener/ReadListener.php
src/Util/RequestParser.php

When requesting the API with a url like `/foo?order[baz]=asc&order[bar]=asc` the order is not preserved anymore as it used to be since 1.0
The root cause is the Symfony `Request::getQueryString()` not preserving the order when re-generating the string.
For now I've ported the Symfony function and removed the sorting thing for now.

Ensure that OrderFilter preserves the query string parameters order

---

features/main/configurable.feature
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php

This was an issue for some people that decided to change the way the folder
of configuration of api platform is defined.
The idea of this fix is to not interfer with the user configuration.
| Fixed tickets | none, but still an issue
```yaml
api_platform:
mapping:
paths: ['%kernel.project_dir%/config/api_platform/resources']
```
_Then imagine having the `%kernel.project_dir%/config/api_platform/routes` folder._
The dump of resources folders is:
```
array:2 [
0 => "/var/www/apps/cadi-back/config/api_platform/resources"
1 => "/var/www/apps/cadi-back/config/api_platform"
]
```
The dump of resources …

Fix wrong automatic configuration for Sf flex

---

src/EventListener/ReadListener.php

According to https://github.com/api-platform/core/blob/fb7cc479046c03352d96dedc57d97f1dbc3fe323/src/EventListener/ReadListener.php#L73, the normalization context array is in the `normalization_context` index of the context array. So, if we pass the whole context array to the `EagerLoadingExtension::joinRelations()` method, we can't properly retrieve groups, max depth and attributes.

Fix initialization of the serialization context

---

.travis.yml
CONTRIBUTING.md
appveyor.yml
behat.yml.dist
features/doctrine/order_filter.feature
features/main/exposed_state.feature
features/main/relation.feature
src/Bridge/Doctrine/Common/DataPersister.php
tests/Bridge/Doctrine/Common/DataPersisterTest.php
tests/Fixtures/TestBundle/Entity/DummyTableInheritanceRelated.php
tests/Fixtures/TestBundle/Entity/TruncatedDummy.php

The state of the object presented after a POST/PUT operation doesn't reflects the actual status of the persisted object(s).
With an entity declared with `@ORM\Column(type="decimal", precision=4, scale=1, nullable=false)` for example:
POST/PUT request to the entity with value
```
{
"value": 20.334"
}
```
would return 
```
{
...
"value": 20.334"
...
}
```
but then the GET would return 
```
{
...
"value": 20.3"
...
}
```
The exposed values  in GET/PUT/POST are always consistent
```
{
...
"value": 20.3"
...
}
```
I also found that tests marked with the `@postgres` tag were never run on …

BugFix: Fix object state inconsistency after persitence

---

features/doctrine/search_filter.feature
src/Annotation/ApiFilter.php
src/Util/AnnotationFilterExtractorTrait.php
tests/Fixtures/TestBundle/Entity/DummyCar.php
tests/Util/AnnotationFilterExtractorTraitTest.php

| Doc PR        | not yet
When using multiple filters of the same class with @ApiFilter annotation( for example `GroupFilter::class`, one with option `overrideDefaultGroups:true` and the other one with `overrideDefaultGroups:false` ), only the first one was registered. 
This PR try to fix that by adding an 'id' option to the ApiFilter filter annotation to make it unique per-class and per-filter.

Allow to declare multiple filters with same class

---

.travis.yml
src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php

| Fixed tickets | #1688 
| Doc PR        | https://github.com/api-platform/docs/pull/389
Closes #1688.

Support YAML output from SwaggerCommand with --yaml

---

features/main/custom_operation.feature
src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php
tests/Fixtures/TestBundle/Controller/CustomActionController.php
tests/Fixtures/TestBundle/Entity/CustomActionDummy.php
tests/Metadata/Resource/Factory/OperationResourceMetadataFactoryTest.php

| Doc PR        | will open this is upvoted
Inspired by and following #1470  This PR aims to give a shortcut configuration for custom operation. Over the time I find my self repeating this code a lot. 
Before:
```
/**
*     collectionOperations={
*         "get",
*         "post",
*         "custom_denormalization_action"={"route_name"="custom_denormalization_action"},
*     },
*     itemOperations={
*         "get",
*         "put",
*         "custom_normalization_action"={"route_name"="custom_normalization_action"},
*     }
* )
*/
```
After:
```
/**
* …
```

Ease custom operation configuration

---

src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Util/QueryBuilderHelper.php
tests/Bridge/Doctrine/Orm/Util/QueryBuilderHelperTest.php

`$queryBuilder->getRootAliases()[0]` is not working in the case of the FilterEagerLoadingExtension because it uses subquery and the first root alias is not necessarily the one we want

fix bc break regaring the FilterEagerLoadingExtension

---

features/main/relation.feature
src/Serializer/AbstractItemNormalizer.php

A normalizer can work on any data type, not only on arrays. This PR reverts a BC break introduced in #1547  preventing non arrays to be normalized, and provides an alternative fix.
ping @jdeniau @ymarillet

Fix a BC break introduced by #1547

---

features/bootstrap/GraphqlContext.php
src/Api/OperationMethodResolverInterface.php
src/Bridge/Doctrine/EventListener/WriteListener.php
src/Bridge/FosUser/EventListener.php
src/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProvider.php
src/Bridge/Symfony/Routing/OperationMethodResolver.php
src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
src/EventListener/DeserializeListener.php
src/EventListener/ReadListener.php
src/EventListener/RespondListener.php
src/EventListener/WriteListener.php
src/Serializer/SerializerContextBuilder.php
src/Validator/EventListener/ValidateListener.php
tests/Bridge/Doctrine/EventListener/WriteListenerTest.php
tests/Bridge/FosUser/EventListenerTest.php
tests/Bridge/Symfony/Validator/EventListener/ValidateListenerTest.php
tests/EventListener/DeserializeListenerTest.php
tests/EventListener/ReadListenerTest.php
tests/EventListener/RespondListenerTest.php
tests/EventListener/WriteListenerTest.php
tests/Serializer/SerializerContextBuilderTest.php
tests/Validator/EventListener/ValidateListenerTest.php

Remove Request::METHOD_* constants & uppercase HTTP methods

---

src/Bridge/Symfony/Routing/CachedRouteNameResolver.php

Prefering a cherry-pick of 3b53ff2e9041697b8a182beb21dd4ef4b29c3542
https://github.com/api-platform/core/pull/1770
https://github.com/api-platform/core/issues/1769

Backport: fix route name resolver cache with subresources

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/app/config/config_test.yml

Follows https://github.com/api-platform/core/issues/1724#issuecomment-367701990
TODO: fix tests
It's significant on my computer:
**Before**
Behat: 2m18.08s (2.16Gb)
PHPUnit: Time: 21.17 seconds, Memory: 104.25MB
**After**
Behat: 0m42.23s (498.70Mb)
Time: 25.72 seconds, Memory: 102.25MB
Can you try with your code base @jdeniau?

Add a api_platform.metadata_cache parameter

---

src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php

Having this option by default is a good choice since it offers better and more accurate perfomance in many situations. However there is some cases when having the fetch join collection counter productive : like many items retrieved for a simple query without join, as it forces to have 2 queries (first the disctinct, then an IN queries which is worst for performance in heavy table)
This commit allow users to set use fetch join collection to false (it still is true by default) in their resource / operation attributes for those special cases.

Allow to deactivate fetch join collection

---

src/EventListener/SerializeListener.php
src/Serializer/ResourceList.php
tests/EventListener/SerializeListenerTest.php
tests/Serializer/ResourceListTest.php

| Fixed tickets | #1307
In #1307, an anonymous class was introduced to fix a performance problem but it introduced another.
In these `ItemNormalizers`:
https://github.com/api-platform/core/blob/master/src/Hal/Serializer/ItemNormalizer.php#L219
https://github.com/api-platform/core/blob/master/src/JsonApi/Serializer/ItemNormalizer.php#L337
the context is serialized to produce a cache key, but anonymous classes are not serializable: https://3v4l.org/tvMGa.
This effectively disables the intended caching in the HAL and Json API item normalizers.
Blackfire comparison for a HAL endpoint returning 500 items …

Serializer listener performance - anonymous class not serializable

---

src/Bridge/Doctrine/Common/DataPersister.php
tests/Bridge/Doctrine/Common/DataPersisterTest.php

Fix a BC in 2.2.
In 2.1, a `persist` was made **only** on a POST.
In 2.2, the call is also made on a PUT or a PATCH.
See the difference:
- https://github.com/api-platform/core/blob/2.1/src/Bridge/Doctrine/EventListener/WriteListener.php#L57
- https://github.com/api-platform/core/blob/2.2/src/EventListener/WriteListener.php#L49
This PR fix this BC by making the call only when needed, when the entity is not already managed (see http://www.doctrine-project.org/api/orm/2.5/class-Doctrine.ORM.EntityManager.html#_contains).
This BC could result in some issues if changes are done outside the …

Persist data in Doctrine DataPersister only if needed

---

src/Bridge/Symfony/Routing/ApiLoader.php
tests/Annotation/AnnotatedClass.php
tests/Annotation/ApiResourceTest.php
tests/Bridge/Symfony/Routing/ApiLoaderTest.php
tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php

Indeed, all our attributes use snake case except this one.
cc @Toflar

Convert the route prefix attribute name to snake case

---

features/graphql/mutation.feature
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php

Fix an issue in update mutations, when an ID can be denormalized.
For instance, in `Dummy` entity, since there is `setId` method, an update cannot be done.
The error is the following:
`The type of the "id" attribute must be "int", "string" given.`
The first commit is the failing test.
Maybe we also need to add the possibility to change the ID (using `_id` argument)?

[GraphQL] Fix update mutation when ID can be denormalized

---

features/graphql/mutation.feature
src/GraphQl/Serializer/ItemNormalizer.php
src/GraphQl/Type/Definition/InputUnionType.php
src/GraphQl/Type/SchemaBuilder.php
src/Serializer/ItemNormalizer.php
tests/GraphQl/Type/Definition/InputUnionTypeTest.php

| Fixed tickets | #1750
TODO:
Add a new InputUnionType to allow using either an IRI or data for relations.
It allows to modify embedded entities or to update a related existing resource (#1363).

[GraphQL] Embedded entities support for mutations

---

src/Api/CachedIdentifiersExtractor.php
tests/Api/CachedIdentifiersExtractorTest.php
tests/Api/IdentifiersExtractorTest.php

#1101 introduced support for string castable identifier, which was later refactored to `IdentifiersExtractorInterface`, but the support was not maintained in the `CachedIdentifiersExtractor`.
My app uses ramsey uuids for identifiers, and I noticed caching not working here. Using object identifiers effectively disabled the caching of the `CachedIdentifiersExtractor`, making it call the decorated `IdentifiersExtractor` every time.
This change results in a 20% performance boost for my app with an endpoint returning 500 resources: …

Fix Cached identifiers extractor support for stringable identifers.

---

src/Annotation/ApiResource.php
tests/Annotation/AnnotatedClass.php
tests/Annotation/ApiResourceTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPassTest.php
tests/Fixtures/AnnotatedClass.php
tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php

This PR adds the ability to configure resource attributes directly at the first level of the `@ApiResource` annotation. This improves the DX by adding autocompletion on annotation properties with modern IDEs.
Attribute keys are normally in snake_case but we use lowerCamelCase at the first level of the `@ApiResource` annotation. So I made the choice to define them also in lowerCamelCase here but they are then normalized to snake_case.
About private properties (see the second commit), they are "virtual" because of this issue: …

Fallback attributes in the @ApiResource annotation

---

features/graphql/mutation.feature
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
tests/Fixtures/TestBundle/Entity/WritableId.php

Currently, it's not possible to set or update an ID (in the case where it is not autogenerated).
This PR fixes this bug.

GraphQL: fix creating or updating an ID

---

src/Api/CachedIdentifiersExtractor.php
src/Api/IdentifiersExtractor.php
src/Api/ResourceClassResolver.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
tests/Api/CachedIdentifiersExtractorTest.php
tests/Api/IdentifiersExtractorTest.php
tests/Bridge/Symfony/Routing/IriConverterTest.php

| Fixed tickets | #1781 (last comment)
My original fix https://github.com/api-platform/core/pull/1101 is wrong. Indeed when an relation Entity is an object AND has a `__toString()` method it won't be considered as relation in the file, where it should.
This is only a partial fix because https://github.com/api-platform/core/pull/1478 is the proper fix for the string issue on uuid identifiers for example.

Fix identifier cache

---

features/graphql/mutation.feature

Please be careful on trying behat suite on your environments... Second time I have to fix regexp ^^".
See #1761 
It's painful to debug travis if the local suite doesn't pass. @dunglas my guess is that the regex of travis linux aren't based on the same as the one on my local env. I don't see how it's possible if that's not the case.

fix local graphql tests (again)

---

src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/GraphQl/Serializer/ItemNormalizer.php
src/Serializer/ItemNormalizer.php

Related to https://github.com/api-platform/core/pull/1803.
The commit https://github.com/api-platform/core/commit/d7ada1bc5a0b4f548bce061a8a9129f79c000d37 is bringing issues when merging 2.2 into master.
It's because with this commit the generic item normalizer is used instead of the abstract one.
But in 2.2 this commit https://github.com/api-platform/core/commit/4e489cd9b1b859981c4b69aaf95cfeb7a9611575#diff-3c0fe204222ffb162653db261a74ca6aR89 has begun to invert `id` with `id`.
But it's not finished and when merging 2.2 into master, it highlights the issue.
This PR is fixing it by …

[GraphQL] Fix identifiers

---

src/DataProvider/ChainSubresourceDataProvider.php
tests/DataProvider/ChainSubresourcedataProviderTest.php

`ChainItemDataProvider` and `ChainCollectionDataProvider` were able to handle data providers that implements `RestrictedDataProviderInterface`. 
I added the same logic for `ChainSubresourceDataProvider`.
My usecase is to create a custom `SubresourceDataProvider` that is supported only if a certain key is present in the context. 
Adding support for `RestrictedDataProviderInterface::supports()` is prettier than throwing a `ResourceClassNotSupportedException` in the `SubresourceDataProviderInterface::getSubresource()` method.
That's my first contribution to an open source project, …

Update ChainSubresourceDataProvider to take into account RestrictedDataProviderInterface

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Even if the docs are disabled, the `AddLinkHeader` listener tries to add a `Link` header to the `api_doc` route. But the generator fails if the route does not exists, triggers a 500 instead of having an expected result.
Checking for the parameter `%api_platform.enable_docs%` solves the problem.

If docs are disabled, do not try to add a link header to the docs

---

src/EventListener/DeserializeListener.php
tests/EventListener/DeserializeListenerTest.php

| New feature?  | somehow
| BC breaks?    | maybe?
| Tests pass?   | dunno yet
Hi, 
A POST request with an empty body and a content-type set to json throw a `syntax error` exception at deserialization.
This PR propose to allow empty content for POST request (just like empty content for `PUT` is already ok).
Didn’t find any strong indication to forbid empty post request by a quick search.
see also: http://lists.w3.org/Archives/Public/ietf-http-wg/2010JulSep/0272.html
(note, will write test if the idea is accepted ;) )
```json
{
"@context": "/api/v2/contexts/Error",
"@type": "hydra:Error",
"hydra:title": "An error occurred", …
```

Allow a POST request to have an empty body

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/app/config/config_test.yml

| Fixed tickets | #1818
This backports issue #1725 onto the 2.2 branch.
closes  #1818 
Directly cherry picked from commit 52a3a32d7aa5b5c5c8b02bf7ad0c061509a39298.

Backport #1725 into 2.2 branch.

---

src/Bridge/Symfony/Bundle/DataCollector/RequestDataCollector.php
src/Bridge/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php

This PR aims to improve the Datacollector by : 
- Use the `profiler_dump()` function for a cleaner rendering
- Format the keys of the arrays and limit their size in the array
- Highlight the Resource class and move the Acceptable content type at the bottom
- Presents the attributes on 2 columns only
- Highlight the actual operation
- Add the resource class display from the toolbar
@jdeniau I hope this is going in the direction you initially had in mind, and that the change from 3 to 2 columns is ok, IMO mot of the time the really interesting information is/was not the method nor …

Enhance Api Platform Profiler

---

src/Bridge/Symfony/Routing/ApiLoader.php
src/Operation/Factory/SubresourceOperationFactory.php
tests/Bridge/Symfony/Routing/ApiLoaderTest.php

| Fixed tickets | #1828 
This PR implements the ability to set the `controller` on a subresource. See referenced issue for details (#1828).

Implement ability to define the controller for a subresource

---

composer.json

This PR fixes missing steps with low dependencies:
```
--- FeatureContext has missing steps. Define them with these snippets:
/**
* @Then the JSON node :arg1 should match :arg2
*/
public function theJsonNodeShouldMatch($arg1, $arg2)
{
throw new PendingException();
}
```
See https://travis-ci.org/api-platform/core/jobs/365496238#L699-L707 for example.

Fix the Behat test suite with low dependencies

---

features/graphql/collection.feature
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Type/SchemaBuilder.php
tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
tests/GraphQl/Type/SchemaBuilderTest.php

| Fixed tickets | #1862 
This feature adds `totalCount` field for paginated collections to GraphQL endpoint.
I will add tests later today.

[GraphQL] Add totalCount field for paginated collections

---

features/hydra/collection.feature
features/jsonapi/pagination.feature
src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php

| Fixed tickets | #1860
This PR adds casting `page[page]` parameter to `int` and page number validation. It throws an error when page number is less than 1 and tries to convert a string to int when possible.

Page number int casting

---

features/main/subresource.feature
src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
src/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php
src/Operation/Factory/SubresourceOperationFactory.php
tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php
tests/Operation/Factory/SubresourceOperationFactoryTest.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/644 kinda https://github.com/api-platform/core/pull/1875
Say you had a subresource on a collection:
```php
<?php
namespace App;
use App\Bar;
/**
* @ApiResource
*/
class Foo {
/**
* @ApiSubresource
* @var Bar[]
*/
public $bars;
}
```
this was declaring the following routes:
```
/bars
/foo
/foo/{id}/bars
```
This patch enables subresource item operations:
```
/bars
/foo
/foo/{id}/bars
/foo/{id}/bars/{barId}
```
Note: I'll work on the subresource documentation soon it lacks lot of things :).

Enable item route on collection subresources

---

src/Bridge/Symfony/Routing/IriConverter.php
tests/Bridge/Symfony/Routing/IriConverterTest.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/644 kinda
Let's say you declare a custom operation to identify a resource by something different then `id`:
```yaml
resources:
App\Product\Entity\Product:
itemOperations:
get:
method: 'GET'
put:
method: 'PUT'
get_by_code:
method: 'GET'
path: '/products/by_code/{id}'
```
Then, you just have to create a custom item data provider:
```php
<?php
declare(strict_types=1);
namespace App\Product\DataProvider;
use ApiPlatform\Core\DataProvider\ItemDataProviderInterface;
use ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface;
use …
```

Forward operation name in the iri converter

---

features/doctrine/order_filter.feature
features/graphql/filters.feature
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Type/SchemaBuilder.php

| Fixed tickets | #1714, #1867
Possible replacement for #1743 without updating the filter but just the way filters are passed to the data provider.
ping @alanpoulain  @IonBazan

Allow GraphQL to filter on nested property

---

src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php

Follows #1663 and fix it correctly.
The added test throws a deprecation without the fix

The OrderFilter is still triggering bad deprecation/function calls

---

features/graphql/authorization.feature
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Resolver/ItemResolver.php
src/GraphQl/Resolver/ResourceAccessCheckerTrait.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php

Add `access_control_message` attribute like in REST.

[GraphQL] Access control message

---

src/Bridge/Symfony/Bundle/DataCollector/RequestDataCollector.php
src/Bridge/Symfony/Bundle/Resources/config/data_collector.xml
src/Bridge/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php

before:
after:
and a warning in the toolbar:
or when no filters are available:

Enhance filters description in DataCollector/WebProfiler

---

.circleci/config.yml
.editorconfig
.travis.yml
phpunit.xml.dist
src/Test/DoctrineOrmFilterTestCase.php
tests/Bridge/Doctrine/Orm/Filter/BooleanFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/ExistsFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/NumericFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/RangeFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
tests/Fixtures/app/config/config_test_phpunit.yml

I propose to use CircleCI for the test coverage jobs. Also includes some minor CI / test-related fixes.
Todo:

Move coverage jobs to CircleCI

---

src/Bridge/Symfony/Routing/CachedRouteNameResolver.php
src/Operation/Factory/CachedSubresourceOperationFactory.php
tests/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php
tests/Operation/Factory/CachedSubresourceOperationFactoryTest.php

We normally use local caches in conjunction with `CacheItemPool`s. They were missing here.

add some local caches where they are missing

---

features/bootstrap/FeatureContext.php
features/doctrine/search_filter.feature
features/main/non_resource.feature
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Identifier/Normalizer/ChainIdentifierDenormalizer.php
src/Identifier/Normalizer/IntegerDenormalizer.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Identifier/Normalizer/ChainIdentifierDenormalizerTest.php

Right now the Identifier Denormalizer will automatically result in the identifier being casted to string.
This basicaly break the search filter on related entities with a strict typehint on the `getId()` because when getting references to the object in the [getItemFromIri()](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php#L374) the call to `getId()` will result in a TypeError.
ping @soyuka

[Bug] Fix integer Identifiers denormalization

---

src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
tests/Bridge/Doctrine/Orm/Filter/BooleanFilterTest.php

no need for extra query builder named parameters here. just use `$expr->literal(...)`

Simplify boolean filter

---

src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
tests/Bridge/Doctrine/Orm/Filter/BooleanFilterTest.php

Reverts api-platform/core#1905
A value is a value, not a literal. If we go by this logic, then we'll use literals for many other things too, which would of course also be wrong.

Revert "Simplify boolean filter"

---

src/Bridge/Symfony/Routing/CachedRouteNameResolver.php
src/Cache/CachedTrait.php
src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php
src/Metadata/Property/Factory/CachedPropertyNameCollectionFactory.php
src/Metadata/Resource/Factory/CachedResourceMetadataFactory.php
src/Metadata/Resource/Factory/CachedResourceNameCollectionFactory.php
src/Operation/Factory/CachedSubresourceOperationFactory.php

cc @dunglas  as discussed.
I noticed we were doing the same thing in quite a few places.
Thoughts please?
P.S. i've put very little thought into the naming of the trait and function. Please suggest something better!

RFC: Cache trait

---

src/GraphQl/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php
tests/GraphQl/Serializer/ItemNormalizerTest.php
tests/Hal/Serializer/ItemNormalizerTest.php
tests/Hydra/Serializer/ItemNormalizerTest.php
tests/JsonApi/Serializer/ItemNormalizerTest.php
tests/Serializer/AbstractItemNormalizerTest.php
tests/Serializer/ItemNormalizerTest.php

There is an optimization to be had here.
Good improvement on one of my collection endpoints.
https://blackfire.io/profiles/compare/644d280a-c6ad-4770-adc9-b23afec5ec18/graph

ItemNormalizer: Supports normalization performance

---

src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
src/Hydra/Serializer/DocumentationNormalizer.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | api-platform/admin#93
cc @mauchede

Fix api-platform/admin#93: use a name converter if defined in the Hydra documentation

---

src/Cache/CachedTrait.php

Sorry, I missed the #1908 review.

Remove useless try/catch in the CachedTrait

---

src/Bridge/Doctrine/Orm/Filter/DateFilter.php
tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php

| Fixed tickets | #669 
Add a way to always include null values.

feature: add a way to always include null in the date filter

---

features/main/relation.feature
src/Exception/InvalidValueException.php
src/Serializer/AbstractItemNormalizer.php

| Fixed tickets | #1840 
#1547 introduced an `is_array` check to prevent the normalize to act on writable relations so that we could use plain identifiers, and was reverted by #1762 because not all relations are arrays, and can be iris.
But this revert triggered also the fact that we cannot use plain ids anymore on writable relations. This PR aims to fix that ; if we encounter the invalid argument exception while trying to denormalize the relation, and that we allowed plain identifiers and we have an item provider, we should try the next block if it's not an array. Now that I think about it, I should …

Fix relations denormalization with plain ids

---

features/graphql/introspection.feature
features/graphql/mutation.feature
features/graphql/query.feature
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/GraphQl/Type/SchemaBuilder.php
src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
tests/Fixtures/TestBundle/Entity/DummyGroup.php
tests/GraphQl/Type/SchemaBuilderTest.php

This PR fixes the serialization for GraphQL.
It was not working before although the serialization context could be added to the `graphql` attribute.
That's why I think it should target 2.2.
Documentation will follow if this PR is merged.

[GraphQL] Serialization

---

features/main/relation.feature
features/swagger/docs.feature
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Fixtures/TestBundle/Entity/RelatedToDummyFriend.php
tests/Fixtures/app/config/config_test.yml

fix issue with subresource filters, was incorrectly adding filters for the parent instead of the subresource
DocumentationNormalizer was loading filters for the `ResourceClass` instead of the `SubresourceClass`, this resolves that issue. I didn't create a bug report and this will require no changes to documentation.

Subresource Filter Fix

---

src/Annotation/ApiProperty.php
src/Annotation/ApiResource.php
src/Annotation/AttributesHydratorTrait.php
src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Annotation/ApiPropertyTest.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php

| Fixed tickets | n:a
Same as #1788 but for `@ApiProperty`. Also add support for some missing attributes in `@ApiResource`.

Add resource fallback for ApiProperty

---

features/bootstrap/GraphqlContext.php
features/graphql/introspection.feature
src/Annotation/ApiProperty.php
src/Annotation/ApiResource.php
src/GraphQl/Type/SchemaBuilder.php
tests/Fixtures/TestBundle/Entity/DeprecatedResource.php

Allows to deprecate GraphQL fields and resources:
```php
/**
* @ApiResource(deprecationReason="This resource is deprecated")
*/
class DeprecatedResource
{
public $id;
/**
* @ApiProperty(deprecationReason="This field is deprecated")
*/
public $deprecatedField;
}
```
I'll add support for the same attribute in both Swagger and Hydra (using OWL) in subsequent Pull Requests.
~~As you can see, `@ApiProperty`'s doesn't support the simplified attributes syntax introduced in …

[GraphQL] Deprecation support

---

features/main/circular_reference.feature
src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php

Fix #1959 do not join same association twice

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php

Because it confuses some users that `['enable_max_depth' => false]` actually triggers the check.

Check the value of enable_max_depth if defined

---

src/Bridge/Doctrine/Common/DataPersister.php
src/Bridge/Doctrine/EventListener/WriteListener.php
src/DataPersister/ChainDataPersister.php
src/DataPersister/DataPersisterInterface.php
src/EventListener/WriteListener.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
tests/Bridge/Doctrine/Common/DataPersisterTest.php
tests/EventListener/WriteListenerTest.php

| Tests pass?   | *unit tests are green, bdd are red, master too seems wrecked 🎶*
| Fixed tickets | #1799 
| Doc PR        | @todo
closes #1799
`DataPersisterInterface` can now return the result of the persistence call instead of relying on data mutation. Thus allowing persistence layer to deal with immutable data.
At least, this PR breaks the technical detail that was implicitly using objects instance reference as an identifier for an entity, and conceptually I find this a huge win :)

Allow DataPersister to return a new instance instead of mutating

---

features/swagger/docs.feature
src/Metadata/Resource/ResourceMetadata.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Metadata/Resource/ResourceMetadataTest.php

Follows #1962. Add the `deprecated` flag to operations that can be applied to deprecated resources:
```php
/**
* @ApiResource(deprecationReason="This resource is deprecated")
*/
class DeprecatedResource
{
// ...
}
```
Unfortunately, unlike GraphQL, Open API v2 doesn't support fields deprecation, or deprecation messages. Open API v3 supports fields deprecation, but API Platform don't have support for this version yet (help welcome)!

Add deprecation support in Swagger

---

features/bootstrap/HydraContext.php
features/hydra/docs.feature
src/Hydra/Serializer/DocumentationNormalizer.php

Follows #1976 and  #1962. Add the `owl:deprecated` annotation to deprecated `operations` and `supportedProperties`.
```php
/**
* @ApiResource(deprecationReason="This resource is deprecated")
*/
class DeprecatedResource
{
public $id;
/**
* @ApiProperty(deprecationReason="This field is deprecated")
*/
public $deprecatedField;
}
```
Unlike GraphQL, OWL and Hydra don't support deprecation messages.

Add deprecation support for Hydra

---

src/Annotation/ApiProperty.php
src/Annotation/ApiResource.php
tests/Annotation/ApiPropertyTest.php

Add support for the `deprecationReason` attribute.

Support the "deprecationReason" attribute in the ApiProperty annotation

---

composer.json
src/GraphQl/Type/Definition/IterableType.php
tests/GraphQl/Type/Definition/IterableTypeTest.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/704
Fix the iterable type after a BC in graphql-php.
Maybe we need to force users to require a specific version of graphql-php in order to avoid this kind of issue.
For example in the doc, instead of:
`composer require webonyx/graphql-php`
we would have:
`composer require webonyx/graphql-php:^0.12.0`
WDYT?

[GraphQL] Fix iterable type

---

features/main/circular_reference.feature
src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

Disable eager loading when no groups are specified to avoid recursive joins

---

.circleci/config.yml
.php_cs.dist
.travis.yml
features/bootstrap/FeatureContext.php
features/bootstrap/HydraContext.php
features/bootstrap/JsonContext.php
features/bootstrap/SwaggerContext.php
src/Bridge/Doctrine/Common/DataPersister.php
src/DataProvider/ChainItemDataProvider.php
src/JsonApi/Serializer/ConstraintViolationListNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ReservedAttributeNameConverter.php
src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php
src/Serializer/AbstractCollectionNormalizer.php
src/Serializer/SerializerContextBuilder.php
src/Util/AnnotationFilterExtractorTrait.php
tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/DataProvider/ChainCollectionDataProviderTest.php
tests/Fixtures/TestBundle/Serializer/Denormalizer/SerializableResourceDenormalizer.php
tests/JsonApi/Serializer/ItemNormalizerTest.php
tests/Metadata/Resource/ResourceMetadataTest.php

Move lint jobs to CircleCI

---

.php_cs.dist
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
tests/Bridge/Doctrine/Orm/Filter/BooleanFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/NumericFilterTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Hal/Serializer/CollectionNormalizerTest.php
tests/Hydra/Serializer/ConstraintViolationNormalizerTest.php
tests/Hydra/Serializer/ItemNormalizerTest.php
tests/Metadata/Resource/Factory/FileConfigurationMetadataFactoryProvider.php
tests/Operation/Factory/SubresourceOperationFactoryTest.php
tests/Problem/Serializer/ConstraintViolationNormalizerTest.php
tests/Problem/Serializer/ErrorNormalizerTest.php
tests/Util/AnnotationFilterExtractorTraitTest.php
tests/Util/IriHelperTest.php

Update PHP-CS-Fixer rules

---

features/serializer/deserialize_objects_using_constructor.feature
src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php
src/Hydra/Serializer/DocumentationNormalizer.php
src/Metadata/Property/PropertyMetadata.php
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/DummyObjectWithConstructor.php
tests/Fixtures/DummyObjectWithoutConstructor.php
tests/Fixtures/TestBundle/Entity/DummyEntityWithConstructor.php
tests/Metadata/Property/PropertyMetadataTest.php

This is motivated because other tools are already constructor friendly (ie Symfony serializer and Doctrine).
Also using constructors must be recommended and not supporting them is a serious feature missing.
| Bug fix?      | somehow
| Fixed tickets | https://github.com/api-platform/core/issues/1747

Make resource constructor parameters writables

---

src/Hal/Serializer/ItemNormalizer.php

here: https://github.com/api-platform/core/pull/1971 i accidentally created a performance issue.
I didn't spot this because the (prod) cached metadata factory does not have a local lookup:
https://github.com/symfony/symfony/blob/1b2bd8f41971f7903fd04d898801a1874a0427dc/src/Symfony/Component/Serializer/Mapping/Factory/CacheClassMetadataFactory.php#L46
while the (dev) uncached one does:
https://github.com/symfony/symfony/blob/1b2bd8f41971f7903fd04d898801a1874a0427dc/src/Symfony/Component/Serializer/Mapping/Factory/ClassMetadataFactory.php#L44-L48
This means that in prod mode, many many …

Hal Item Normalizer: add a local cache for classMetadataFactory

---

features/main/validation.feature
src/Bridge/Symfony/Validator/Validator.php
tests/Fixtures/TestBundle/Controller/DummyValidationController.php
tests/Fixtures/TestBundle/Entity/DummyValidation.php
tests/Fixtures/TestBundle/Validator/DummyValidationGroupsGenerator.php
tests/Fixtures/app/config/config_test.yml

Add support for GroupSequence

---

src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php

Hello,
The cause is explained in #2012.
I have two doubts/things i am not proud of:
- the optimisation is skipped for related joins
- i am not sure of the behaviour of this fix with composite relations.
| Fixed tickets | #2012 
| Doc PR        | None
(It is a reedition of the PR #2013, due to my mistake, sorry for the duplicate).

FilterEagerLoadingExtension accepts joins with class name as join value

---

src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php

| Fixed tickets | #2023
| Doc PR        | api-platform/doc#506
Option to specify file to write generate contents instead of stdout.

added an --output option to the api:swagger:export

---

src/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php
tests/Metadata/Property/Factory/AnnotationSubresourceMetadataFactoryTest.php

Currently, when a property has a @ApiSubresource declaration, but no proper type declaration, this results in a "Fatal error: Call to a member function isCollection() on null", which is hard to debug. Instead throw an exception referencing the offending property, so the declaration can be fixed.

Fix fatal error when subresource type is not defined

---

src/EventListener/WriteListener.php
src/HttpCache/EventListener/AddTagsListener.php

Add final to the WriteListener
Don't call getResponse in the cache, use the variable instead

Small code tweaks

---

src/DataPersister/ChainDataPersister.php
tests/DataPersister/ChainDataPersisterTest.php

| BC breaks?    | (fix one)
| Tests pass?   | this features tests are green
| Fixed tickets | https://github.com/api-platform/core/pull/1967#discussion_r199755449
fixes https://github.com/api-platform/core/pull/1967#discussion_r199755449
Fix a unwanted behavior when multiple DataPersisters support an item, the first supporting one was called, other were skipped.
This PR, fix this.

fix skipped data persisters on persist

---

src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Routing/IriConverter.php
src/DataProvider/OperationDataProviderTrait.php
src/EventListener/ReadListener.php
src/Filter/QueryParameterValidateListener.php
src/Identifier/IdentifierConverter.php
src/Identifier/IdentifierConverterInterface.php
tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php
tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Routing/IriConverterTest.php
tests/EventListener/ReadListenerTest.php
tests/Identifier/IdentifierConverterTest.php

Fix some SensioLabs Insight violations

---

src/EventListener/WriteListener.php
src/Util/AttributesExtractor.php
tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
tests/EventListener/AddFormatListenerTest.php
tests/EventListener/DeserializeListenerTest.php
tests/EventListener/WriteListenerTest.php
tests/Serializer/SerializerFilterContextBuilderTest.php
tests/Util/RequestAttributesExtractorTest.php

| Doc PR        | api-platform/docs#523
Add a new `_api_persist` flag to skip the `WriteListener`. See also https://stackoverflow.com/q/51147945/1352334 for the use case.

New "_api_persist" request attribute to skip the WriteListener

---

features/graphql/filters.feature
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Type/SchemaBuilder.php

| Doc PR        | https://github.com/api-platform/docs/pull/524
Using the SearchFilter with multiple values was not possible with graphql.
Using the same synthax than the query filter (`foo[]=bar`) was not possible because characters `[` and `]` in a graphql query are invalid and it seems that it's not possible to use the same key for both single value filter and multi values filter.
The idea is to prefix the field name with a special keyword to make the distinction between single and multiple values.

[graphql] Add graphql filter with multiple values

---

src/GraphQl/Type/SchemaBuilder.php
tests/GraphQl/Type/SchemaBuilderTest.php

| Fixed tickets | #2082
Against some graphql client implementation (like apollo for ios), the presence of a relation/nested property with the `.` (dot character) in the schema is not supported.
So, the array of filter definitions should be cleaned by removing the nested property once it has been sanitized (the `.` character is replaced by the `_` charceter)

Unset the filter (with a dot character), in case of a relation, once it has been sanitized

---

composer.json
src/Annotation/AttributesHydratorTrait.php
src/Bridge/Symfony/Routing/RouteNameGenerator.php
src/GraphQl/Type/SchemaBuilder.php
src/Operation/DashPathSegmentNameGenerator.php
src/Operation/UnderscorePathSegmentNameGenerator.php

@dunglas I think that the ClassLoader is used by symfony in https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Test/DoctrineTestHelper.php#L56 if that's not the case I don't get it (see DoctrineOrmFilterTestCase).
I'm really not sure how we can fix those deprecations right now.

Fix tests doctrine deprecation

---

.travis.yml
appveyor.yml

Fix allow_failures on Travis CI

---

features/main/crud.feature
features/main/crud_abstract.feature
features/main/custom_normalized.feature
features/main/custom_writable_identifier.feature
features/main/uuid.feature
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/EventListener/RespondListener.php
src/EventListener/WriteListener.php
tests/EventListener/RespondListenerTest.php
tests/EventListener/WriteListenerTest.php

| Deprecations? | yes, i add one
| Tests pass?   | no, but i work on this
| Fixed tickets | #1912 

Better HTTP headers

---

composer.json
tests/Fixtures/TestBundle/Controller/CustomActionController.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config_test.yml

We forgot to remove `sensio/framework-extra-bundle` from the dev dependencies in #2108.

Remove sensio/framework-extra-bundle from the dev dependencies

---

.circleci/config.yml

Maybe that we should fix the phpstan version instead and bump it manually every once in a while?

Fix phpstan@0.10.2 issues

---

features/bootstrap/FeatureContext.php
features/jsonapi/related-resouces-inclusion.feature
src/JsonApi/Serializer/CollectionNormalizer.php

In `src/JsonApi/Serializer/CollectionNormalizer.php`  must reindex array cause `array_unique` preserve keys and after that `json_encode`  [ parse php array to JSON  array not to JSON object](https://stackoverflow.com/questions/11195692/json-encode-sparse-php-array-as-json-array-not-json-object).

Fix JSON API inlcude form when remove duplicate data

---

features/graphql/authorization.feature
features/graphql/mutation.feature
src/GraphQl/Action/EntrypointAction.php

| Fixed tickets | #1952
As discussed in #1952, the GraphQL entrypoint should always returns a 200 because GraphQL should not use HTTP status codes.

[GraphQL] Fix response status code

---

src/Bridge/Doctrine/Orm/Util/QueryChecker.php
tests/Bridge/Doctrine/Orm/Util/QueryCheckerTest.php

changed QueryChecker hasRootEntityWithForeignKeyIdentifier() and hasRootEntityWithCompositeIdentifier() to operate as method names imply.
updated unit tests.
| Fixed tickets | #2136 

QueryChecker fix

---

src/Operation/Factory/SubresourceOperationFactory.php
tests/Fixtures/DummyEntityFilterAnnotated.php
tests/Operation/Factory/SubresourceOperationFactoryTest.php

| Fixed tickets | #1711, #2103
Seems to be we have an issue with the reset of Subresource maxDepth.
We need to reset the $depth if we return to the $rootResourceClass and this before the maxDepth Check... If not, only the maxDepth of the FIRST subresource of the rootResourceClass is generating...
But I have one fear on this: the case of a self-referencing subresource. DummyEntity -subRe-> DummyEntity. Because the maxDepth will be always reset to 0.
I think I will try to create a test for this special case and How is it handle without maxDepht btw?
ping @soyuka We already have this discussion in my …

Fix reset on maxDepth

---

src/GraphQl/Type/SchemaBuilder.php

| Fixed tickets | #2149
When a property was corresponding to a subresource, the context given to `getResourceFieldConfiguration` was wrong.
It was creating issues like the one referenced, because the generated arguments for the collection were the parent's ones.
The following test was working because the parent entity (`Dummy`) has a search filter for its `name` field:
https://github.com/api-platform/core/blob/ebe842f3cc8d22f90f3099484b615bb183e9f8f5/features/graphql/filters.feature#L87-L113

[GraphQL] Fix subresource context

---

features/jsonld/context.feature
features/main/operation.feature
src/Bridge/Symfony/Bundle/Resources/config/metadata/annotation.xml
src/Bridge/Symfony/Bundle/Resources/config/metadata/xml.xml
src/Bridge/Symfony/Bundle/Resources/config/metadata/yaml.xml
src/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php
src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php
src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
tests/Fixtures/TestBundle/Entity/ReadableOnlyProperty.php
tests/Metadata/Property/Factory/AnnotationPropertyMetadataFactoryTest.php
tests/Metadata/Property/Factory/FileConfigurationMetadataFactoryProvider.php

| Fixed tickets | #1980 
See issue.

fix #1980 user defined property metadata takes precedence

---

features/serializer/vo_relations.feature
src/Serializer/AbstractItemNormalizer.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Fixtures/TestBundle/Entity/VoDummyCar.php
tests/Fixtures/TestBundle/Entity/VoDummyDriver.php
tests/Fixtures/TestBundle/Entity/VoDummyIdAwareTrait.php
tests/Fixtures/TestBundle/Entity/VoDummyInspection.php
tests/Fixtures/TestBundle/Entity/VoDummyInsuranceCompany.php
tests/Fixtures/TestBundle/Entity/VoDummyVehicle.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | #2169
Connected with: https://github.com/api-platform/core/pull/1749, https://github.com/symfony/symfony/pull/28263
TODO:

Constructor relations writtable

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

This PR is related to reported bug in [api-platform/api-platform](https://github.com/api-platform/api-platform/issues/799) project.
So problem is caused because the same tables is joined multiple times **ON same condition** but with different aliases. 
I find useful article by Marco Pivetta about [Doctrine hydration](http://ocramius.github.io/blog/doctrine-orm-optimization-hydration/) where they said about coding multi-step hydration, that is used in PR.

Fix duplicate data in Eager loads relations

---

src/GraphQl/Type/SchemaBuilder.php

| Fixed tickets | ø
| Doc PR        | ø
Otherwise, GraphiQL gives this lovely message:
> Mutation fields must be an object with field names as keys or a function which returns [...]

[GraphQL] Only exposes the mutations if any

---

src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

fixes #2161
Signed-off-by: RJ Garcia <rj@bighead.net>
| Fixed tickets | #2161

Expose Pagination in Swagger UI

---

src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php

fix #2115 SwaggerCommand with --yaml now properly serializes nested objects

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

Reverts api-platform/core#2183
Revert because it can cause performances issues see https://github.com/api-platform/core/pull/2183#issuecomment-422009161
Rel: https://github.com/api-platform/core/pull/2188

Revert "Fix duplicate data in Eager loads relations"

---

.circleci/config.yml
.travis.yml
appveyor.yml
phpunit.xml.dist

Simplify env var config

---

features/doctrine/search_filter.feature
src/Bridge/Symfony/Routing/IriConverter.php
tests/Bridge/Symfony/Routing/IriConverterTest.php

When using the search filter on an exact association for example, if the obviously bad value is a matching collection url, the filter IriConverter will throw `Either \"item_operation_name\" or \"collection_operation_name\" must be defined, unless the \"_api_receive\" request attribute is set to false.`
This is because `getItemFromIri()` will get a match on the router but won't match the expected the attributes.
an easy way to reproduce this on the demo is to try to filter `/reviews?book=foo` versus `/reviews?book=parchments` or `/reviews?book=book`

[2.3] Throw an InvalidArgument when trying to get Item from a collection route

---

features/bootstrap/FeatureContext.php
features/hal/max_depth.feature
features/jsonld/max_depth.feature
src/Hal/Serializer/ItemNormalizer.php
tests/Fixtures/TestBundle/Entity/MaxDepthEagerDummy.php

Max depth annotation was not working in HAL when fetch eager was disabled.

Fix: max depth not working when fetch eager is disabled

---

src/Bridge/Doctrine/Common/DataPersister.php
tests/Bridge/Doctrine/Common/DataPersisterTest.php

| BC breaks?    | maybe
| Fixed tickets | #2155
As reported in #2155 doctrine entities are not persisted if change tracking policy is `DEFERRED_EXPLICIT`.
This implementation relies on `ClassMetadataInfo`, which is the `ClassMetadata` implementation. As it's API might change, I've added a test on method existence.

Persist doctrine entities with DEFERRED_EXPLICIT change tracking policy

---

src/GraphQl/Type/SchemaBuilder.php
tests/GraphQl/Type/SchemaBuilderTest.php

Mandatory for GraphQL support in Sylius.

GraphQL: fix a bug when the class name isn't provided

---

tests/Swagger/Serializer/DocumentationNormalizerTest.php

| Fixed tickets | #2199
There's a merged PR https://github.com/api-platform/core/pull/2114 but this part wasn't tested yet, so I added the test in the case of an array collection filters in the Swagger documentation.

Add Swagger DocumentationNormalizer test for array collection filters

---

src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js
src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
tests/Bridge/Symfony/Bundle/Action/SwaggerUiActionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| License       | WTFPL
| Doc PR        | api-platform/doc#612
One of the greatest bugs in the Human software is their fear of spiders. In some cases, the simple seeing of something big go down the screen makes them feel bad for some seconds, before realizing it's just Webby.
Problem is, the Human software is closed-source, so this PR tries to manage that issue by providing a way to disable displaying Webby on the Swagger UI pages. Of course, Webby remains visible by default.
To disable Webby's display, just add this to API Platform's config:
```yaml
api_platform:
show_webby: false # defaults to true
```

Arachnophobia mode

---

.circleci/config.yml
appveyor.yml
features/security/README.md
phpstan.neon
src/Bridge/Doctrine/Orm/Util/QueryJoinParser.php
src/DataProvider/SubresourceDataProviderInterface.php
src/GraphQl/Type/Definition/IterableType.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Bridge/Doctrine/Orm/Util/QueryJoinParserTest.php
tests/Metadata/Property/Factory/InheritedPropertyNameCollectionFactoryTest.php

and fix a mistake in a readme
Instead of adding a new exclude rule, I would rather drop [this code](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Util/QueryJoinParser.php#L103-L111) and in other places in the QueryJoinParser. Those are public method that didn't moved since 6 years and are still there in the next 3.0, I fail to understand what it is trying to fix and why if the method is to be removed at some point, we expect the internal property to still be there.
let me know if it is ok

Bump PHPStan version

---

src/GraphQl/Type/SchemaBuilder.php

In order to avoid performance issues with large schema, the Schema config allow to add a `typeLoader` option.
See : http://webonyx.github.io/graphql-php/type-system/schema/#lazy-loading-of-types
The `graphqlTypes` property has been changed into a simple one-dimensional array in order to retrieve fields by type name.
Note : Some behat tests are failing but this seems unrelated because they are failing on master too.

[GraphQl] Add typeLoader option in schema constructor

---

features/http_cache/tags.feature
tests/Fixtures/TestBundle/Entity/Relation3.php

Refs https://github.com/api-platform/core/pull/2282#discussion_r228714918

Add tests on doctrine collection purge

---

src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php

| Tests pass?   | -
| Fixed tickets | #2285 

Force Yaml::dump to dump empty array as actual empty array

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php

When an entity had more that one relation, if the first relation was not present in the attributes array in the normalization context the whole array was removed so they was no test for other relations on the next loop iteration.
The aim of this pull request is to fix this behavior and to let the chance to other relations to be eager loaded.

[EagerLoadingExtension] Remove unset attributes key in normalization context

---

.circleci/config.yml
phpstan.neon
src/Annotation/ApiFilter.php
src/Annotation/AttributesHydratorTrait.php
src/Bridge/Doctrine/Orm/Filter/DateFilter.php
src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Bridge/Doctrine/Orm/ItemDataProvider.php
src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
src/Bridge/Symfony/Routing/ApiLoader.php
src/Bridge/Symfony/Routing/IriConverter.php
src/DataProvider/OperationDataProviderTrait.php
src/EventListener/AddFormatListener.php
src/Filter/QueryParameterValidateListener.php
src/GraphQl/Action/EntrypointAction.php
src/GraphQl/Serializer/ItemNormalizer.php
src/GraphQl/Type/SchemaBuilder.php
src/Metadata/Extractor/XmlExtractor.php
src/Metadata/Extractor/YamlExtractor.php
src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php
src/Operation/Factory/SubresourceOperationFactory.php
src/Swagger/Serializer/ApiGatewayNormalizer.php
src/Util/RequestParser.php
tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
tests/GraphQl/Type/SchemaBuilderTest.php
tests/Swagger/Serializer/ApiGatewayNormalizerTest.php

ref https://github.com/api-platform/core/pull/2267#issuecomment-432523409

Bump PHPStan analysis to level 6

---

src/Operation/Factory/SubresourceOperationFactory.php
tests/Operation/Factory/SubresourceOperationFactoryTest.php

I think this is a bug, sorry if it isn't. This will make a sub-resource have the same route_prefix as the root resource. Is this the expected behaviour?

Prefix root resource's route_prefix to sub-resources

---

.circleci/config.yml
.travis.yml
tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
tests/Fixtures/TestBundle/Entity/DummyCar.php

Edit: Adding test decrease coverage... of course 😈

Add a non regression test for #2285 #2286

---

src/Annotation/ApiResource.php
src/Bridge/Symfony/Bundle/Resources/config/http_cache.xml
src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
src/HttpCache/EventListener/AddHeadersListener.php
tests/Annotation/ApiResourceTest.php
tests/Fixtures/AnnotatedClass.php
tests/HttpCache/EventListener/AddHeadersListenerTest.php

The cache headers should be able to be modified and then not overwritten by the `AddHeadersListener`. Also added annotation configuration for cache header expiry times so each resource can have a different expiry time if required.
| Fixed tickets | https://github.com/api-platform/core/issues/2207
| Doc PR        | (not created yet)

Ability to modify response headers (mainly cache related headers)

---

src/Bridge/Doctrine/Orm/Util/QueryChecker.php
src/Bridge/Doctrine/Orm/Util/QueryJoinParser.php
tests/Bridge/Doctrine/Orm/Util/QueryJoinParserTest.php

Follows https://github.com/api-platform/core/pull/2267

Deprecate dead code in QueryJoinParser and remove internal usage

---

features/doctrine/date_filter.feature
features/doctrine/numeric_filter.feature
features/main/crud.feature
src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
tests/Bridge/Doctrine/Orm/Filter/NumericFilterTest.php

| Fixed tickets |  #2190
This PR allow to use the numeric filter with multiple values
The values with non-numerical keys are removed in the `normalizeValues` function to avoid collision between this filter and the `RangeFilter`

allow to use multiple values with NumericFilter

---

src/Bridge/Doctrine/Orm/Extension/FilterExtension.php

This improvement allows to have several orderFilters in one entity.
I faced a problem when I created my own custom Order Filter. As a result in the same class I use 2 different order  filters: default and my custom (which extends default). But Api-Platform can't handle several order filters - only last one wins. This commit fixes this issue.

Allow multiple order filters in entity.

---

features/bootstrap/FeatureContext.php
features/main/subresource.feature
src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
tests/Fixtures/TestBundle/Entity/RelatedOwnedDummy.php
tests/Fixtures/TestBundle/Entity/RelatedOwningDummy.php

| Fixed tickets | #1801
This is a rework for this PR https://github.com/api-platform/core/pull/2228
@soyuka I'm struggling with UnitTest right now I don't now why prophecy contradicted itself... When I mock getClassMetadata and getRepository it says only getClassMetadata is called and when I remove getRepository it says only getRepository is called... Any help or clue on this could be appreciated.
Another question, it could be great to add a test with behat in subresource.feature to test OneToOne subresource in both way but I think there is no context for subresources and relation. Any clue on this? …

fix OneToOne bidirectional + unitTest WIP

---

src/Swagger/Serializer/DocumentationNormalizer.php

| Bug fix?      | "yes"
| Fixed tickets | /
| Doc PR        | /
` $this->subresourceOperationFactory ` is already defined on line 96

Fix duplicate attribute definition

---

src/EventListener/ReadListener.php

This PR improves exception handling to throw also previous Exception. I spent a lot of time, to figure out what's happening there: ReadListener should not mute Exceptions. It should also pass previously caught Exception (in line 104 like this commit or in line 108). I also improved NotFoundHttpException's message.
| Tests pass?   | hopefully
| Fixed tickets | no ticket for this
| Doc PR        | no doc needed
branch/version: 2.3 (because in 2.2 we are catching an even more common exception)

(Very small improvement) Improves exception handling in ReadListener

---

composer.json
src/Hal/Serializer/ItemNormalizer.php
src/Hydra/Serializer/ErrorNormalizer.php
src/JsonApi/Serializer/ErrorNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/JsonLd/Serializer/ItemNormalizer.php
src/Problem/Serializer/ConstraintViolationListNormalizer.php
src/Problem/Serializer/ErrorNormalizer.php
src/Serializer/AbstractItemNormalizer.php
src/Swagger/Serializer/ApiGatewayNormalizer.php
src/Swagger/Serializer/DocumentationNormalizer.php

Introduces a default context for all our normalizers, similarly to the one introduced in Symfony 4.2 (symfony/symfony#28709).
Will allow to also use the new config option (https://github.com/symfony/symfony/pull/28927) with API Platform.

Add a default context in concerned normalizers

---

src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/FileConfigurations/resources.yml
tests/Fixtures/app/config/config_test.yml

Corrects the format for referencing consts in yaml since [symfony 3.4](https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.4.md#yaml)

suggest correct !php/const format for symfony 3.4 and above

---

src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

| New feature?  | yes?
| Fixed tickets | =
Seems like a nice sane default for Doctrine. thoughts?
I needed this in my API anyway.

return HTTP_CONFLICT 409 on Doctrine OptimisticLockException

---

src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
tests/Metadata/Property/Factory/SerializerPropertyMetadataFactoryTest.php

Prevent an error when using the following configuration (using strings in this case is supported in Symfony Serializer since the latest version):
```php
/**
* @ORM\Entity(repositoryClass="App\Repository\UserRepository")
*     normalizationContext={"groups": "user:read"}
* )
*/
```
This PR fixes a performance warning thrown by PHP Inspections.

Allow strings for single serialization groups

---

src/Serializer/Filter/GroupFilter.php
src/Serializer/Filter/PropertyFilter.php
tests/Serializer/Filter/GroupFilterTest.php
tests/Serializer/Filter/PropertyFilterTest.php

| Fixed tickets | #2370
This fixes #2370 in which properties[] is not documented as an array of strings as expected.

Correctly expose properties[] as a collection parameter

---

.php_cs.dist

We don't notice the problem in our CI, because the PHP-CS-Fixer job is always separate.

Fix exclude app cache path for PHP-CS-Fixer

---

src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml

| Doc PR        |n/a
This allows to leverage the `autoconfigure` flag when creating custom data providers. Without this explicit priority, the default provider can be registered before custom ones, which is counter-intuitive and annoying.
This is a potential (tiny) BC break (it's why I not targeted 2.3), but I think it is worth it.

Fix Doctrine DataPersister priority

---

src/Serializer/Filter/PropertyFilter.php
tests/Serializer/Filter/PropertyFilterTest.php

I think this qualifies as a bugfix because the only thing it really only does is add some swagger docs to the `PropertyFilter`. That's not really something that has to wait for a new minor release imho 😄

Added swagger description to property filter

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerTest.php

Always pass an array for AdvancedNameConverterInterface::normalize

---

src/Annotation/ApiResource.php
src/EventListener/DeserializeListener.php
src/EventListener/SerializeListener.php
src/EventListener/WriteListener.php
tests/EventListener/DeserializeListenerTest.php
tests/EventListener/SerializeListenerTest.php
tests/EventListener/WriteListenerTest.php

This PR allows to set the new `input_class` and `output_class` attributes to `false`. It hints API Platform that the corresponding operation(s) will respectively expect an empty input, or will return nothing.
This is especially convenient when creating an endpoint that will return nothing. My use case: I create have a `POST /reset-password` endpoint that sends a token by mail. This endpoint returns `202 Accepted` and nothing else.
The next step will be to support `input_class` and `output_class` (including this new option) in the documentation normalizers.

Allow to disable input and output class

---

src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js

When you access your resource in swagger with an id the execute action is triggered too fast.
We get an error because the input value isn't already updated.
For example, if you try a query like this one:
http://localhost/{entityName}/{id}
You will get an error in your input.
This fix is only intended to be a workaround.
To fix this we should maybe have a better way to handle with the onComplete in swagger ui which should be fired up when all the ajax calls are done.
We could use MutationObservers too but we don't know when we should fire up the execute click.
Feel free to reply if …

Temporary fix for swagger-ui executing query too fast

---

src/Serializer/ItemNormalizer.php
tests/Serializer/ItemNormalizerTest.php

---
We store some document in Elasticsearch and we hydrate them with the Serializer.
But the `ItemNormalizer` raise an error because the `resource_class` is not defined.

Do not try do retrieve object in ItemNormalizer $context['resource_class'] is not defined

---

src/DataProvider/OperationDataProviderTrait.php

Follow up on #2393
Those underlying functions expects string but might get boolean and 💥😄

Avoid type error when output_class is false

---

src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
src/Hydra/Serializer/DocumentationNormalizer.php
src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
tests/Fixtures/TestBundle/Entity/DummyCar.php

Allows to use the short syntax for serialization groups introduced in https://github.com/symfony/symfony/pull/27503 with API Platform.

Allow to pass a single value for the groups opt

---

src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php

When falling back to SwaggerUiAction, correctly case Operation ID
to enable correct matching.

Allow strict matching for operation names

---

src/Hydra/Serializer/DocumentationNormalizer.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php

Adds the support for the `input_class` and `output_class` attributes in the Hydra documentation normalizer.

Add support for input and output classes to Hydra

---

features/graphql/mutation.feature
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php

| Fixed tickets | #2364 
This prevents passing IRIs belonging to different resource classes, which would bypass access control in some instances (see #2364).

[GraphQL] Check item resource class in mutation

---

composer.json
features/push_relations/push.feature
src/Annotation/ApiProperty.php
src/EventListener/DeserializeListener.php
src/EventListener/SerializeListener.php
src/Serializer/AbstractItemNormalizer.php
tests/Annotation/ApiPropertyTest.php
tests/EventListener/SerializeListenerTest.php
tests/Fixtures/TestBundle/Entity/Dummy.php

| Doc PR        | https://github.com/api-platform/docs/pull/714
This new feature allows to use the web server to push relations of the current resources using HTTP/2. It's especially useful when used together with [the built-in HTTP cache invalidation system (based on Varnish)](https://api-platform.com/docs/core/performance/#enabling-the-built-in-http-cache-invalidation-system).
The usage is very easy:
```php
<?php
/**
* @ApiResource
*/
class Book
{
/**
* @var Author $author
* …
```

Allow to push relations to the client using HTTP/2

---

src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Bridge/Symfony/Bundle/Resources/config/elasticsearch.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPassTest.php

This PR allows to use the abstract definitions of filter services when using the filter annotation.
It also allows to use Elasticsearch filters with the filter annotation without issues. In fact, without this fix the passed name converter to the Elasticsearch filter constructor is `null` because of the autowiring.
WDYT?

Enhance the filter annotation

---

features/hydra/docs.feature
features/swagger/docs.feature
src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
tests/Fixtures/app/config/config_test.yml

| Bug fix?      | not sure
| Fixed tickets | https://github.com/api-platform/core/issues/2458
This PR allow to keep the original formatting, before : 
```
description: |
A multiline
description
```
would become
```
info:
...
description: "A multiline\ndescription"
```
and will now be preserved.

https://github.com/api-platform/core/issues/2458

---

composer.json

This updates `composer.json` with a `conflict` constraint for Doctrine MongoDB ODM. Since the ODM dependency is optional, using `conflict` is the only way to enforce having 2.0 or later. Users with 1.0 will get weird errors about repositories not being of the expected type instead of a useful message that they should be using API Platform with 2.0 only.

Fix version constraints for Doctrine MongoDB ODM

---

src/EventListener/WriteListener.php
tests/EventListener/WriteListenerTest.php

In our app we use table inheritance like `File`  and `FooFile` extending `File`
In 2.3 we can update a FooFile even if it not an ApiResource by send a PUT request on File.
it is not possible anymore as the iriConverter will throw on `getIriFromItem`.
So basically at this point in the listener, `$controllerResult` would be a `FooFile`, `api_resource` and `output_class` attributes would be equal to `File`
I'm really unsure that this is the correct fix. ping @soyuka

Fix a small BC break

---

.circleci/config.yml
behat.yml.dist
features/doctrine/date_filter.feature
features/main/crud.feature
features/main/relation.feature
features/main/subresource.feature
features/mongodb/filters.feature
src/Bridge/Doctrine/MongoDbOdm/PropertyHelperTrait.php
tests/Bridge/Doctrine/MongoDbOdm/Extension/OrderExtensionTest.php
tests/Fixtures/TestBundle/Document/FourthLevel.php
tests/Fixtures/TestBundle/Document/ThirdLevel.php
tests/Fixtures/TestBundle/Entity/FourthLevel.php
tests/Fixtures/TestBundle/Entity/ThirdLevel.php
tests/Fixtures/app/config/config_mongodb.yml
tests/Fixtures/app/config/config_orm.yml

To have an error if references are not stored as `id` or `ref`.

Error if references are not stored correctly for lookups

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

- Added ability to disable messenger from config
- Removed previous check if container has message_bus
Signed-off-by: RJ Garcia <rj@bighead.net>

Disable Messenger From Config

---

src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/Entity/DummyForAdditionalFields.php
tests/Fixtures/TestBundle/Entity/DummyForAdditionalFieldsInput.php
tests/Serializer/AbstractItemNormalizerTest.php

Fixes the bug where AbstractItemSerializer would use
the resource class instead of the input class to
determine allowed properties.
Enforced `$context['resource_class']` to be set to
current denormalized class to resolve issue. Figured this
should be the case since AbstractItemNormalizer only works
on resources.
Signed-off-by: RJ Garcia <rj@bighead.net>

Fix Bug Preventing Denormalization of Input Classes with Different Fields

---

composer.json
src/Api/FormatsProvider.php
src/Bridge/Doctrine/MongoDbOdm/Filter/AbstractFilter.php
src/Bridge/Doctrine/MongoDbOdm/Paginator.php
src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Elasticsearch/DataProvider/Paginator.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/security.xml
src/Bridge/Symfony/Bundle/Resources/config/security_expression_language.xml
src/Cache/CachedTrait.php
src/DataProvider/Pagination.php
src/GraphQl/Type/SchemaBuilder.php
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/Metadata/Extractor/AbstractExtractor.php
src/Security/Core/Authorization/ExpressionLanguageProvider.php
src/Security/ExpressionLanguage.php
src/Security/ResourceAccessChecker.php
src/Serializer/AbstractItemNormalizer.php
src/Serializer/Filter/GroupFilter.php
src/Serializer/Filter/PropertyFilter.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Fixed tickets | #2265
Using the framework `security.expression_language` service rather than our own one allows us to extend the expression language with our own functions easily. Symfony already provides an easy way to register custom functions in `AddExpressionLanguageProvidersPass`. ApiPlatform currently does not. But I figured instead of providing our own compiler pass we can just use the built-in `security.expression_language`, extend that with our `is_granted()` function and thus at the same time also allow developers to add even more functions. Wdyt?

[WIP/RFC] Use framework expression language service instead of custom one

---

src/Bridge/Symfony/Bundle/ApiPlatformBundle.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlTypePass.php
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/GraphQl/Type/Definition/IterableType.php
src/GraphQl/Type/Definition/TypeInterface.php
src/GraphQl/Type/SchemaBuilder.php
src/GraphQl/Type/TypesFactory.php
src/GraphQl/Type/TypesFactoryInterface.php
tests/Bridge/Symfony/Bundle/ApiPlatformBundleTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlTypePassTest.php
tests/GraphQl/Type/Definition/IterableTypeTest.php
tests/GraphQl/Type/SchemaBuilderTest.php
tests/GraphQl/Type/TypesFactoryTest.php

| Deprecations? | yes?
Add a `TypeInterface` to register automatically custom types in GraphQL.
The `IterableType` has been modified to be used this way.
A `TypesFactory` service has been added, along with its interface to allow to register custom types any way you want.
Should we add a deprecation (see my comment below)?

[GraphQL] Custom types

---

features/main/crud.feature
src/Bridge/Symfony/Routing/IriConverter.php
tests/Bridge/Symfony/Routing/IriConverterTest.php

If you want to reproduce here is a little insight on how to do it: 
Let's say you have this resource:
```yaml
MyNameSpace\Duration:
shortName: 'Duration'
itemOperations:
get:
method: 'GET'
path: "/duration"
collectionOperations:
post:
method: 'POST'
path: "/duration"
controller: 'MyDomaine/DurationAPIController'
denormalization_context:
dateinterval_format: 'P%dDT%hH%iM'
normalization_context:
dateinterval_format: 'P%dDT%hH%iM'
properties:
id:
identifier: true
```
The duration is a VO that contains 3 fields.
The controller just use a librarie to calculate a start date + an …

bugfix: throw InvalidArgument on matching something that looks like an url

---

features/bootstrap/DoctrineContext.php
features/hydra/collection.feature
src/Annotation/ApiResource.php
src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
src/Hydra/Serializer/PartialCollectionViewNormalizer.php
src/Util/IriHelper.php
tests/Fixtures/TestBundle/Document/SoMany.php
tests/Fixtures/TestBundle/Entity/SoMany.php
tests/Hydra/Serializer/PartialCollectionViewNormalizerTest.php

Add tests for the SoMany collection
Uses the PropertyAccessor service and don't break the BC
Allow to use multiple fields
Fix cs
To avoid breaking @sroze branch I'm creating a new PR with his work. Original PR is https://github.com/api-platform/core/pull/1915 . I only rebased, squashed and fixed CS.

Enable the pagination via cursor (no page-based pagination)

---

src/Serializer/AbstractItemNormalizer.php
tests/Serializer/AbstractItemNormalizerTest.php

fix error case when denormalizing relations with plain identifiers. null is returned, no exceptions are thrown.
Not sure which branch to merge into. let me know!

fix error case when denormalizing relations with plain identifiers.

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php

Overriding the adapter for the `api_platform.elasticsearch.cache.metadata.document` cache pool was missing.

add missing cache pool adapter override

---

phpstan.neon
src/Bridge/Elasticsearch/DataProvider/Extension/SortExtension.php
src/Bridge/Elasticsearch/DataProvider/Filter/AbstractSearchFilter.php
src/Bridge/Elasticsearch/DataProvider/Filter/OrderFilter.php
src/Bridge/Elasticsearch/Serializer/ItemNormalizer.php
src/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverter.php
src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPass.php
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ConstraintViolationListNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ReservedAttributeNameConverter.php
src/JsonLd/ContextBuilder.php
src/Serializer/AbstractConstraintViolationListNormalizer.php
src/Serializer/AbstractItemNormalizer.php
tests/Bridge/Elasticsearch/DataProvider/Extension/SortExtensionTest.php
tests/Bridge/Elasticsearch/DataProvider/Filter/MatchFilterTest.php
tests/Bridge/Elasticsearch/DataProvider/Filter/OrderFilterTest.php
tests/Bridge/Elasticsearch/DataProvider/Filter/TermFilterTest.php
tests/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverterTest.php
tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php
tests/Hydra/Serializer/ConstraintViolationNormalizerTest.php
tests/JsonApi/Serializer/ConstraintViolationNormalizerTest.php
tests/Problem/Serializer/ConstraintViolationNormalizerTest.php

| Fixed tickets | #2342
| Doc PR        | https://github.com/api-platform/docs/pull/735
Make use of the new AdvancedNameConverterInterface

fix #2342 add metadata aware name converter if available

---

features/hydra/collection.feature
src/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtension.php
src/Bridge/Doctrine/MongoDbOdm/Paginator.php
tests/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtensionTest.php
tests/Bridge/Doctrine/MongoDbOdm/PaginatorTest.php

This PR allows to set a limit equals to 0 for MongoDB.
This is a little tricky since MongoDB doesn't allow it by default.
It is a requirement for this PR: https://github.com/api-platform/core/pull/2142

[MongoDB] Allow limit 0

---

features/main/crud_abstract.feature
src/EventListener/WriteListener.php
src/Serializer/AbstractItemNormalizer.php
tests/EventListener/WriteListenerTest.php
tests/Fixtures/TestBundle/Document/AbstractDummy.php
tests/Fixtures/TestBundle/Entity/AbstractDummy.php
tests/Fixtures/TestBundle/Resources/config/serialization/abstract_dummy.yml

The bug here is:
if you are trying to update a resource that has discriminator mapping, using a URI that is mapped on the abstract class, the class discriminator mapping resolution may fail because when updating a resource, there is no need to send the discriminator in the request.
Instead we should prioritize `OBJECT_TO_POPULATE` as it is already known which resource we have, via the Read Listener.

Fix instantiating object with discriminator mapping

---

src/Serializer/AbstractItemNormalizer.php
tests/Serializer/AbstractItemNormalizerTest.php

| Doc PR        | n/a (already explained)
This PR updates the denormalization process to honour the [ObjectNormalizer::DISABLE_TYPE_ENFORCEMENT](http://symfony.com/doc/current/components/serializer.html#recursive-denormalization-and-type-safety) flag, allowing invalid types to be handled by the validation layer instead of endpoints returning (by default) 500 status serialization errors.

Fixes ignoring type checks during denormalization

---

features/graphql/collection.feature
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php

| Fixed tickets | #2139
Backport of the fix from https://github.com/api-platform/core/pull/2142

[GraphQL] Fix pagination

---

src/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverter.php
src/Bridge/Symfony/Bundle/ApiPlatformBundle.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPass.php
tests/Bridge/Symfony/Bundle/ApiPlatformBundleTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php

| Fixed tickets | #2523
the `MetadataAwareNameConverter` wasn't being registered because the compiler pass had forgotten to be added :)

add missing MetadataAwareNameConverterPass registration 🐛

---

features/graphql/mutation.feature
src/GraphQl/Type/SchemaBuilder.php

| Fixed tickets | #2570 
As a reference, the [current Relay specification](https://facebook.github.io/relay/graphql/mutations.htm#sec-Mutation-inputs) contains the following:
> In particular, all mutations must expose exactly one argument, named input. This argument’s type must be a NON_NULL wrapper around an INPUT_OBJECT. That input object type **may** contain an argument named clientMutationId. **If provided**, that argument must be a String. That argument **may** be non‐null.

[GraphQL] Make clientMutationId nullable

---

features/doctrine/search_filter.feature
src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php
tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
tests/Fixtures/TestBundle/Document/RelatedToDummyFriend.php

| Fixed tickets | #2574
The search filter should not use DbRef when searching by association because lookups need raw ids.

Search filter should not use DbRef for association

---

features/graphql/introspection.feature
features/graphql/mutation.feature
src/GraphQl/Type/SchemaBuilder.php

| Tests pass?   | 
It makes sense for non-writeable fields to be excluded from the GraphQL **input** types, but they should surely be accessible in the payload data read back from a mutation.
To give a simple example, `Person._id` is non-writeable, as my IDs are auto generated by the server, but I still want to be able to see the generated ID after calling `createPerson`.
```graphql
mutation CreatePersonMutation {
createPerson(input: {name: "Alice"}) {
_id
name
}
}
```
The above query would previously have failed (`_id` not found in `createPersonPayload`) -- this PR corrects that.

[GraphQL] Allow non-writeable fields in mutation response

---

src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm_mercure_publisher.xml

When persisting from a messenger Handler, mercure updates where not published because `kernel.terminate` is not used in that context. This will use doctrine `postFlush` instead to publish mercure updates.

Publish mercure updates on flush

---

src/GraphQl/Serializer/ItemNormalizer.php
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/JsonLd/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php
src/Serializer/SerializerContextBuilder.php
tests/Hal/Serializer/ItemNormalizerTest.php
tests/Hydra/Serializer/ItemNormalizerTest.php
tests/JsonApi/Serializer/ItemNormalizerTest.php
tests/Serializer/AbstractItemNormalizerTest.php
tests/Serializer/ItemNormalizerTest.php
tests/Serializer/SerializerContextBuilderTest.php

| Fixed tickets | n/a will prevent some
This PR prevents the use of ApiPlatform's ItemNormalizer when not in the correct context. 
This means that:
- if we're using Symfony without any supported formats and outside ApiPlatform context, we're using symfony normalizers
- if it's a hypermedia format (`jsonld`, `hal`, `jsonapi`) we're using ApiPlatform's normalizers even if we're inside symfony
- if it's another format but we're using ApiPlatform we're still using our ItemNormalizers

Use the ItemNormalizer in the correct context

---

src/Bridge/Doctrine/Common/DataPersister.php
src/Bridge/Symfony/Bundle/DataPersister/TraceableChainDataPersister.php
src/Bridge/Symfony/Messenger/DataPersister.php
src/DataPersister/ChainDataPersister.php
src/DataPersister/ContextAwareDataPersisterInterface.php
src/EventListener/WriteListener.php
tests/DataPersister/ChainDataPersisterTest.php
tests/EventListener/WriteListenerTest.php

Re-do https://github.com/api-platform/core/pull/2569 as I merged it too quickly
Updates the ChainDataPersisters with the context so that it gets propagated to the messenger data persister.

Use ContextAware on data persister chains

---

src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Bridge/Symfony/Routing/IriConverter.php
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Resolver/ResourceFieldResolver.php
src/GraphQl/Serializer/ItemNormalizer.php
src/GraphQl/Type/SchemaBuilder.php
tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
tests/GraphQl/Resolver/ResourceFieldResolverTest.php
tests/GraphQl/Serializer/ItemNormalizerTest.php

Following https://github.com/api-platform/core/pull/2358.
Replace calls to serialize with computed data in the normalizer to improve performance.
In master because there are some BC breaks (but no deprecated since it's still experimental).

[GraphQL] Avoid to call serialize in ItemNormalizer

---

features/doctrine/date_filter.feature
features/doctrine/exists_filter.feature
features/graphql/filters.feature
features/main/crud.feature
src/Bridge/Doctrine/Common/Filter/ExistsFilterTrait.php
src/Bridge/Doctrine/MongoDbOdm/Filter/ExistsFilter.php
src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/Common/Filter/ExistsFilterTestTrait.php
tests/Bridge/Doctrine/MongoDbOdm/Filter/ExistsFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/ExistsFilterTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/app/config/config_orm.yml
tests/Fixtures/app/config/config_services_mongodb.yml

| Bug fix?      | yes (for GraphQL)
| Fixed tickets | #2231
| Doc PR        | api-platform/docs#613
Improve the behavior of the `ExistsFilter` filter to be declared according to the following syntax:
- on a REST collection endpoints: `/dummies?exists[<property>]=true/false`
- on the GraphQL endpoint: `dummies(exists: {<property>: "true/false"}) { ... }`
The name of the query parameter is controlled via the bundle configuration:
```yaml
api_platform:
collection:
exists_parameter_name: 'not_null'
``` 
It allows to use an `ExistsFilter` and a `SearchFilter` on the same property via the GraphQL endpoint.

Improve the ExistsFilter behavior (to cohabit with the SearchFilter)

---

src/Annotation/ApiResource.php
src/Bridge/Elasticsearch/DataProvider/CollectionDataProvider.php
src/Bridge/Elasticsearch/DataProvider/ItemDataProvider.php
src/Bridge/Symfony/Bundle/Resources/config/elasticsearch.xml
tests/Bridge/Elasticsearch/DataProvider/CollectionDataProviderTest.php
tests/Bridge/Elasticsearch/DataProvider/ItemDataProviderTest.php

If you want to use Elasticsearch on top of doctrine it's currently not possible (unless you override the Elasticsearch DataProvider). 
This adds an `elasticsearch` attribute that you can use to disable elasticsearch (it's enabled y default as soon as you have a mapping). 
For example:
```
*   elasticsearch=false,
*   collectionOperations={"get",
*     "create"={"input"=BookmarkInput::class, "output"=false, "status"=202, "method"="POST", "messenger"=true},
*     "search"={"elasticsearch"=true, "method"="GET", "path"="/bookmarks/search.{_format}"}
*   }
* )
``` …

Attribute to allow disabling elasticsearch

---

src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Bundle/Resources/config/elasticsearch.xml
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Bridge/Symfony/Bundle/Resources/config/hal.xml
src/Bridge/Symfony/Bundle/Resources/config/jsonapi.xml
src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
src/GraphQl/Serializer/ItemNormalizer.php
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/JsonLd/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php
src/Serializer/InputOutputMetadataTrait.php
src/Serializer/ItemNormalizer.php
src/Serializer/SerializerContextBuilder.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/GraphQl/Serializer/ItemNormalizerTest.php
tests/Hal/Serializer/ItemNormalizerTest.php
tests/Hydra/Serializer/ItemNormalizerTest.php
tests/JsonApi/Serializer/ItemNormalizerTest.php
tests/Serializer/AbstractItemNormalizerTest.php
tests/Serializer/ItemNormalizerTest.php
tests/Serializer/SerializerContextBuilderTest.php

| Fixed tickets | #2563, #2591, ...; alternative to #2566 (reverted here)
This should ensure the same caching of `supports*` methods as before for resource classes. For non-resource classes (handled by a separate instance), the `supports*` methods use the `$context`, thus not cacheable.
Not sure about the performance impact (positive or negative), but I think this is cleaner as we don't indiscriminately say yes to things we might not be able to handle (provided we're at a low enough priority). And there's no need for `use_api_platform` and/or special treatment of some formats.
Big thanks to @soyuka …

Use separate instance of ItemNormalizer for handling non-resource

---

src/Bridge/Symfony/Messenger/DataPersister.php
tests/Bridge/Symfony/Messenger/DataPersisterTest.php

| Doc PR        | soon
When the context is available in the Messenger Data Persister, let's use it. This also gives us the ability to send an Input to the messenger (skip the transformation see https://github.com/api-platform/core/pull/2495 discussion).

Fix messenger persister

---

behat.yml.dist
features/bootstrap/CommandContext.php
features/graphql/schema.feature
src/Bridge/Symfony/Bundle/Command/GraphQlExportCommand.php
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Doc PR        | https://github.com/api-platform/docs/pull/759
It can be useful for some tools to have the file representing the GraphQL schema.
Can be exported in a file like this:
```shell
bin/console api:graphql:export > schema.graphql
```

[GraphQL] Add a command for exporting a SDL schema

---

src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml

| Doc PR        | https://github.com/api-platform/docs/pull/760
Because we changed the priorities on normalizers, let's change these as well. This will simplify the documentation and user-land extensions should have positive priorities.

Change doctrine extension priorities

---

src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php

| Bug fix?      | yes ?
| Fixed tickets | https://github.com/api-platform/core/issues/2552
@teohhanhui would this work?

Do not use DISTINCT where there are no joins

---

features/bootstrap/DoctrineContext.php
features/hal/input_output.feature
features/jsonapi/input_output.feature
features/main/input_output.feature
features/main/non_resource.feature
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php

[jsonapi][jsonhal] Correct normalization of output class and non-resource

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/app/config/config_common.yml

| Fixed tickets | #2593 (partially)
| Doc PR        | https://github.com/api-platform/docs/pull/766
With the cache enabled, changing API resource metadata in `dev` still works without a manual `cache:clear`.

Do not disable cache in dev

---

features/main/input_output.feature
src/EventListener/SerializeListener.php
src/Validator/EventListener/ValidateListener.php

Adds a test to write on a resource with an `input=false`. Should we throw an error if the user sent data and only accept empty data?

Create a resource with a falsy input

---

features/main/input_output.feature
src/Annotation/ApiResource.php
src/Bridge/Symfony/Bundle/Resources/config/messenger.xml
src/Bridge/Symfony/Messenger/DataPersister.php
src/Bridge/Symfony/Messenger/DataTransformer.php
src/EventListener/RespondListener.php
src/EventListener/WriteListener.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Messenger/DataTransformerTest.php
tests/EventListener/RespondListenerTest.php
tests/Fixtures/TestBundle/Dto/MessengerInput.php
tests/Fixtures/TestBundle/Dto/MessengerResponseInput.php
tests/Fixtures/TestBundle/Entity/MessengerWithInput.php
tests/Fixtures/TestBundle/Entity/MessengerWithResponse.php
tests/Fixtures/TestBundle/MessengerHandler/MessengerWithInputHandler.php
tests/Fixtures/TestBundle/MessengerHandler/MessengerWithResponseHandler.php
tests/Fixtures/app/config/config_common.yml

Add a helper to use Inputs as messages

---

src/HttpCache/EventListener/AddHeadersListener.php
tests/HttpCache/EventListener/AddHeadersListenerTest.php

Following our conversation on Slack, this PR aims at avoiding Api-Platform to generate cache headers on 4xx / 5xx responses.

Ensure unsuccessful responses are not cached

---

src/Bridge/Doctrine/Orm/Filter/SearchFilter.php

Remove a BC break introduced in #2630

[2.4] Allow autowiring of class extending SearchFilter

---

phpstan.neon.dist
src/Metadata/Property/Factory/InheritedPropertyMetadataFactory.php
src/Metadata/Property/Factory/InheritedPropertyNameCollectionFactory.php
src/Metadata/Resource/ResourceNameCollection.php

Fix phpstan v0.11.5 false positives

---

src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php

Remove a BC break introduced by #2243

---

src/Bridge/Symfony/Bundle/CacheWarmer/CachePoolClearerCacheWarmer.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/app/config/config_common.yml

| Fixed tickets | alternative fix for #2644, reverts the revert #2648, partially #2593
| Doc PR        | https://github.com/api-platform/docs/pull/772
Note: Does not really warm the cache (lol)

Add a cache warmer to clear cache pools in dev

---

features/main/input_output.feature
src/Bridge/Symfony/Messenger/DataPersister.php
src/Bridge/Symfony/Messenger/DataTransformer.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/GraphQl/Type/SchemaBuilder.php
src/Metadata/Resource/Factory/InputOutputResourceMetadataFactory.php
tests/Bridge/Symfony/Messenger/DataPersisterTest.php
tests/Bridge/Symfony/Messenger/DataTransformerTest.php
tests/Fixtures/TestBundle/Entity/MessengerWithInput.php
tests/Metadata/Resource/Factory/InputOutputResourceMetadataFactoryTest.php

We forgot to take graphql mutations into consideration when retrieving the metadata. This now works correctly when performing a `createBookmark` mutation on my resource:
```
/**
*      graphql={"create"={"input"=BookmarkInput::class, "messenger"="input"}}
* )
*/
class Bookmark {}
``` 
It'll forward `BookmarkInput` to the messenger via the mutation :fire: :fire:  :fire:  . 
Note: for naming consistency I took the liberty of changing `graphql_operation_name` to `graphql_mutation_name` in our internal `$context` because else it's confusing.

GraphQl: parse input&messenger metadata

---

src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Serializer/NoOpScalarNormalizer.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Fixed tickets | #2593 (partially)
/cc @bastnic

Add a cacheable no-op scalar normalizer

---

src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Bridge/Symfony/Bundle/ApiPlatformBundle.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php
tests/Bridge/Symfony/Bundle/ApiPlatformBundleTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPassTest.php

| Fixed tickets | https://github.com/api-platform/core/pull/2643#issuecomment-476202544

Alternative fix to #2643: allow autowiring of filter classes

---

composer.json
phpstan.neon.dist
src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
src/Bridge/Doctrine/Orm/Util/QueryBuilderHelper.php
src/Bridge/Doctrine/Orm/Util/QueryChecker.php
src/Bridge/Doctrine/Orm/Util/QueryJoinParser.php
tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php
tests/Bridge/Doctrine/Orm/Util/QueryBuilderHelperTest.php
tests/Bridge/Doctrine/Orm/Util/QueryCheckerTest.php
tests/Bridge/Doctrine/Orm/Util/QueryJoinParserTest.php

| New feature?  | no?
| BC breaks?    | no?
| Fixed tickets | https://github.com/api-platform/core/pull/2611#issuecomment-474909777, https://github.com/api-platform/core/pull/2611#issuecomment-474910906
| Doc PR        | https://github.com/api-platform/docs/pull/771
Refactor `QueryChecker` etc.
I've removed the flawed handling of "join by class", as we simply have not enough information to do the right thing there. The main caveat (as was before) is that our checking covers the "80%":
- join by association
- no complex expression in `SELECT` / `ORDER BY` clauses
but will be confused in the remaining "20%".
For example:
🗹 Supported:
```dql
SELECT d, a_1
FROM …
```

Don't use fetchJoinCollection on Doctrine Paginator when not needed

---

features/bootstrap/DoctrineContext.php
features/graphql/mutation.feature
phpstan.neon.dist
src/Bridge/Symfony/Bundle/ApiPlatformBundle.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlMutationResolverPass.php
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/GraphQl/Resolver/Factory/ItemResolverFactory.php
src/GraphQl/Resolver/MutationResolverInterface.php
tests/Bridge/Symfony/Bundle/ApiPlatformBundleTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Document/DummyCustomMutation.php
tests/Fixtures/TestBundle/Entity/DummyCustomMutation.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryCollectionResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryItemResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryNotRetrievedItemDocumentResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryNotRetrievedItemResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/SumMutationResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/SumNotPersistedMutationResolver.php
tests/Fixtures/app/config/config_common.yml
tests/Fixtures/app/config/config_orm.yml
tests/Fixtures/app/config/config_services_mongodb.yml
tests/GraphQl/Resolver/Factory/ItemMutationResolverFactoryTest.php
tests/GraphQl/Resolver/Factory/ItemResolverFactoryTest.php

Introduce a new `MutationResolverInterface` interface.
Create a service which implements this interface and declare your custom mutation on your entity:
```
@ApiResource(graphql={
"create",
"update",
"increment"={"mutation"=IncrementMutation::class}
})
```
If `null` is returned from the resolver, the item will not be persisted.

[GraphQL] Add custom mutations

---

composer.json
phpstan.neon.dist

| Fixed tickets | /
Currently, the required version of the symfony/serializer is ^4.1 but in api-platform/core 2.4 we use an interface that is available only since Serializer v4.2 :
`final class ReservedAttributeNameConverter implements AdvancedNameConverterInterface`
This creates a nice error like that:
```
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception                       
[RuntimeException] …
```

fix: update symfony/serializer required version

---

src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php

In every other metadata factory, we check if attributes is `null`. The AnnotationResourceMetadataFactory is one of the first to run and sets the attributes to an empty array. This then blocks other metadata factories, and they will not set the `attributes` value because it's not null.

Metadata: Attributes default value should be null not an empty array

---

src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlMutationResolverPass.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlQueryResolverPass.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlTypePass.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlMutationResolverPassTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlQueryResolverPassTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlTypePassTest.php

Compiler passes ran with no graphql which was producing errors.

GraphQl: Use compiler pass only when enabled

---

features/graphql/mutation.feature
src/GraphQl/Type/SchemaBuilder.php

Relay Input Object Mutations Specification was not fully respected: https://facebook.github.io/relay/graphql/mutations.htm#sec-Mutation-inputs.
The input object needs to be wrapped around a non-null wrapper.

[GraphQL] Non-null input for mutations

---

features/bootstrap/DoctrineContext.php
features/main/relation.feature
tests/Fixtures/TestBundle/Document/Address.php
tests/Fixtures/TestBundle/Document/Customer.php
tests/Fixtures/TestBundle/Document/Order.php
tests/Fixtures/TestBundle/Entity/Address.php
tests/Fixtures/TestBundle/Entity/Customer.php
tests/Fixtures/TestBundle/Entity/Order.php

This test is related with approved [PR](https://github.com/api-platform/core/pull/2183) and reported bug [#799](https://github.com/api-platform/api-platform/issues/799).

Add Behat test for PR 2183

---

features/openapi/docs.feature
features/swagger/docs.feature
src/Swagger/Serializer/DocumentationNormalizer.php

| Fixed tickets | #1812
| Doc PR        | not needed
This is the updated PR from https://github.com/api-platform/core/pull/1812. I'm sorry @RonRademaker I couldn't keep your commits separate and continue the work but instead I had to redo quite a bit because of the recent addition of OpenAPI Spec 3.0 support. I've made sure the commit is co-authored though so you get the attribution you deserve 😄 
Thanks for the initial work!

Added support for pagination parameters in subresource docs

---

features/main/table_inheritance.feature
src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php
tests/Fixtures/FileConfigurations/interface_resource.yml
tests/Fixtures/TestBundle/DataProvider/ResourceInterfaceImplementationDataProvider.php
tests/Fixtures/TestBundle/OtherResources/ResourceInterface.php
tests/Fixtures/TestBundle/OtherResources/ResourceInterfaceImplementation.php
tests/Fixtures/TestBundle/Resources/config/api_resources.yml
tests/Metadata/Property/Factory/ExtractorPropertyMetadataFactoryTest.php

| Fixed tickets | Related to https://github.com/api-platform/core/issues/1574
TL;DR: Before: no "item" route working because we can't define an identifier. After: we can define a property for an interface and it will not be considered as "not found property".
1. It makes no sense to check if an interface exists in case it's an interface ;
2. If the property is not recognized as one and there is no identifier, then API Platform will not be able to call the DataProvider for a given item and interface as a resource is an incomplete feature.
```yaml
Me\InterfaceAsAResource:
properties:
foo: …
```

Ignore property that does not exist for interfaces (identifiers for interfaces)

---

src/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php
tests/Bridge/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
tests/Fixtures/TestBundle/Entity/DummyNoGetOperation.php

#EUFOSSA
Since we can get rid of get operations, we should not trigger the cache for these.
Moreover we should not call purge method if there is nothing to purge.

fix (cache): prevent avoidable purge

---

features/security/strong_typing.feature
tests/Fixtures/TestBundle/Entity/Dummy.php

| Fixed tickets | https://github.com/api-platform/core/pull/2054
Apparently this has been fixed in the meantime. I still added the test and fixed it (`gettype()` returns `null` uppercase).

Added an additional test for strict types validation

---

features/doctrine/search_filter.feature
src/Bridge/Doctrine/Common/Filter/SearchFilterTrait.php
src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php
src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Test/DoctrineMongoDbOdmFilterTestCase.php
tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Document/DummyCar.php
tests/Fixtures/TestBundle/Entity/DummyCar.php
tests/Util/AnnotationFilterExtractorTraitTest.php

| Fixed tickets | #775
This PRs update the ids management for association in the SearchFilter.
I've not updated the single at the moment because I think it should be done in another PR. 
This fixes #775.
Something I'm not sure is the behaviour, do we ignore the filter (this is the current implementation) or do we return 0 elements (like by replacing the invalid values with null instead of logging + return) ?

feature: improve ids management for association and fix invalid iri/uuid in SearchFilter

---

features/graphql/input_output.feature
tests/Fixtures/TestBundle/Document/MessengerWithInput.php
tests/Fixtures/TestBundle/MessengerHandler/Document/MessengerWithInputHandler.php
tests/Fixtures/TestBundle/MessengerHandler/Entity/MessengerWithInputHandler.php
tests/Fixtures/app/config/config_common.yml
tests/Fixtures/app/config/config_orm.yml
tests/Fixtures/app/config/config_services_mongodb.yml

Input messenger was not tested with MongoDB.

Test input messenger with MongoDB

---

src/EventListener/WriteListener.php
tests/EventListener/WriteListenerTest.php

Not using the persistResult could cause issues in generating the IRI for
new resources because the ID was not set on the controllerResult but
only on the persistResult for example.
| BC breaks?    | not sure?
| Fixed tickets | #2692 
| Doc PR        | not relevant?

Make sure to always use the persistResult for follow-up actions

---

src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php

| Bug fix?      | no, but prevent bug in client application
#2712 targeted `master`. Cherry-picked for `2.4` instead.

Convert HTTP method to uppercase

---

src/Api/IdentifiersExtractor.php
tests/Api/IdentifiersExtractorTest.php
tests/Bridge/Symfony/Routing/IriConverterTest.php

It was probably a bad copy/paste
| Fixed tickets | None

Fix error message in identifiers extractor

---

features/jsonld/input_output.feature
phpstan.neon.dist
src/EventListener/SerializeListener.php
src/Metadata/Resource/Factory/InputOutputResourceMetadataFactory.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/EventListener/SerializeListenerTest.php
tests/Fixtures/TestBundle/Controller/DummyDtoNoInput/CreateItemAction.php
tests/Fixtures/TestBundle/Controller/DummyDtoNoInput/DoubleBatAction.php
tests/Fixtures/TestBundle/DataTransformer/DummyDtoNoInputToOutputDtoDataTransformer.php
tests/Fixtures/TestBundle/Document/DummyDtoNoInput.php
tests/Fixtures/TestBundle/Entity/DummyDtoNoInput.php
tests/Fixtures/app/config/config_common.yml

Also fix Behat test for when input class is set to `null`.

Fix HTTP status code when output class is set to null

---

src/Bridge/Doctrine/MongoDbOdm/Filter/ExistsFilter.php
src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Bridge/Doctrine/MongoDbOdm/Filter/ExistsFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/ExistsFilterTest.php

This PR aims to provide an alternative to https://github.com/api-platform/core/pull/2640
As i'm working on supporting name converters in filters, adding another optional argument is way harder now, so i went with what have been done in #1844

Simplify ExistsFilter declaration

---

phpstan.neon.dist
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

We should wait for https://github.com/symfony/symfony/pull/31173 to be merged first.

Rename ContainerBuilder::addRemovedBindingId to ContainerBuilder::removeBindings

---

.php_cs.dist
phpstan.neon.dist
tests/Fixtures/app/console

Fix the test app/console binary

---

features/main/crud.feature
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/EventListener/DeserializeListener.php
src/EventListener/ReadListener.php
src/EventListener/SerializeListener.php
src/EventListener/WriteListener.php
src/Metadata/Resource/Factory/InputOutputResourceMetadataFactory.php
src/Metadata/Resource/ToggleableOperationAttributeTrait.php
src/Validator/EventListener/ValidateListener.php
tests/Bridge/Symfony/Validator/EventListener/ValidateListenerTest.php
tests/EventListener/DeserializeListenerTest.php
tests/EventListener/ReadListenerTest.php
tests/EventListener/SerializeListenerTest.php
tests/EventListener/WriteListenerTest.php
tests/Validator/EventListener/ValidateListenerTest.php

| New feature?  | kinda?
| Fixed tickets | #1282, #2731
The toggleable listeners are:
- ReadListener ("read")
- DeserializeListener ("deserialize")
- ValidateListener ("validate")
- WriteListener ("write")
- SerializeListener ("serialize")
Basically, we fix the handling of empty request content by **removing** explicit handling of empty request content (which was wrong, resulting in weird bugs such as #2731), but allowing the user to be in control instead.
TODO:

Fix handling of empty request content by allowing to disable listeners per operation

---

composer.json
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPass.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php
tests/Fixtures/Elasticsearch/Fixtures/tweet.json
tests/Fixtures/Elasticsearch/Fixtures/user.json
tests/Fixtures/Elasticsearch/Mappings/tweet.json
tests/Fixtures/Elasticsearch/Mappings/user.json
tests/Fixtures/app/config/config_elasticsearch.yml

| Fixed tickets | #2677
ping @ogirardkaliop @teohhanhui

Use the metadata aware name converter when available fix #2677

---

src/Serializer/Filter/PropertyFilter.php
tests/Serializer/Filter/PropertyFilterTest.php

| Fixed tickets | See https://github.com/api-platform/core/issues/2370#issuecomment-459306935
| Doc PR        | not needed
Found when making the SymfonyCasts tutorial :). The Swagger/OpenAPI description of the filter was awesome - it's just missing the `[]` when you actually *try* it. 
Cheers!

swagger/openapi bug with PropertyFilter use ?properties[]= not ?properties=

---

features/graphql/collection.feature
features/graphql/filters.feature
features/graphql/mutation.feature
features/graphql/type.feature
phpstan.neon.dist
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/FieldsBuilderInterface.php
src/GraphQl/Type/SchemaBuilder.php
src/GraphQl/Type/TypeBuilder.php
src/GraphQl/Type/TypeBuilderInterface.php
src/GraphQl/Type/TypeConverter.php
src/GraphQl/Type/TypeConverterInterface.php
src/GraphQl/Type/TypeNotFoundException.php
src/GraphQl/Type/TypesContainer.php
src/GraphQl/Type/TypesContainerInterface.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/GraphQl/Type/Definition/DateTimeType.php
tests/Fixtures/TestBundle/GraphQl/Type/TypeConverter.php
tests/Fixtures/app/config/config_common.yml
tests/GraphQl/Type/FieldsBuilderTest.php
tests/GraphQl/Type/SchemaBuilderTest.php
tests/GraphQl/Type/TypeBuilderTest.php
tests/GraphQl/Type/TypeConverterTest.php
tests/GraphQl/Type/TypesContainerTest.php

| BC breaks?    | yes (experimental)
A big improvement of the GraphQL system with more services having consistent responsibilities.
With this refactoring, the system will be more maintainable, well tested and customizable :rocket:
Featuring:
- a new `TypeConverter` service to manage types. It can be decorated to manage custom types. An example is done in the tests.
- a `TypesContainer` service containing all the loaded types and respecting the PSR-11.
- all unit tests rewritten to cover the majority of cases for each service.
In order to do so, it was mandatory to break the circular dependencies of the …

[GraphQL] Services Refactoring

---

features/authorization/deny.feature
src/EventListener/ReadListener.php
src/Security/EventListener/DenyAccessListener.php
tests/EventListener/ReadListenerTest.php
tests/Fixtures/TestBundle/Document/SecuredDummy.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php

| Fixed tickets | #1646
Alternative approach to #2710 as discussed there.
The good thing about this one is that it is totally BC.
The disadvantage is that it might be harder to discover even if covered by documentation and users will not be "protected" out of the box.

Add the original data to attributes and allow to access it in ExpressionLanguage

---

src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
src/Bridge/Doctrine/Orm/Util/QueryBuilderHelper.php
tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
tests/Bridge/Doctrine/Orm/Util/QueryBuilderHelperTest.php

| Fixed tickets | #2792
This PR aims to finish #2221 by adding a non-regression test.
I didn't push on the original fork as it was targeting master and I think this needs to target 2.4 as a bugfix.
I've kept your commit @Siregacvek
ping @beleneglorion, please confirm that it works in your case too

[2.4] Fixed join condition replacement.

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php

I noticed that in Swagger docs properties that are not readable and not writable are presented anyway.
In our case it was `id` field that we don't want do expose in API in favor of `pif` field.
Below I include our configuration, simplified to focus on bug
Resource configuration
```yaml
App\Entity\BankAccount:
attributes:
normalization_context:
groups: ['bankAccount:read']
denormalization_context:
groups: ['bankAccount:write']
collectionOperations:
get: ~
itemOperations:
get: ~
properties:
id:
identifier: false
pid:
identifier: true
```
serializer configuration
```yaml …
```

Skip not readable and not writable properties in Swagger

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

| Doc PR        | not needed
Hi!
I noticed that the `servers` key on OpenAPI always look like this:
The `url` originally comes from `$request->getBasePath()` in `DocumentationAction`. The problem is that if I try to pass the URL to the documentation straight to Postman (which supports OpenAPI 3), I see this error:
> Error while importing Open API 3.0: The OpenAPI spec should have a valid URL in each servers object
In fact, `servers` defaults to `/` in OpenAPI if not specified. There was just a bit of missing logic to skip setting it if the base path is an empty string. This fixes the import into …

Fixing bug where servers would be added and set to an empty string in OpenAPI

---

features/authorization/deny.feature
src/EventListener/ReadListener.php
src/Security/EventListener/DenyAccessListener.php
tests/EventListener/ReadListenerTest.php
tests/Fixtures/TestBundle/Document/SecuredDummy.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php

| Doc PR        | api-platform/doc#814
Hi friends!
#2779 was coded as a feature and therefore was merged into master. I think that's a mistake, as it's related to security. It's currently not possible to do something like this:
```
"access_control"="is_granted('ROLE_USER') and object.getOwner() == user",
```
Without potentially exposing your API to unwanted access: a user could change the `owner` to be themselves. For the reason, even though this *is* technically a feature, I think it's critical enough for security (and simple) that it should be backported.
Thanks!

Backport original_data access control variable to 2.4 as a bug fix

---

CHANGELOG.md

| Fixed tickets | https://github.com/api-platform/core/pull/2757#issuecomment-494345598
/cc @borNfreee

Add a note in the CHANGELOG about empty request content bugfix

---

src/HttpCache/EventListener/AddHeadersListener.php
tests/Annotation/ApiResourceTest.php
tests/Fixtures/AnnotatedClass.php
tests/HttpCache/EventListener/AddHeadersListenerTest.php

Besides of setting the default value of the `vary` header, it would be useful if one could also set/modify it by resource.
Real life use case:
I have to implement an authenticated and cached API. Most of the endpoints' results should be cached per user, so the default setting like this works fine:
```yaml
vary: ['Content-Type', 'Authorization', 'Accept-Language']
```
But there are some endpoints that serve common, shared resources, so they shouldn't vary by Authorization.
| Fixed tickets | #2742 
| Doc PR        | api-platform/docs#820

Ability to modify the Vary header

---

src/GraphQl/Serializer/ItemNormalizer.php
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/JsonLd/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php

Implementing additional interfaces (`ContextAwareNormalizerInterface` and `ContextAwareDenormalizerInterface`) in an abstract class is a BC break.

Fix BC break in AbstractItemNormalizer introduced in v2.4

---

.circleci/config.yml
composer.json
phpstan.neon.dist
phpunit.xml.dist
phpunit_mongodb.xml
src/Security/ResourceAccessChecker.php
tests/Security/EventListener/DenyAccessListenerTest.php

Fix build with Symfony 4.3

---

.circleci/config.yml
.travis.yml
appveyor.yml
composer.json
tests/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtensionTest.php
tests/Bridge/Doctrine/MongoDbOdm/PaginatorTest.php
tests/Fixtures/app/bootstrap.php
tests/Fixtures/app/config/config_common.yml

Also re-add mongodb packages to `require-dev` as we want developers to be able to run `phpstan` successfully. This means they must have `ext-mongodb`, but it's easy to satisfy this requirement...

Don't try to mock UnitOfWork as it's final

---

features/authorization/deny.feature
features/graphql/authorization.feature
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/GraphQl/Resolver/ItemResolver.php
src/GraphQl/Resolver/ResourceAccessCheckerTrait.php
tests/Fixtures/TestBundle/Document/SecuredDummy.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php

| Bug fix?      | yes (kind of)
| BC breaks?    | yes (in an experimental trait)
Add support for `previous_object` in GraphQL too, and fix an inconsistency between REST and GraphQL (previously, the object was passed to the security expression before the deserialization, while with REST it was after).
See #2779 and #2811 (/cc @weaverryan)

GraphQL: add support for previous_object in access_control

---

src/Bridge/Doctrine/Orm/Paginator.php
src/Bridge/Doctrine/Orm/QueryAwareInterface.php

This pull request adds `getQuery` method to `ApiPlatform\Core\Bridge\Doctrine\Orm\AbstractPaginator`. 
Why: When making Translatable entity from Doctrine Extensions work I had to set hints for Query (https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/translatable.md#using-orm-query-hint). The best way to do this from my point of view was to decorate pagination extension (`api_platform.doctrine.orm.query_extension.pagination`) and the only thing I was missing is a way to manipulate with a Query object. Otherwise I would have to rewrite whole Pagination Extension.
`Doctrine\ORM\Tools\Pagination\Paginator` …

Doctrine ORM Paginator should provide possibility to get  Query object

---

.travis.yml
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config_common.yml

Improve MongoDB Bundle detection

---

features/graphql/collection.feature
features/graphql/mutation.feature
features/graphql/query.feature
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/FieldsBuilderInterface.php
src/GraphQl/Type/TypeBuilder.php
src/GraphQl/Type/TypeConverter.php
src/GraphQl/Type/TypeConverterInterface.php
tests/Fixtures/TestBundle/Document/DummyCustomMutation.php
tests/Fixtures/TestBundle/Document/DummyCustomQuery.php
tests/Fixtures/TestBundle/Entity/DummyCustomMutation.php
tests/Fixtures/TestBundle/Entity/DummyCustomQuery.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryCollectionResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryItemResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/SumMutationResolver.php
tests/Fixtures/TestBundle/GraphQl/Type/Definition/DateTimeType.php
tests/Fixtures/TestBundle/GraphQl/Type/TypeConverter.php
tests/GraphQl/Type/FieldsBuilderTest.php
tests/GraphQl/Type/TypeBuilderTest.php
tests/GraphQl/Type/TypeConverterTest.php

| Doc PR        | https://github.com/api-platform/docs/pull/830
The last feature needed before documenting the custom queries and mutations!
It allows to modify args of custom queries or mutations by using the GraphQL type system.
For instance, if you want to change the default args of a custom mutation (the `id` of the mutated item by default), you can do it like this:
```php
/**
* @ApiResource(graphql={
*     "myMutation"={
*         "mutation"="app.graphql.mutation_resolver.my_mutation",
*         "args"={"customArg"={"type"="[Int!]!"}}
*     }
* })
*/
class Example
```
Now, the `myMutation` mutation …

[GraphQL] Resolve types in custom operations

---

features/serializer/deserialize_objects_using_constructor.feature
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/Document/DummyEntityWithConstructor.php
tests/Fixtures/TestBundle/Entity/DummyEntityWithConstructor.php

Hi Folks!
After upgrading to 2.4.4 (from 2.4.2) I started getting an error.
The error wording is: `The property path constructor needs a string or an instance of \"Symfony\\Component\\PropertyAccess\\PropertyPath\". Got: \"integer\" in symfony/serializer/Normalizer/AbstractObjectNormalizer.php, line 302`.
I fixed this bug by adding '[]' to the class of the collection argument at [this line](https://github.com/api-platform/core/blob/v2.4.4/src/Serializer/AbstractItemNormalizer.php#L666).
| Fixed tickets | PR adds the test case

Fixed denormalization of a constructor argument which is a collection of non-resources

---

features/main/custom_operation.feature
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/JsonLd/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/Controller/Payment/VoidPaymentAction.php
tests/Fixtures/TestBundle/Document/Payment.php
tests/Fixtures/TestBundle/Document/VoidPayment.php
tests/Fixtures/TestBundle/Entity/Payment.php
tests/Fixtures/TestBundle/Entity/VoidPayment.php
tests/Fixtures/app/config/config_common.yml
tests/GraphQl/Serializer/ItemNormalizerTest.php
tests/Hal/Serializer/ItemNormalizerTest.php
tests/Hydra/Serializer/CollectionFiltersNormalizerTest.php
tests/Hydra/Serializer/CollectionNormalizerTest.php
tests/JsonApi/Serializer/ItemNormalizerTest.php
tests/JsonLd/Serializer/ItemNormalizerTest.php
tests/Serializer/AbstractItemNormalizerTest.php
tests/Serializer/ItemNormalizerTest.php

| Fixed tickets | #2855, api-platform/api-platform#1172

Allow custom operations to return a different class than the expected resource class

---

src/Security/ResourceAccessChecker.php

Remove unused trait import

---

composer.json
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/test.xml
src/Bridge/Symfony/Bundle/Test/ApiTestCase.php
src/Bridge/Symfony/Bundle/Test/Client.php
src/Bridge/Symfony/Bundle/Test/Response.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/Test/ClientTest.php
tests/Bridge/Symfony/Bundle/Test/ResponseTest.php

Currently, there are no very satisfactory solutions to write functional tests for web APIs built in PHP (API Platform and Symfony included):
* Mink/Behat/Behatch are BDD-oriented (which is completely fine, but doesn't fit with all projects/teams), are a bit complex to setup, have a high barrier to entry and are still not fully compatible with Symfony 4 (you need to rely on a dev version of Behat). They also lack of utilities, for database testing for instance.
* WebTestCase/BrowserKit are dedicated to webpage testing through web scraping (DOM Crawler, CSS selectors, simulation …

Add an HTTP client dedicated to functional API testing

---

phpstan.neon.dist

symfony/symfony#31903 was released.
https://github.com/api-platform/core/pull/2885 is blocked on `2.4`, but this should be good for `master`.

Remove ignored errors in phpstan which have been resolved upstream

---

tests/Annotation/ApiResourceTest.php
tests/Fixtures/AnnotatedClass.php
tests/Fixtures/TestBundle/Document/SecuredDummy.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php
tests/Security/EventListener/DenyAccessListenerTest.php
tests/Security/ResourceAccessCheckerTest.php

| Fixed tickets | #2896 
| Doc PR        | api-platform/doc
This PR remove this deprecation notice : Using the "has_role()" function in security expressions is deprecated since Symfony 4.2, use "is_granted()" instead.

Replace has_role() by is_granted()

---

src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js

| Fixed tickets | https://github.com/nelmio/NelmioApiDocBundle/issues/1517
Quick fix just to change the arrow function to something that IE11 supports. Everything else in the Nelmio API Doc Bundle works, just this single file arrow function breaks it in IE11

Change arrow function to an IE11 compatible function

---

src/Identifier/CompositeIdentifierParser.php
tests/Identifier/CompositeIdentifierParserTest.php

This modification allow to correctly fetch item with composite identifiers where some fields might be blank (not null) but are still needed to determine the correct record.
Currently it would fail as the `ApiPlatform\Core\Identifier\IdentifierConverter` would throw an `ApiPlatform\Core\Exception\InvalidIdentifierException` [here](https://github.com/api-platform/core/blob/d46ac32d404e0858c2d2dd13966fb1a5a52f6719/src/Identifier/IdentifierConverter.php#L54-L65) resulting in a `Symfony\Component\HttpKernel\Exception\NotFoundHttpException` in the …

Allow to extract blank values from composite identifier

---

features/security/validate_incoming_content-types.feature
src/EventListener/DeserializeListener.php
tests/EventListener/DeserializeListenerTest.php

A faulty Content-Type should return the 415 status code, not 406

---

phpstan.neon.dist
src/Bridge/Doctrine/MongoDbOdm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php

Use a workaround for a phpstan error ignored in https://github.com/api-platform/core/pull/2897
See https://github.com/phpstan/phpstan/issues/1905#issuecomment-464388880 for some context. But in short:
phpstan does not infer property type from constructor argument type, and it's not planned to be supported
I believe this would be a problem for any project that follows the current Symfony CS of not adding `@var` on a property when the matching argument is already type-hinted in the constructor. We've been told that IDEs support that just fine, but we will not have relief in …

Use workaround for a phpstan error

---

.gitignore
features/jsonld/json_serializable.feature
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Bundle/Resources/config/elasticsearch.xml
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Bridge/Symfony/Bundle/Resources/config/hal.xml
src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
src/Bridge/Symfony/Bundle/Resources/config/jsonapi.xml
src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
tests/Fixtures/TestBundle/Document/Content.php
tests/Fixtures/TestBundle/Document/Field.php
tests/Fixtures/TestBundle/Entity/Content.php
tests/Fixtures/TestBundle/Entity/Field.php
tests/Fixtures/TestBundle/Enum/ContentStatus.php

| Fixed tickets | api-platform/api-platform#1018, #2813
Replaces #2732

Fix normalizer priorities for correct JsonSerializable handling

---

phpstan.neon.dist
src/Bridge/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
src/EventListener/ExceptionListener.php
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/app/AppKernel.php

Fix deprecation notices in 2.4

---

.travis.yml
composer.json
features/bootstrap/HydraContext.php
features/graphql/mutation.feature
features/hydra/docs.feature
features/jsonld/context.feature
phpstan.neon.dist
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm_mercure_publisher.xml
src/Bridge/Symfony/Bundle/Resources/config/messenger.xml
src/Bridge/Symfony/Messenger/DataPersister.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Messenger/DataPersisterTest.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config_common.yml

| Fixed tickets | #2912, api-platform/api-platform#1169
#2784 fixed compatibility for Symfony 4.3 in `master` / `2.5`. This is basically the same but without bumping the dependencies.
Together with #2920 (and maybe more to do in #2911) this should allow full Symfony 4.3 compatibility in `2.4`.

Fix compatibility with Symfony 4.3

---

.circleci/config.yml
.gitignore
composer.json
features/json/input_output.feature
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/EventListener/ExceptionListener.php
src/Test/DoctrineMongoDbOdmFilterTestCase.php
src/Test/DoctrineMongoDbOdmSetup.php
src/Test/DoctrineOrmFilterTestCase.php
tests/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtensionTest.php
tests/Bridge/Elasticsearch/DataProvider/PaginatorTest.php
tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Bridge/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php
tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
tests/Fixtures/TestBundle/MessageHandler/PasswordResetRequestHandler.php
tests/JsonApi/EventListener/TransformFieldsetsParametersListenerTest.php
tests/JsonApi/EventListener/TransformFilteringParametersListenerTest.php
tests/JsonApi/EventListener/TransformPaginationParametersListenerTest.php
tests/JsonApi/EventListener/TransformSortingParametersListenerTest.php
tests/JsonApi/Serializer/ReservedAttributeNameConverterTest.php
tests/JsonLd/ContextBuilderTest.php
tests/Metadata/schema/XmlSchemaTest.php
tests/Serializer/JsonEncoderTest.php
tests/Serializer/ResourceListTest.php
tests/Serializer/SerializerContextBuilderTest.php
tests/Swagger/Serializer/ApiGatewayNormalizerTest.php
tests/Util/AnnotationFilterExtractorTraitTest.php

| Fixed tickets | #2856
As suggested by @karser
Also, since coverage jobs were failing, due to a `phpdbg` bug (see https://github.com/symfony/symfony/issues/32521):
Allow phpunit 8 and use `pcov` for coverage jobs.

Unwrap exception thrown in handler for Symfony Messenger 4.3

---

composer.json
tests/Bridge/Symfony/Bundle/Test/Constraint/ArraySubsetTest.php
tests/Fixtures/ArrayAccessible.php

| Fixed tickets | https://github.com/api-platform/core/pull/2887#discussion_r303496186

Do not rely on fixture from phpunit tests directory

---

src/Serializer/AbstractItemNormalizer.php
tests/Serializer/AbstractItemNormalizerTest.php

| Fixed tickets | api-platform/api-platform#1159
For child relations, iri is not set and it breaks varnish cache invalidation. See api-platform/api-platform#1159 for tests samples

Generate iri for child related resources

---

src/Bridge/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
tests/Bridge/Symfony/Bundle/Test/ApiTestCaseTest.php

| New feature?  | yes?
| Fixed tickets | https://github.com/api-platform/core/pull/2887#discussion_r304079495
| Doc PR        | @dunglas TODO?

Allow string in JSON assertions

---

features/graphql/collection.feature
features/graphql/mutation.feature
features/graphql/query.feature
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/GraphQl/Resolver/Factory/ItemResolverFactory.php
tests/Fixtures/TestBundle/Document/DummyCustomMutation.php
tests/Fixtures/TestBundle/Document/DummyCustomQuery.php
tests/Fixtures/TestBundle/Entity/DummyCustomMutation.php
tests/Fixtures/TestBundle/Entity/DummyCustomQuery.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryNoReadAndSerializeCollectionResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryNoReadAndSerializeItemDocumentResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryNoReadAndSerializeItemResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/SumNoWriteCustomResultMutationResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/SumOnlyPersistDocumentMutationResolver.php
tests/Fixtures/TestBundle/GraphQl/Resolver/SumOnlyPersistMutationResolver.php
tests/Fixtures/app/config/config_common.yml
tests/Fixtures/app/config/config_mongodb.yml
tests/Fixtures/app/config/config_test.yml
tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
tests/GraphQl/Resolver/Factory/ItemMutationResolverFactoryTest.php
tests/GraphQl/Resolver/Factory/ItemResolverFactoryTest.php

| Doc PR        | Will be added in https://github.com/api-platform/docs/pull/830
Since the introduction of custom queries and mutations, a needed feature was missing: the possibility to disable some "steps" the main resolver is doing.
For instance, if we want to create a custom mutation and letting it persist the mutated item as it wants, it was not possible before (`null` could be returned but the returned data was also `null`).
Now it can be done by disabling the `write` step in the operation attributes:
```php
<?php
namespace App\Model;
use …
```

[GraphQL] Disable some steps by setting operation attributes

---

CHANGELOG.md

[GraphQL] Update changelog

---

src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
src/Bridge/Symfony/Messenger/DataPersister.php
src/Bridge/Symfony/Messenger/DispatchTrait.php
src/EventListener/ExceptionListener.php
tests/EventListener/ExceptionListenerTest.php

| Fixed tickets | https://github.com/api-platform/core/pull/2930#issuecomment-511497096, https://github.com/api-platform/core/pull/2930#issuecomment-519565288
| Doc PR        | N/A?

Unwrap Messenger HandlerFailedException at the dispatch call site

---

features/graphql/filters.feature
src/GraphQl/Type/SchemaBuilder.php
tests/Fixtures/TestBundle/Document/DummyCarColor.php
tests/Fixtures/TestBundle/Entity/DummyCarColor.php
tests/GraphQl/Type/SchemaBuilderTest.php

| Fixed tickets | #2969
Backport of https://github.com/api-platform/core/pull/2970

[GraphQL] Use correct resource configuration for filter args of nested collection

---

composer.json
features/openapi/docs.feature
phpstan.neon.dist
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
src/Bridge/Symfony/Bundle/Resources/config/json_schema.xml
src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
src/Hydra/JsonSchema/SchemaFactory.php
src/JsonSchema/Schema.php
src/JsonSchema/SchemaFactory.php
src/JsonSchema/SchemaFactoryInterface.php
src/JsonSchema/TypeFactory.php
src/JsonSchema/TypeFactoryInterface.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/JsonSchema/SchemaTest.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

| Fixed tickets | #2715, #2415, #2502, api-platform/api-platform#1222
Introduce a new service allowing to generate a JSON Schema from any class, including those marked with `@ApiResource`.
It's an alternative approach to https://github.com/api-platform/core/pull/2715 to support specific JSON Schemas per MIME type in OpenAPI (this part is not ready yet).
It will also allow to generate JSON Schema directly, without having to rely on OpenAPI. It can be practical for validation, or to use libraries such as https://github.com/mozilla-services/react-jsonschema-form
This new capability will also replace …

[OpenAPI] Extract the JSON Schema builder

---

features/authorization/deny.feature
src/EventListener/ReadListener.php
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/Util/CloneTrait.php
tests/Fixtures/TestBundle/DataProvider/GeneratorDataProvider.php
tests/Fixtures/TestBundle/Document/SecuredDummy.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php
tests/Fixtures/app/config/config_test.yml
tests/Util/CloneTraitTest.php

| Doc PR        |  https://github.com/api-platform/docs/pull/858
Add a clone trait with a method `clone` that returns a clone of the given variable if cloneable.
Inspired by @alanpoulain from #2978

Prevent cloning generator when instanciating previous_data

---

src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/GraphQl/Resolver/Factory/ItemResolverFactory.php
src/GraphQl/Resolver/Stage/DenyAccessStage.php
src/GraphQl/Resolver/Stage/DenyAccessStageInterface.php
src/GraphQl/Resolver/Stage/DeserializeStage.php
src/GraphQl/Resolver/Stage/DeserializeStageInterface.php
src/GraphQl/Resolver/Stage/ReadStage.php
src/GraphQl/Resolver/Stage/ReadStageInterface.php
src/GraphQl/Resolver/Stage/SerializeStage.php
src/GraphQl/Resolver/Stage/SerializeStageInterface.php
src/GraphQl/Resolver/Stage/ValidateStage.php
src/GraphQl/Resolver/Stage/ValidateStageInterface.php
src/GraphQl/Resolver/Stage/WriteStage.php
src/GraphQl/Resolver/Stage/WriteStageInterface.php
tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
tests/GraphQl/Resolver/Factory/ItemMutationResolverFactoryTest.php
tests/GraphQl/Resolver/Factory/ItemResolverFactoryTest.php
tests/GraphQl/Resolver/Stage/DenyAccessStageTest.php
tests/GraphQl/Resolver/Stage/DeserializeStageTest.php
tests/GraphQl/Resolver/Stage/ReadStageTest.php
tests/GraphQl/Resolver/Stage/SerializeStageTest.php
tests/GraphQl/Resolver/Stage/ValidateStageTest.php
tests/GraphQl/Resolver/Stage/WriteStageTest.php

Use `__invoke` instead of `apply` following @bendavies comment.

[GraphQL] Use __invoke instead of apply for stages

---

tests/JsonSchema/TypeFactoryTest.php

[JSON Schema] Add test for TypeFactory

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php

| New feature?  | Yes
| Fixed tickets | #2982 

Fix : Throw a better message if http-client is not installed

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

Add default, min, max specification in pagination parameter API docs

---

features/authorization/legacy_deny.feature
src/Annotation/ApiResource.php
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Bridge/Symfony/Bundle/Resources/config/security.xml
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/GraphQl/Resolver/Factory/ItemResolverFactory.php
src/GraphQl/Resolver/Stage/SecurityPostDenormalizeStage.php
src/GraphQl/Resolver/Stage/SecurityPostDenormalizeStageInterface.php
src/GraphQl/Resolver/Stage/SecurityStage.php
src/GraphQl/Resolver/Stage/SecurityStageInterface.php
src/Security/EventListener/DenyAccessListener.php
src/Security/ResourceAccessChecker.php
tests/Annotation/ApiResourceTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/AnnotatedClass.php
tests/Fixtures/TestBundle/Document/LegacySecuredDummy.php
tests/Fixtures/TestBundle/Document/SecuredDummy.php
tests/Fixtures/TestBundle/Entity/LegacySecuredDummy.php
tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
tests/GraphQl/Resolver/Factory/ItemMutationResolverFactoryTest.php
tests/GraphQl/Resolver/Factory/ItemResolverFactoryTest.php
tests/GraphQl/Resolver/Stage/SecurityPostDenormalizeStageTest.php
tests/GraphQl/Resolver/Stage/SecurityStageTest.php
tests/Security/EventListener/DenyAccessListenerTest.php
tests/Security/ResourceAccessCheckerTest.php

| Waiting for PR?      | api-platform/core#2990
| Fixed tickets | #1646, api-platform/api-platform#1218
| Doc PR        | api-platform/docs#859

Deprecate access_control attribute, add security + security_post_denormalize attributes

---

src/Bridge/Doctrine/Common/Filter/OrderFilterTrait.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Bridge/Doctrine/Common/Filter/OrderFilterTestTrait.php
tests/Bridge/Doctrine/MongoDbOdm/Filter/OrderFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

Improve order filter generated API doc

---

src/Bridge/Symfony/Bundle/Resources/config/json_schema.xml
src/JsonSchema/Command/JsonSchemaGenerateCommand.php
src/JsonSchema/SchemaFactory.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php

Add a command to generate a JSON Schema for a resource.
Can be used for the whole resource or by operation

add command to generate json schema

---

src/DataTransformer/DataTransformerInterface.php
src/Serializer/AbstractItemNormalizer.php

Update docblock for data transformer interface. Support method signature was wrong, object name is wrong too. It can be object or array depending if we normalize / denormalize.

Fix docblock DataTransformerInterface::supportsTransformation

---

CHANGELOG.md
features/graphql/authorization.feature
features/graphql/collection.feature
features/graphql/introspection.feature
features/graphql/query.feature
features/graphql/schema.feature
src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/GraphQl/Resolver/Factory/ItemResolverFactory.php
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/SchemaBuilder.php
src/GraphQl/Type/TypeBuilder.php
src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php
tests/Fixtures/FileConfigurations/single_resource.yml
tests/Fixtures/TestBundle/Document/DummyGroup.php
tests/Fixtures/TestBundle/Document/DummyProperty.php
tests/Fixtures/TestBundle/Document/LegacySecuredDummy.php
tests/Fixtures/TestBundle/Document/SecuredDummy.php
tests/Fixtures/TestBundle/Entity/DummyGroup.php
tests/Fixtures/TestBundle/Entity/DummyProperty.php
tests/Fixtures/TestBundle/Entity/LegacySecuredDummy.php
tests/Fixtures/TestBundle/Entity/SecuredDummy.php
tests/GraphQl/Type/FieldsBuilderTest.php
tests/GraphQl/Type/SchemaBuilderTest.php
tests/GraphQl/Type/TypeBuilderTest.php

| Fixed tickets | #2988 
| Doc PR        | api-platform/doc
This allows user to be able to use different security  and serialization groups for items and collections.
I didn't create pull request for docs because I wasn't sure you will accept this.

[GraphQL] making item_query and collection_query as top level operation

---

phpstan.neon.dist
src/Bridge/Doctrine/Orm/CollectionDataProvider.php
src/Bridge/Elasticsearch/DataProvider/ItemDataProvider.php
src/Bridge/Symfony/Bundle/Resources/config/test.xml
src/Bridge/Symfony/Bundle/Test/ApiTestCase.php
src/Bridge/Symfony/Bundle/Test/Client.php
src/Bridge/Symfony/Bundle/Test/Response.php
src/GraphQl/Resolver/Stage/DeserializeStage.php
src/HttpCache/EventListener/AddHeadersListener.php
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/BrowserKit/Client.php
tests/Fixtures/app/config/config_common.yml

Merge 2.4 into master

---

features/graphql/input_output.feature
features/graphql/mutation.feature
features/graphql/schema.feature
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/TypeBuilder.php
tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
tests/GraphQl/Resolver/Factory/ItemResolverFactoryTest.php
tests/GraphQl/Resolver/Stage/DeserializeStageTest.php
tests/GraphQl/Resolver/Stage/ReadStageTest.php
tests/GraphQl/Resolver/Stage/SecurityPostDenormalizeStageTest.php
tests/GraphQl/Resolver/Stage/SecurityStageTest.php
tests/GraphQl/Resolver/Stage/SerializeStageTest.php
tests/GraphQl/Resolver/Stage/ValidateStageTest.php
tests/GraphQl/Resolver/Stage/WriteStageTest.php
tests/GraphQl/Serializer/SerializerContextBuilderTest.php
tests/GraphQl/Type/FieldsBuilderTest.php
tests/GraphQl/Type/TypeBuilderTest.php

Some missing code changes after https://github.com/api-platform/core/pull/3015.

[GraphQL] Fix some issue with the separation of query

---

src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

| Fixed tickets | #3047 
Make use of ` is_a()` instead of `is_subclass_of()` for DateTime objects, allowing to type-hint `DateTimeInterface` properties.

Fix DateTimeInterface type-hinting

---

composer.json
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Test/ApiTestCase.php

| Fixed tickets | related: #2982, #2994, #2999
Currently it results in:
```
Error: Class 'Symfony\Component\BrowserKit\AbstractBrowser' not found
```

Fix ApiTestCase::createClient when the BrowserKit component is not installed

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Fixed tickets | #3075 
Fix custom doctrine ODM extension loading

Fix autoregister ODM extensions

---

composer.json
phpstan.neon.dist
src/Bridge/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
src/Bridge/Symfony/Bundle/Test/Constraint/MatchesJsonSchema.php
src/Hydra/JsonSchema/SchemaFactory.php
src/JsonSchema/Command/JsonSchemaGenerateCommand.php
src/JsonSchema/Schema.php
src/JsonSchema/SchemaFactory.php
src/JsonSchema/SchemaFactoryInterface.php
src/JsonSchema/TypeFactory.php
src/Swagger/Serializer/DocumentationNormalizer.php
tests/Bridge/Symfony/Bundle/Test/ApiTestCaseTest.php
tests/Fixtures/TestBundle/DataProvider/SerializableItemDataProvider.php
tests/Hydra/JsonSchema/SchemaFactoryTest.php
tests/JsonSchema/TypeFactoryTest.php

Add assertions for testing response against JSON Schema from API resource

---

features/main/operation.feature
src/Action/NotFoundAction.php
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/JsonSchema/SchemaFactory.php
src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Document/DisableItemOperation.php
tests/Fixtures/TestBundle/Entity/DisableItemOperation.php
tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
tests/Metadata/Resource/Factory/OperationResourceMetadataFactoryTest.php

Add the ability to declare empty item operations

---

CHANGELOG.md
features/bootstrap/DoctrineContext.php
features/graphql/collection.feature
features/graphql/filters.feature
features/graphql/mutation.feature
features/graphql/query.feature
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/GraphQl/Resolver/Stage/ReadStage.php
src/GraphQl/Serializer/SerializerContextBuilder.php
src/GraphQl/Type/FieldsBuilder.php
src/Serializer/Filter/PropertyFilter.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/app/config/config_common.yml
tests/GraphQl/Resolver/Stage/ReadStageTest.php
tests/GraphQl/Serializer/SerializerContextBuilderTest.php
tests/GraphQl/Type/FieldsBuilderTest.php

| Bug fix?      | ?
That will also make filtering possible with #2751 
I could add unit tests if you feel it is needed and the idea/implementation is OK

Add support for name converter in GraphQL

---

features/main/patch.feature
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/EventListener/RespondListener.php
src/Serializer/SerializerContextBuilder.php
tests/Fixtures/TestBundle/Document/PatchDummy.php
tests/Fixtures/TestBundle/Entity/PatchDummy.php

| Doc PR        | https://github.com/api-platform/docs/pull/878
* Add support for the [`Accept-Patch`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Patch) HTTP header
* Add functional tests for the `PATCH` method
* Fix a bug in JSON Merge Patch support when this format is enabled at the operation level instead of globally

Add support for the Accept-Patch header

---

src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
src/Bridge/Symfony/Bundle/Test/Client.php
src/JsonSchema/SchemaFactory.php
src/Serializer/AbstractItemNormalizer.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

When using `normalizationContext={"groups"="foo"}` (shortcut string notation), docs doesn't take into account the normalization group. This PR fixes this issue and ensure that groups are casted as arrays everywhere.

Ensure that serialization groups are always an array

---

CHANGELOG.md
features/bootstrap/DoctrineContext.php
features/graphql/collection.feature
features/graphql/input_output.feature
features/graphql/introspection.feature
features/graphql/mutation.feature
features/graphql/query.feature
features/graphql/schema.feature
src/GraphQl/Type/TypeBuilder.php
tests/Fixtures/TestBundle/Document/DummyDifferentGraphQlSerializationGroup.php
tests/Fixtures/TestBundle/Entity/DummyDifferentGraphQlSerializationGroup.php
tests/GraphQl/Type/TypeBuilderTest.php

| Fixed tickets | #3059
Adding condition based on serialization groups for GraphQL item_query and collection_query types.
check the issue ticket for more info.
@lukasluecke Sorry it took that long. I hope you didn't spend time on this.

[GraphQL] Adding serialization group difference condition for item_query and collection_query types

---

features/bootstrap/JsonApiContext.php
features/hydra/entrypoint.feature
src/Hydra/Serializer/EntrypointNormalizer.php
tests/Hydra/Serializer/EntrypointNormalizerTest.php

| Fixed tickets | #3091
As described in https://github.com/api-platform/core/issues/3091, the main entrypoint returns resources names without any coherent sorting, as it can change depending of your `get_declared_classes()` returned values order.
Caution : this can be a BC break as tests can fail for existing projects.

Add entrypoints sorting

---

features/push_relations/push.feature
src/EventListener/SerializeListener.php

Fix missing "as" attribute for pushed resources 

---

features/json/relation.feature
features/main/relation.feature
src/Bridge/Symfony/Bundle/Resources/config/metadata/xml.xml
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/Document/RelatedDummy.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php

| Fixed tickets | #3133
Targeting `2.4` so that we're able to demonstrate that it works correctly on `2.4`.
Background:
Before #3036, the `$options` we pass to the PropertyNameCollectionFactory was wrong, because it was using the (Serializer) `$context` directly. Specifically, the `$context['groups']` were not translated to `$options['serializer_groups']`, so they had no effect. (There could have been many bugs caused by that.)
That bug fix however in turn revealed the problem with incorrect property metadata set on API resources in some projects (see for example #3133).
For example, the `id` …

Add test for updating embedded relation using plain identifier

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php

We are constantly using custom Swagger definitions and found the issue that `DocumentationNormalizer` appends `body` parameter regardless of whether we already defined it or not.
This produces validation error when we validate resulting OpenAPI schema json:
```
Semantic error at paths./api/xxx/{id}.put.parameters
Multiple body parameters are not allowed.
```

Do not append `body` parameter if it already exists

---

src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php

Related to https://github.com/symfony/symfony/pull/33775/
We can already apply this change without BC
It was the only command in this case

non-int value in the execute command will be deprecated

---

src/Bridge/RamseyUuid/Identifier/Normalizer/UuidNormalizer.php
src/EventListener/ReadListener.php
tests/Bridge/RamseyUuid/Normalizer/UuidNormalizerTest.php

| Tests pass?   | yes 
| Fixed tickets | #3045 
| Doc PR        | not applicable
As discussed in issue #3045, the given error message was misleading.
I also updated the thrown exception according to the Exception
mentioned in the same issue. Of course I updated the related PHPUnit
test too.

Update thrown exception and clarify error message for UuidNormalizer.

---

src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/GraphQl/Resolver/Stage/SecurityPostDenormalizeStage.php
src/GraphQl/Resolver/Stage/SecurityStage.php
tests/GraphQl/Resolver/Stage/SecurityPostDenormalizeStageTest.php
tests/GraphQl/Resolver/Stage/SecurityStageTest.php

| Fixed tickets | https://github.com/api-platform/api-platform/issues/1265

Fixed dependency issue when SecurityBundle is not installed

---

CHANGELOG.md
src/Bridge/Doctrine/MongoDbOdm/CollectionDataProvider.php
src/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtension.php
src/Bridge/Doctrine/MongoDbOdm/ItemDataProvider.php
src/Bridge/Doctrine/MongoDbOdm/SubresourceDataProvider.php
src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
tests/Bridge/Doctrine/MongoDbOdm/CollectionDataProviderTest.php
tests/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtensionTest.php
tests/Bridge/Doctrine/MongoDbOdm/ItemDataProviderTest.php
tests/Bridge/Doctrine/MongoDbOdm/SubresourceDataProviderTest.php
tests/Fixtures/TestBundle/Document/Dummy.php

| Doc PR        | https://github.com/api-platform/docs/pull/918
Allow to use execute options (corresponding to the [aggregate command fields](https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields) in MongoDB) like `allowDiskUse`.
To do so, modify the resource configuration like this:
```php
/**
* @ApiResource(attributes={
*     "doctrine_mongodb"={
*       "execute_options"={
*         "allowDiskUse"=true
*       }
*     }
* })
* @ODM\Document
*/
```

[MongoDB] Possibility to add execute options

---

src/Bridge/Symfony/Messenger/ContextStamp.php
src/Bridge/Symfony/Messenger/DataPersister.php
tests/Bridge/Symfony/Messenger/ContextStampTest.php
tests/Bridge/Symfony/Messenger/DataPersisterTest.php

Context stamp

---

src/Operation/DashPathSegmentNameGenerator.php
tests/Operation/DashedPathSegmentNameGeneratorTest.php

| Tickets       | fix #3188
This will correctly convert `orderingPerson` to `ordering-people`

[2.5] Fix dashed path segment generation

---

src/Api/FilterInterface.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPassTest.php
tests/Fixtures/TestBundle/Filter/DoesNotImplementInterfaceFilter.php
tests/Fixtures/TestBundle/Filter/NoConstructorFilter.php
tests/Fixtures/TestBundle/Filter/NoPropertiesArgumentFilter.php

| Bug fix?      | yes/
| Fixed tickets |  #3049 

Fix support for custom filters without constructor in ApiFilter annotation

---

.circleci/config.yml
.github/workflows/ci.yml
.travis.yml
behat.yml.dist
features/graphql/mutation.feature

Move the Behat tests to the CI workflow on GitHub Actions, so that we can move away from Travis CI completely.
TODO:

Move behat tests to CI workflow on GitHub Actions

---

composer.json

False positives are reported on the path of the file

Fix phpstan false positives

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

DI: Improve swagger versions parameter (fix #3115)

---

src/Annotation/ApiResource.php

| Tickets       | ~fixes~ https://github.com/api-platform/docs/issues/868 
I started work on https://github.com/api-platform/docs/issues/868 because it was marked as `good first issue` :)
First, I added links to documentation for API Resource properties and sort properties alphabetically.
But there are some points I don't understand from this issue.
What should we do with `@see https://github.com/Haehnchen/idea-php-annotation-plugin/issues/112` in the class ApiResource?
I found this [PR](https://github.com/api-platform/core/pull/1788#pullrequestreview-107255243) but still can't understand.

Add links to documentation to ApiResource properties

---

src/Exception/ExceptionInterface.php

| Tickets       | N/a
| Doc PR        | N/a
This makes it more clear this interface can be 'caught'

Make the base exception extend throwable

---

features/jsonapi/filtering.feature
src/JsonApi/EventListener/TransformFilteringParametersListener.php

| New feature?  |no 
| Deprecations? |no
| Tickets       | fixes #3189 
This PR fixes issue #3189, when using the jsonapi protocol pagination was overwritten when applying additional filters.

fix #3189 - JSONAPI pagination ignored when using filter parameter

---

phpunit.xml.dist

| Tickets       | N/a
| Doc PR        | N/a
This will allow IDEs to provide hints/ autocompletion

Link to local XSD

---

features/doctrine/date_filter.feature
features/doctrine/exists_filter.feature
features/hal/max_depth.feature
features/jsonapi/errors.feature
features/jsonapi/related-resouces-inclusion.feature
features/main/validation.feature
features/serializer/group_filter.feature
features/serializer/property_filter.feature

Fixes a flawed test in Behat test suite

Improve tests

---

CHANGELOG.md

Add changelog for v2.5.1

---

src/Annotation/ApiResource.php

`$paginationPartial` in `src/Annotation/ApiResource.php` is declared as a boolean in the attributes annotation, but is declared as an int in the class.

Fix ApiResource annotation : 'int' should be 'bool'

---

composer.json
phpstan.neon.dist
src/Action/ExceptionAction.php
src/Hydra/Serializer/ErrorNormalizer.php
src/JsonApi/Serializer/ErrorNormalizer.php
src/Problem/Serializer/ErrorNormalizer.php
src/Problem/Serializer/ErrorNormalizerTrait.php
tests/Fixtures/app/AppKernel.php

The symfony/error-render component has been reverted, its api has been partially added to the error-handler one.
This fixes the outdated compatibility layers and add some missing ones.

Fix symfony/error-handler compatibility

---

src/Hydra/EventListener/AddLinkHeaderListener.php
src/Mercure/EventListener/AddLinkHeaderListener.php
src/Util/CorsTrait.php
tests/Hydra/EventListener/AddLinkHeaderListenerTest.php
tests/Mercure/EventListener/AddLinkHeaderListenerTest.php

| Tickets       | fixes #3262
Preflight requests cannot be accessed in JS, therefore settings the `Link` headers for Hydra and Mercure is useless for these requests Not setting them prevent the issues with invalid URLs being generated. This an alternative fix to #3262.

Prevent adding Link headers for CORS preflight requets

---

.circleci/config.yml
.github/workflows/ci.yml
.travis.yml

The `./configure` and `make` were taking quite a long time.
Thanks @bendavies for your exploration in #3253

Cache ext-mongodb build directory

---

phpstan.neon.dist
src/JsonApi/Serializer/ItemNormalizer.php
src/Serializer/AbstractItemNormalizer.php

Stricter type checking in `normalizeRelation` to improve code quality. Also cleaned up some ~dead~ wrong(?) code (related to #2073 and #2074).

Ensure correct return type from AbstractItemNormalizer::normalizeRelation

---

phpstan.neon.dist
src/Bridge/Symfony/Validator/EventListener/ValidationExceptionListener.php
src/EventListener/ExceptionListener.php
tests/Bridge/Symfony/Validator/EventListener/ValidationExceptionListenerTest.php
tests/EventListener/ExceptionListenerTest.php

fix compat with Symfony 5

---

CHANGELOG.md
features/graphql/collection.feature
src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/DataProvider/Pagination.php
src/GraphQl/Resolver/Stage/SerializeStage.php
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/TypeBuilder.php
src/GraphQl/Type/TypeBuilderInterface.php
tests/Fixtures/TestBundle/Document/FooDummy.php
tests/Fixtures/TestBundle/Entity/FooDummy.php
tests/GraphQl/Type/FieldsBuilderTest.php
tests/GraphQl/Type/TypeBuilderTest.php

| Tickets       | fixes #2762, https://github.com/api-platform/api-platform/issues/1152
This PR allows to use a page-based pagination using GraphQL instead of the default cursor-based pagination. This choice is made at operation/resource level.

Add page-based pagination to GraphQL

---

src/Hydra/Serializer/CollectionNormalizer.php
tests/Hydra/Serializer/CollectionNormalizerTest.php

Allows to generate IRIs instead of embedding documents for Hydra collections.
TODO:

Improve Vulcain support

---

src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/EventListener/ExceptionListener.php
tests/EventListener/ExceptionListenerTest.php

| Tickets       | https://github.com/symfony/symfony/issues/34509
If is not enough to check for the existence of `Symfony\Component\HttpKernel\EventListener\ErrorListener` to know if we can use it or not on symfony 4.4.
It may have been [removed from the container](https://github.com/symfony/symfony/blob/bfae515d521a421b413cb39e8fae727ffb4ca28b/src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/ExceptionListenerPass.php#L37).
The new ErrorListener is functionally different to the deprecated one, as the new one [flattens exceptions with the KernelEvents::CONTROLLER_ARGUMENTS …

Fix symfony 4.4 compat

---

.circleci/config.yml
.github/workflows/ci.yml
.travis.yml
composer.json

This avoids dependency conflicts and prevents phpstan from holding back the versions of Symfony packages.
#SymfonyHackday

Switch to phpstan-shim

---

src/Annotation/ApiProperty.php
src/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php
src/Bridge/Symfony/Bundle/Resources/config/metadata/metadata.xml
src/JsonSchema/SchemaFactory.php
src/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php
src/Metadata/Property/Factory/DefaultPropertyMetadataFactory.php
src/Metadata/Property/PropertyMetadata.php
tests/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactoryTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Entity/DummyPropertyWithDefaultValue.php
tests/Metadata/Property/Factory/DefaultPropertyMetadataFactoryTest.php
tests/Metadata/Property/PropertyMetadataTest.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php

| Fixed tickets | #2363
Add default and example information to swagger context if php properties
have default values so the exemple documentation section use these values.
With a class
```
<?php
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Serializer\Annotation\Groups;
/**
* @ORM\Entity
*     normalizationContext={"groups": {"person:read"}}
* )
* @ApiResource
*/
class Person
{
/**
* @var UuidInterface
*
* @ApiProperty(identifier=true)
* …
```

Use default value of PHP properties to Swagger doc

---

src/Bridge/Doctrine/Orm/Filter/SearchFilter.php

| Tickets       | - 
Replaces #3292

Get class metadata only when it's needed

---

src/Api/ResourceClassResolver.php

See #3316, perf improvment on `ResourceClassResolver::getResourceClass()` by providing a local cache for the computed value.

#3316: local cache on ResourceClassResolver::getResourceClass()

---

tests/Security/ResourceAccessCheckerTest.php

Funny bug!
In the `TokenInterface` (https://github.com/symfony/symfony/blob/v4.4.2/src/Symfony/Component/Security/Core/Authentication/Token/TokenInterface.php), there is a method only defined in the doc block annotation:
```php
* @method string[] getRoleNames()
```
https://github.com/symfony/symfony/blob/5973dacbd9587d9bf1234dfcb546c3cbdfbc4c9e/src/Symfony/Component/Security/Core/Authentication/Token/TokenInterface.php#L24
Because of the new release of https://github.com/phpDocumentor/ReflectionDocBlock, and particularly this PR: https://github.com/phpDocumentor/ReflectionDocBlock/pull/188, this …

Fix ResourceAccessCheckerTest

---

src/GraphQl/Type/TypeBuilder.php
tests/GraphQl/Type/TypeBuilderTest.php

| Tickets       | fixes #https://github.com/api-platform/api-platform/issues/1043 #https://github.com/api-platform/api-platform/issues/836
It seems some people were having issues when not using Doctrine and when a resource had a collection property.
In this case, the `DoctrineExtractor` (https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php) is not used and the `PhpDocExtractor` (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php) is used instead.
The best way to detect if a type is a collection is to see …

[GraphQL] Better detection of collection types

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

Following the documentation for Oauth in OAS3 (https://swagger.io/docs/specification/authentication/oauth2/), flows now need to be an array.
This fix turn this
in this
I kept the current behaviour for swagger v2.

[OpenApi] [Oauth] Fix render oauth when using OpenApi v3

---

CHANGELOG.md
src/GraphQl/Resolver/Stage/SerializeStage.php
tests/GraphQl/Resolver/Stage/SerializeStageTest.php

| Tickets       | fixes #3355 
Relates to #3355. Please see it for description.

Throw exception if cursor value is set, but empty.

---

src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
tests/Bridge/Symfony/Bundle/Command/SwaggerCommandUnitTest.php

This ensures that the generated OpenAPI schema JSON dump does not contain forward-slashes, such as `"#\/foo\/bar\/MyModel"`, which confuses tooling relying on direct string match in referenced models (most notably, the IntelliJ OpenAPI/Swagger tooling)

Ensure that `api:openapi:export` produces JSON with unescaped forward slashes

---

src/JsonSchema/TypeFactory.php
tests/JsonSchema/TypeFactoryTest.php

Reverts api-platform/core#3362
It was an invalid fix.

Revert "fix getClassType with no readableLink"

---

src/JsonSchema/TypeFactory.php
tests/JsonSchema/TypeFactoryTest.php

Add the DateInterval class as duration in json schemas

Add date interval to type factory

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/config/validator.xml
src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaFormat.php
src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaLengthRestriction.php
src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRegexRestriction.php
src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRestrictionMetadataInterface.php
src/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php
src/JsonSchema/SchemaFactory.php
src/Metadata/Property/PropertyMetadata.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
tests/Fixtures/DummyValidatedEntity.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

| Tickets       | fixes #3319 
| Doc PR        | api-platform/docs#1015
Generate specification property restrictions based on Symfony’s built-in validator.

Add specification property field's values restrictions based on validator setting

---

src/Bridge/Doctrine/Orm/SubresourceDataProvider.php

| Bug fix?      | yes (kinda) 
This PR try to change DQL queries generated to fetch subresource, to improve performance on large tables.
The generated SQL to query a subresource uses a `WHERE ... IN ( <subquery> )`, in order to be recursive when subresources also have subresources (introduced by #1608).
The subquery, on large table (at work 4M+ lines), takes a significant amount of time (2-5s), even with the proper SQL indexes (at least on MySQL).
```SQL
SELECT
DISTINCT c0_.idpurchase AS idpurchase_0,
c0_.idpurchase AS idpurchase_1
FROM purchase c0_
LEFT JOIN customer c1_ ON c0_.idcustomer = c1_.idcustomer
-- Some …
```

Improve subresources DB query performance by removing a subquery

---

tests/Fixtures/TestBundle/Entity/Dummy.php

This should fix the failing jobs (`-symfony-next`) with dev packages.

Rename a method in fixture class to avoid "getter" false positive

---

src/Hydra/JsonSchema/SchemaFactory.php

Enable decorating schema factory by it's interface.
The Hydra Json Schema Factory could not be decorated with a custom SchemaFactoryInterface.
The JsonSchemaFactory was used as a default. I've changed the type hint to the interface so everybody can now generate their own SchemaFactory implementations.

Don't typehint the SchemaFactory decorator by its implementation, but by its interface

---

CHANGELOG.md
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Validator/ValidationGroupsGeneratorInterface.php
src/Bridge/Symfony/Validator/Validator.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Validator/ValidatorTest.php
tests/Fixtures/TestBundle/Validator/DummyValidationGroupsGenerator.php

| Doc PR        | api-platform/docs#1023
When having many validation groups generators for resources, you need to make every generator as a public service, and this doesn't work with `_instanceof` configuration where you could add a custom marker and make those services public, because symfony doesn't detect that those services are used and removes from container.
This adds `ApiPlatform\Core\Validator\ValidationGroupsGeneratorInterface` so apps can leverage the autoconfiguration + autowiring of those generators. Generators are collected and registered in a custom service locator, but consumers won't need anymore any …

Allow to autoconfigure validation groups generators

---

src/JsonSchema/SchemaFactory.php
tests/JsonSchema/SchemaFactoryTest.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

| Tickets       | fixes #2868, fixes #3146, fixes #3424
I had an issue where nested properties / classes didn't show up on OpenApi / Swagger docs.
With this PR the issue seems to be solved as the PropertyMetadataFactory gets the options. Thanks to @teohhanhui for the help on this.
TODO:

Pass $options to PropertyInfoMetadataFactory

---

.circleci/config.yml

The result cache is a huge win.
CircleCI takes a very long time saving /tmp/phpstan/cache for some reason,
and this cache doesn't affect the run time much anyway.

Only save /tmp/phpstan/resultCache.php to cache

---

.github/workflows/ci.yml

Update codecov/codecov-action to use tokenless upload

---

src/Exception/ErrorCodeSerializableInterface.php
src/JsonApi/Serializer/ErrorNormalizer.php
src/Problem/Serializer/ErrorNormalizerTrait.php
tests/JsonApi/Serializer/ErrorNormalizerTest.php
tests/Mock/Exception/ErrorCodeSerializable.php

Hi,
I added the possibility to specify an error code for JsonApi Errors as specified in the JsonApi Spec.
https://jsonapi.org/format/#errors
In short when throwing an Exception like:
```
throw new MyError('my bad error', 1234);
```
the Normalizer now uses the Exception Code like so:
```
{
"title": "..",
"description": "...",
"code": 1234
}
```
It's a minor change so I'm not sure if master is the correct base branch.

Add error code for JsonApi errors.

---

.circleci/config.yml
.github/workflows/ci.yml
.php_cs.dist
appveyor.yml
composer.json

| Tickets       | fixes #3236, fixes https://github.com/api-platform/core/pull/3368#discussion_r372307596

Add a stub package for ext-mongodb

---

src/HttpCache/EventListener/AddHeadersListener.php
tests/HttpCache/EventListener/AddHeadersListenerTest.php

| Tickets       | fixes #3421  
Add support for stale-while-revalidate and stale-if-error cache-control extensions

add support for stale-while-revalidate and stale-if-error cache-control extensions

---

src/Bridge/Symfony/Bundle/Resources/config/swagger.xml

add default for the $defaultContext parameter so that swagger.versions parameter is properly sent to the swagger normalizer
rebases https://github.com/api-platform/core/pull/3433

add missing parameter for swagger normalizer

---

src/Bridge/Symfony/Bundle/Command/GraphQlExportCommand.php

The reason for this change is to allow decorating the `SchemaBuilder`.
Currently, `SchemaBuilder` cannot be decorated because in the constructor of `GraphQlExportCommand` the interface is not used.

Use SchemaBuilderInterface in GraphQlExportCommand

---

.github/workflows/ci.yml
src/Bridge/Doctrine/MongoDbOdm/Extension/OrderExtension.php
src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Fixtures/app/config/config_common.yml
tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php

Remove http_cache.invalidation deprecation and fix some remaining deprec

---

src/Api/ResourceClassResolver.php
src/Serializer/AbstractItemNormalizer.php
tests/Api/ResourceClassResolverTest.php

Do not treat classes implementing `\Traversable` as collection if defined as resource
| Tickets       | #3461
Classes implementing `\Traversable` were always interpreted as Collection by the `ResourceClassResolver `service, based on the fact they implemented the `\Traversable` interface.
Classes that implement this interface will now only be treated as a Collection if they are not explicitly defined as a Resource in the configuration.

…Do not treat classes implementing \Traversable as collection

---

src/Bridge/Symfony/Bundle/Test/Client.php

Add files to test client

---

features/jsonapi/pagination.feature
src/DataProvider/Pagination.php

| Tickets       | n/a 
I integrate a schemathesis tool for automatically testing api based on the openapi standard
When setting a large pag value, for example 9223372036854775807, a 500 error is caused
"Return value of ApiPlatform \\ Core \\ DataProvider \\ Pagination :: getOffset () must be of the type integer, float returned"
Added a check for the type of the return value in the getOffset method on Pagination class,
if the value is outside the scope of int64 (https://www.php.net/manual/en/language.types.integer.php) throw an error "Large page and limit values"

Fix error pagination

---

CHANGELOG.md
features/doctrine/range_filter.feature
src/Bridge/Doctrine/MongoDbOdm/Filter/RangeFilter.php
src/Bridge/Doctrine/Orm/Filter/RangeFilter.php
tests/Bridge/Doctrine/Common/Filter/RangeFilterTestTrait.php
tests/Bridge/Doctrine/MongoDbOdm/Filter/RangeFilterTest.php
tests/Bridge/Doctrine/Orm/Filter/RangeFilterTest.php

Improve the behavior of the RangeFilter filter in case the values of the between operator are equals
In such case, the DQL query is defined with the equals operation

Improve the RangeFilter DQL query in case the "between" values are equals

---

src/EventListener/RespondListener.php
tests/EventListener/RespondListenerTest.php

When a POST request issues a response with status code 200 setted by API Platform, the client receives 302 status code because of header Location added by RespondListener.
In this case, Safari follows the redirect and the client performs a GET operation on the URL in Location header.
According [PHP doc](https://www.php.net/manual/en/function.header) :
> The second special case is the "Location:" header. Not only does it send this header back to the browser, but it also returns a REDIRECT (302) status code to the browser unless the 201 or a 3xx status code has already been set.
PHP seems overwrite the original status code to 302 when it's not …

Prevent header Location on POST when status code is not 201 or 30x

---

src/Bridge/Symfony/Bundle/Test/Client.php

| Bug fix?      | yno
Added a new method on Client to access the cookie jar to test api endpoint that uses cookie as a mechanism for authentication.

feat: CookieJar on Client

---

src/GraphQl/Type/FieldsBuilder.php
tests/GraphQl/Type/FieldsBuilderTest.php

```yaml
resources:
App\Entity\Account:
graphql:
custom:
mutation: App\Mutation\Account\CustomMutation
description: Custom description
```
Before commit: `Customs a Account`
After commit: `Custom description`

[GraphQL] Mutations have description field

---

CHANGELOG.md
features/doctrine/search_filter.feature
features/graphql/query.feature
src/GraphQl/Serializer/SerializerContextBuilder.php
src/GraphQl/Type/FieldsBuilder.php
tests/Fixtures/TestBundle/Document/DummyCar.php
tests/Fixtures/TestBundle/Entity/DummyCar.php
tests/GraphQl/Serializer/SerializerContextBuilderTest.php
tests/GraphQl/Type/FieldsBuilderTest.php
tests/Util/AnnotationFilterExtractorTraitTest.php

Following https://github.com/api-platform/core/pull/3455.

[GraphQL] Support serialized name

---

CHANGELOG.md
features/graphql/collection.feature
src/GraphQl/Serializer/SerializerContextBuilder.php

| Tickets       | fixes https://github.com/api-platform/core/pull/3175#issuecomment-618393563

[GraphQL] Fix serializer context attributes for page-based pagination

---

src/GraphQl/Serializer/Exception/HttpExceptionNormalizer.php

use interface HttpExceptionInterface instead of HttpException

---

features/bootstrap/DoctrineContext.php
features/jsonld/interface_as_resource.feature
src/Hydra/Serializer/CollectionNormalizer.php
tests/Hal/Serializer/CollectionNormalizerTest.php
tests/Hydra/Serializer/CollectionNormalizerTest.php

Fix tests and PHPStan

---

CHANGELOG.md
features/bootstrap/GraphqlContext.php
features/graphql/query.feature
src/GraphQl/Action/EntrypointAction.php
tests/GraphQl/Action/EntrypointActionTest.php

| Tickets       | fixes #3566 
The operation name in Data is attempting to pull from operation instead of operationName. Because of this, applications leveraging the StandardServer cannot handle a request with multiple operations (it returns an error saying the operation name is required).
In this PR, I only updated the way the class parses the data on the parseData function.

change operation to OperationName in the parser

---

src/Bridge/RamseyUuid/Identifier/Normalizer/UuidNormalizer.php
tests/Bridge/RamseyUuid/Normalizer/UuidNormalizerTest.php

The supports method wasn't explicit enough and should not be called with something other then a string.

fix: Uuid identifier normalizer should support only strings
