api-platform/core

src/Bridge/Doctrine/Common/Filter/SearchFilterTrait.php

Based on static analysis this can never return null, so no need to check.

Remove unnecessary not null check

---

behat.yml.dist
features/bootstrap/DoctrineContext.php

Switch to UserPasswordEncoder instead of password_verify

---

tests/Action/ExceptionActionTest.php

Fix random failures like this one: https://travis-ci.org/api-platform/core/jobs/550375583

Fix flaky test

---

src/GraphQl/Serializer/ItemNormalizer.php
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/JsonLd/Serializer/ItemNormalizer.php

Remove unused variables

---

features/bootstrap/DoctrineContext.php
features/doctrine/search_filter.feature
phpstan.neon.dist
src/Bridge/Doctrine/MongoDbOdm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
tests/Fixtures/TestBundle/Document/ConvertedOwner.php
tests/Fixtures/TestBundle/Document/ConvertedRelated.php
tests/Fixtures/TestBundle/Entity/ConvertedOwner.php
tests/Fixtures/TestBundle/Entity/ConvertedRelated.php

| Fixed tickets | #2893
This will ensure that nested properties will pass through name converters by parts.

Fix nested filtering with name converters

---

src/Bridge/Elasticsearch/DataProvider/Paginator.php
tests/Bridge/Elasticsearch/DataProvider/PaginatorTest.php

Closes https://github.com/api-platform/core/pull/2836

Fix paginator for elasticsearch 7

---

features/json/input_output.feature
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Bridge/Symfony/Messenger/DataTransformer.php
src/EventListener/WriteListener.php
src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
src/Util/ResourceClassInfoTrait.php
tests/Fixtures/TestBundle/Document/User.php
tests/Fixtures/TestBundle/Dto/PasswordResetRequest.php
tests/Fixtures/TestBundle/Dto/PasswordResetRequestResult.php
tests/Fixtures/TestBundle/Entity/User.php
tests/Fixtures/TestBundle/MessageHandler/PasswordResetRequestHandler.php
tests/Fixtures/app/config/config_common.yml

| Fixed tickets | #2860, #2810, #2803
Replaces #2878

Fix WriteListener trying to generate IRI for non-resource

---

src/Bridge/Symfony/Bundle/Test/ApiTestCase.php
src/Bridge/Symfony/Bundle/Test/Client.php
tests/Bridge/Symfony/Bundle/Test/ClientTest.php

| Doc PR        | @dunglas TODO?
TODO:

Allow setting default options on the test Client

---

src/EventListener/ExceptionListener.php
tests/EventListener/ExceptionListenerTest.php

| Fixed tickets | https://github.com/api-platform/core/pull/2930#issuecomment-516052630

Unwrap nested HandlerFailedException

---

features/graphql/filters.feature
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/TypeConverter.php
src/GraphQl/Type/TypeConverterInterface.php
tests/Fixtures/TestBundle/Document/DummyCarColor.php
tests/Fixtures/TestBundle/Entity/DummyCarColor.php
tests/Fixtures/TestBundle/GraphQl/Type/TypeConverter.php
tests/GraphQl/Type/FieldsBuilderTest.php
tests/GraphQl/Type/TypeConverterTest.php

| Fixed tickets | #2969 
See issue for details.

Use correct resource configuration for filter args of nested collection

---

features/graphql/filters.feature
src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
src/Bridge/Symfony/Messenger/DataPersister.php
src/Bridge/Symfony/Messenger/DispatchTrait.php
src/EventListener/ExceptionListener.php
tests/EventListener/ExceptionListenerTest.php

Merge 2.4 into master

---

tests/Hydra/JsonSchema/SchemaFactoryTest.php

Add test for Hydra json schema factory

---

composer.json
src/GraphQl/Resolver/ItemResolver.php

| Fixed tickets | https://github.com/api-platform/core/pull/2990#issuecomment-522727014

Add missing call to Clone::clone

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Test/ApiTestCase.php

| Fixed tickets | #2982, #2994
Fix a regression introduced by #2994.

[Test] Throw a better error if HttpClient is not installed

---

src/Bridge/Doctrine/Orm/CollectionDataProvider.php
src/Bridge/Doctrine/Orm/ItemDataProvider.php

Use EntityManagerInterface to consist with ODM
| Fixed tickets | no

Check for EntityManagerInterface in Doctrine ORM data providers

---

src/EventListener/WriteListener.php
tests/EventListener/WriteListenerTest.php

Fix Context never passed to data persister remove in WriteListener

---

phpstan.neon.dist
src/Bridge/Elasticsearch/DataProvider/ItemDataProvider.php
src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
src/HttpCache/EventListener/AddHeadersListener.php
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/BrowserKit/Client.php
tests/Fixtures/app/config/config_common.yml

| Fixed tickets | see https://github.com/symfony/symfony/issues/33393

Fix the failing build

---

src/Bridge/Doctrine/Orm/CollectionDataProvider.php

Ref: #3005 https://github.com/api-platform/core/pull/3005/files#r319220582

[MINOR] PHPDoc Typo

---

CHANGELOG.md
features/graphql/authorization.feature
features/graphql/schema.feature
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/FieldsBuilderInterface.php
src/GraphQl/Type/SchemaBuilder.php
tests/GraphQl/Type/FieldsBuilderTest.php
tests/GraphQl/Type/SchemaBuilderTest.php

A bit of refactoring following https://github.com/api-platform/core/pull/3015.

[GraphQL] Introduce getItemQueryFields and getCollectionQueryFields

---

.circleci/config.yml
.editorconfig
.github/workflows/ci.yml
.travis.yml
composer.json
phpstan.neon.dist
src/EventListener/SerializeListener.php
src/Hal/Serializer/ItemNormalizer.php
src/JsonApi/Serializer/ItemNormalizer.php
src/Operation/Factory/SubresourceOperationFactory.php
src/Serializer/AbstractItemNormalizer.php
src/Serializer/CacheKeyTrait.php
src/Serializer/ItemNormalizer.php
src/Serializer/ResourceList.php
tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
tests/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php
tests/Fixtures/TestBundle/BrowserKit/Client.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php
tests/JsonApi/Serializer/ConstraintViolationNormalizerTest.php
tests/Metadata/Property/Factory/CachedPropertyMetadataFactoryTest.php
tests/Metadata/Property/Factory/CachedPropertyNameCollectionFactoryTest.php
tests/Metadata/Resource/Factory/CachedResourceMetadataFactoryTest.php
tests/Metadata/Resource/Factory/CachedResourceNameCollectionFactoryTest.php
tests/Operation/Factory/CachedSubresourceOperationFactoryTest.php
tests/Serializer/ResourceListTest.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

| Bug fix?      | ~no~ probably!

Add a CI workflow using GitHub Actions

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Fix inexistant parameter when graphql is disabled

---

CHANGELOG.md

see https://github.com/api-platform/core/pull/3039 rebased

Add old priority for services

---

src/Bridge/Symfony/Bundle/Resources/config/data_provider.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Add missing autowiring alias for Pagination

---

src/Annotation/ApiFilter.php
tests/Annotation/ApiFilterTest.php

see https://github.com/api-platform/core/pull/3020 )can't push on contributor's remote anymore?!)

Improve error message when filter class is not imported

---

phpstan.neon.dist
src/Bridge/Symfony/Bundle/Test/ApiTestCase.php
tests/Bridge/Symfony/Bundle/Test/ApiTestCaseTest.php

| Doc PR        | wip
Usage:
```php
$this->request('PUT', $this->findIriBy(Book::class, ['isbn' => '9790456981541']), $data);
```

[ApiTestCase] Add a helper method to find the IRI of a resource

---

src/JsonSchema/SchemaFactory.php

[JSON Schema] Fix command

---

composer.json

| Doc PR        | https://github.com/api-platform/docs/pull/905

[MongoDB] MongoDB ODM 2.0 released! 🎉

---

src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js
src/Bridge/Symfony/Bundle/Resources/public/swagger-ui/oauth2-redirect.html
src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
update-js.sh

Q | A
-- | --
Bug fix? | yes
New feature? | no
BC breaks? | no
Deprecations? | no
Tests pass? | -
Fixed tickets | #3131
License | MIT
Doc PR
This is a follow up to  #3019 .

[Swagger-UI] add missing oauth2-redirect configuration

---

features/json/relation.feature
features/main/relation.feature
src/Bridge/Symfony/Bundle/Resources/config/metadata/xml.xml
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/Document/RelatedDummy.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php

Merge 2.4 onto 2.5

---

src/Bridge/Elasticsearch/DataProvider/Filter/AbstractSearchFilter.php

Allow multiple elasticsearch queries to be set

---

README.md

The link to the Problem Details spec was way outdated. It's long been an RFC.

Update Problem Details link to point to RFC

---

.travis.yml

This will improve performance of MySQL in travis CI.

Improve mysql performance on Travis

---

src/Bridge/Doctrine/Common/Util/IdentifierManagerTrait.php
tests/Bridge/Doctrine/Common/Util/IdentifierManagerTraitTest.php

Catch wrong identifier type

---

CHANGELOG.md
features/main/subresource.feature
src/Bridge/Symfony/Bundle/Test/ApiTestAssertionsTrait.php

Fix some typos.
Same as https://github.com/api-platform/core/pull/3208 but for the `2.5` branch.

Fix spelling

---

CONTRIBUTING.md

| Tickets       | N/a
| Doc PR        | N/a

Use https instead of http

---

src/Annotation/ApiResource.php

Add missing link to docs for the Elasticsearch attribute

---

.circleci/config.yml
.github/workflows/ci.yml
behat.yml.dist
composer.json
phpunit.xml.dist
phpunit_mongodb.xml

No need to run separate coverage jobs.
It increases the time for the jobs with coverage enabled on GitHub Actions, but I think it's fine? The whole CI workflow (21 jobs!) still completes in under 15 minutes.
TODO:

Enable code coverage in test jobs

---

src/JsonSchema/SchemaFactory.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php

see https://github.com/api-platform/core/pull/3228 by @MLDMoritz

More Descriptive Input/Output class names

---

composer.json

| Bug fix?      |  no 
| Tickets       | n/a 

Fix Behatch constraint

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

https://github.com/api-platform/core/pull/2749

Allow changing the location of Swagger UI

---

.circleci/config.yml
.github/workflows/ci.yml
.travis.yml

GitHub Actions recently added support for caching: https://github.com/actions/cache
This is a first step, caching composer dependencies.
Cannot be merged until https://github.com/actions/cache/issues/12 is resolved

GitHub Actions: cache composer dependencies

---

phpstan.neon.dist

Fix PHPStan ignored error pattern

---

phpstan.neon.dist

Remove a false positive that has been fixed

---

phpstan.neon.dist
src/Serializer/AbstractItemNormalizer.php
tests/JsonApi/Serializer/ItemNormalizerTest.php
tests/Serializer/AbstractItemNormalizerTest.php

Fix phpstan running on Symfony 5.0

---

phpstan.neon.dist
tests/Fixtures/TestBundle/DataProvider/DummyDtoNoInputCollectionDataProvider.php

Fix PHPStan issues after Doctrine Persistence release

---

.circleci/config.yml
.github/workflows/ci.yml
.travis.yml
appveyor.yml

Fix AppVeyor build broken since PHP 7.4 release

---

src/Bridge/Symfony/Bundle/Resources/config/json_schema.xml
src/Hydra/JsonSchema/SchemaFactory.php
src/JsonSchema/SchemaFactory.php
src/JsonSchema/SchemaFactoryInterface.php
src/JsonSchema/TypeFactory.php
src/JsonSchema/TypeFactoryInterface.php
tests/JsonSchema/SchemaFactoryTest.php

| Tickets       | fixes #1787, fixes #2818, replaces #3298
TODO:

Fix JSON Schema generation for non-resource class

---

src/DataProvider/Pagination.php

Allow to avoid some issue when https://github.com/api-platform/core/pull/3327 will be merged into 2.5 and 2.5 will be merged into master.

[GraphQL] Fix getGraphQlPaginationType when not a resource

---

src/JsonSchema/TypeFactory.php
tests/JsonSchema/TypeFactoryTest.php

| Tickets       | [issue 3361](https://github.com/api-platform/core/issues/3361)
Fix condition
Additionally:
- Always add tests and ensure they pass.
- Never break backward compatibility.
- Bug fixes should be based against the current stable version branch.
- Features and deprecations must be submitted against master branch.
- Legacy code removals go to the master branch.
- Update CHANGELOG.md file.
-->

fix getClassType with no readableLink

---

src/DataTransformer/DataTransformerInterface.php

fix(documentation): Fix DataTransformerInterface documentation

---

CONTRIBUTING.md

fix outdated pull request template link in contribution guide

---

CHANGELOG.md

Don't mention v2.5.5 in CHANGELOG as it does not exist yet

---

src/Validator/EventListener/ValidateListener.php
src/Validator/ValidatorInterface.php

Fix wrong exception class thrown by ValidatorInterface

---

.github/workflows/ci.yml
.travis.yml
behat.yml.dist
features/jsonld/non_resource.feature
phpunit.xml.dist
phpunit_mongodb.xml
tests/Fixtures/app/AppKernel.php

~Failures with Symfony 5.1 / `master` seem to be caused by a Symfony (`PropertyInfo`?) bug? (Bad detection of hasser method - a hasser method must never have any required arguments.)~ Fixed by #3410
Other Behat job failures caused by https://github.com/sebastianbergmann/phpcov/issues/94

Bump CI to check Symfony 5.1 compatibility

---

.github/workflows/ci.yml
.travis.yml
behat.yml.dist
features/jsonld/non_resource.feature
phpunit.xml.dist
phpunit_mongodb.xml
src/JsonSchema/TypeFactory.php
src/Validator/EventListener/ValidateListener.php
src/Validator/ValidatorInterface.php
tests/Fixtures/TestBundle/Entity/Dummy.php
tests/Fixtures/app/AppKernel.php
tests/JsonSchema/TypeFactoryTest.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

Merge 2.5 into master

---

.php_cs.dist
phpstan.neon.dist
src/Bridge/Doctrine/Common/PropertyHelperTrait.php
src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php
src/Bridge/Doctrine/Orm/PropertyHelperTrait.php

Fix cs, use static::class instead of get_class($this)

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php

Fix accessing a non existent key

---

composer.json

Stop suggestion FOSUser, it harms more than it helps

---

.github/workflows/ci.yml

Ignore FOSUser deprecations only

---

features/main/uuid.feature
src/Bridge/RamseyUuid/Serializer/UuidDenormalizer.php
src/Bridge/Symfony/Bundle/Resources/config/ramsey_uuid.xml
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

| Tickets       | fixes #3473 

Fix ramsey uuid denormalization #3473

---

CHANGELOG.md
src/GraphQl/Type/FieldsBuilder.php
tests/GraphQl/Type/FieldsBuilderTest.php

| Doc PR        | https://github.com/api-platform/docs/pull/1097
Following https://github.com/api-platform/core/pull/3477.
Add custom descriptions for queries too.

[GraphQL] Custom description for queries

---

src/Bridge/Doctrine/Orm/Filter/SearchFilter.php

Revert "Passing custom doctrine type to addWhereByStrategy"

---

CHANGELOG.md

Changelog 2.5.6

---

composer.json

feat: allow Doctrine Inflector 2.0

---

src/DataProvider/Pagination.php
tests/Fixtures/TestBundle/Document/FooDummy.php
tests/Fixtures/TestBundle/Entity/FooDummy.php
tests/GraphQl/Type/FieldsBuilderTest.php
tests/GraphQl/Type/TypeBuilderTest.php

| Tickets       | fixes #3613
All other attributes are in snake case.

Use snake case for pagination type

---

src/GraphQl/Error/ErrorHandler.php

Following https://github.com/api-platform/core/pull/3632.
The error handler should be final.

[GraphQL] Make the error handler final

---

.github/workflows/ci.yml
README.md
src/HttpCache/EventListener/AddHeadersListener.php
tests/HttpCache/EventListener/AddHeadersListenerTest.php

Bump mongodb in CI

---

features/openapi/docs.feature
src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
src/Bridge/Symfony/Bundle/Resources/config/swagger-ui.xml
src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
src/Bridge/Symfony/Bundle/SwaggerUi/SwaggerUiAction.php
src/Bridge/Symfony/Bundle/SwaggerUi/SwaggerUiContext.php
tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Bridge/Symfony/Bundle/SwaggerUi/SwaggerUiActionTest.php

fix: use new OpenApi with SwaggerUI

---

features/main/custom_identifier_with_subresource.feature
src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
tests/Fixtures/TestBundle/Entity/SlugChildDummy.php
tests/Fixtures/TestBundle/Entity/SlugParentDummy.php

commit b5fcf46f711bee9b56e164cde352e0db3859adc2
Author: soyuka <soyuka@users.noreply.github.com>
Date:   Wed Aug 12 16:02:51 2020 +0200
fix phpstan
commit 0cbc7e2847626d1f44b40b5e3cf628c32ba9e828
Author: Arnaud J <jabin@cikaba.com>
Date:   Sat Aug 8 16:35:09 2020 +0200
:white_check_mark: Test API subresources with custom identifiers
commit d7419500c756afe5e4d85617dc840b5c65fb12cb
Author: mahmood bazdar <mahmood.bazdar@gmail.com>
Date:   Mon Apr 27 15:29:01 2020 +0430
Fixing error for none database identifiers Api ids

Merge #3529 and #3671

---

src/Bridge/Doctrine/MongoDbOdm/Filter/AbstractFilter.php
tests/Fixtures/TestBundle/Document/SlugChildDummy.php
tests/Fixtures/TestBundle/Document/SlugParentDummy.php

Following:
- https://github.com/api-platform/core/pull/3673
- https://github.com/api-platform/core/pull/3675

[MongoDB] Fix Behat tests

---

src/JsonApi/EventListener/TransformPaginationParametersListener.php

Just added a missing use statement (see line 31/32)

Fix missing use statement

---

src/Swagger/Serializer/DocumentationNormalizer.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
tests/Swagger/Serializer/DocumentationNormalizerV3Test.php

| Tickets       | fixes https://github.com/api-platform/core/issues/3551

[Swagger] Fix that subresource endpoints do not override custom endpoints

---

CHANGELOG.md

Add changelog for 2.5.7

---

.github/workflows/ci.yml

Ci windows split behat and phpunit and increase timeout

Ci windows split behat and phpunit and increase timeout

---

src/Bridge/Symfony/Bundle/Test/Client.php

| Tickets       | fixes #3299 
Backport PR #3486 from `master` to `2.5`

Backport pull request #3486

---

src/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php

fix: simplify PurgeHttpCacheListener

---

phpstan.neon.dist
tests/Bridge/Elasticsearch/DataProvider/PaginatorTest.php

ci: fix PHPStan

---

composer.json

| Tickets       | fixes nothing 
| Doc PR        | Ø
Just use a stable version of PHPUnit Bridge.

Use PHPUnit Bridge 5.1 instead of version 5.x-dev

---

src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
src/Bridge/Symfony/Bundle/Resources/config/swagger.xml

| License       |
Backport of #3798 for branch 2.5

Lazy load SwaggerCommand

---

.github/workflows/ci.yml

Add git everywhere

---

.github/workflows/ci.yml
behat.yml.dist
composer.json
tests/Behat/CoverageContext.php
tests/Fixtures/TestBundle/Document/Dummy.php
tests/Fixtures/TestBundle/Document/User.php
tests/Fixtures/app/config/config_postgres.yml

Use setup-php in github actions.

Use setup-php

---

features/openapi/docs.feature
src/Bridge/Symfony/Bundle/Resources/config/api.xml
src/JsonSchema/SchemaFactory.php
src/OpenApi/Factory/OpenApiFactory.php
tests/Behat/OpenApiContext.php
tests/OpenApi/Factory/OpenApiFactoryTest.php

TBD:
- add groups to definitions on v3
- fix schema type missing on v2?

Fix OpenApi /docs?spec_version=3 not using OpenApiFactory

---

features/jsonld/input_output.feature
src/Serializer/AbstractItemNormalizer.php

| Tickets       |  na
Change the message error when an Input can not be denormalized. 
@weaverryan @dunglas

Rewrite bad input denormalization error

---

composer.json

Fixes issues with github authentification limits.

Remove behatch/contexts repository

---

src/Bridge/Symfony/Bundle/Test/ApiTestAssertionsTrait.php

Disable additionalProperties in json schema assertions

---

src/Documentation/Action/DocumentationAction.php
tests/Documentation/Action/DocumentationActionTest.php

| Tickets       | fixes #3844 

Fix #3844 open api shows with jsonld normalizer

---

CHANGELOG.md

Changelog for v2.5.8

---

tests/Bridge/Elasticsearch/DataProvider/PaginatorTest.php

Fix phpstan error unmatched 

---

src/Annotation/ApiResource.php

| New feature?  | yes| BC breaks?    | no
| Tickets       | fixes n/a
Fix a bug preventing the attribute to work properly.

fix: ApiResource attribute

---

.github/workflows/ci.yml
.php_cs.dist
phpstan.neon.dist
src/Annotation/ApiFilter.php
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php
src/GraphQl/Type/TypeBuilder.php
src/JsonSchema/TypeFactory.php
src/Metadata/Resource/Factory/AnnotationResourceFilterMetadataFactory.php
src/Util/AnnotationFilterExtractorTrait.php
tests/Annotation/ApiFilterTest.php
tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPassTest.php
tests/Fixtures/TestBundle/Entity/DummyPhp8.php
tests/Fixtures/TestBundle/Util/AnnotationFilterExtractor.php
tests/Metadata/Resource/Factory/AnnotationResourceFilterMetadataFactoryTest.php

| New feature?  | yes/no 
| Tickets       | fixes n/a

feat: add ApiFilter attribute

---

src/Annotation/ApiSubresource.php
src/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php

feat: add ApiSubresource attribute

---

src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php

fix: support for defaults

---

src/Api/IdentifiersExtractor.php
tests/Api/IdentifiersExtractorTest.php
tests/Fixtures/TestBundle/Entity/DummyForAdditionalFieldsInput.php
tests/Fixtures/TestBundle/Model/ResourceBarInterface.php

Throw an error when no identifier is defined

---

CHANGELOG.md

docs: editorial changes to the changelog for 2.5.8

---

src/JsonSchema/SchemaFactory.php
tests/JsonSchema/SchemaFactoryTest.php

Fix for empty example and empty default value

---

.github/workflows/ci.yml
CHANGELOG.md

docs: changelog for 2.5.9

---

src/OpenApi/Factory/OpenApiFactory.php
src/OpenApi/Model/SecurityScheme.php
tests/Bridge/Symfony/Bundle/Command/OpenApiCommandTest.php
tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
tests/OpenApi/Factory/OpenApiFactoryTest.php

| Tickets       | fixes #3920
| Doc PR        |  na.

OpenAPI: fix #3920 security scheme

---

src/OpenApi/Factory/OpenApiFactory.php
tests/OpenApi/Factory/OpenApiFactoryTest.php

| BC breaks?    | maybe
| Tickets       | fixes #3914
fix wrong custom filter schema generation

fix wrong custom filter schema generation and edit test to check.

---

composer.json
src/Serializer/AbstractConstraintViolationListNormalizer.php

Upgrade and fix PHPStan issues

---

src/OpenApi/Factory/OpenApiFactory.php
tests/OpenApi/Factory/OpenApiFactoryTest.php

fix: add prefix to subresources and operations

---

src/JsonSchema/SchemaFactory.php
tests/Swagger/Serializer/DocumentationNormalizerV2Test.php

| Tickets       | fixes #3945  

Fix:  #3945

---

features/openapi/docs.feature
src/OpenApi/Factory/OpenApiFactory.php

| Tickets       | fixes #3892 

[OpenApi] Fix: add filters for subresources path

---

src/Bridge/Symfony/Identifier/Normalizer/UuidNormalizer.php
src/Serializer/AbstractConstraintViolationListNormalizer.php

ci: fix tests

---

phpstan.neon.dist
tests/Behat/JsonContext.php

A bug was fixed upstream we can remove these false positives!

Remove phpstan false-positive

---

src/Bridge/Symfony/Bundle/Test/ApiTestAssertionsTrait.php

| Tickets       | fixes  #3881
ping @pmontoya 
Also related to #4006

Fix #3881 revert setting ALLOW_EXTRA_ATTRIBUTES

---

src/Bridge/Symfony/Bundle/DataCollector/RequestDataCollector.php
tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php

| Tickets       | fixes #3976 

Fix data collection recursive issue #3976

---

.github/workflows/ci.yml

Attempt to fix windows ci for an unknown reason it installs php-fig/link:2.0 with php 7.4

Windows CI use php 8

---

src/OpenApi/Model/Parameter.php

Reverts api-platform/core#4033

Revert "Fix getStyle, getName, getIn return type to be consistent with construct."

---

CHANGELOG.md

docs: changelog for 2.6.3

---

.github/workflows/ci.yml
tests/Bridge/Symfony/Bundle/SwaggerUi/SwaggerUiActionTest.php
tests/Fixtures/app/AppKernel.php

Fix deprecations and set direct deprec to 0 for symfony 5.3

Fix deprecations

---

src/OpenApi/OpenApi.php

Hello, i just add the return type for method `getPaths`
cherry-pick from https://github.com/api-platform/core/pull/4094

Fix getPaths return type

---

src/Bridge/Symfony/Bundle/Resources/config/data_provider.xml
src/DataProvider/PaginationOptions.php

I added this object with the OpenApi refactoring. let's add every pagination options in it.

Add every pagination options in PaginationOptions

---

CHANGELOG.md

docs: update changelog for 2.6.3

---

CHANGELOG.md
src/OpenApi/Factory/OpenApiFactory.php
tests/OpenApi/Factory/OpenApiFactoryTest.php

| Tickets       | Fix #4080 #4106

OpenAPI fixes

---

CHANGELOG.md
features/graphql/collection.feature
src/GraphQl/Resolver/Stage/SerializeStage.php
tests/GraphQl/Resolver/Stage/SerializeStageTest.php

| Tickets       | fixes #3215 

[GraphQL] Partial Pagination Support

---

tests/Fixtures/TestBundle/Entity/DummyCar.php

Fix doctrine cascade definition

---

src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php
src/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php

Fix parameter name changes when implementing PropertyMetadataFactoryInterface

---

src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRegexRestriction.php
tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php

| Tickets       | Fix https://github.com/api-platform/core/pull/4176#discussion_r609893023

Safer PropertySchemaRegexRestriction pattern anchor

---

CHANGELOG.md
src/OpenApi/Factory/OpenApiFactory.php
tests/OpenApi/Factory/OpenApiFactoryTest.php

Fix undefined index for custom openapi_context response without content

---

src/OpenApi/Factory/OpenApiFactory.php

chore(open-api-factory): unused variable removal

---

features/swagger/docs.feature

| Bug fix?      | no (fix test suite)
Apparently forgotten in #4070

Fix undefined steps in Swagger Behat tests

---

phpunit.xml.dist

Phpunit schema changed and I'm seeing that warning too much

chore(phpunit): migrate phpunit.xml schema

---

.github/workflows/ci.yml
composer.json
tests/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtensionTest.php
tests/Bridge/Doctrine/MongoDbOdm/ItemDataProviderTest.php
tests/Bridge/Doctrine/MongoDbOdm/SubresourceDataProviderTest.php

Fixes a conflict with php8 on Match.

test(mongodb): use MatchStage instead of Match (conflicts with php8)

---

.php-cs-fixer.dist.php

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md.

chore: change configuration file for php-cs-fixer 3

---

src/Bridge/Symfony/Validator/EventListener/ValidationExceptionListener.php
tests/Bridge/Symfony/Validator/EventListener/ValidationExceptionListenerTest.php

Without this patch, the exception is not catched, and it processed by
the Symfony ErrorListener and a log message is processed. This is kind
of useless.
With this patch, the exeption is not logged anymore and is processed is
any other validation exception.

fix: do not log ValidationException

---

src/Util/Inflector.php
tests/Fixtures/app/AppKernel.php

| Tickets       | #4249
... and add corresponding `@phpstan-ignore` comments

fix: revert regression in Doctrine Inflector deprecation handling

---

.github/workflows/ci.yml

Remove duplicate option for phpstan analysis

---

src/Bridge/Symfony/Bundle/Test/Client.php
tests/Bridge/Symfony/Bundle/Test/ApiTestCaseTest.php

Update ApiTestCase to be more consistent with WebTestCase

---

src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
tests/Bridge/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php

| Tickets       | Fix #4164 
| Doc PR        | api-platform/docs/pull/1360 
Adds the `iri` (iriConverter) and `escape` (rawurlencode) functions to mercure allowing generate `topics` dynamically and satisfying the need to restrict the access of subscribers, according to the example described in the Mercure specification (https://mercure.rocks/spec#subscribers).
Example
```php
<?php
// api/src/Entity/Book.php
use App\Entity\User;
#[
ApiResource(
mercure: 'object.getMercureOptions()',
)
]
class Book
{
private ?User $owner;
public function getMercureOptions(): array
{
$topic1 …
```

feat: Add iri and urlencode to expression language on Mercure

---

src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRegexRestriction.php
tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRegexRestrictionTest.php

| Tickets       | #4022
Cf https://github.com/symfony/symfony/blob/v4.4.25/src/Symfony/Component/Validator/Constraints/Regex.php#L90-L94

feat(openapi): handle Regex match=false

---

src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php

Call ```addFunction``` only if has ```Expression Language```.
https://github.com/api-platform/core/pull/4153#discussion_r658715964

fix: Optional expression language on Mercure

---

.github/workflows/ci.yml
composer.json
src/Core/Bridge/Elasticsearch/DataProvider/CollectionDataProvider.php
src/Core/Bridge/Symfony/Identifier/Normalizer/UuidNormalizer.php
tests/Core/Behat/ElasticsearchContext.php
tests/Core/Bridge/Elasticsearch/DataProvider/CollectionDataProviderTest.php
tests/Core/Bridge/Elasticsearch/DataProvider/ItemDataProviderTest.php
tests/Core/Bridge/Elasticsearch/DataProvider/SubresourceDataProviderTest.php
tests/Core/Bridge/Elasticsearch/Metadata/Document/Factory/CatDocumentMetadataFactoryTest.php
tests/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Core/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
tests/Fixtures/Elasticsearch/Mappings/tweet.json
tests/Fixtures/Elasticsearch/Mappings/user.json

Updates elasticsearch from  6.18 to 7.14
deprecates IdentifierExtractorInterface

feat: elastic search update

---

src/State/LegacyDataPersisterProcessor.php
src/State/LegacyDataProviderState.php

fix: cleanup state bridge with the legacy system

---

.github/workflows/ci.yml
phpstan.neon.dist
src/Core/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php
src/Core/Bridge/Doctrine/MongoDbOdm/ItemDataProvider.php
src/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Core/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm_mercure_publisher.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/doctrine_orm_mercure_publisher.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/http_cache_tags.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/metadata/annotation.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/openapi.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/swagger-ui.xml
src/Core/Bridge/Symfony/Routing/ApiLoader.php
src/Core/Bridge/Symfony/Routing/RouteNameResolver.php
src/Core/JsonApi/Serializer/ObjectNormalizer.php
src/Core/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php
src/Metadata/Resource/Factory/LegacyResourceMetadataResourceMetadataCollectionFactory.php
tests/Bridge/Symfony/Routing/ApiLoaderTest.php
tests/Core/Bridge/Symfony/Bundle/Command/OpenApiCommandTest.php
tests/Core/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
tests/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Core/Bridge/Symfony/Bundle/Test/ApiTestCaseTest.php
tests/Core/Bridge/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php
tests/Core/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config_common.yml

This adds a test suite with the `metadata_backward_compatibility_layer: true` configuration.

test: legacy metadata backward compatibility

---

src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php
tests/Fixtures/TestBundle/Entity/DummyPhp8ApiPropertyAttribute.php
tests/Metadata/Property/Factory/AttributePropertyMetadataFactoryTest.php

fix: restore property attributes merging

---

src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php

Replace https://github.com/api-platform/core/pull/4419 (more generic).

fix(metadata): support merging all properties of ApiPropert

---

src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php

fix(metadata): ApiResource: add some return types and fix PHPdoc

---

src/Metadata/ApiProperty.php
src/Metadata/ApiResource.php

feat(medata): ApiProperty: fix types and improve docs

---

src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php
tests/Metadata/Property/Factory/AttributePropertyMetadataFactoryTest.php

Fixes a mistake I introduced in https://github.com/api-platform/core/pull/4420.

fix(metadata): property metadata merging

---

docs/adr/0001-resource-identifiers.md
docs/adr/0002-resource-definition.md
docs/adr/0003-uri-variables.md

Update the ADR document with ApiResource instead of Resource as its a PHP reserved word.

doc(adr): Resource => ApiResource

---

.github/workflows/ci.yml
features/main/operation_resource.feature
src/Core/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Symfony/EventListener/WriteListener.php
tests/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Core/EventListener/WriteListenerTest.php
tests/Fixtures/TestBundle/Entity/OperationResource.php
tests/Fixtures/TestBundle/State/OperationResourceProcessor.php
tests/Fixtures/app/config/config_common.yml
tests/Symfony/WriteListenerTest.php

Feat(doctrine): create new writeListener which only use processor

---

docs/adr/0000-subresources-definition.md
docs/adr/0001-resource-identifiers.md
docs/adr/0002-resource-definition.md
docs/adr/0003-uri-variables.md

Improve docs:
- Fix broken links
- Format HTML code
- Fix typos

chore(docs): improve docs

---

src/Core/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Core/EventListener/WriteListener.php
src/Symfony/EventListener/WriteListener.php
tests/Core/EventListener/WriteListenerTest.php
tests/Symfony/WriteListenerTest.php

fix(doctrine): improve writelistener

---

src/Core/Bridge/Symfony/Bundle/Command/GraphQlExportCommand.php
src/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Core/Bridge/Symfony/Bundle/Resources/config/graphql.xml
src/Core/EventListener/WriteListener.php
src/Core/GraphQl/Type/FieldsBuilder.php
src/Core/GraphQl/Type/FieldsBuilderInterface.php
src/Core/GraphQl/Type/SchemaBuilder.php
src/Core/GraphQl/Type/SchemaBuilderInterface.php
src/Core/GraphQl/Type/TypeBuilder.php
src/Core/GraphQl/Type/TypeBuilderInterface.php
src/Core/GraphQl/Type/TypeConverter.php
src/Core/GraphQl/Type/TypeConverterInterface.php
src/Core/Hal/Serializer/EntrypointNormalizer.php
src/Core/Util/AttributesExtractor.php
src/GraphQl/Action/EntrypointAction.php
src/deprecation.php
tests/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Core/EventListener/WriteListenerTest.php
tests/Fixtures/TestBundle/GraphQl/Type/TypeConverterLegacy.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config_common.yml
tests/Fixtures/app/config/config_metadata_backward_compatibility_layer.yml

feat(graphql): follow the metadata backward compatibility layer flag

---

src/Core/Bridge/Symfony/Bundle/Resources/config/api.xml
src/Symfony/Routing/IriConverter.php
tests/Symfony/Routing/IriConverterTest.php

fix: decorate legacy iri converter

---

src/Metadata/ApiResource.php
src/Metadata/GraphQl/Operation.php
src/Metadata/Resource/Factory/LegacyResourceMetadataResourceMetadataCollectionFactory.php
src/Metadata/WithResourceTrait.php
tests/Metadata/Resource/OperationTest.php

Follow up of https://github.com/api-platform/core/pull/4429
Related to https://github.com/api-platform/core/pull/4449

fix(metadata): call is/can/get methods within copyFrom

---

.github/workflows/ci.yml
features/main/crud.feature
src/Bridge/Doctrine/Odm/State/CollectionProvider.php
src/Bridge/Doctrine/Odm/State/ItemProvider.php
src/Bridge/Doctrine/Orm/State/CollectionProvider.php
src/Bridge/Doctrine/Orm/State/ItemProvider.php
src/Core/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Core/Bridge/Symfony/Bundle/Resources/config/state.xml
src/State/LegacyDataProviderState.php
tests/Bridge/Doctrine/Odm/State/CollectionProviderTest.php
tests/Bridge/Doctrine/Odm/State/ItemProviderTest.php
tests/Bridge/Doctrine/Orm/State/CollectionProviderTest.php
tests/Bridge/Doctrine/Orm/State/ItemProviderTest.php
tests/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/Document/ProviderEntity.php
tests/Fixtures/TestBundle/Entity/ProcessorEntity.php
tests/Fixtures/TestBundle/Entity/ProviderEntity.php

Add item and collection providers

feat(doctrine): state providers

---

src/Metadata/GraphQl/Mutation.php
src/Metadata/GraphQl/Query.php
src/Metadata/GraphQl/QueryCollection.php
src/Metadata/GraphQl/Subscription.php

| Tickets       | https://github.com/api-platform/core/issues/4474

fix(graphql): add securityPostValidation args to metadata

---

CHANGELOG.md

docs: add changelog for version 2.6.6

---

src/Api/IdentifiersExtractor.php
tests/Api/IdentifiersExtractorTest.php
tests/Api/UriVariableTransformer/DateTimeUriVariableTransformerTest.php
tests/Core/Hal/Serializer/ObjectNormalizerTest.php
tests/Fixtures/TestBundle/Entity/OperationResource.php

Issue 4497

---

composer.json

fix: branch-alias for 2.6

---

composer.json
src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
src/HttpCache/EventListener/AddHeadersListener.php
tests/Bridge/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
tests/Bridge/Doctrine/EventListener/WriteListenerTest.php
tests/Bridge/Symfony/Validator/EventListener/ValidateListenerTest.php
tests/Bridge/Symfony/Validator/EventListener/ValidationExceptionListenerTest.php
tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaOneOfRestrictionTest.php
tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
tests/Bridge/Symfony/Validator/ValidatorTest.php
tests/EventListener/ExceptionListenerTest.php
tests/EventListener/RespondListenerTest.php
tests/EventListener/SerializeListenerTest.php
tests/EventListener/WriteListenerTest.php
tests/Fixtures/TestBundle/Doctrine/Generator/Uuid.php
tests/Fixtures/TestBundle/Entity/Dummy.php
tests/GraphQl/Resolver/Stage/SerializeStageTest.php
tests/HttpCache/EventListener/AddHeadersListenerTest.php
tests/HttpCache/EventListener/AddTagsListenerTest.php
tests/Hydra/EventListener/AddLinkHeaderListenerTest.php
tests/Hydra/Serializer/PartialCollectionViewNormalizerTest.php
tests/Mercure/EventListener/AddLinkHeaderListenerTest.php
tests/Validator/EventListener/ValidateListenerTest.php

chore: improve compatibility with Symfony 6

---

.github/workflows/ci.yml

ci: include PHP 8.1 in the test matrix

---

CHANGELOG.md

docs: changelog for 2.6.7

---

src/Metadata/Delete.php
src/Metadata/Get.php
src/Metadata/GetCollection.php
src/Metadata/Operation.php
src/Metadata/Patch.php
src/Metadata/Post.php
src/Metadata/Put.php
src/Symfony/EventListener/DenyAccessListener.php

We forgot to reintroduce the option inside the REST Operation.

fix(security): post validation in Operation #4392

---

tests/Fixtures/app/AppKernel.php

Fixes symfony-related deprecations (https://github.com/api-platform/core/runs/4627312860?check_suite_focus=true)

fix(test): Deprecations on Symfony 5.4

---

src/Serializer/AbstractItemNormalizer.php

fix: serializing embedded non resource objects

---

CONTRIBUTING.md

docs: fix link to PHP CS Fixer

---

CHANGELOG.md

docs: changelog for version 2.6.8

---

.gitattributes

fix: remove the docs/ directory from the archives

---

src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Add ProcessorInterface auto configuration.

fix: processor auto configuration

---

src/Symfony/Bundle/DataCollector/RequestDataCollector.php
src/Symfony/Bundle/Provider/TraceableChainProvider.php
src/Symfony/Bundle/Resources/config/v3/data_collector.xml
src/Symfony/Bundle/Resources/config/v3/debug.xml
src/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
tests/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php

By @emmanuel-tilleuls 
Adds Providers and Processors to the API Platform debug panel.

feat(symfony): debug profiler state provider and processor

---

src/Symfony/Bundle/Processor/TraceableChainProcessor.php
tests/Fixtures/TestBundle/State/DummyDtoNoOutputProcessor.php
tests/Fixtures/TestBundle/State/OperationResourceProcessor.php

Forgot to remove it from the fixtures.

fix: remove resumable method

---

src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
src/Symfony/Bundle/Resources/config/v3/doctrine_odm.xml
tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

https://github.com/api-platform/core/issues/4613#issuecomment-1094166400

fix(metadata): wrong service loaded w/ backward compatibility

---

src/Core/Bridge/Elasticsearch/DataProvider/CollectionDataProvider.php

https://github.com/api-platform/core/issues/4613#issuecomment-1103492256

fix(provider): legacy pagination injection

---

src/Elasticsearch/Serializer/ItemNormalizer.php

fixes https://github.com/api-platform/core/issues/4613#issuecomment-1103752254

fix(elasticsearch): add back missing const

---

src/Symfony/Bundle/Resources/config/legacy/metadata.xml
src/Symfony/Bundle/Resources/config/legacy/metadata_annotation.xml

fixes https://github.com/api-platform/core/issues/4613#issuecomment-1112189704

fix(symfony): optional doctrine/annotation for subresource metadata

---

src/Symfony/Bundle/Resources/config/v3/swagger_ui.xml

https://github.com/api-platform/core/issues/4613#issuecomment-1119376464

fix(swagger-ui): openapi dependency injection

---

src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
src/Core/Upgrade/UpgradeApiSubresourceVisitor.php

Fixes https://github.com/api-platform/core/issues/4613#issuecomment-1117097430

fix: upgrade subresource with resource

---

src/Metadata/Extractor/XmlResourceExtractor.php
src/Metadata/Extractor/YamlResourceExtractor.php
tests/Metadata/Extractor/XmlExtractorTest.php
tests/Metadata/Extractor/YamlExtractorTest.php

Fix https://github.com/api-platform/core/issues/4613#issuecomment-1125753638

fix(metadata): Add missing processor and provider to extractor

---

features/graphql/mutation.feature
features/graphql/query.feature
src/Core/GraphQl/Type/TypeBuilder.php
src/GraphQl/Type/TypeBuilder.php
tests/Fixtures/TestBundle/DataTransformer/DummyCustomMutationDtoDataTransformer.php
tests/Fixtures/TestBundle/DataTransformer/DummyCustomQueryDtoDataTransformer.php
tests/Fixtures/TestBundle/Document/DummyCustomMutation.php
tests/Fixtures/TestBundle/Document/DummyCustomQuery.php
tests/Fixtures/TestBundle/Entity/DummyCustomMutation.php
tests/Fixtures/TestBundle/Entity/DummyCustomQuery.php
tests/Fixtures/app/config/config_common.yml
tests/GraphQl/Type/TypeBuilderTest.php

Cherry-pick of https://github.com/api-platform/core/pull/4766 for 2.7

fix(graphql): output creates its own type in TypeBuilder

---

src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php

Fixes https://github.com/api-platform/core/issues/4613#issuecomment-1144574642

fix(doctrine): Fix binding for ORM AbstractFilter

---

src/Metadata/Resource/ResourceMetadataCollection.php

This can be reduced to one coalescing operator call

Reduce coalescing operator call

---

src/Metadata/Property/Factory/DefaultPropertyMetadataFactory.php

Fix resource typo

---

features/jsonld/iri_only.feature
src/Symfony/Bundle/Resources/config/routing/jsonld.xml

Fix api_jsonld_context route declaration

---

phpstan.neon.dist
src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
src/Core/Upgrade/UpgradeApiPropertyVisitor.php
src/Core/Upgrade/UpgradeApiResourceVisitor.php
tests/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommandTest.php
tests/Fixtures/TestBundle/Entity/RelatedDummy.php

Migrate ApiProperty to new format

---

src/Symfony/Bundle/Resources/config/openapi.xml

Remove duplicate OpenApiFactoryInterface service

---

src/Documentation/Action/DocumentationAction.php
src/Symfony/Bundle/Resources/config/api.xml
tests/Documentation/Action/DocumentationActionTest.php

OpenApiFactoryInterface can be null but not sure of this is the right fix.

Fix nullable OpenApiFactoryInterface

---

tests/Symfony/Routing/IriConverterTest.php

Remove unused var iriConverter

---

tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

I think this was forgotten when removing the backwards compatibility layer

Cleanup backward compatibility configuration

---

src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
src/Symfony/Bundle/Resources/config/doctrine_orm.xml
tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Related to:
- https://github.com/api-platform/core/issues/4815
- https://github.com/api-platform/docs/issues/1568
- https://github.com/api-platform/docs/pull/1583

fix(doctrine): use conventional service names

---

src/Symfony/Bundle/DependencyInjection/Configuration.php

This class is not used anymore

Remove FOSUserBundle use statement

---

src/Symfony/Bundle/Resources/config/metadata/property.xml

Remove duplicate service api_platform.metadata.property.metadata_factory

---

phpstan.neon.dist
tests/Fixtures/TestBundle/BrowserKit/Client.php

Cleanup phpstan

---

src/Symfony/EventListener/DenyAccessListener.php

I think this was forgotten in https://github.com/api-platform/core/commit/5b63577e3322f7ecb3a35535d361c40ab3499c3f#diff-e6fad1d6c367b8ad49904d85e11a6f196e170b8a785ff93d9e36a7ad96a8700eL114

Cleanup backward compatibility DenyAccessListener

---

phpunit.xml.dist

chore: cleanup phpunit

---

src/Symfony/Bundle/Resources/config/http_cache_purger.xml
tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

chore: cleanup varnish_client service

---

src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php

According to the latest changes in Symfony recommendations for the bundles' directory structure ([here](https://symfony.com/doc/current/bundles/best_practices.html#directory-structure)) in this PR I add a few additional paths to mapping for bundles. TBH I have no idea how I should write tests for it but if you have any hints, I'll do it :slightly_smiling_face:

feat: adjust mapping paths to the SF best practices for Bundles

---

src/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

Related to https://github.com/api-platform/core/pull/4853#issuecomment-1199182748.

feat: add default for mapping.paths

---

src/JsonSchema/SchemaFactory.php
src/Symfony/EventListener/AddFormatListener.php
src/Symfony/EventListener/ValidateListener.php
src/Symfony/Routing/IriConverter.php
tests/Doctrine/Common/Filter/ExistsFilterTestTrait.php
tests/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
tests/Fixtures/TestBundle/GraphQl/Resolver/UploadMultipleMediaObjectResolver.php
tests/GraphQl/Resolver/Factory/ItemMutationResolverFactoryTest.php
tests/GraphQl/Resolver/Stage/ReadStageTest.php
tests/GraphQl/Resolver/Stage/SecurityPostDenormalizeStageTest.php
tests/GraphQl/Resolver/Stage/SerializeStageTest.php
tests/GraphQl/Resolver/Stage/WriteStageTest.php
tests/Symfony/Bundle/Test/ApiTestCaseTest.php
tests/Symfony/Routing/ApiLoaderTest.php
tests/Symfony/Routing/IriConverterTest.php

chore: remove unused vars

---

src/Metadata/Resource/Factory/LinkFactory.php
tests/Metadata/Resource/Factory/LinkFactoryTest.php

Do not auto-set id as identifier if it is set as identifier=false

---

src/Doctrine/Orm/Extension/QueryResultCollectionExtensionInterface.php
src/Doctrine/Orm/Extension/QueryResultItemExtensionInterface.php
src/State/Pagination/PaginatorInterface.php
src/State/Pagination/PartialPaginatorInterface.php
src/State/ProviderInterface.php

DX: Provider generics phpdoc

---

src/Api/FilterInterface.php

I'm not sure about the expected text here, but the current text looks wrong.

Fix typo “… is … is”

---

.commitlintrc
.github/workflows/ci.yml

Scopes:
```
"symfony",
"doctrine",
"metadata",
"elasticsearch",
"mongodb",
"jsonld",
"hydra",
"jsonapi",
"graphql",
"openapi",
"serializer",
"jsonschema",
"validation",
"cs"
```

chore: add commitlint

---

src/Symfony/EventListener/ReadListener.php

chore: minor perf improvement in ReadListener

---

src/Metadata/Resource/Factory/NotExposedOperationResourceMetadataCollectionFactory.php

fix(metadata): add not exposed when no get

---

src/Symfony/EventListener/ReadListener.php

Chore/merge 2.7

---

CHANGELOG.md

docs: minor changelog fixes

---

composer.json
src/Hydra/EventListener/AddLinkHeaderListener.php
src/Symfony/EventListener/AddLinkHeaderListener.php
src/Symfony/EventListener/SerializeListener.php
tests/Hydra/EventListener/AddLinkHeaderListenerTest.php
tests/Symfony/EventListener/AddLinkHeaderListenerTest.php

To tidy up deps a bit since this is not needed.

Drop dependency on fig/link-util

---

src/Symfony/Bundle/Resources/config/elasticsearch.xml

fix(symfony): missing Elasticsearch DocumentMetadataFactoryInterface alias definition

---

src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php

fix(symfony): upgrade command requires diff

---

src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Fixes: #4980 and https://github.com/api-platform/core/issues/4965

fix(symfony): resource class directories bc break

---

src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Symfony/Bundle/Resources/config/state.xml

Reverts api-platform/core#4986 I did a mistake squashing another commit

Revert "fix(symfony): metadata cache is broken in dev/prod"

---

composer.json

chore: update branch-alias

---

src/State/CreateProvider.php
src/State/ObjectProvider.php
src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Symfony/Bundle/Resources/config/state.xml

fix(doctrine): ignore api_platform.state.item_provider when Doctrine is not enabled

---

tests/Metadata/Extractor/YamlExtractorTest.php

| Tickets       | #
Fix tests/Metadata/Extractor/YamlExtractorTest.php with php-cs-fixer 
Branch: 
- 2.7 for

fix: upate yaml extractor test file coding standard

---

src/Core/Upgrade/UpgradeApiResourceVisitor.php

origin: https://github.com/api-platform/core/pull/5105

fix(metadata): upgrade script keep operation name

---

.github/stale.yml

A stale bot added to remove automatically issues without activity.

chore: adding of stale bot

---

src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
src/Symfony/Bundle/DataCollector/DataCollected.php
src/Symfony/Bundle/DataCollector/RequestDataCollector.php
src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Symfony/Bundle/Resources/config/graphql.xml
src/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
src/Symfony/GraphQl/Resolver/Factory/DataCollectorResolverFactory.php
tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
tests/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Symfony/GraphQl/Resolver/Factory/DataCollectorResolverFactoryTest.php

| Branch?       | main  
| Tickets       | https://github.com/api-platform/core/issues/4833
This PR enables the usage of the profiler with GraphQL requests. Maybe some GraphQL specific information are still missing but those can be added later.

feature(graphql): enabled api-platform profiler panel when using graphql

---

src/Metadata/Operations.php
src/Metadata/Resource/ResourceMetadataCollection.php
tests/Metadata/Resource/ResourceMetadataCollectionTest.php

fix(metadata): getOperation cache matches arguments

---

src/Metadata/Resource/Factory/PhpDocResourceMetadataCollectionFactory.php

fix: not initialized params in PhpDocResourceMetadataCollectionFactory

---

src/Metadata/Resource/Factory/ExtractorResourceMetadataCollectionFactory.php
src/Symfony/Bundle/Resources/config/metadata/resource.xml
tests/Metadata/Extractor/ResourceMetadataCompatibilityTest.php

fix(graphql): dont add graphql operations when disabled

---

src/Documentation/Action/DocumentationAction.php
src/Test/DoctrineMongoDbOdmSetup.php
src/Test/DoctrineMongoDbOdmTestCase.php

Make PHPStan green again

---

src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php
tests/Fixtures/TestBundle/MessageHandler/PasswordResetRequestHandler.php
tests/Fixtures/TestBundle/MessengerHandler/Document/MessengerWithInputHandler.php
tests/Fixtures/TestBundle/MessengerHandler/Entity/MessengerWithInputHandler.php
tests/Fixtures/TestBundle/MessengerHandler/MessengerWithResponseHandler.php
tests/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestrictionTest.php

Get rid of some more deprecations in the 3.x branch

chore(deprecations): Fix some more deprecations

---

src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php

fix(metadata): fix extra properties method

---

src/Doctrine/EventListener/PublishMercureUpdatesListener.php
src/Doctrine/EventListener/PurgeHttpCacheListener.php

use getObjectManager instead of deprecated getEntityManager

chore(doctrine): use getObjectManager

---

src/Elasticsearch/State/ItemProvider.php
tests/Elasticsearch/State/ItemProviderTest.php

| Tickets       | https://github.com/api-platform/core/pull/5297#discussion_r1060135544
Elasticsearch client’s first implementation for ignoring exceptions [came with v0.4](https://github.com/elastic/elasticsearch-php/commit/4cfa5e1833ee3d7e79c7ff1ba8395ce3cfa80485) and [ended with v2](https://github.com/elastic/elasticsearch-php/commit/f56d55cc707c24d93e502d82a90c47890b798a5a). This was eight years ago so I didn’t add support for it.
[The implementation from v2](https://github.com/elastic/elasticsearch-php/blob/2.0/docs/per-request-configuration.asciidoc#ignoring-exceptions) lasted until v8. As we are currently conflicting with `"elasticsearch/elasticsearch": ">=8.0"` I only used …

refactor(elasticsearch): ignore Missing404Exception instead of catching it

---

features/graphql/query.feature
src/GraphQl/Type/FieldsBuilder.php
tests/Behat/DoctrineContext.php
tests/Fixtures/TestBundle/Entity/TreeDummy.php

| Tickets       | #5310
Reproducer for the bug reported in #5310

fix(graphql): use depth for nested resource class operation

---

src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php

| Tickets       | #5340 
Use return instead of yield to fix the issue

fix: fix argument resolver error

---

features/sub_resources/multiple_relation.feature
src/Api/IdentifiersExtractor.php
tests/Api/IdentifiersExtractorTest.php
tests/Behat/DoctrineContext.php
tests/Fixtures/TestBundle/Entity/RelationMultiple.php
tests/Fixtures/TestBundle/State/RelationMultipleProvider.php
tests/Fixtures/app/config/config_common.yml

fix: identifier value ignore to property field

---

src/Core/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php

fix(metadata): reader should be nullable

---

features/jsonld/inheritance.feature
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/ApiResource/Issue5438/Contractor.php
tests/Fixtures/TestBundle/ApiResource/Issue5438/Employee.php
tests/Fixtures/TestBundle/ApiResource/Issue5438/Person.php

fix(serializer): find parent class operation

---

src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php

fixes https://github.com/api-platform/core/issues/5446

fix(metadata): no deprecation when elasticsearch is null

---

src/Symfony/Bundle/Resources/config/metadata/property.xml

| Branch?       | 3.1 
| Tickets       | #5285  

Add cache identifier metadata factory

---

.github/workflows/ci.yml

Add GitHub Actions concurrency

---

src/Metadata/Resource/Factory/OperationDefaultsTrait.php
tests/Fixtures/TestBundle/ApiResource/AttributeConfigOperations.php
tests/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactoryTest.php

fix(metadata): add operations config

---

features/authorization/deny_authentication_before_filter.feature
src/Symfony/Bundle/Resources/config/symfony/validator.xml
tests/Fixtures/TestBundle/Entity/SecuredDummyWithFilter.php

| Tickets       | https://github.com/api-platform/core/issues/4389
Fix : query ParamValidateListner run after authentication.

fix: QueryParamerterValidateListener after authentication

---

src/Symfony/Bundle/Resources/config/elasticsearch.xml

fix(elasticsearch): Remove old bridge service

---

src/Symfony/Bundle/Resources/config/api.xml

fix(serialize): cache class metadata factory

---

src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php
tests/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactoryTest.php

Reverts api-platform/core#5499

Revert "fix(metadata): no deprecation when elasticsearch is null"

---

src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
src/Symfony/Bundle/Resources/config/doctrine_orm.xml
src/Symfony/Bundle/Resources/config/metadata/links.xml
src/Symfony/Bundle/Resources/config/metadata/property.xml
src/Symfony/Bundle/Resources/config/metadata/yaml.xml
tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

fix(metadata): remove identifier_metadata_factory services

---

features/jsonld/non_resource.feature
src/Serializer/AbstractItemNormalizer.php
tests/Behat/DoctrineContext.php
tests/Fixtures/TestBundle/ApiResource/EntityClassWithDateTime.php
tests/Fixtures/TestBundle/Entity/EntityClassWithDateTime.php

Simple bugfix : force_resource_class needs to be reset before trying to normalize children attributes.

 fix(serializer): no forced resource class relation 

---

src/Api/FilterInterface.php
src/Api/ResourceClassResolverInterface.php
src/Metadata/FilterInterface.php
src/Metadata/Operation/PathSegmentNameGeneratorInterface.php
src/Metadata/ResourceClassResolverInterface.php
src/Operation/PathSegmentNameGeneratorInterface.php

chore: move interfaces without breaking

---

src/Metadata/Resource/ResourceMetadataCollection.php

Fixes the code style failures currently affecting `main`: https://github.com/api-platform/core/actions/runs/4794808588/jobs/8528601685#step:4:17

chore: fix code style

---

features/jsonld/interface_dto_output.feature
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/ApiResource/EntityWithDtoOutput.php

related to https://github.com/api-platform/api-platform/issues/2409

fix: test that using dto interface as output works

---

CHANGELOG.md

| Tickets       | n/a| License       | MIT

Merge 2.7 in 3.1

---

.github/workflows/ci.yml

ci: tiny improvements

---

tests/Fixtures/app/AppKernel.php

The integration with NelmioApiDoc has been removed in API Platform 3.

test: remove dead code

---

src/Serializer/AbstractItemNormalizer.php

Problem found by @mrossard. Closes #5691.

fix: merge

---

composer.json

ci: allow ramsey/uuid-doctrine

---

.github/workflows/ci.yml

ci: always install ext-mongodb to prevent some deprecations

---

src/Elasticsearch/Serializer/DocumentNormalizer.php

fix: deprecations in Elasticsearch normalizer

---

.github/workflows/ci.yml
composer.json
phpunit.xml.dist
tests/.ignored-deprecations
tests/Fixtures/TestBundle/Entity/Person.php
tests/Fixtures/app/bootstrap.php

Also, allow running the test suite with the default install of XDebug.

ci: fix remaining deprecation notices

---

composer.json
tests/Fixtures/DummyCompoundValidatedEntity.php
tests/Fixtures/DummyCountValidatedEntity.php
tests/Fixtures/DummyIgnoreProperty.php
tests/Fixtures/DummyIriWithValidationEntity.php
tests/Fixtures/DummyNumericValidatedEntity.php
tests/Fixtures/DummyRangeValidatedEntity.php
tests/Fixtures/DummyUniqueValidatedEntity.php
tests/Fixtures/DummyValidatedChoiceEntity.php
tests/Fixtures/DummyValidatedHostnameEntity.php
tests/Fixtures/DummyValidatedUlidEntity.php
tests/Fixtures/NotAResource.php
tests/Fixtures/TestBundle/Controller/Common/CustomController.php
tests/Fixtures/TestBundle/Entity/NonCloneableDummy.php
tests/Fixtures/TestBundle/Validator/Constraint/DummyCompoundRequirements.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config_common.yml
tests/Fixtures/app/config/config_mongodb.yml

test: compatibility with Symfony 6.4

---

src/OpenApi/Model/Components.php
src/OpenApi/Model/Example.php
src/OpenApi/Model/Header.php
src/OpenApi/Model/Reference.php
src/OpenApi/Tests/Serializer/OpenApiNormalizerTest.php

fix(openapi): Example, Header and Reference models

---

features/hydra/error.feature
features/jsonld/context.feature
src/Serializer/AbstractItemNormalizer.php
src/Symfony/Bundle/Resources/config/jsonld.xml
tests/Serializer/ItemNormalizerTest.php

| Tickets       | Backport https://github.com/api-platform/core/pull/5495
Following green light: https://github.com/api-platform/core/pull/5495#issuecomment-1674430291
@soyuka please review ASAP, I need to my private project, it's blocking me to update from `2.6` to `2.7`.
Thanks a lot!

Backported fixed #5495 changes from 3.1 to 2.7

---

features/main/sub_resource.feature
src/State/CreateProvider.php
tests/Fixtures/TestBundle/Entity/SubresourceFactory.php
tests/Fixtures/TestBundle/Entity/SubresourceOrganization.php

fix(metadata): fix CreateProvider

---

src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php

Follows https://github.com/symfony/symfony/pull/51497

fix(serializer): no mapping cache in debug mode

---

composer.json

fix(symfony): missing translation contracts

---

src/State/Provider/ReadProvider.php

fix(state): read provider without request

---

features/openapi/docs.feature
src/Documentation/Action/DocumentationAction.php
src/OpenApi/Serializer/OpenApiNormalizer.php
src/OpenApi/Tests/Serializer/ApiGatewayNormalizerTest.php
src/Serializer/Tests/YamlEncoderTest.php
src/Serializer/YamlEncoder.php
src/Serializer/composer.json
src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Symfony/Bundle/DependencyInjection/Configuration.php
src/Symfony/Bundle/Resources/config/api.xml
src/Symfony/Bundle/Resources/config/legacy/events.xml
src/Symfony/Bundle/Resources/config/openapi.xml
src/Symfony/Bundle/Resources/config/swagger_ui.xml
src/Symfony/EventListener/AddFormatListener.php
tests/Fixtures/app/config/config_common.yml
tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

introduces documentation formats
notes this is continuing the work at #5632

feat: deprecate not setting formats manually

---

CHANGELOG.md

Cf. https://github.com/api-platform/core/pull/5815

chore: update changelog about Doctrine filters

---

docs/guides/create-a-custom-doctrine-filter.php
docs/guides/declare-a-resource.php
docs/guides/doctrine-entity-as-resource.php
docs/guides/extend-openapi-documentation.php
docs/guides/hook-a-persistence-layer-with-a-processor.php
docs/guides/provide-the-resource-state.php

docs: wrong comment inside guide

---

src/Hydra/Serializer/CollectionNormalizer.php
src/Serializer/AbstractCollectionNormalizer.php
src/Serializer/AbstractItemNormalizer.php
src/Serializer/OperationContextTrait.php
src/Serializer/SerializerContextBuilder.php
src/Symfony/Routing/IriConverter.php
tests/Symfony/Routing/IriConverterTest.php

Cherry-picked from https://github.com/api-platform/core/commit/e3e6a0d3213feeffa1365c3e52d7283eb7444d7d
- Did not include any changes related to operationMetadataFactory

refactor(serializer): child definition context creation

---

src/State/Processor/AddLinkHeaderProcessor.php
src/State/Tests/Processor/AddLinkHeaderProcessorTest.php

fix(state): add link header processor without links

---

src/Symfony/Bundle/SwaggerUi/SwaggerUiProvider.php
tests/Symfony/Bundle/SwaggerUi/SwaggerUiProviderTest.php

fix(symfony): swagger ui should use base url

---

src/Hydra/Serializer/ErrorNormalizer.php
src/JsonApi/Serializer/ErrorNormalizer.php
src/Problem/Serializer/ErrorNormalizer.php
tests/Symfony/Bundle/Test/ApiTestCaseTest.php

fix(symfony): 404 wrongly normalized

---

phpstan.neon.dist
src/Core/GraphQl/Resolver/ResourceFieldResolver.php
src/Symfony/Routing/IriConverter.php
tests/Fixtures/TestBundle/Entity/Dummy.php
tests/Fixtures/app/AppKernel.php

Follow up #https://github.com/api-platform/core/pull/5905

ci: fix 2.7 PHPSTAN

---

src/JsonSchema/SchemaFactory.php

fixes #5988 
for more information see the issue

Bugfix childentity openapi generation

---

src/Metadata/Extractor/XmlResourceExtractor.php
src/Metadata/Extractor/YamlResourceExtractor.php

Related to https://github.com/api-platform/core/pull/5872#discussion_r1350099960

feat(metadata): throw exception if itemUriTemplate if used on invalid operation (xml/yaml formats)

---

src/Serializer/AbstractItemNormalizer.php
tests/Serializer/AbstractItemNormalizerTest.php

https://github.com/api-platform/core/pull/6071

fix(serializer): integrate root_resource_class to cache key

---

codecov.yml

Updates Codecov configuration to ignore tests in components

ci: update ignore paths to ignore tests in new components

---

src/Elasticsearch/Filter/AbstractSearchFilter.php

Reverts api-platform/core#6147

Revert "Update AbstractSearchFilter to fix error after upgrading to 3.2"

---

tests/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestrictionTest.php

see https://github.com/symfony/symfony/commit/b341535558945105172df13a95ef55055377959b

test(symfony): empty collection without fields

---

features/doctrine/issue6175/standard_put_entity_inheritence.feature
src/Doctrine/Common/State/PersistProcessor.php
tests/Behat/DoctrineContext.php
tests/Fixtures/TestBundle/Entity/DummyMappedSubclass.php
tests/Fixtures/TestBundle/Entity/DummyMappedSuperclass.php

Recursively get reflectionProperties to allow modifications on parent properties
| Tickets       | Closes #6175 

fix(doctrine): PersistProcessor on PUT operation

---

src/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php
tests/Fixtures/DummyValidatedEntity.php
tests/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php

| Tickets       | Closes #6183

fix: Stop considering properties marked with NotBlank(allowNull=true) as required

---

src/Serializer/AbstractItemNormalizer.php
src/Serializer/Tests/AbstractItemNormalizerTest.php
src/Serializer/Tests/Fixtures/ApiResource/Dummy.php

fix(serializer): fix union types on collection denormalization

---

src/Doctrine/EventListener/PublishMercureUpdatesListener.php
tests/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
tests/Fixtures/TestBundle/Document/MercureWithTopicsAndGetOperation.php
tests/Fixtures/TestBundle/Entity/MercureWithTopicsAndGetOperation.php

Expression Language functions must be snake-case

fix(doctrine): fix case on Mercure ExpressionLanguage

---

src/Serializer/AbstractConstraintViolationListNormalizer.php
tests/Hydra/Serializer/ConstraintViolationNormalizerTest.php
tests/Problem/Serializer/ConstraintViolationNormalizerTest.php

fix(serializer): skip symfony validation exception

---

src/Api/Entrypoint.php
src/Api/QueryParameterValidator/Validator/Enum.php
src/Api/QueryParameterValidator/Validator/Length.php
src/Api/QueryParameterValidator/Validator/MultipleOf.php
src/Api/QueryParameterValidator/Validator/Pattern.php
src/Api/QueryParameterValidator/Validator/Required.php

Reverts api-platform/core#6227

Revert "fix: class_exists calls without argument"

---

src/Hydra/Serializer/CollectionFiltersNormalizer.php
src/OpenApi/Factory/OpenApiFactory.php
src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
src/Serializer/Parameter/SerializerFilterParameterProvider.php
src/State/ParameterProviderInterface.php
src/State/Provider/ParameterProvider.php
src/State/Tests/ParameterProviderTest.php
src/Symfony/Bundle/Resources/config/api.xml
src/Symfony/Bundle/Resources/config/metadata/resource.xml
src/Symfony/Bundle/Resources/config/state/provider.xml
tests/Fixtures/TestBundle/ApiResource/Headers.php
tests/Fixtures/TestBundle/ApiResource/WithParameter.php
tests/Fixtures/TestBundle/Parameter/CustomGroupParameterProvider.php
tests/Fixtures/app/config/config_common.yml
tests/Functional/Parameters/HydraTests.php
tests/Functional/Parameters/ParameterTests.php

Implement Parameter logic for serializer and openapi. 
Doctrine implementation is at: https://github.com/soyuka/core/pull/74

feat(serializer): attribute Parameter

---

src/Metadata/Extractor/XmlResourceExtractor.php
src/Metadata/Extractor/YamlResourceExtractor.php
src/Metadata/Tests/Extractor/ResourceMetadataCompatibilityTest.php
src/Metadata/Tests/Extractor/XmlExtractorTest.php
src/Metadata/Tests/Extractor/YamlExtractorTest.php

fix(elasticsearch): wrong namespace for stateOptions

---

src/Doctrine/Odm/Filter/AbstractFilter.php
src/Doctrine/Orm/Filter/AbstractFilter.php

fix(doctrine): wrong return type without name converter 

---

src/Hydra/Serializer/DocumentationNormalizer.php
src/Metadata/Resource/Factory/OperationDefaultsTrait.php
src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
src/State/ApiResource/Error.php
src/Symfony/Bundle/Resources/config/routing/api.xml
src/Symfony/Routing/IriConverter.php
src/Symfony/Validator/Exception/ValidationException.php

fix: multiple error routes #6214

---

src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php

| Tickets       | Closes #6271
**Note:** Simply using `$operations[] = $this->merge(...` causes tests to blow up. This seemed the most sensible option to start with.

fix(metadata): index operations

---

src/Symfony/Bundle/Resources/config/routing/api.xml
src/Symfony/Bundle/Resources/config/routing/errors.xml
src/Symfony/Routing/ApiLoader.php
tests/Symfony/Routing/ApiLoaderTest.php

fix(symfony): register api_error route

---

docs/guides/create-a-custom-doctrine-filter.php
src/Api/FilterInterface.php
src/ParameterValidator/Validator/ValidatorInterface.php
tests/Fixtures/DummyFilter.php
tests/Fixtures/TestBundle/Filter/NoConstructorFilter.php
tests/Fixtures/TestBundle/Filter/NoPropertiesArgumentFilter.php

chore: deprecate ApiPlatform\Api\FilterInterface

---

src/JsonApi/JsonSchema/SchemaFactory.php
tests/Fixtures/TestBundle/ApiResource/Animal.php
tests/Fixtures/TestBundle/ApiResource/AnimalObservation.php
tests/Fixtures/TestBundle/ApiResource/Species.php
tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php

| Tickets       | Related to #6320
Fixes a [derp-derp](https://github.com/api-platform/core/pull/6320/files#diff-3c1227349a8ff4f76d0085e642776cf04e4dc7675f7abe41ba42e31d59fdd30cL206) I made … plus more tests. :dog2::canned_food:

fix(jsonapi): re-add continue once relation is determined

---

.github/workflows/ci.yml
composer.json

ci: phpunit-bridge ^6.4.1

---

src/Doctrine/Orm/Filter/SearchFilter.php

fix(doctrine): test Doctrine Types:ARRAY existence before using it

---

docs/config/packages/framework.yaml
src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Symfony/Bundle/DependencyInjection/Configuration.php

fix(symfony): define use_symfony_listeners

---

src/State/Provider/ReadProvider.php
src/State/Tests/Provider/ReadProviderTest.php
tests/Fixtures/TestBundle/ApiResource/Headers.php

Fixes https://github.com/api-platform/core/issues/6341

fix(state): read without output

---

docs/guides/test-your-api.php

| Branch?       | 3.2 
https://api-platform.com/docs/guides/test-your-api/

Fix typo on "Test your API" guide page

---

src/Symfony/EventListener/WriteListener.php
tests/Symfony/EventListener/WriteListenerTest.php

fix(symfony): store original data without clone

---

src/Metadata/FilterInterface.php

Add phpdoc to FilterInterface

---

.commitlintrc
behat.yml.dist
features/main/patch.feature
tests/Fixtures/TestBundle/Controller/Issue6355/UpdateOrderProductCountController.php

see https://github.com/api-platform/core/pull/6357/files#r1596828409
Changes a behat assertion that printed the result insted of asserting it "works"

test: PATCH on controller w/ dto

---

phpstan.neon.dist
src/GraphQl/Serializer/SerializerContextBuilder.php
src/GraphQl/Type/FieldsBuilder.php
src/Serializer/AbstractConstraintViolationListNormalizer.php
src/Symfony/Validator/Serializer/ValidationExceptionNormalizer.php

see https://github.com/symfony/symfony/commit/d088047dfa7d417a25348aee961fc96ff00201d8

fix(graphql): name converter with class

---

.github/workflows/api_platform.yml

see also https://github.com/api-platform/api-platform/pull/2715

ci: on tag update distribution

---

docs/guides/subresource.php

Fix endpoint in subresource guide

---

src/Metadata/Parameter.php
src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php

fix(state): provider as ParameterProviderInterface

---

src/Symfony/Validator/State/ParameterValidatorProvider.php

List all violations which occurred during query parameters validation instead of breaking at the first invalid parameter

feat(state): list all violations during query parameters validation

---

src/OpenApi/Command/OpenApiCommand.php
src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Symfony/Bundle/Resources/config/openapi.xml
src/Symfony/Bundle/Resources/config/openapi/yaml.xml

see https://github.com/api-platform/core/pull/6439

fix(openapi): optional yaml component

---

src/Doctrine/Common/ParameterValueExtractorTrait.php
src/Doctrine/Odm/Extension/ParameterExtension.php
src/Doctrine/Orm/Extension/ParameterExtension.php
src/Metadata/Parameter.php
src/Metadata/Parameters.php
src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php
src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
src/Metadata/Tests/Resource/Factory/ParameterResourceMetadataCollectionFactoryTests.php
src/State/ParameterNotFound.php
src/State/Provider/ParameterProvider.php
src/State/Tests/ParameterProviderTest.php
src/State/Util/ParameterParserTrait.php
src/Symfony/Validator/State/ParameterValidatorProvider.php
tests/Fixtures/TestBundle/ApiResource/WithParameter.php
tests/Functional/Parameters/ParameterTest.php

basically a subset of #6450 that targets 3.3 improving the overall code managing parameters

fix(state): query and header parameter with the same name

---

src/JsonSchema/SchemaFactory.php

Reverts api-platform/core#6394

Revert "fix(jsonschema): make all required properties optional in PATCH operation with 'json' format"

---

features/openapi/docs.feature
src/Hydra/JsonSchema/SchemaFactory.php
tests/Hydra/JsonSchema/SchemaFactoryTest.php
tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php

Reverts api-platform/core#6366

Revert "feat(jsonschema): make JSON-LD specific properties required"

---

.github/workflows/ci.yml

This line actually runs Behat.

ci: fix naming of Windows Behat matrix line

---

src/Elasticsearch/Serializer/ItemNormalizer.php

| Tickets       | Closes #6492

fix(elasticsearch): change normalize return type to compatible with other normalizers

---

src/Doctrine/Orm/composer.json
src/GraphQl/composer.json
src/Hydra/composer.json
src/Metadata/composer.json
src/OpenApi/composer.json
src/Serializer/composer.json
src/State/composer.json
src/Symfony/composer.json

fix: add missing v4 version constraints

---

src/Laravel/resources/views/swagger-ui.blade.php

fix(laravel): SwaggerUI title

---

src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php

fix(laravel): identitifer is not writable unless marked as writable

---

src/Laravel/README.md

doc: link monorepo to test laravel

---

composer.json
src/Laravel/.gitattributes
src/Laravel/CONTRIBUTING.md
src/Laravel/LICENSE
src/Laravel/README.md
src/Laravel/composer.json
src/Symfony/README.md
src/Symfony/composer.json

docs: cleanup and minor marketing improvements

---

src/Laravel/ApiPlatformProvider.php

chore(laravel): remove duplicated ItemNormalizer definition

---

src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php

feat(laravel): supports more Eloquent types

---

src/GraphQl/Tests/Type/FieldsBuilderTest.php
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/TypeBuilder.php
src/GraphQl/composer.json
src/Laravel/ApiPlatformProvider.php
src/Laravel/Eloquent/Metadata/Factory/Resource/EloquentResourceCollectionMetadataFactory.php
src/Laravel/Eloquent/State/CollectionProvider.php
src/Laravel/Eloquent/State/LinksHandler.php
src/Laravel/Exception/ErrorHandler.php
src/Laravel/GraphQl/Controller/EntrypointController.php
src/Laravel/GraphQl/Controller/GraphiQlController.php
src/Laravel/State/ValidateProvider.php
src/Laravel/composer.json
src/Laravel/config/api-platform.php
src/Laravel/resources/views/graphiql.blade.php
src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php
src/State/Util/ParameterParserTrait.php
src/Symfony/Bundle/Resources/config/graphql.xml

Adds the graphql entrypoint to laravel implementation.

feat(laravel): enable graphQl support

---

src/Laravel/ApiPlatformProvider.php
src/Laravel/ApiResource/Error.php
src/Laravel/Exception/ErrorHandler.php
src/Laravel/Metadata/CachePropertyMetadataFactory.php
src/Laravel/Metadata/CachePropertyNameCollectionMetadataFactory.php
src/Laravel/Metadata/CacheResourceCollectionMetadataFactory.php
src/Laravel/Tests/JsonLdTest.php
src/Laravel/Tests/JsonProblemTest.php

fix(laravel): cache metadata, add trace on debug mode

---

features/hydra/collection.feature
src/Hydra/JsonSchema/SchemaFactory.php
src/Hydra/Serializer/CollectionFiltersNormalizer.php
src/Hydra/Serializer/CollectionNormalizer.php
src/Hydra/Serializer/ConstraintViolationListNormalizer.php
src/Hydra/Serializer/DocumentationNormalizer.php
src/Hydra/Serializer/PartialCollectionViewNormalizer.php
src/JsonLd/ContextBuilder.php
src/JsonLd/Serializer/HydraPrefixTrait.php
src/OpenApi/Factory/OpenApiFactory.php
src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Symfony/Bundle/DependencyInjection/Configuration.php
src/Symfony/Bundle/Resources/config/elasticsearch.xml
src/Symfony/Bundle/Resources/config/hydra.xml
src/Symfony/Bundle/Resources/config/jsonld.xml
src/Symfony/Tests/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
tests/Fixtures/TestBundle/ApiResource/NoHydraPrefix.php
tests/Fixtures/app/AppKernel.php
tests/Fixtures/app/config/config_common.yml
tests/Hydra/JsonSchema/SchemaFactoryTest.php
tests/Hydra/Serializer/CollectionNormalizerTest.php
tests/Hydra/Serializer/DocumentationNormalizerTest.php
tests/JsonLd/ContextBuilderTest.php
tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

Closes #6209, closes #6415.
Closes #5514.

feat: remove hydra prefix

---

src/Laravel/ApiPlatformProvider.php

Without this normalizer, pagination hypermedia controls are missing.
For the record, `CollectionFiltersNormalizer` is not registered as well. This must be done (in follow-up PR).

fix(laravel): register HydraPartialCollectionViewNormalizer

---

src/Laravel/ApiPlatformProvider.php
src/Laravel/Eloquent/Filter/DateFilter.php
src/Laravel/Eloquent/Filter/OrFilter.php
src/Laravel/Eloquent/Filter/OrderFilter.php
src/Laravel/Eloquent/Filter/RangeFilter.php
src/Laravel/Tests/Eloquent/Filter/DateFilterTest.php
src/Laravel/Tests/EloquentTest.php
src/Laravel/workbench/app/Models/Book.php
src/Metadata/JsonSchemaFilterInterface.php
src/Metadata/OpenApiParameterFilterInterface.php
src/Metadata/Parameter.php
src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
src/OpenApi/Factory/OpenApiFactory.php
src/Serializer/Filter/PropertyFilter.php

feat(laravel): eloquent filters date range

---

src/Laravel/ApiPlatformProvider.php
src/Laravel/config/api-platform.php

feat(laravel): add CSV support

---

src/Laravel/Eloquent/Metadata/Factory/Resource/EloquentResourceCollectionMetadataFactory.php
src/Laravel/Security/ResourceAccessChecker.php
src/Laravel/Tests/Policy/BookAllowPolicy.php
src/Laravel/Tests/Policy/BookDenyPolicy.php
src/Laravel/Tests/Policy/PolicyAllowTest.php
src/Laravel/Tests/Policy/PolicyDenyTest.php

feat: if a policy matches the name of a model we automatically register it

---

src/Hal/Serializer/ObjectNormalizer.php
src/Hal/composer.json
src/Laravel/ApiPlatformProvider.php
src/Laravel/Tests/HalTest.php
src/Laravel/composer.json

This PR adds HAL support for Laravel

feat: add hal support for laravel

---

composer.json
docs/composer.json
src/Doctrine/Common/composer.json
src/Doctrine/Odm/composer.json
src/Doctrine/Orm/composer.json
src/Documentation/composer.json
src/Elasticsearch/composer.json
src/GraphQl/composer.json
src/HttpCache/composer.json
src/Hydra/composer.json
src/JsonApi/composer.json
src/JsonLd/composer.json
src/JsonSchema/composer.json
src/Metadata/composer.json
src/OpenApi/composer.json
src/ParameterValidator/composer.json
src/RamseyUuid/composer.json
src/Serializer/composer.json
src/State/composer.json
src/Symfony/composer.json
src/Validator/composer.json

chore: setup star forwarding

---

src/Doctrine/Common/State/PersistProcessor.php
src/JsonLd/Serializer/ItemNormalizer.php
src/State/Provider/DeserializeProvider.php
src/Symfony/Bundle/DependencyInjection/Configuration.php
tests/Fixtures/app/AppKernel.php
tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

fix: default format and standard_put values

---

src/Symfony/Bundle/Resources/config/api.xml

Fixes incorrect namespaces in new release.

fix: incorrect namespace

---

src/GraphQl/Exception/InvalidTypeException.php
src/GraphQl/Type/FieldsBuilder.php

fix(graphql): wrong exception namespace

---

src/Doctrine/Common/README.md
src/Doctrine/Odm/README.md
src/Doctrine/Orm/README.md
src/Documentation/README.md
src/Elasticsearch/README.md
src/GraphQl/README.md
src/Hal/README.md
src/HttpCache/README.md
src/Hydra/README.md
src/JsonApi/README.md
src/JsonLd/README.md
src/JsonSchema/README.md
src/Metadata/README.md
src/OpenApi/README.md
src/ParameterValidator/README.md
src/RamseyUuid/README.md
src/State/README.md
src/Symfony/README.md

doc: add README files for components

---

src/Laravel/.github/workflows/close_pr.yml
src/Laravel/README.md

chore: add close PR action and README for Laravel component

---

CHANGELOG.md
features/hydra/error.feature
src/JsonLd/ContextBuilder.php
src/JsonLd/Serializer/ErrorNormalizer.php
src/Symfony/Bundle/Resources/config/jsonld.xml

fix(hydra): hydra_prefix on errors

---

src/Laravel/ApiPlatformProvider.php

| Branch?       | 4.0 (laravel)
| Tickets       | Closes #6694 

 fix(laravel): skip resource path when not available 

---

docs/guides/error-resource.php

Test https://github.com/api-platform/core/issues/6688

doc: error guide remove useless configuration

---

src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php

fix(laravel): match integer type

---

features/main/relation.feature
features/serializer/vo_relations.feature
src/JsonLd/Serializer/ErrorNormalizer.php
tests/JsonLd/Serializer/ErrorNormalizerTest.php

Fixes https://github.com/api-platform/core/issues/6701#issuecomment-2407507638

 fix(jsonld): prefix error @type with hydra: 

---

src/GraphQl/Type/FieldsBuilder.php

 fix(graphql): register query parameter arguments with filters 

---

src/State/Provider/ParameterProvider.php
tests/Fixtures/TestBundle/ApiResource/Issue6673/MutlipleParameterProvider.php
tests/Functional/Parameters/ParameterProviderTest.php

| Tickets       | Closes #6673

fix: multiple parameter provider #6673

---

src/Hydra/Serializer/CollectionFiltersNormalizer.php
src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
src/OpenApi/Factory/OpenApiFactory.php
src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
tests/Fixtures/TestBundle/ApiResource/FilterWithStateOptions.php
tests/Fixtures/TestBundle/Entity/FilterWithStateOptionsEntity.php
tests/Functional/Parameters/DoctrineTest.php

 fix(hydra): iri template when using query parameter 

---

src/JsonApi/Serializer/ErrorNormalizer.php
src/JsonApi/Serializer/ReservedAttributeNameConverter.php
src/Laravel/ApiPlatformProvider.php
src/Laravel/ApiResource/Error.php
src/Laravel/ApiResource/ValidationError.php
src/Laravel/State/ValidateProvider.php
src/Laravel/Tests/EloquentTest.php
src/Laravel/Tests/JsonApiTest.php
src/Laravel/workbench/app/ApiResource/RuleValidation.php
src/State/ApiResource/Error.php

| Tickets       | Closes #6745

fix(laravel): jsonapi error serialization

---

src/Hal/.gitattributes
src/HttpCache/.gitattributes

| Doc PR        | not required

chore: missing .gitattributes

---

src/Laravel/ApiPlatformProvider.php
src/Laravel/config/api-platform.php

fix(laravel): add contact & license options to fix swagger UI issues

---

src/Laravel/ApiPlatformProvider.php

| Branch?       |4.0
| Tickets       | closes #6814 

fix(laravel): graphQl type locator indexes

---

src/OpenApi/Factory/OpenApiFactory.php

| Branch?       | `3.4`
Fixes CI issues like [this job](https://github.com/api-platform/core/actions/runs/12033577614/job/33548095850).

cs: php-cs-fixer 3.65.0 compatibility

---

src/Laravel/Eloquent/State/LinksHandler.php

| Tickets       | closes #6817 

feat(laravel): belongs to many relations

---

src/Laravel/Eloquent/State/CollectionProvider.php

| Tickets       | Closes #6839

[Laravel] Fix default order by

---

src/Laravel/Eloquent/Metadata/ModelMetadata.php

| Tickets       | Closes #6842

[Laravel] Fix foregin keys (relations) beeing in attributes

---

src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
src/Metadata/Tests/Resource/Factory/ParameterResourceMetadataCollectionFactoryTest.php
src/OpenApi/Factory/OpenApiFactory.php

fix: filter may not use FilterInterface

---

src/JsonLd/ContextBuilder.php
src/JsonLd/Serializer/JsonLdContextTrait.php
tests/Fixtures/TestBundle/ApiResource/Issue6810/JsonLdContextOutput.php
tests/Fixtures/TestBundle/ApiResource/Issue6810/Output.php
tests/Functional/JsonLdTest.php
tests/JsonLd/ContextBuilderTest.php

fix(jsonld): anonymous context hydra_prefix value

---

src/ParameterValidator/Exception/ValidationException.php
src/ParameterValidator/Exception/ValidationExceptionInterface.php
src/ParameterValidator/FilterLocatorTrait.php
src/ParameterValidator/ParameterValidator.php
src/ParameterValidator/Tests/ParameterValidatorTest.php
src/ParameterValidator/Tests/Validator/ArrayItemsTest.php
src/ParameterValidator/Tests/Validator/BoundsTest.php
src/ParameterValidator/Tests/Validator/EnumTest.php
src/ParameterValidator/Tests/Validator/LengthTest.php
src/ParameterValidator/Tests/Validator/MultipleOfTest.php
src/ParameterValidator/Tests/Validator/PatternTest.php
src/ParameterValidator/Tests/Validator/RequiredTest.php
src/ParameterValidator/Validator/ArrayItems.php
src/ParameterValidator/Validator/Bounds.php
src/ParameterValidator/Validator/Enum.php
src/ParameterValidator/Validator/Length.php
src/ParameterValidator/Validator/MultipleOf.php
src/ParameterValidator/Validator/Pattern.php
src/ParameterValidator/Validator/Required.php
src/ParameterValidator/Validator/ValidatorInterface.php
src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
src/Symfony/Bundle/DependencyInjection/Configuration.php
src/Symfony/Bundle/Resources/config/legacy/parameter_validator/parameter_validator.xml
src/Symfony/Bundle/Resources/config/legacy/parameter_validator/state.xml
tests/Fixtures/app/config/config_common.yml
tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php

 chore: add missing deprecation notices to ParameterValidator 

---

src/Symfony/Bundle/Resources/config/json_schema.xml

fix(symfony): revert json schema bc break

---

src/State/ProcessorInterface.php

| Branch?       | `4.0`
Fixes CI issues like [this job](https://github.com/api-platform/core/actions/runs/12691121688/job/35373461272).

cs: php-cs-fixer 3.66.0 compatibility

---

src/Symfony/EventListener/ErrorListener.php
tests/Fixtures/TestBundle/ApiResource/Issue6926/Error.php
tests/Fixtures/TestBundle/ApiResource/Issue6926/ThrowsAnExceptionWithGroup.php
tests/Functional/Issues/Issue6926Test.php

| Tickets       | Closes #6926 

fix(symfony): error wrongly inherit normalization context

---

src/Doctrine/Orm/State/ItemProvider.php

| Branch?       | 4.0, but I'm not sure it's the lowest maintained branch
It could occur when using a DTO

fix(doctrine): Add a proper exception when a doctrine manager could not be found for a resource class

---

src/Doctrine/Orm/Extension/ParameterExtension.php

fix(doctrine): correct the use statement for ManagerRegistry

---

src/OpenApi/Factory/OpenApiFactory.php
src/OpenApi/Tests/Factory/OpenApiFactoryTest.php

fix(openapi): boolean "true" value in HttpOperation::openapi

---

src/Laravel/ApiPlatformProvider.php
src/Laravel/Tests/JsonLdTest.php

fix(laravel): register ErrorProvider

---

src/Laravel/Eloquent/State/CollectionProvider.php
src/Laravel/Eloquent/State/ItemProvider.php
src/Laravel/Eloquent/State/LinksHandlerLocatorTrait.php
src/Laravel/Eloquent/State/ModelClassTrait.php
src/Laravel/Eloquent/State/Options.php
src/Laravel/Tests/JsonLdTest.php
src/Laravel/workbench/app/ApiResource/ResourceWithModel.php

refactor(laravel): using trait to handle modelClass option
test(laravel): add test to validate the modelClass option
Rebasing #7010

feat(laravel): stateOptions modelClass for eloquent

---

features/hydra/collection.feature
features/hydra/error.feature
features/jsonld/input_output.feature
features/main/attribute_resource.feature
features/main/crud.feature
features/main/not_exposed.feature
features/main/relation.feature
features/main/union_intersect_types.feature
features/main/validation.feature
features/mongodb/filters.feature
features/security/strong_typing.feature
features/security/validate_incoming_content-types.feature
features/serializer/vo_relations.feature
src/JsonLd/Serializer/ErrorNormalizer.php
tests/Functional/ErrorTest.php
tests/Functional/ItemUriTemplateTest.php
tests/JsonLd/Serializer/ErrorNormalizerTest.php

fix(jsonld): duplicate error fields when prefix is enabled

---

src/Laravel/ApiPlatformDeferredProvider.php
src/Laravel/ApiPlatformProvider.php
src/Laravel/Tests/AutoconfigureTest.php
src/Laravel/composer.json
src/Laravel/config/api-platform.php
src/Laravel/testbench.yaml
src/Laravel/workbench/app/ApiResource/ServiceProvider.php
src/Laravel/workbench/app/Providers/WorkbenchServiceProvider.php
src/Laravel/workbench/app/Services/DummyService.php
src/Laravel/workbench/app/State/CustomProviderWithDependency.php

fix(laravel): defer autoconfiguration

---

.github/workflows/ci.yml
src/Laravel/ApiPlatformDeferredProvider.php
src/Laravel/ApiPlatformProvider.php

fix(laravel): defer "filters" dependent services

---

src/Symfony/Bundle/DataCollector/RequestDataCollector.php
src/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
tests/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
tests/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php

Revamps the api platform profiler:

fix(symfony): serialization of closure inside the profiler

---

src/Laravel/ApiPlatformDeferredProvider.php

fix(laravel): missing filters

---

src/Doctrine/Orm/Extension/EagerLoadingExtension.php

fix(doctrine): joinColumn might be an array

---

features/hydra/collection.feature
features/hydra/error.feature
features/jsonld/input_output.feature
features/main/attribute_resource.feature
features/main/crud.feature
features/main/not_exposed.feature
features/main/relation.feature
features/main/union_intersect_types.feature
features/main/validation.feature
features/mongodb/filters.feature
features/security/strong_typing.feature
features/security/validate_incoming_content-types.feature
features/serializer/vo_relations.feature
src/JsonLd/Serializer/ErrorNormalizer.php
tests/Functional/ErrorTest.php
tests/Functional/ItemUriTemplateTest.php
tests/JsonLd/Serializer/ErrorNormalizerTest.php

Reverts api-platform/core#7021

Revert "fix(jsonld): duplicate error fields when prefix is enabled"

---

src/Laravel/Eloquent/State/LinksHandler.php
src/Laravel/Tests/EloquentTest.php
src/Laravel/workbench/app/Models/GrandFather.php
src/Laravel/workbench/app/Models/GrandSon.php
src/Laravel/workbench/database/factories/GrandFatherFactory.php
src/Laravel/workbench/database/factories/GrandSonFactory.php
src/Laravel/workbench/database/migrations/2025_04_10_104829_create_grandson_table.php

fix(laravel): eloquent BelongsTo linking

---

src/Laravel/ApiPlatformDeferredProvider.php
src/Metadata/Util/ReflectionClassRecursiveIterator.php

fix(symfony): do not ignore Test files on symfony

---

src/Metadata/Parameters.php

Use template typehint in parameters

---

src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php
src/Laravel/composer.json

https://github.com/mtarld/core/pull/7

feat(laravel): use `TypeInfo`'s `Type`

---

src/GraphQl/Resolver/Factory/ResolverFactory.php
src/GraphQl/Tests/Type/FieldsBuilderTest.php
src/GraphQl/Tests/Type/TypeBuilderTest.php
src/GraphQl/Tests/Type/TypeConverterTest.php
src/GraphQl/Type/ContextAwareTypeBuilderInterface.php
src/GraphQl/Type/FieldsBuilder.php
src/GraphQl/Type/TypeBuilder.php
src/GraphQl/Type/TypeConverter.php
src/GraphQl/Type/TypeConverterInterface.php
src/GraphQl/composer.json
src/GraphQl/phpunit.xml.dist
src/Serializer/AbstractItemNormalizer.php
tests/Fixtures/TestBundle/GraphQl/Type/TypeConverter.php

revamp of https://github.com/api-platform/core/pull/7102

 feat(graphql): use TypeInfo type 

---

src/Serializer/AbstractItemNormalizer.php
src/Serializer/Tests/AbstractItemNormalizerTest.php

fix(serializer): throw NotNormalizableValueException when resource not found or invalid IRI on denormalization

---

src/Doctrine/Odm/Filter/DateFilter.php
src/Doctrine/Odm/Filter/NumericFilter.php
src/Doctrine/Orm/Filter/DateFilter.php
src/Doctrine/Orm/Filter/NumericFilter.php
src/State/ApiResource/Error.php
tests/Fixtures/TestBundle/ApiResource/WithParameter.php
tests/Fixtures/TestBundle/Document/FilteredDateParameter.php
tests/Fixtures/TestBundle/Document/FilteredRangeParameter.php

fix(doctrine): filters schema for dates and numbers

---

src/Doctrine/Common/composer.json
src/Doctrine/Odm/composer.json
src/Doctrine/Orm/composer.json

chore(doctrine): constraint api-platform/state v4.1.8

---

src/Hydra/Serializer/CollectionNormalizer.php
src/Laravel/ApiPlatformProvider.php
src/Symfony/Bundle/Resources/config/hydra.xml

| Branch?       | 4.0 or 4.1
I targeted the 4.1 branch, I don't know if it can be considered a bugfix for 4.0 as it's just an omission. Let me know.

chore(hydra): remove 3.4 deprecation

---

src/Laravel/ApiPlatformProvider.php
src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php
src/Laravel/Eloquent/Metadata/ModelMetadata.php
src/Laravel/Eloquent/State/PersistProcessor.php
src/Laravel/Tests/EloquentTest.php
src/Laravel/workbench/app/Models/CartItem.php
src/Laravel/workbench/app/Models/ShoppingCart.php
src/Laravel/workbench/database/factories/CartItemFactory.php
src/Laravel/workbench/database/factories/ShoppingCartFactory.php
src/Laravel/workbench/database/migrations/2025_05_20_143303_create_cart.php
src/Serializer/AbstractItemNormalizer.php

fix(laravel): persist embeded relations with groups

---

composer.json
src/Doctrine/Common/composer.json
src/Doctrine/Odm/composer.json
src/Doctrine/Orm/composer.json
src/Elasticsearch/composer.json
src/GraphQl/composer.json
src/Hal/composer.json
src/HttpCache/composer.json
src/Hydra/composer.json
src/JsonApi/composer.json
src/JsonLd/composer.json
src/JsonSchema/composer.json
src/Laravel/composer.json
src/Metadata/composer.json
src/OpenApi/composer.json
src/RamseyUuid/composer.json
src/Serializer/composer.json
src/State/composer.json
src/Symfony/composer.json
src/Validator/composer.json

chore: use type-info:^7.3 

---

src/OpenApi/Factory/OpenApiFactory.php

fix(openapi): fix duplicate get path for webhooks

---

src/Metadata/Extractor/PhpFileResourceExtractor.php
src/Metadata/Tests/Extractor/PhpFileResourceExtractorTest.php
src/Metadata/Tests/Extractor/php/another_valid_php_file.php

During review on Resource side here https://github.com/Sylius/SyliusResourceBundle/pull/1004, @diimpp spotted an issue.

fix(metadata) Fix new PHP file resource extractor

---

src/State/composer.json

| Tickets       | Closes #7209
This fixes #7209. See also https://github.com/api-platform/core/pull/7169#pullrequestreview-2971150920.

fix(state): depend only on translation contracts

---

src/Doctrine/Common/Tests/State/PersistProcessorTest.php
src/Doctrine/Common/composer.json

| Branch?       | main for features

chore: allow doctrine/persistence 4.0

---

src/Laravel/ApiPlatformProvider.php
src/Laravel/Eloquent/Serializer/SerializerClassMetadataFactory.php.bak
src/Laravel/Tests/EloquentTest.php
src/Laravel/workbench/app/Models/Author.php
src/Laravel/workbench/app/Models/DeliveryRequest.php
src/Laravel/workbench/app/Models/Slot.php
src/Laravel/workbench/app/Models/TimeSlot.php
src/Laravel/workbench/database/factories/DeliveryRequestFactory.php
src/Laravel/workbench/database/factories/TimeSlotFactory.php
src/Laravel/workbench/database/migrations/2025_08_29_000000_create_delivery_requests_and_time_slots_table.php
src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php
src/Metadata/Property/Factory/ClassLevelAttributePropertyNameCollectionFactory.php
src/Serializer/Mapping/Loader/PropertyMetadataLoader.php

fix(laravel): serialization issue with camelCase relation

---

src/Laravel/Eloquent/Extension/FilterQueryExtension.php
src/Laravel/Tests/Eloquent/Filter/OrderFilterTest.php
src/Laravel/Tests/EloquentTest.php
src/Laravel/Tests/ValidationTest.php
src/Laravel/workbench/app/ApiResource/SlotsForDate.php
src/Laravel/workbench/app/Http/Requests/GetDropOffSlotsRequest.php
src/Laravel/workbench/app/Http/Requests/StoreSlotRequest.php
src/Laravel/workbench/app/Models/ActiveBook.php
src/Laravel/workbench/app/Models/Area.php
src/Laravel/workbench/app/Models/Slot.php
src/Laravel/workbench/database/factories/ActiveBookFactory.php
src/Laravel/workbench/database/factories/AreaFactory.php
src/Laravel/workbench/database/factories/SlotFactory.php
src/Laravel/workbench/database/migrations/2025_09_25_111111_create_slots_table.php
src/Laravel/workbench/database/migrations/2025_09_26_000000_create_active_books_table.php

test(laravel): rules on a collection #7280

---

src/Laravel/ApiPlatformProvider.php
src/Laravel/Tests/JsonLdTest.php
src/Laravel/workbench/app/ApiResource/Issue7338Input.php
src/Laravel/workbench/app/ApiResource/Issue7338Output.php
src/Laravel/workbench/app/ApiResource/Issue7338Reproducer.php
src/Laravel/workbench/database/migrations/2025_09_26_000001_create_author_with_groups_table.php
src/Laravel/workbench/database/migrations/2025_09_26_000002_create_book_with_relations_table.php

fix(laravel): groups with input/output

---

.commitlintrc
src/Validator/Exception/ValidationException.php

fix(validator): validation exception without constraint violation list
