api-platform/core

- src/Annotation/AttributesHydratorTrait.php
- src/Bridge/Doctrine/Inflector/Inflector.php
- src/Bridge/Elasticsearch/Metadata/Document/Factory/CatDocumentMetadataFactory.php
- src/Bridge/Symfony/Routing/RouteNameGenerator.php
- src/GraphQl/Type/FieldsBuilder.php
- src/Operation/DashPathSegmentNameGenerator.php
- src/Operation/UnderscorePathSegmentNameGenerator.php
- src/Util/AnnotationFilterExtractorTrait.php
- src/Util/Inflector.php
| Tickets       | #2626
This is an alternative approach to #3560. Since Doctrine Inflector cannot be bumped to version 1.4 without dropping support for php 7.1, this PR introduces a façade that uses the new API if it's available and falls back to the 1.3 API otherwise.
This change removed a lot of messages from my application's deprecation log.
> Handle deprecations from Doctrine Inflector

- CONTRIBUTING.md
- tests/Fixtures/app/AppKernel.php
> Fix --prefer-lowest tests

- CHANGELOG.md
> Add changelog for v2.5.6

- CHANGELOG.md
- src/Metadata/Extractor/XmlExtractor.php
- src/Metadata/Extractor/YamlExtractor.php
- tests/Fixtures/FileConfigurations/resources_with_parameters.xml
- tests/Fixtures/FileConfigurations/resources_with_parameters.yml
- tests/Metadata/Extractor/ExtractorTestCase.php
| Bug fix?      | no, more like an improvement
| New feature?  | yes, in a way
| Tickets       | https://github.com/api-platform/core/issues/3559
This PR will allow you to define `subresource.resourceClass` as a parameter of the container.
The extractors have support for resolving class names through container defined parameters, but the subResource class did not have support for this, which kind of makes the use of parameters as a flexibility measure a little less useful when you want to use subResources.
> Support subresource resourceClass resolving

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/filter.xml
- src/Bridge/Symfony/Bundle/Resources/config/nelmio_api_doc.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
This PR addresses method signatures of the Symfony Config and DependencyInjection components that have changed in Symfony 5.1.
> Handle deprecations from Symfony 5.1

- src/HttpCache/EventListener/AddHeadersListener.php
- tests/HttpCache/EventListener/AddHeadersListenerTest.php
This change allows to mark a resource as "private" in the cache headers, to avoid having it being cached by shared caching services (Varnish, etc.)
**Example:**
User resources (`/api/user/xxx`) may contain sensitive information that cannot be controlled fine-grained enough with a Vary-header. So these resources should only be cached on the client.
**Configuration:**
```yaml
resources:
App\Entity\User:
attributes:
cache_headers:
public: false
shared_max_age: 0 # <- this is ignored as not relevant on private resources
```
> Allow a resource Cache-Control HTTP header to be private

- src/Metadata/Extractor/AbstractExtractor.php
Fix whitespace in namespace token.
If the RFC at https://wiki.php.net/rfc/namespaced_names_as_token gets accepted, then this will cause a parse error in PHP 8.
> Fix whitespace in namespace

- CHANGELOG.md
- features/bootstrap/DoctrineContext.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
- src/GraphQl/Action/EntrypointAction.php
- src/GraphQl/Error/ErrorHandler.php
- src/GraphQl/Error/ErrorHandlerInterface.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/GraphQl/Action/EntrypointActionTest.php
Porting the functionality from the 2.5.x branch over to master - replaces existing PR #3630 
Errors thrown from the platform are caught by GraphQL and can't be logged or tracked in production environments, making it impossible to track down the cause of errors or use error analysers. This PR allows the errors from GraphQL to be handled by the developers by decorating the ErrorHandler. The errors can either logged (though a service like monolog) or sent to a 3rd party error analyser, like Sentry or NewRelic.
> Handling GraphQL errors

- src/GraphQl/Type/Definition/IterableType.php
- src/GraphQl/Type/Definition/UploadType.php
Following https://github.com/api-platform/core/pull/3621.
Do not add BC for types.
> [GraphQL] No BC for types

- features/bootstrap/DoctrineContext.php
- src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
- src/JsonSchema/Command/JsonSchemaGenerateCommand.php
| Type       | improvement
Since Symfony 3.4 console commands can be lazy thanks to a [static name property](https://github.com/symfony/symfony/pull/23887).
This change does not break BC because the BC layer is already [in the base command's constructor](https://github.com/symfony/symfony/pull/23887/files#diff-8e80595663798837db1b033187835535R75).
> Lazy console commands

- src/Bridge/Doctrine/Common/DataPersister.php
- tests/Bridge/Doctrine/Common/DataPersisterTest.php
`DataPersister` checks change tracking policy before persisting it. It works only with ORM since ODM metadata class is not the same. The aim of this PR is to fix it.
> Check change tracking deferred for ODM

- src/Swagger/Serializer/DocumentationNormalizer.php
| Bug fix?      | yes - it fixes wrong behavior
| BC breaks?    | possibly it can enable pagination (in documentation) in some specyfic cases
| Deprecations? |no
| Tickets       | #3676 
Now the decision of subresource pagination is based on subresource operation or if not set, on subresource resource. Previously was based on Primary resource get operation or Primary resource itself.
> #3676 - fixed subresource pagination support if primary resource has pagination disabled

- tests/ProphecyTrait.php
annotation `@postCondition` is only available from phpunit ^9.1.
see https://github.com/sebastianbergmann/phpunit/commit/85fefa381541fb3fcbbfe9b5f32be386551cd774
> fix prophecy trait

- CHANGELOG.md
- features/openapi/docs.feature
- src/JsonSchema/SchemaFactory.php
- tests/Hydra/JsonSchema/SchemaFactoryTest.php
- tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
| Tickets       | fixes #1969
Replaces PR #3669 
From https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#componentsObject
`All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.`
Invalid characters will be replaced by `.`. (see https://github.com/api-platform/core/pull/3669#issuecomment-681941187)
> Fix definition names to be compliant with OpenAPI 3.0 and JSON Point Spec

- .github/workflows/ci.yml
- composer.json
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/symfony_uid.xml
- src/Bridge/Symfony/Identifier/Normalizer/UlidNormalizer.php
- src/Bridge/Symfony/Identifier/Normalizer/UuidNormalizer.php
- src/JsonSchema/TypeFactory.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Identifier/Normalizer/UlidNormalizerTest.php
- tests/Bridge/Symfony/Identifier/Normalizer/UuidNormalizerTest.php
| Tickets       | fixes #3714
- Added support for denormalizing identifiers with symfony uuid/ulid;
- Added ulid/uuid support to json schema;
> Add Symfony Uid support

- src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
- tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php
Fatal error:
```bash
TypeError: Argument 1 passed to ApiPlatform\Core\Metadata\Resource\ResourceMetadata::withDescription() must be of the type string, null given, called in /var/www/vendor/api-platform/core/src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php on line 120
```
This was cause when trying to merge two metadata, parent & child ones. By default `ApiPlatform\Core\Annotation\ApiResource` (as well as parent here: `ApiPlatform\Core\Metadata\Resource\ResourceMetadata`) has some of fields marked as default = `null`, when merging right now it's not validated that child has value set, thus due …
> Bugfix | Don't try to set `null` values when merging metadata

- CHANGELOG.md
- composer.json
- src/Bridge/Symfony/Bundle/DataCollector/RequestDataCollector.php
- src/Bridge/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
- tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
- tests/Bridge/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php
After a small discussion with @dunglas it appears it could be nice to display the Api-Platform's version in the Symfony's debug-bar.
Two solutions were talked about, adding a constant (:-1: because it needs to be maintained), or using ocramius/package-versions (this package is required-dev by symfony/orm).
This feature was proposed to Symfony but it was [refused](https://github.com/symfony/symfony/pull/34221).
So here we are :-)
Output:
Note:
I was not sure about adding tests or not, as the outpu depends of a final class, that might exists or not
> Add Api-Platform's version in debug bar

- features/graphql/input_output.feature
- features/jsonld/input_output.feature
- features/jsonld/non_resource.feature
- features/main/operation.feature
- features/main/relation.feature
- features/serializer/deserialize_objects_using_constructor.feature
- src/JsonLd/ContextBuilder.php
- src/JsonLd/Serializer/JsonLdContextTrait.php
- src/JsonLd/Serializer/ObjectNormalizer.php
- tests/JsonLd/ContextBuilderTest.php
- tests/JsonLd/Serializer/ObjectNormalizerTest.php
| Tickets       | fixes  
The `@type` property was missing from collection using output DTOs.
> Fix mising @type in output DTO collections

- CHANGELOG.md
- src/Annotation/ApiResource.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Routing/ApiLoader.php
- src/Metadata/Resource/Factory/OperationResourceMetadataFactory.php
- src/Operation/Factory/SubresourceOperationFactory.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Routing/ApiLoaderTest.php
- tests/Fixtures/FileConfigurations/resources.xml
- tests/Fixtures/FileConfigurations/resources.yml
- tests/Fixtures/FileConfigurations/single_resource.yml
- tests/Fixtures/app/config/config_common.yml
- tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php
- tests/Metadata/Resource/Factory/ExtractorResourceMetadataFactoryTest.php
- tests/Metadata/Resource/Factory/FileConfigurationMetadataFactoryProvider.php
- tests/Metadata/Resource/Factory/OperationResourceMetadataFactoryTest.php
In Symfony 5.1, it will be possible to declare routes as stateless (https://github.com/symfony/symfony/pull/35732)
For stateless routes, kernel will either throw an exception (debug enabled) or log a warning (debug disabled) on session usage.
As API Platform shouldn't use session (according to REST architecture constraints), this PR proposes to add an ApiResource attribute in order to declare related routes as stateless: `stateless`
`false` will be the default in order to prevent BC break (and we could set it at `true` in the next major)
One question still remains. API Plateform could be on top of …
> Add stateless ApiResource attribute

- src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
Argument would always be ignored as null coalescing operator has a higher precedence than ternary operator
| Tickets       |  
> Fix expression language argument for PublishMercureUpdatesListener

- composer.json
Make the 2.5 pipeline green again. That was likely due to the master branch being removed from the symfony/phpunit-bridge
> [2.5] Fix CI

- .github/workflows/ci.yml
-
We might want to skip the installation of symfony/uid for legacy tests completely. The rationale behind this is that we can't install this package when the symfony requirement is limited to `^3.4 | ^4.0` only.
> Try to fix master pipeline

- src/Util/AttributesExtractor.php
- tests/Util/RequestAttributesExtractorTest.php
| Tickets       | fixes #3751
Expose the previous_data attribute into DataPersisters context.
ref https://github.com/api-platform/core/issues/3751#issuecomment-706753166
> Add previous_data to persisters context when available

- src/OpenApi/Model/Paths.php
Found this bug on a brand new Symfony project while trying to check the Open Api documentation while no Entity was created yet with `"api-platform/core": "2.6.x-dev"`
> Fix openApi when no data provided

- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Model/Operation.php
- src/OpenApi/Model/PathItem.php
- src/OpenApi/Serializer/OpenApiNormalizer.php
- tests/OpenApi/Serializer/OpenApiNormalizerTest.php
This fixes:
~~- ability to normalize OpenApi v3 using `/docs.json`~~ (will be in another patch #3759)
- removes `servers` on operations when it's empty to fix the swagger-ui bug :
- Allows to specify `security` as an empty array on an `openapi_context` to remove previously enabled security.
> fix OpenApi operation servers/security

- CHANGELOG.md
- features/bootstrap/DoctrineContext.php
- features/graphql/filters.feature
- src/GraphQl/Resolver/Stage/ReadStage.php
- src/GraphQl/Type/FieldsBuilder.php
- src/Util/ArrayTrait.php
- tests/GraphQl/Resolver/Stage/ReadStageTest.php
- tests/GraphQl/Type/FieldsBuilderTest.php
- tests/ProphecyTrait.php
- tests/Util/ArrayTraitTest.php
The InputObjectType doesn't preserve the order of the arguments passed to it and it's the order declared in the service declaration that is used. This can lead to bug when the order of the arguments matter, like with the OrderFilter for example.
The solution is to change the type of the filter argument from InputObjectType to a list of InputObjectType because the order of a list is preserved.
The "old" syntax `order: {foo: asc, bar: desc}` is still "working" (but it's buggy) and the following syntax should be used instead `order: [{foo: 'asc'}, {bar: 'desc'}]`
In the first commit there is a falling behat test that use the current syntax to order a collection across 2 fields, and the order is first apply one the field `name` before the field `description`.
| …
> [GraphQL] Fix filter arguments order

- features/bootstrap/DoctrineContext.php
- features/jsonld/iri_only.feature
- src/Hydra/Serializer/CollectionNormalizer.php
- src/JsonLd/ContextBuilder.php
- src/Serializer/SerializerContextBuilder.php
- tests/Fixtures/TestBundle/Document/IriOnlyDummy.php
- tests/Fixtures/TestBundle/Entity/IriOnlyDummy.php
- tests/Hydra/Serializer/CollectionNormalizerTest.php
- tests/JsonLd/ContextBuilderTest.php
- tests/Serializer/SerializerContextBuilderTest.php
| Tickets       | no
adds an "iri_only" parameter to the "collectionOperations" annotation. allows the display of resources in IRI list form
> feat: improves iri_only implementation

- src/Identifier/IdentifierConverter.php
Currently the identifier denormalization loops continues when an identifier is denormalized. This causes issues if you want to denormalize an identifier and if it then gets denormalized again.
> fix identifiers do not denormalize the same identifier twice

- src/Bridge/Symfony/Routing/Router.php
| Tickets       | fixes #3775
I made a comparison before slashing the first baseUrl from IRI as security check, maybe it can be removed. I used substr as it is faster than preg_replace.
> Slash baseUrl only from IRI beginning

- src/Bridge/Symfony/Bundle/Test/Constraint/ArraySubset.php
| Tickets       | n/a (but I lost hours trying to find out why my PHPUnit version wasn't detected correctly ^^)
> fix: better PHPUnit version detection

- src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
| Tickets       | fixes #3681
When using a method or property (like [this example](https://api-platform.com/docs/core/mercure/#dispatching-private-updates-authorized-mode) from the documentation) you can't return `false` right now.
Currently, this example:
```
<?php
// api/src/Entity/Book.php
use Doctrine\ORM\Mapping as ORM;
/**
* @ApiResource(mercure="object.mercureOptions()")
*/
class Book
{
/**
* @ORM\Column(type="string")
*/
private $foo;
public function mercureOptions()
{
if ($this->foo !== 'bar') {
return false;
}
return …
```
> Allow method/property to return false

- src/Bridge/Symfony/Bundle/Command/OpenApiCommand.php
- src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
| Tickets       | n/c
| Doc PR        | n/c
Some commands are already lazy loaded, but when profiling a command execution using Blackfire, I found this.
> Lazy load remaining commands

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/hal.xml
- src/Bridge/Symfony/Bundle/Resources/config/jsonapi.xml
- src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
When using ApiPlatform without the SecurityBundle, the following error occurres:
> The service "api_platform.jsonld.normalizer.item" has a dependency on a non-existent service "api_platform.security.resource_access_checker".
This PR fixes the coupling between ItemNormalizer and `api_platform.security.resource_access_checker` service
> Do not inject api_platform.security.resource_access_checker on ItemNormalizer if SecurityBundle is not installed

- src/Bridge/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
This PR is part of a set of PR whose purpose is to make the assertions `assertMatchesResourceItemJsonSchema` and `assertMatchesResourceCollectionJsonSchema` work correctly.
The PR are:
- https://github.com/api-platform/core/pull/3803
- https://github.com/api-platform/core/pull/3804
- https://github.com/api-platform/core/pull/3806
- https://github.com/api-platform/core/pull/3807 (this one)
Without doing this, the refs are not correctly expanded and the value is not correctly validated against the JSON Schema.
It's because of this line:
https://github.com/justinrainbow/json-schema/blob/fa4d2d3c1e40a222 …
> fix: use getArrayCopy for assertMatchesJsonSchema

- src/Hydra/JsonSchema/SchemaFactory.php
- src/JsonSchema/Schema.php
- tests/Hydra/JsonSchema/SchemaFactoryTest.php
- tests/JsonSchema/SchemaTest.php
This PR is part of a set of PR whose purpose is to make the assertions `assertMatchesResourceItemJsonSchema` and `assertMatchesResourceCollectionJsonSchema` work correctly.
The PR are:
- https://github.com/api-platform/core/pull/3803 (this one)
- https://github.com/api-platform/core/pull/3804
- https://github.com/api-platform/core/pull/3806
- https://github.com/api-platform/core/pull/3807
It adds the base Hydra properties (`@id`, `@type`) to collection items definition in the JSON Schema.
Before:
```json
{
"$schema":"http:\/\/json-schema.org\/draft-07\/schema#",
"type":"object",
"definitions":{ …
```
> [JSON Schema] Add base Hydra properties to collection items definition

- phpstan.neon.dist
- src/JsonSchema/SchemaFactory.php
- tests/JsonSchema/SchemaFactoryTest.php
- tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
- tests/Swagger/Serializer/DocumentationNormalizerV3Test.php
This PR is part of a set of PR whose purpose is to make the assertions `assertMatchesResourceItemJsonSchema` and `assertMatchesResourceCollectionJsonSchema` work correctly.
The PR are:
- https://github.com/api-platform/core/pull/3803
- https://github.com/api-platform/core/pull/3804 (this one)
- https://github.com/api-platform/core/pull/3806
- https://github.com/api-platform/core/pull/3807
It add `additionalProperties` (to false) to the definitions in order to not validate a schema if the validated object has additional properties (it could be another resource in this case).
> [JSON Schema] Add `additionalProperties` (false) to the generated JSON schema

- src/JsonSchema/SchemaFactory.php
- tests/JsonSchema/SchemaFactoryTest.php
This PR is part of a set of PR whose purpose is to make the assertions `assertMatchesResourceItemJsonSchema` and `assertMatchesResourceCollectionJsonSchema` work correctly.
The PR are:
- https://github.com/api-platform/core/pull/3803
- https://github.com/api-platform/core/pull/3804
- https://github.com/api-platform/core/pull/3806 (this one)
- https://github.com/api-platform/core/pull/3807
It uses the validation groups when creating the property metadata. The aim is to use correctly the `ValidatorPropertyMetadataFactory`, mainly to receive correctly the `required` attribute: …
> [JSON Schema] Use validation groups for property metadata in JSON Schema factory

- src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/swagger-ui.xml
- src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
- src/Bridge/Symfony/Bundle/SwaggerUi/SwaggerUiAction.php
- src/Bridge/Symfony/Bundle/SwaggerUi/SwaggerUiContext.php
- tests/Bridge/Symfony/Bundle/Action/SwaggerUiActionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
- tests/Bridge/Symfony/Bundle/SwaggerUi/SwaggerUiActionTest.php
| Tickets       | fixes #3760
| Doc PR        | api-platform/docs#1186
This PR introduces a new config parameter: `asset_package`
It enables the users to specify a custom asset package ([as in Symfony framework](https://symfony.com/doc/4.4/reference/configuration/framework.html#packages)) to be used by the Swagger UI template.
In this way, we have more fine-grained control over the asset url generations.
The new parameter is optional with a `null` default value. It results in the same `asset(...)` twig function calls as it was before.
----
Example usage of the new parameter:
```yaml
api_platform:
asset_package: 'api_platform'
```
and the …
> Configurable asset package

- features/main/default_order.feature
- src/Bridge/Doctrine/MongoDbOdm/Extension/OrderExtension.php
- src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
- tests/Fixtures/TestBundle/Document/Foo.php
- tests/Fixtures/TestBundle/Entity/Foo.php
| Tickets       |  #1321
| Doc PR        | api-platform/docs#1195
Currently, the `default-order` impact all the defined collection operations, so, it is not possible to have two different custom operations with different `default-order` configurations.
The idea is to support both, the definition of an order in a global way and also in a more specific way.
For example:
```yaml
resources:
attributes:
order: ["foo", "ASC"]
App\Entity\Book:
collectionOperations:
get_desc:
method: GET
path: /books/desc
order: ["name", "DESC"]
normalization_context:
groups: ['group1']
get_asc:
method: GET
path: /books/asc
order: ["name", "ASC"] …
```
> [DEFAULT ORDER] #1246: Support default order for a specific custom operation

- src/JsonSchema/TypeFactory.php
- tests/JsonSchema/TypeFactoryTest.php
Following https://github.com/api-platform/core/pull/3402 and the list of PR from https://github.com/api-platform/core/pull/3807.
In order to validate correctly nullable data against the generated JSON Schema (using `assertMatchesResourceItemJsonSchema` and `assertMatchesResourceCollectionJsonSchema`), the schema needs to be compliant with the specification for nullability:
```json
{"type": ["string", "null"]}
```
However OpenAPI < 3.1 doesn't understand this syntax (OpenAPI 3.1 will at least! https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0) and only understands:
```json
{"type": …
```
> [JSON Schema] Manage correctly nullability

- features/graphql/mutation.feature
- features/hal/problem.feature
- features/hydra/error.feature
- features/jsonapi/errors.feature
- features/main/validation.feature
- features/security/send_security_headers.feature
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
- src/Bridge/Symfony/Validator/EventListener/ValidationExceptionListener.php
- src/GraphQl/Serializer/Exception/ValidationExceptionNormalizer.php
- tests/Bridge/Symfony/Validator/EventListener/ValidationExceptionListenerTest.php
- tests/GraphQl/Serializer/Exception/ValidationExceptionNormalizerTest.php
| New feature?  |no 
| Fixed tickets |  
| Doc PR |  api-platform/docs#1206
In general, I think it's a good practice to use *400 Bad Request* http status code when the request body is malformed (i.e. incorrect syntax in the payload or invalid parameters in the URL) and  use *422 Unprocessable Entity*  when the query is semantically incorrect.
According to the RFC https://tools.ietf.org/html/rfc4918#section-11.2 the code 422 seems to me to be much more appropriate and specific in a case of data validation failure.
Cause the server understands the content type of the request entity and the syntax of the request entity is correct but was unable to process the data …
> [ValidationException] Allow customization of validation error status code

- .github/workflows/ci.yml
Just use `composer config` instead of jq + sponge to add `minimum-stability: dev` to composer.json
> Speed up symfony 5.2 build

- features/doctrine/search_filter.feature
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Common/Filter/SearchFilterTestTrait.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
| Tickets       | fixes #3782
**Description**  
For now the SearchFilter accept many values only with the "exact" strategy: https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php#L122
This is a limitation and we could make it possible to search partially many values.
With many values, the exact strategy adds a WHERE IN clause. 
Doing the same for the partial, start, end and word_start we could add LIKE OK LIKE [...] clause.
**Example**  
```php
/**
* @ApiFilter(SearchFilter::class, properties={"email": "partial"})
*/
class Contact 
{
private $email;
}
```
```yaml
Contact:
john:
email: …
```
> Allow to search on multiple values on every strategies

- src/Bridge/Doctrine/MongoDbOdm/Filter/OrderFilter.php
- src/Bridge/Doctrine/MongoDbOdm/SubresourceDataProvider.php
- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/GraphQl/Type/FieldsBuilder.php
- src/HttpCache/VarnishPurger.php
- src/Security/Core/Authorization/ExpressionLanguageProvider.php
- src/Security/ExpressionLanguage.php
- src/Security/ResourceAccessChecker.php
- src/Util/RequestParser.php
> Apply "static_lambda" CS rule under `src/` dir

- phpstan.neon.dist
- src/JsonSchema/SchemaFactory.php
- tests/JsonSchema/SchemaFactoryTest.php
- tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
- tests/Swagger/Serializer/DocumentationNormalizerV3Test.php
| Tickets       | fixes https://github.com/api-platform/core/issues/3382
| Doc PR        | todo?
According to https://github.com/api-platform/core/pull/3388 additionalProperties should respect the normalization context allow_extra_attributes value. Adds up to https://github.com/api-platform/core/pull/3804.
> Specify AdditionalProperties according to allow_extra_attributes

- .github/workflows/ci.yml
- tests/JsonLd/Serializer/ObjectNormalizerTest.php
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> CI: Set-env is deprecated

- src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Common/Filter/SearchFilterTestTrait.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
| BC breaks?    | yes: search terms no longer need or support explicit escaping, and consequently, regex special characters no longer behave like they're special.
| Tickets       | Fixes #3754
> Escape search terms before using them in a Regex

- src/Annotation/ApiProperty.php
- src/Annotation/ApiResource.php
- src/Annotation/AttributesHydratorTrait.php
- tests/Annotation/ApiResourceTest.php
Since https://github.com/Haehnchen/idea-php-annotation-plugin/commit/7a75efc63ffada9eeeb3b228def62aeaff9e0a45 is merged, there is no need to have private properties anymore (see https://github.com/api-platform/core/pull/1788).
> Remove unuseful private properties from ApiResource

- src/HttpCache/VarnishPurger.php
- tests/HttpCache/VarnishPurgerTest.php
| Tickets       | fixes #3168 and #1856
This PR chunks the regex to send it in separate requests to avoid `400 Bad Request` responses from Varnish when the maximum header length is exceeded. The default limit is 8000 for now since it's Varnish's default value, but that could be easily made configurable in another iteration (maybe for next minor release instead of 2.5?).
> Chunk headers to comply with Varnish max length

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/openapi.xml
- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Model/Contact.php
- src/OpenApi/Model/License.php
- src/OpenApi/Options.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
| Doc PR        | Not yet
Enables the configuration of ToS, Contact and License in the SwaggerUI. 
I wasnt sure about the contact model. All properties there have a default value which is not needed imho, contact e.g. also works if you only set one field. I think it would be better to make them nullable so they are not serialized at all.
> OpenAPI - make all info model fields configurable

- docs/adr/0000-subresources-definition.md
| Bug fix?      | na
| New feature?  | na
| Deprecations? | na
| Tickets       |  #2706
@GregoireHebert @dunglas @vincentchalamon @Deuchnord
> Subresource definition ADR proposal

- docs/adr/0001-resource-identifiers.md
Following https://github.com/api-platform/core/pull/3838 an ADR for identifiers.
> Resource identifiers ADR

- .gitignore
- .php_cs.dist
- phpstan.neon.dist
- src/Annotation/ApiProperty.php
- src/Annotation/ApiResource.php
- src/Annotation/AttributesHydratorTrait.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php
- src/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactory.php
- src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
- src/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php
- tests/Annotation/ApiPropertyTest.php
- tests/Annotation/ApiResourceTest.php
- tests/Fixtures/TestBundle/Entity/DummyPhp8.php
- tests/Metadata/Property/Factory/AnnotationPropertyMetadataFactoryTest.php
- tests/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactoryTest.php
- tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php
- tests/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactoryTest.php
PHP 8 has been released today, let's celebrate!
```php
#[ApiResource(description: "Hey PHP 8", iri: "https://php.net")]
class DummyPhp8
{
#[ApiProperty(description: "We support attributes!")]
public string $hello = 'hi';
}
```
> feat: add an ApiResource PHP 8 attribute

- composer.json
| Tickets       | fixes #3854
Changed the version string for `willdurand/negotiation` to `^2.0.3 || ^3.0` to allow PHP 8.0
> Update composer.json to support PHP 8.0

- features/hal/problem.feature
- features/hydra/error.feature
- features/main/validation.feature
- src/Serializer/AbstractConstraintViolationListNormalizer.php
- tests/Hydra/Serializer/ConstraintViolationNormalizerTest.php
- tests/Problem/Serializer/ConstraintViolationNormalizerTest.php
| BC breaks?    | potentially
| Tickets       | None
| Doc PR        | Unnecessary
When returning the list of violations, in some context it is better to rely on a violation code/identifier rather than the message itself. The Symfony Validator already provides such a feature (although may not be enforced by all custom constraints), so we can directly take advantage of it.
If you're fine with the idea I'll look into finishing this PR
> Add the violation code to the violation properties

- features/main/patch.feature
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/SerializerContextBuilder.php
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/PatchDummyRelation.php
- tests/Fixtures/TestBundle/Entity/PatchDummyRelation.php
- tests/Serializer/SerializerContextBuilderTest.php
| Tickets       | fixes #3087 
| Doc PR        | Should add one for `skip_null_values`
This PR fixes inconsistencies when updating deep objects. In an update context, we should always set the `deep_object_to_populate`, at least for the `application/merge-patch+json` content type. 
Note that this fixes incoherent behavior for PATCH when updating nested resources. 
Also, now we support `deep_object_to_populate` and this fixes #3087. Users can enable it via the `denormalization_context` if needed. 
Many thanks @Toflar for reporting this and helping me get to the bottom of this!
> Deep object update consistency

- CHANGELOG.md
- src/Bridge/Elasticsearch/DataProvider/CollectionDataProvider.php
- src/Bridge/Elasticsearch/DataProvider/Paginator.php
- tests/Bridge/Elasticsearch/DataProvider/CollectionDataProviderTest.php
- tests/Bridge/Elasticsearch/DataProvider/PaginatorTest.php
| BC breaks?    | probably yes...
This patch enables the Elasticsearch paginator to receive the serialization context so that documents can be denormalized to objects using the serialization groups.
> [Elasticsearch] inject denormalization context into `Paginator` to have access to serialization groups

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Fixtures/app/config/config_common.yml
| Deprecations? | n/a
| Tickets       | https://github.com/api-platform/core/pull/3436, https://github.com/api-platform/api-platform/pull/1703, https://github.com/symfony/recipes/pull/853
It's not possible to enable `stateless` by default because it conflicts with the default configuration of the Symfony firewall. Let's disable this option in the bundle, and enable it in the distribution.
> fix: set stateless to false by default and remove the deprecation

- src/Hydra/JsonSchema/SchemaFactory.php
My entites have the following filter, to select properties. Parameter name have been overrode.
` * @ApiFilter(PropertyFilter::class, arguments={"parameterName": "fields"})`
And I got the following error in my tests, using `assertMatchesResourceCollectionJsonSchema` assertion
```
│             ...
│             3 => Array &9 (
│                 '@type' => 'IriTemplateMapping'
│                 'variable' => 'fields[]'
│                 'property' => null
│                 'required' => false
│             )
│             ...
│     )
│ ) matches the provided JSON Schema.
│ hydra:search.hydra:mapping[3].property: NULL value found, but a string is required
```
> Make "hydra:mapping" item's property nullable

- .php_cs.dist
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Util/Inflector.php
- tests/Fixtures/app/AppKernel.php
> Update php-cs-fixer configuration

- src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
This pull requests should fix a php warning when opcache preload is active:
<pre><code>PHP Warning:  Can't preload unlinked class class@anonymous: Unknown parent ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\AbstractPaginator in /app/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php on line 178</code></pre>
This fix uses the solution of https://github.com/symfony/symfony/pull/38533.
> fix warning for preloading AbstractPaginator class

- src/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php
- tests/Bridge/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
- tests/HttpCache/VarnishPurgerTest.php
| Tickets       | #3893
`PurgerInterface::purge($iris)` expects `string[]` and never used string keys from the `$iris` argument anyway.
> Fix passing tags to purge

- src/Security/ResourceAccessChecker.php
- tests/Security/ResourceAccessCheckerTest.php
Anonymous users don't exist anymore when using the Symfony Authentication manager (No token in token storage, which doesn't necessarily mean you're not behind a firewall)
> allow absence of token for sf authentication manager

- .gitignore
- .php_cs.dist
- src/Util/Inflector.php
- tests/Fixtures/app/AppKernel.php
| BC breaks?    | no (I hope)
About CS errors, I suspect a bug in PHP-CS-Fixer 2.17. I am waiting for their opinion: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5357.
~About PHPStan errors, I applied the fix from https://github.com/api-platform/core/pull/3886. I'm not sure if the new thrown exception might be a BC break.~
> Try to fix CI errors

- src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
- tests/Bridge/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
| Bug fix?      | yes  (2.6)
Currently, it's not possible to publish as multiple topics (arrays) via Mercure options because it's strictly checking for string type:
Encountered as `Argument 1 passed to ApiPlatform\Core\Bridge\Doctrine\EventListener\PublishMercureUpdatesListener::buildUpdate() must be of the type string, array given, called in /srv/api/vendor/api-platform/core/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php on line 22`
Related https://github.com/api-platform/core/pull/3728, however that PR went silent, so I went ahead  and added test.
> fix: mercure multiple topic publishing

- src/OpenApi/Factory/OpenApiFactory.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
Fixes `security` in OpenAPI spec which must be an array.
> Fix OpenApi spec security must be an array

- src/OpenApi/Model/ExtensionTrait.php
| Bug fix?      | no (well, sort of)
Do not limit the extension property to strings only. E.g. for [redoc](https://github.com/Redocly/redoc) you can specifiy an array for the logo information. I need to be able to write this:
```php
$info = $openApi->getInfo();
$info = $info->withExtensionProperty('x-logo', ['url' => 'assets/logo.svg']);
$openApi = $openApi->withInfo($info);
```
Also see https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-logo.
> Allow arbitrary extension property types

- src/DataProvider/OperationDataProviderTrait.php
- tests/EventListener/ReadListenerTest.php
- tests/Identifier/IdentifierConverterTest.php
| Tickets       | fi
Fixes a regression in 2.6 where composite identifiers are not denormalized correctly anymore
There was an existing test that was supposed to avoid such regression but it was marked as skipped during a refactoring unfortunately.
https://github.com/api-platform/core/blob/ed59e8df62a50e57eb2bbb3b8cdaefcfd241dcb5/tests/Identifier/IdentifierConverterTest.php#L33-L59
Not sure what would be the best place to test this now if needed, ping @soyuka
> Restore composite identifier denormalization

- src/OpenApi/Factory/OpenApiFactory.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
Up until now, `summary` has also been autogenerated (see e.g. https://github.com/api-platform/core/blob/2.5/src/Swagger/Serializer/DocumentationNormalizer.php#L327 or just search for `summary` there :)). It's also the one preferred by some JS tools like redoc for the navigation. I think there's nothing wrong in providing a good default for both, `description` as well as `summary`. You can always override them if you want to.
> Make sure both, description and summary are generated

- src/Serializer/AbstractItemNormalizer.php
- tests/Serializer/AbstractItemNormalizerTest.php
| New feature?  | sort of
In #3503 @GregoireHebert introduced support for the `security` attribute on an api property.
I found that this is very useful to me because I can get rid of my own normalizer. However, my permission system depends not only on roles but you can have different roles per organisation. This in turn means, it depends on the object.
The object itself is already passed on in e.g. the DenyAccessListener (https://github.com/api-platform/core/blob/master/src/Security/EventListener/DenyAccessListener.php#L100) so we should also have it here.
By introducing that, I was able to super conveniently restrict access …
> Also pass the object to the resource access checker in the serializer

- behat.yml.dist
- composer.json
- features/doctrine/search_filter.feature
- features/graphql/introspection.feature
- features/jsonapi/related-resouces-inclusion.feature
- features/main/composite.feature
- features/main/content_negotiation.feature
- features/main/subresource.feature
- src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyNameCollectionFactory.php
- src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
- src/Operation/Factory/SubresourceOperationFactory.php
- src/Serializer/AbstractItemNormalizer.php
- tests/Behat/JsonContext.php
- tests/Behat/XmlContext.php
- tests/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyNameCollectionFactoryTest.php
- tests/Fixtures/DummyIgnoreProperty.php
- tests/Fixtures/TestBundle/Entity/RelatedDummy.php
- tests/Metadata/Property/Factory/SerializerPropertyMetadataFactoryTest.php
- tests/Serializer/AbstractItemNormalizerTest.php
| Tickets       | fixes #1566
This PR is an alternative to #3820 & #3907 and adds the `@Ignore` annotation support in accordance with https://github.com/symfony/symfony/pull/28744.
> Add the @Ignore annotation support

- src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
- src/Metadata/Resource/Factory/ExtractorResourceMetadataFactory.php
- tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php
- tests/Metadata/Resource/Factory/ExtractorResourceMetadataFactoryTest.php
| Tickets       | fixes n/a
Defaults aren't applied properly when using attributes, because the default value is null.
TODO:
> fix: defaults when using attributes

- src/Bridge/Symfony/Bundle/DataPersister/TraceableChainDataPersister.php
- tests/Bridge/Symfony/Bundle/DataPersister/TraceableChainDataPersisterTest.php
| Tickets       | fixes #3980 
fix #3980 TraceableDataPersister supports called without context
> fix #3980 TraceableDataPersister supports called without context

- README.md
- composer.json
- src/Annotation/ApiResource.php
Fixing the link "https://api-platform.com/docs/core/swagger/" that leads to a 404
> Fix Swagger link in comments

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> Fix: allow to disable OpenAPI, Swagger UI

- src/OpenApi/Factory/OpenApiFactory.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
| Tickets       | fixes #3989 #4000 
Allow to override/add parameters and the RequestBody via the `openapi_context`.
> Openapi context: parameters, requestBody missing

- src/Annotation/ApiSubresource.php
- tests/Annotation/ApiSubresourceTest.php
| Tickets       | fixes #3982 
- fix the issue with the `maxDepth` parameter of the `ApiSubresource` not working
> Fix #3982 maxDepth property of the ApiSubresource annotation not working

- src/Operation/Factory/SubresourceOperationFactory.php
- tests/Operation/Factory/SubresourceOperationFactoryTest.php
| Tickets       | fixes #3573
It is not possible to set `openapi_context` on subresource operations right now.
With this PR the openapi_context property on the subresource operation with be copied within SubresourceOperationFactory  and afterwards used in OpenApiFactory.
This allows to override tags, summary and more as described [here](https://api-platform.com/docs/core/openapi/#changing-operations-in-the-openapi-documentation).
Example use case:
```php
use ApiPlatform\Core\Annotation\ApiSubresource;
/**
*   subresourceOperations={
* …
```
> Allow to set openapi_context on subresourceOperations

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/ramsey_uuid.xml
- src/Identifier/IdentifierConverter.php
- tests/Identifier/IdentifierConverterTest.php
| Tickets       | fixes #3979 
- lower priority of our identifier denormalizer for better DX
- break the chain of normalizers when an identifier transformer is found
> Fix #3979 identifier chain not breaking after denormalizing

- src/OpenApi/Serializer/OpenApiNormalizer.php
- tests/OpenApi/Serializer/OpenApiNormalizerTest.php
| Tickets       | fixes #3996 
Fixes openapi paths and schemas sorting following #3995 by @stiffroy
> Fix openapi sort #3996 

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Tickets       | fixes #3992 
> fix pagination defaults and add tests

- src/Bridge/Symfony/Bundle/Resources/config/openapi.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/OpenApi/Serializer/OpenApiNormalizerTest.php
| Tickets       | fixes #3997 
When adding a name converter some properties of OpenAPI were serialized without respecting the specification causing issues. This fixes it.
> Serialize openapi properly fix #3997

- phpstan.neon.dist
- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRegexRestriction.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyValidatedEntity.php
| Tickets       | fixes #4022 
https://swagger.io/docs/specification/data-models/data-types/#pattern uses [ECMA 262 regex syntax](https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1), so use getHtmlPattern() to get valid expression.
> pattern must be compliant with ECMA 262 regex

- src/DataProvider/OperationDataProviderTrait.php
- src/Identifier/IdentifierConverter.php
- tests/Identifier/IdentifierConverterTest.php
| Tickets       | fixes #4024
| Doc PR        | na.
IdentifierConverter was missing the context to map identifiers to the correct classes.
> Fix #4024 identifiers with multiple classes

- features/hydra/collection.feature
- src/Hydra/Serializer/PartialCollectionViewNormalizer.php
- tests/Hydra/Serializer/PartialCollectionViewNormalizerTest.php
| Tickets       | fixes https://github.com/api-platform/core/pull/3967#issuecomment-771677553
@jeremyteyssedre confused `$pageTotalItems` with the total number of items in the collection. `$pageTotalItems` is the number of items in the current page. As a reminder, with the partial pagination we cannot determine if it is the last page. Because of this, we will always have the `hydra:next` property, even on the last page. It is an "assumed bug".
cc @clementtalleu
> Fix partial pagination which no longer returns the "hydra:next" property

- src/OpenApi/Model/Parameter.php
When I put some custom documentation in my project with openapi_context I have the following error:
> The method "ApiPlatform\Core\OpenApi\Model\Parameter::getStyle()" returned "null", but expected type "string". Did you forget to initialize a property or to make the return type nullable using "?string"?
When I check this class, I can see that there are some errors in return type definition. (Maybe adding attribute type definition could help phpstan to detect this kind of problems ?)
Fix getStyle, getName, getIn return type to be consistent with construct.
> Fix getStyle, getName, getIn return type to be consistent with construct.

- src/OpenApi/Serializer/OpenApiNormalizer.php
- tests/OpenApi/Serializer/OpenApiNormalizerTest.php
| Tickets       | fixes #4047
Fixes schemas sort as it's an ArrayObject not an array.
> Fix openapi schema sort

- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Model/Parameter.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
When I put some custom documentation in my project with openapi_context I have the following error:
> The method "ApiPlatform\Core\OpenApi\Model\Parameter::getStyle()" returned "null", but expected type "string". Did you forget to initialize a property or to make the return type nullable using "?string"?
When I check this class, I can see that there are some errors in return type definition. (Maybe adding attribute type definition could help phpstan to detect this kind of problems ?)
Fix getStyle, getName, getIn return type to be consistent with construct.
@cacahouwete
> Fix openapi parameter style

- CHANGELOG.md
- src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
- tests/Bridge/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
| Tickets       | fixes #3969 
Supersedes https://github.com/api-platform/core/pull/4054.
> When using Mercure and when an entity is deleted, APIP evaluates how to retrieve entity properties.
> If we use a custom method with `@ApiResource(mercure="object.mercureOptions()")` the data provided by this function is used, with no regard if we are posting, updating or deleting the entity.
> If the custom function returns `data`, in case of a deletion, the data is still sent.
> 
> See bug report to fully understand what's wrong.
> fix(mercure): do not use data options when deleting

- CHANGELOG.md
- src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
- tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
- tests/Fixtures/TestBundle/Entity/DummyCar.php
- tests/Fixtures/TestBundle/Entity/DummyCarColor.php
- tests/Fixtures/TestBundle/Entity/DummyCarIdentifier.php
- tests/Fixtures/TestBundle/Entity/DummyTravel.php
> #4041 bugfix: FilterEagerLoadingExtension foreign identifier handling

- tests/Fixtures/TestBundle/DataTransformer/RPCOutputDataTransformer.php
After https://github.com/api-platform/core/pull/4052.
> Fix MongoDB tests for RPC

- CHANGELOG.md
- src/Bridge/Doctrine/Common/Util/IdentifierManagerTrait.php
- src/Bridge/Doctrine/Orm/ItemDataProvider.php
- src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Bridge/Doctrine/Common/Util/IdentifierManagerTraitTest.php
- tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php
- tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
| Tickets       | ???
I had some issues to understand this error with some entities that have a lot of sub-entities. To make this easier to understand, just add the resource to the exception and it became way easier :smile:
> [DoctrineBridge][UX] Better Doctrine exceptions

- CHANGELOG.md
- src/Bridge/Doctrine/Common/Filter/DateFilterTrait.php
- src/Bridge/Doctrine/MongoDbOdm/Filter/DateFilter.php
- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
- tests/Bridge/Doctrine/Common/Filter/DateFilterTestTrait.php
| Tickets       | fixes #3858 
> Allow mixed type value when apply to DateFilter.

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/ApiPlatformBundle.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AuthenticatorManagerPass.php
- src/Security/ResourceAccessChecker.php
- tests/Bridge/Symfony/Bundle/ApiPlatformBundleTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AuthenticatorManagerPassTest.php
- tests/Security/ResourceAccessCheckerTest.php
| Tickets       | Fix #4055, fix #3922
Rework of https://github.com/api-platform/core/pull/3899.
Throw back the exception if the new authenticator manager is not used (like https://github.com/symfony/symfony/blob/494ef421c554a78b38c6779c4b7deb9a20d89923/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php#L52).
Use the `NullToken` if the new authenticator manager is used and if there is no token in order to use the variables in the `security` attribute (see also https://github.com/symfony/symfony/pull/37620).
> Use a null token when using the authenticator manager

- CHANGELOG.md
| Docs fix | yes
| Tickets       | fixes #3335 
| Doc PR        | N/D
Adding a note to the v2.5.0-beta1 about the default PATCH behavior and how to override it.
> Add missing note about the default behavior of the PATCH method

- CHANGELOG.md
- src/DataProvider/TraversablePaginator.php
- tests/DataProvider/TraversablePaginatorTest.php
| Doc PR        | api-platform/docs#1194
I've had need of a paginator for my custom data provider that returns a Generator, so I thought I'd submit this as an addition to the core, if that's so desired?
> Add traversable paginator

- CHANGELOG.md
- src/JsonSchema/SchemaFactory.php
- tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
| Tickets       | Fix #4009
In https://github.com/api-platform/core/pull/3957 a change got introduced that unintentionally removed `$ref`'s from the OpenApi documentation in some cases. The PR changed an existing test without adding a new one.
`$propertySchema` is filled with the `type` that gets passed in the `@ApiProperty()` `openapi_context` or `swagger_context` attribute. So in the previous PR it was thought that whenever `$propertySchema` contains _something_ it was certainly filled because someone tried to define their own type and we shouldn't add a `$ref`. However `$propertySchema` is also filled with `description` …
> Fix missing $ref in OpenApi documentation (#4009)

- CHANGELOG.md
- src/OpenApi/Factory/OpenApiFactory.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
> Remove "oauth2" scheme from openapi security scheme

- .github/workflows/ci.yml
- CHANGELOG.md
- behat.yml.dist
- features/doctrine/search_filter.feature
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Behat/DoctrineContext.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
- tests/Fixtures/TestBundle/Entity/RamseyUuidBinaryDummy.php
- tests/Fixtures/app/config/config_common.yml
- tests/Fixtures/app/config/config_mysql.yml
- tests/Fixtures/app/config/config_postgres.yml
- tests/Fixtures/app/config/config_sqlite.yml
| Tickets       | fixes https://github.com/api-platform/api-platform/issues/1139
When searching on a binary UUID field, current behaviour leads to search done on Doctrine with the string UUID and not the binary version of it.
This is because the field type must be provided to Doctrine each time we use QueryBuilder. Why ? Because Doctrine sees string on input, and does not know it needs conversion.
This PR reads `$metadata->getTypeOfField()` and force field type.
**WARNING**
Current PR passes the unit tests (so it does not break current behaviour), but does not implement two new needed tests (to make sure it fixes the issue mentioned) : 
- …
> Handle binary UUID in SearchFilter

- CHANGELOG.md
- features/graphql/query.feature
- src/GraphQl/Resolver/Factory/ItemResolverFactory.php
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/WithJsonDummy.php
- tests/Fixtures/TestBundle/Entity/WithJsonDummy.php
- tests/GraphQl/Resolver/Factory/ItemResolverFactoryTest.php
| Tickets       | Fix #3465
Supersedes https://github.com/api-platform/core/pull/3727.
I'm not checking that the resource class is `null`, I think @moduleon's comment is interesting (see https://github.com/api-platform/core/pull/3727#discussion_r490246181) but there is no use case for now (and no test).
It can be modified if necessary later.
> [GraphQL] null iterable field should be resolved directly

- CHANGELOG.md
- src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Common/Filter/SearchFilterTestTrait.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
This potentially improves performance significantly with queries that use many filters on nested properties.
| BC breaks?    | potentially
| Tickets       | n/a 
Please note that this change has been poorly tested and this PR must be considered more of a discussion than an actual mergable PR.
In our app we have an Doctrine Entity with multiple associated `ManyToOne` and `ManyToMany` Collections. We have also defined `SearchFilter`s for properties of these Collections in the Annotation for this entity.
While using the GraphQL API, we define the query with all these properties. When the user does not use the filter it will still be defined …
> Do not add JOINs for Filters without a value

- CHANGELOG.md
- src/Bridge/Doctrine/Common/Filter/OrderFilterInterface.php
- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- tests/Bridge/Doctrine/Common/Filter/OrderFilterTestTrait.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/OrderFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
| Tickets       | (no issue)
| Doc PR        | api-platform/docs#1297
Add `nulls_always_first` and `nulls_always_last` to `nulls_comparison` of the `OrderFilter`. This allows to always sort in `null` values first or last, independent of the current order. 
This is useful for UIs with optional fields; displaying empty fields might not be useful to the user. Sorting these always last, independent of the chosen ordering, is the expected behavior.
Given something like
```
/**
* @ApiResource(order={"number": "ASC"})
* @ApiFilter(
*     OrderFilter::class,
*     properties={
*         "number": {
*             "nulls_comparison": …
```
> Add nulls_always_first and nulls_always_last to nulls_comparison

- .github/workflows/ci.yml
- src/OpenApi/Model/PathItem.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
After disabling itemOperation `GET`
```
itemOperations: [
'get' => [
'controller' => ApiPlatform\Core\Action\NotFoundAction::class,
'read' => false,
'output' => false,
],
]
```
there is not nice way to remove that path from OpenApi docs. Now to do
that you have to write:
```
$pathItem = $openApi->getPaths()->getPath('/resource/{id}');
$openApi->getPaths()->addPath(
'/resource/{id}',
new Model\PathItem(
$pathItem->getRef(),
$pathItem->getSummary(),
$pathItem->getDescription(),
null,
$pathItem->getPut(),
$pathItem->getPost(),
$pathItem->getDelete(),
$pathItem->getOptions(),
$pathItem->getHead(),
$pathItem->getPatch(),
$pathItem->getTrace(),
$pathItem->getServers(),
$pathItem->getParameters(),
)
);
```
After change it will be:
```
$pathItem = $openApi->getPaths()->getPath('/resource/{id}'); …
```
> Allow unset PathItem method

- CHANGELOG.md
- src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
- tests/Metadata/Property/Factory/SerializerPropertyMetadataFactoryTest.php
| BC breaks?    | this could change behavior for people relying on bug
| Doc PR        | not needed
Hi!
Reproducer with instructions here: https://github.com/SymfonyCasts/api-platform/tree/embedded-output-iri-embedded-bug
It's super tricky and subtle. The tl;dr is that when the `readableLink` of `PropertyMetadata` is calculated for an embedded property, it uses the serializer groups from the target resource class when it *should* use the `output=` class (because that is what will actually be serialized).
I didn't include a test (yet) - I'd like some validation that this it the correct place/idea for this.
Thanks!
> Checking the output option when calculating property metadata

- CHANGELOG.md
- features/filter/filter_validation.feature
- features/main/content_negotiation.feature
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/EventListener/AddFormatListener.php
- tests/Fixtures/TestBundle/Security/AuthenticationEntryPoint.php
- tests/Fixtures/app/AppKernel.php
- tests/Fixtures/app/config/config_common.yml
| Tickets       | fixes #3577
Moved content negotiation to before firewall to allow content aware security responses.
> #3577 moved content negotiation to before firewall

- CHANGELOG.md
- src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
All query manipulations are now located in the same method to ease the creation on classes inherited from SearchFilter.
Example:
```
class ExtendedSearchFilter extends SearchFilter
{
public const STRATEGY_OTHER = 'other';
protected function addWhereByStrategy(string $strategy, QueryBuilder $queryBuilder, string $alias, string $field, $fieldType, $values, bool $caseSensitive, string $valueParameter)
{
if (self::STRATEGY_OTHER === $strategy) {
// ...
return;
}
parent::addWhereByStrategy($strategy, $queryBuilder, $alias, $field, $fieldType, $values, $caseSensitive, $valueParameter);
}
} …
```
> SearchFilter: Refactor code to reduce code duplication and makes it easier to add new strategies to classes inheriting from SearchFilter class

- tests/OpenApi/Factory/OpenApiFactoryTest.php
Previous test didn't test `with*` methods because they return new
(cloned) instance of `$pathItem`. In assertions we test nulls from
`PathItem::_construct()` instead of from `with*` methods.
> Update OpenApi PathItem nullable operation test

- CHANGELOG.md
- src/Action/ExceptionAction.php
- src/Annotation/ApiResource.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- tests/Action/ExceptionActionTest.php
- tests/Annotation/ApiResourceTest.php
This PR allows introduces the `exception_to_status` attribute in operations and resources mapping.
The use case is when some domain exception should be transformed into a specific HTTP status on some API endpoints, but not on others.
For example: a method in some entity throws a `NotPossible` exception when called through an API endpoint. You want that endpoint to return a `400 Bad Request`. But if the same entity method throws that exception when called from unrelated internal code, maybe that's actually an error in the code and should result in a `500 Internal Server Error`.
> Allow defining exception_to_status per operation

- CHANGELOG.md
- src/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php
- tests/Bridge/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
When purging HTTP Cache Tags on Doctrine flush event, API Platform uses Doctrine mapping to determine the tags to purge. When doing so it assumes all mapped associations have a public accessor on the entity but sometimes this is not true and trying to access the value throws an exception.
I assume unreadable associations can be silently ignored as it means the associated entities don't appear in serialized responses which don't have the related tags anyway.
> Fix purging HTTP cache for unreadable relations

- CHANGELOG.md
- src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
- tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php
| Tickets       | fixes #3305
In a case if we use graphql, we have to check attribute `pagination_use_output_walkers` in graphQl operations too.
I feel that this part can be improved - we have to know the operation type - is it `Rest` or `Graphql`, because I think this is not good to check this attribute in all possible sources blindly.
> Check `pagination_use_output_walkers` attribute for graphQl operation

- features/doctrine/eager_loading.feature
- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Util/EagerLoadingTrait.php
- src/Bridge/Doctrine/Orm/Util/QueryBuilderHelper.php
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Behat/DoctrineContext.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Fixtures/TestBundle/Doctrine/Orm/EntityManager.php
- tests/Fixtures/TestBundle/Entity/RelatedDummy.php
- tests/Fixtures/TestBundle/Filter/ComplexSubQueryFilter.php
- tests/Fixtures/app/config/config_test.yml
> Fix duplicated eager loading joins

- src/JsonSchema/SchemaFactory.php
- src/JsonSchema/TypeFactory.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Model/Encoding.php
- src/OpenApi/Model/Parameter.php
- tests/JsonSchema/TypeFactoryTest.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
| Tickets       | Fix #4137 #4124
Improves performances by 60% https://blackfire.io/profiles/compare/d6d1c64b-ec39-4ac9-ac9f-630dac371da4/graph
> OpenAPI: Make sure we do not override defined parameters #4137

- CHANGELOG.md
- features/jsonapi/related-resouces-inclusion.feature
- src/JsonApi/Serializer/ItemNormalizer.php
- tests/Behat/DoctrineContext.php
| Tickets       | fixes #2365 
As specified in the JSON:API specs (https://jsonapi.org/format/#fetching-includes): In order to request resources related to other resources, a dot-separated path for each relationship name can be specified
> GET /articles/1?include=comments.author HTTP/1.1
Accept: application/vnd.api+json
> JSON:API add inclusion of resources from path

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Bug fix?      | yes-ish
| New feature?  | no-ish
This PR makes the loading of mapping resources idempotent by sorting files.
Given two mapping files for two different resources that define the following routes:
* resource FooBar (collection): `/foo/bar`
* resource Foo (item): `/foo/{id}`
Functional tests prove that both routes work as expected. Though, once the tests are executed on some CI, they randomly fail. After a long debugging session, I noticed that routes can only work if the files are loaded in the same order as above because otherwise the second route will always match (because Symfony stops matching as soon as a matching route is …
> Sort mapping resources

- src/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummySequentiallyValidatedEntity.php
| Tickets       | Fix #... 
Currently property metadata from validator constraints (length/regex etc.) is only taken when these constraints are applied directly. Since Symfony 5.1 there is Sequentially constraint which allows to validate as a group sequence but much easier. But api platform doesn't take them because they're nested inside the Sequentially constraint.
~~I have updated to include all nested constraints from the Composite, but maybe that's too wide?
Also not sure about that maybe constraint flattening should be recursive?~~
> Handle sequentially validator constraints when generating property metadata

- .github/workflows/ci.yml
- CHANGELOG.md
- features/main/content_negotiation.feature
- features/xml/deserialization.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Document/ResourceWithBoolean.php
- tests/Fixtures/TestBundle/Document/ResourceWithFloat.php
- tests/Fixtures/TestBundle/Document/ResourceWithInteger.php
- tests/Fixtures/TestBundle/Document/ResourceWithString.php
- tests/Fixtures/TestBundle/Entity/ResourceWithBoolean.php
- tests/Fixtures/TestBundle/Entity/ResourceWithFloat.php
- tests/Fixtures/TestBundle/Entity/ResourceWithInteger.php
- tests/Fixtures/TestBundle/Entity/ResourceWithString.php
- tests/Fixtures/app/config/config_mysql.yml
- tests/Serializer/AbstractItemNormalizerTest.php
| Tickets       | Fixes https://github.com/api-platform/api-platform/issues/1299
Replace https://github.com/api-platform/core/pull/3191.
> This PR fixes an issue where by posting XML content throws errors when a field has a non string primitive type because the XML encoder can only normalize primitive values as strings. This means that post create and update requests fail. This PR adds some additional behaviour where by the AbstractItemNormalizer will cast valid strings as the correct type.
This PR mirrors the Symfony equivalent: https://github.com/symfony/symfony/pull/33850.
> Fix denormalization of basic property-types in XML and CSV

- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaFormat.php
Add [Ulid](https://symfony.com/doc/current/reference/constraints/Ulid.html) management in the `PropertySchemaFormat`.
> Manage Ulid in format property schema restriction

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/Resources/config/validator.xml
- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaOneOfRestriction.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaOneOfRestrictionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyAtLeastOneOfValidatedEntity.php
Following https://github.com/api-platform/core/pull/4139.
Add `PropertySchemaOneOfRestriction` to transform the [AtLeastOneOf](https://symfony.com/doc/current/reference/constraints/AtLeastOneOf.html) validation constraint into [oneOf](https://json-schema.org/understanding-json-schema/reference/combining.html#oneof) JSON Schema restriction.
> Add oneOf property schema restriction

- .github/workflows/ci.yml
- CHANGELOG.md
- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- src/Test/DoctrineMongoDbOdmFilterTestCase.php
- src/Test/DoctrineOrmFilterTestCase.php
- tests/Bridge/Doctrine/Common/Filter/OrderFilterTestTrait.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/OrderFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
| Tickets       | Fixes #4144 Fixes #3440
| Doc PR        | Feature already documented here: Order Filter (Sorting) > [Comparing with Null Values](https://api-platform.com/docs/core/filters/#comparing-with-null-values)
**Comparing with Null Values doesn't work with embeddable.**
Thanks @vsalvans who found the issue in #3440.
I wrote a lot of PhpUnits Tests code. First, I started to test the correct behavior of OrderFilter regarding embaddables. I modified `\ApiPlatform\Core\Tests\Fixtures\TestBundle\Entity\Dummy` to add a `public $embeddedDummy;` property.
By doing this, I was able to add a new test scenario under …
> Fix order filter with embedded and nulls comparison

- src/DataProvider/ItemDataProviderInterface.php
`ItemDataProviderInterface::getItem()` `$id` argument could also be an `object`
eg: an item with an identifier of type `Ramsey\Uuid\UuidInterface`
> update phpdoc ItemDataProviderInterface::getItem()

- CHANGELOG.md
- features/xml/deserialization.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Serializer/AbstractItemNormalizerTest.php
This PR mirrors the Symfony equivalents:
- https://github.com/symfony/symfony/pull/27326
- https://github.com/symfony/symfony/pull/33733
It fixes the denormalization of XML collection with only one element.
> Correctly deserialize a collection with one element in XML

- CHANGELOG.md
- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
| Doc PR        | https://github.com/api-platform/docs/pull/1319
It adds a global configuration to change the nulls_comparisons strategy
> Add global config for nulls order comparison

- tests/Bridge/Symfony/Routing/RouterTest.php
https://github.com/api-platform/core/pull/3776 was missing a non regression unit test, like asked in https://github.com/api-platform/core/pull/3095#pullrequestreview-293846033.
> Add a test for matching with a duplicated base URL in Router

- features/doctrine/eager_loading.feature
- features/filter/property_filter.feature
- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- tests/Behat/DoctrineContext.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Fixtures/TestBundle/Document/DummyPassenger.php
- tests/Fixtures/TestBundle/Document/DummyTravel.php
- tests/Fixtures/app/config/config_common.yml
Hello,
I propose my first contribution to the project.
I found that the final SQL query was not correct in the case where an entity had several doctrinal relationships and was asked to retrieve some properties with the [PropertyFilter](https://api-platform.com/docs/core/filters/#property-filter).
Example:
```php
class Example {
public $property;
public $relation1;
public $relation2;
}
class Relation {
public $property1;
public $property2;
}
```
uri: `/api/examples?properties[relation1][]=property1&properties[relation2][]=property2`
In this case the relation1 has been added but …
> Fix joinRelations with multiple associations.

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/Resources/config/validator.xml
- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaUniqueRestriction.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaUniqueRestrictionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyUniqueValidatedEntity.php
Add a `PropertySchemaUniqueRestriction` to transform [Unique](https://symfony.com/doc/current/reference/constraints/Unique.html) validation constraint into `uniqueItems: true` JSON Schema restriction.
> Add support for generating property schema with Unique restriction

- CHANGELOG.md
- src/HttpCache/EventListener/AddHeadersListener.php
- tests/HttpCache/EventListener/AddHeadersListenerTest.php
> Fix #2928: do not override Vary headers already set in the Response

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/Resources/config/validator.xml
- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRangeRestriction.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRangeRestrictionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyRangeValidatedEntity.php
Add a `PropertySchemaRangeRestriction` to transform for integers and floats [Range](https://symfony.com/doc/current/reference/constraints/Range.html) validation constraint into `minimum`/`maximum` JSON Schema restriction.
> Add support for generating property schema with Range restriction

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/Resources/config/validator.xml
- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaChoiceRestriction.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaChoiceRestrictionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyValidatedChoiceEntity.php
Add a `PropertySchemaChoiceRestriction` to transform [Choice](https://symfony.com/doc/current/reference/constraints/Choice.html) validation constraint into these schemas:
`@Assert\Choice(choices={"choice1", "choice2"})`
```json
{
"enum": ["choice1", "choice2"]
}
```
`@Assert\Choice(choices={"choice1", "choice2"}, multiple=true)`
```json
{
"type": "array",
"items": { "enum": ["choice1", "choice2"] }
}
```
`@Assert\Choice(choices={"choice1", "choice2", "choice3", "choice4"}, multiple=true, min=2, max=4)`
```json
{
"type": "array",
"items": { "enum": ["choice1", "choice2", "choice3", "choice4"] }, …
```
> Add support for generating property schema with Choice restriction

- CHANGELOG.md
- src/GraphQl/Resolver/Stage/ReadStage.php
- tests/GraphQl/Resolver/Stage/ReadStageTest.php
Order filters are being written with underscores in GraphQL but are sent along with dots to access nested entities.
The previous solution appended the dot version to the order array. This leads to an issue where every order filter that accesses a nested property will always be added to the query after local properties.
Looking at the test case: The first order that WAS applied was `localField`. It should have been `some.field` which is now the case.
| Tickets       |  I did not create any
> Make sure the order of nested order filters is preserved

- CHANGELOG.md
- src/Annotation/ApiResource.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/validator.xml
- src/EventListener/QueryParameterValidateListener.php
- tests/Annotation/ApiResourceTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
- tests/EventListener/QueryParameterValidateListenerTest.php
| Doc PR        | https://github.com/api-platform/docs/pull/1329
Query parameter validation can be costly if you are not using any required filters, so we should have an option to disable it.
If you think that this is a good addition, I'll add some tests.
> Add an option to disable query parameter validation

- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaLengthRestriction.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
- tests/OpenApi/Serializer/OpenApiNormalizerTest.php
- tests/Swagger/Serializer/DocumentationNormalizerV3Test.php
| Tickets       | Fix https://github.com/api-platform/core/pull/3329#discussion_r604707880
> Fix PropertySchemaLengthRestriction string-only

- src/Bridge/Doctrine/MongoDbOdm/Extension/OrderExtension.php
- src/Bridge/Doctrine/Orm/Extension/OrderExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Fixtures/app/config/config_common.yml
> Revert using defaults.order as collection.order

- CHANGELOG.md
- src/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyCompoundValidatedEntity.php
- tests/Fixtures/TestBundle/Validator/Constraint/DummyCompoundRequirements.php
In #4139 I have missed that there is a new [Compound](https://symfony.com/doc/current/reference/constraints/Compound.html) constraint which helps to create reusable validations.
This adds support for Compound constraint, but only when used at the top level without nesting.
I think this factory should be refactored later to properly handle constraint nesting.
> Handle Compound validator constraints when generating property metadata

- src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
- src/Bridge/Symfony/Bundle/Resources/config/swagger-ui.xml
- src/Bridge/Symfony/Bundle/SwaggerUi/SwaggerUiAction.php
| Tickets       | Fix #1149 
`twig` is only a part of `require-dev`. But `api_platform.swagger.action.ui` and `api_platform.swagger_ui.action` are requiring it when swagger doc is enabled. As a result, theses services are requiring an unexisting service.
Here is a tiny reproducer:
```bash
$ composer create-project symfony/skeleton:^4.4 # Same goes for 5.x versions
$ cd skeleton
$ composer req api-platform/core:2.6 
[...]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!                                                                                 
!!    The service …
```
> Make twig dependency lazy

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/Resources/config/validator.xml
- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCountRestriction.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCountRestrictionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyCountValidatedEntity.php
Add a `PropertySchemaCountRestriction` to transform [Count](https://symfony.com/doc/current/reference/constraints/Count.html) validation constraint into json schema.
> Add support for generating property schema with Count restriction

- CHANGELOG.md
- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaFormat.php
- tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaFormatTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyValidatedEntity.php
- tests/Fixtures/DummyValidatedHostnameEntity.php
- tests/Fixtures/DummyValidatedUlidEntity.php
Add a `PropertySchemaUrlRestriction` to transform [Url](https://symfony.com/doc/current/reference/constraints/Url.html) validation constraint into json schema.
> Add support for generating property schema format for Url and Hostname

- phpstan.neon.dist
- src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Util/QueryBuilderHelper.php
- tests/Behat/DoctrineContext.php
- tests/Bridge/Symfony/Bundle/Test/ApiTestCaseTest.php
- tests/Bridge/Symfony/Bundle/Test/ClientTest.php
- tests/Bridge/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php
> Fix latest phpstan issues

- src/OpenApi/Factory/OpenApiFactory.php
| Tickets       | Follows https://github.com/api-platform/core/pull/3407#discussion_r609533441 and #4138
The `$links` array is passed by reference and `$schemas` is now an `\ArrayObject` (automatically passed by "handle"), so both get appended to (like `$paths`) at each call to `collectPaths()`
> Simplify refactored OpenApiFactory collectPaths()

- src/OpenApi/Model/Parameter.php
| Tickets       | Fix https://github.com/api-platform/core/pull/4138#discussion_r610613037
> Restore `Model\Parameter::canAllowEmptyValue()`

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Tickets       | Fix #...
In src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php:401 used ?? between `openapi` and `swagger` for `swagger_ui_extra_configuration`, but their value cannot be null - `[]` by default. So, `$config['swagger']['swagger_ui_extra_configuration']` can never be used.
I suggest using `array_merge` to solve this problem.
> FIX: ApiPlatform Extension extra configuration - merging arrays

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/Resources/config/validator.xml
- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestriction.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestrictionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyCollectionValidatedEntity.php
Add a `PropertySchemaCollectionRestriction` to transform [Collection](https://symfony.com/doc/current/reference/constraints/Collection.html) validation constraint into json schema.
> Add support for generating property schema with Collection restriction

- CHANGELOG.md
- features/main/uuid.feature
- src/Bridge/RamseyUuid/Serializer/UuidDenormalizer.php
- tests/Behat/DoctrineContext.php
- tests/Bridge/RamseyUuid/Identifier/Normalizer/UuidNormalizerTest.php
- tests/Bridge/RamseyUuid/Serializer/UuidDenormalizerTest.php
- tests/Fixtures/TestBundle/Entity/RamseyUuidDummy.php
> Convert internal exception in UuidDenormalizer

- CHANGELOG.md
- src/Filter/Validator/Required.php
- tests/Filter/Validator/RequiredTest.php
> Fix issue in Required filter validator with dot notation

- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
| Branch?       | 2.6 
| Tickets       |  
| Doc PR        |  
When running command `bin/console config:dump-reference api_platform`, I noticed that description of param `oauth.type` was not relevant and the same as `oauth.clientSecret.` I suspect a copy/paste issue.
This PR is just a fix about param description.
> Fix configuration description

- src/Bridge/Symfony/Bundle/Test/Client.php
| Doc PR        |  
* The doc is superfluous, so rely on the return type instead.
* This fixes Psalm `InternalMethod` error when clients call methods 
such as such as `toArray()` on `Response`, which is marked internal.
> Remove wrong return doc

- CHANGELOG.md
- features/openapi/docs.feature
- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Model/Operation.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Fixtures/TestBundle/Model/DummyAddress.php
- tests/Fixtures/TestBundle/Resources/config/api_resources/dummy_address.yml
- tests/OpenApi/Factory/OpenApiFactoryTest.php
> OpenAPI: Allow to set extensionProperties with YAML schema definition

- CHANGELOG.md
- src/OpenApi/Factory/OpenApiFactory.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
| Tickets       | Fixes #4212
Since the `$schema` object was reused, the output DTO `$ref` was not overwritten:
https://github.com/api-platform/core/blob/d62e86e9cfa2a7a4eba3029053ff65f43a10e1ce/src/JsonSchema/SchemaFactory.php#L95
> [OpenApi] Do not use output for request body

- src/HttpCache/VarnishPurger.php
- tests/HttpCache/VarnishPurgerTest.php
| Bug fix?      | depends on how you treat perf issue
The current ban regexp is not optimize and killed my varnish server to 100% cpu.
Several reasons, but let's explain how that work. This is a question of
> rq/s * ban/s * size of the cache tags header * complexity of the regexp
I've a high number of requests and bans per seconds. The response has a lot of tags.
But I only ban one resource at a time, so the regexp was not that complex at first look.
Varnish stores all ban in a (deduplicated) list. Each cached resource has a pointer to the last ban checked.
If you add bans, when you call a cached resources, it will check against all the new bans and store the …
> Optimize varnish ban regexp

- src/Bridge/Symfony/Validator/EventListener/ValidationExceptionListener.php
- src/Bridge/Symfony/Validator/Exception/ConstraintViolationListAwareExceptionInterface.php
- src/Bridge/Symfony/Validator/Exception/ValidationException.php
- tests/Bridge/Symfony/Validator/EventListener/ValidationExceptionListenerTest.php
This PR introduces a new `ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ConstraintViolationListAwareExceptionInterface` which adds the ability to have a close management of status code on validation exceptions.
> Add the ability to customize multiple status codes based on the validation exception

- CHANGELOG.md
- behat.yml.dist
- features/elasticsearch/graphql.feature
- src/Bridge/Elasticsearch/DataProvider/SubresourceDataProvider.php
- src/Bridge/Symfony/Bundle/Resources/config/elasticsearch.xml
- tests/Bridge/Elasticsearch/DataProvider/SubresourceDataProviderTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Tickets       | Fixes https://github.com/api-platform/api-platform/issues/1809  
| Doc PR        | na]
Elasticsearch doesn't work for subcollection as there are no SubresourceDataProvider. This patch adds one. 
Runs a GraphQL query like this:
```
query {
products {
collection {
id, attributes { collection { id }}
}
}
}
```
Where you have a sub-collection with Elasticsearch.
> Fix graphql fetching with Elasticsearch

- src/Test/DoctrineMongoDbOdmSetup.php
- src/Test/DoctrineMongoDbOdmTestCase.php
NB: other deprecations need a fix upstream at https://github.com/doctrine/DoctrineMongoDBBundle/blob/4.4.x/DependencyInjection/DoctrineMongoDBExtension.php#L209
> fix(MongoDB): Handle deprecated setMetadataCacheImpl

- features/elasticsearch/read.feature
- src/Bridge/Elasticsearch/DataProvider/ItemDataProvider.php
- src/Bridge/Elasticsearch/DataProvider/Paginator.php
- src/Bridge/Elasticsearch/Serializer/DocumentNormalizer.php
- src/Bridge/Elasticsearch/Serializer/ItemNormalizer.php
- src/Bridge/Symfony/Bundle/Resources/config/elasticsearch.xml
- tests/Bridge/Elasticsearch/DataProvider/ItemDataProviderTest.php
- tests/Bridge/Elasticsearch/DataProvider/PaginatorTest.php
- tests/Bridge/Elasticsearch/Serializer/DocumentNormalizerTest.php
- tests/Bridge/Elasticsearch/Serializer/ItemNormalizerTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Fixtures/Elasticsearch/Fixtures/user.json
- tests/Fixtures/Elasticsearch/Mappings/tweet.json
- tests/Fixtures/Elasticsearch/Mappings/user.json
- tests/Fixtures/Elasticsearch/Model/Tweet.php
- tests/Fixtures/Elasticsearch/Model/User.php
| Tickets       | fixes #3908  fixes #3170 
| Doc PR        | n/A
This PR:
* Reverts the priority of the Elasticsearch documents normalizer from `-890` to `-922`.
* Introduces an item normalizer decorator that prevents the default `ApiPlatform\Core\Serializer\ItemNormalizer` from taking over for the `elasticsearch` format because of priorities when the bridge is enabled.
* Renames the `ApiPlatform\Core\Bridge\Elasticsearch\Serializer\ItemNormalizer` class to `ApiPlatform\Core\Bridge\Elasticsearch\Serializer\DocumentNormalizer` so that the role of the denormalizer is more explicit: to transform Elasticsearch documents into PHP objects. …
> Fix the denormalization of \DateTime(Immutable) for ES documents

- CHANGELOG.md
- src/GraphQl/Type/FieldsBuilder.php
- tests/GraphQl/Type/FieldsBuilderTest.php
| Deprecations? |no
This fixes `FieldsBuilder` not using the recursive version of `getWrappedType`. Without this, if the type is wrapped in both `NonNull` and then `ListOfType`, then `ListOfType` is returned instead of the actual type of the list items - which I think was the original intention of this code, as it's trying to decide if the base type needs a special resolver. For example, a non-null list of non-null strings (`[String!]!`) will now correctly return `String` as the wrapped type with this fix. This means that simple arrays such as this, which are already deserialized by the Symfony deserializer and …
> [GraphQL] Fix `FieldsBuilder` not always fully unwrapping a type before deciding if a resolver is needed.

- CONTRIBUTING.md
| Bug fix?      | yes/no 
| New feature?  | yes/no 
| Tickets       | Fix #... 
> doc: use conventional commits

- phpstan.neon.dist
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/User.php
- tests/Fixtures/TestBundle/Entity/User.php
- tests/Fixtures/TestBundle/Security/AbstractSecurityUser.php
- tests/Fixtures/app/AppKernel.php
> fix: deprecated code paths on Symfony 5.3

- CHANGELOG.md
- features/openapi/docs.feature
- src/JsonSchema/SchemaFactory.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/Swagger/Serializer/DocumentationNormalizer.php
| Tickets       | Fix #4215
Follows #4213
> fix(openapi): do not use jsonld schema for all media types

- .github/workflows/ci.yml
- phpunit.xml.dist
Coverage was not sent because of the change in the PHPUnit configuration file (after https://github.com/api-platform/core/pull/4255).
> chore: fix coverage

- CHANGELOG.md
- features/graphql/mutation.feature
- src/GraphQl/Type/FieldsBuilder.php
- tests/Fixtures/TestBundle/Document/RelatedDummy.php
- tests/Fixtures/TestBundle/Entity/RelatedDummy.php
- tests/GraphQl/Type/FieldsBuilderTest.php
| Tickets       | #3492 #4183
Fixes a regression introduced in https://github.com/api-platform/core/commit/d6f2603fe80236b1c7bac2a92b49b337c8cc6973#diff-d7bf2d1671fc1d774236691a30000b7d2c1a9296094faf093c98fd549f727bd5R299-R300.
The resolver for the mutation (and the subscription) was set for nested payload properties and was wrongly called when resolving the root mutation.
This PR fixes the issue by only setting the mutation resolver for the root payload and uses the item / collection resolver for the nested payload properties.
Notice that this issue only appears when a specific normalization context is used for the mutation (different of the query one). Else the item type is used …
> fix(graphql): do not use a resolver for the nested payload of a mutation or subscription

- CHANGELOG.md
- src/Bridge/Symfony/Routing/ApiLoader.php
- tests/Bridge/Symfony/Routing/ApiLoaderTest.php
| Bug fix?      | no, yes
| New feature?  |no, yes 
| Tickets       | #There's no ticket
Hello there,
Currently, it is not possible to resolve the  default value for the `_format` parameter under a custom operation definition.
This is due to the `ApiLoader` which forces this value to `nul` no matter what value we set in the configuration.
This fix makes it possible to take into account the definition of the `defaults._format` value and have the right value under the request route params.
**Use case:**
Imagine that we have a resource that which is used to export both the data in csv and in xlsx.
resources.yaml:
```
resources:
App\Entity\Activity\Contract: …
```
> [ApiLoader] Support _format resolving

- src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/mercure.xml
- src/GraphQl/Resolver/Factory/ItemSubscriptionResolverFactory.php
- src/GraphQl/Subscription/MercureSubscriptionIriGenerator.php
- src/GraphQl/Subscription/MercureSubscriptionIriGeneratorInterface.php
- src/Mercure/EventListener/AddLinkHeaderListener.php
- tests/Bridge/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
- tests/GraphQl/Resolver/Factory/ItemSubscriptionResolverFactoryTest.php
- tests/GraphQl/Subscription/MercureSubscriptionIriGeneratorTest.php
- tests/Mercure/EventListener/AddLinkHeaderListenerTest.php
This PR is based on https://github.com/api-platform/core/pull/4142 plus:
- Fix tests
- Move deprecations to methods instead of constructor
- Introduce a `enable_async_update` option in the `mercure` attribute with `true` as a default value.
- Deprecate that `true` value in order to progressively drop the async update feature
> Upgrade to mercure-bundle:^0.3

- src/Problem/Serializer/ErrorNormalizerTrait.php
- tests/Problem/Serializer/ErrorNormalizerTest.php
| Tickets       |  https://github.com/api-platform/core/issues/4275
When using custom Exception class and custom HTTP status code, a check was missing if the http status code really exists or is an unofficial ones.
This worked in devel mode because the verbosity mode does not replace the message but failed in production.
> fix: handle unofficial http status code with custom exceptions

- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Model/PathItem.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
| Branch       | current stable (2.6)
Hello!
I'm trying to use a non standard HTTP verb in my ApiResource operations:
```
collectionOperations={
*          "test":{
*              "method": "TEST",
*              "path": "/something",
*              "controller": TesterController::class,
*          },
*      },
``` 
Everything works great, but when I want to access the Swagger UI (`/docs`), I got an error: 
```
Attempted to call an undefined method named "withTEST" of class "ApiPlatform\Core\OpenApi\Model\PathItem".
```
It seems that we don't check the HTTP verb before creating the related `PathItem` method here: 
```php
$pathItem = $pathItem->{'with' . ucfirst($method)}(new Model\Operation(
``` …
> fix(openapi): do not throw error with non standard HTTP verb

- src/Metadata/Extractor/XmlExtractor.php
- src/Metadata/Extractor/YamlExtractor.php
- src/Metadata/schema/metadata.xsd
- tests/Fixtures/FileConfigurations/resources_with_parameters.xml
- tests/Fixtures/FileConfigurations/resources_with_parameters.yml
- tests/Metadata/Extractor/ExtractorTestCase.php
- tests/Metadata/Extractor/XmlExtractorTest.php
- tests/Metadata/Extractor/YamlExtractorTest.php
Allow to use constants in XML configuration, like this:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<resources
xmlns="https://api-platform.com/schema/metadata"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://api-platform.com/schema/metadata
https://api-platform.com/schema/metadata/metadata-2.0.xsd">
<resource class="App\Entity\Book">
<attribute name="url_generation_strategy" type="constant">ApiPlatform\Core\Api\UrlGeneratorInterface::ABS_URL</attribute>
</resource>
</resources>
```
Enable again the tests for the XML / YAML configuration, disabled since a long time.
> fix(metadata): allow to use constants in XML configuration (resource attribute)

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Serializer/Mapping/Factory/ClassMetadataFactory.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
Fix MongoDB tests by resolving the proxy class in the `ClassMetadataFactory`.
Since https://github.com/doctrine/annotations/pull/412, the annotation reader needs the real class to calculate the last modification time.
When normalizing a lazy-loaded relation, metadata are loaded using the proxy object.
In order to solve the issue, the `ClassMetadataFactory` is decorated and our `ClassInfoTrait` is used to determine the real class.
> fix: resolve proxy class in class metadata factory

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
Symfony now recommends for reusable bundles this structure:
```
<your-bundle>/
├── config/
├── docs/
│   └─ index.md
├── public/
├── src/
│   ├── Controller/
│   ├── DependencyInjection/
│   └── AcmeBlogBundle.php
├── templates/
├── tests/
├── translations/
├── LICENSE
└── README.md
```
> feat(mapping): Support mapping api resources in config at root bundle level

- features/openapi/docs.feature
- src/Hydra/JsonSchema/SchemaFactory.php
- tests/Hydra/JsonSchema/SchemaFactoryTest.php
I don't know if this is intentional, but the `hydra:previous` property is not in the SchemaFactory (rendering the openapi specs incomplete).
> Add hydra:previous to the hydra view schema properties

- .github/workflows/ci.yml
- composer.json
- src/Test/DoctrineMongoDbOdmSetup.php
- src/Test/DoctrineMongoDbOdmTestCase.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
- tests/Bridge/Symfony/Bundle/Test/ApiTestCaseTest.php
- tests/Bridge/Symfony/Bundle/Test/ClientTest.php
- tests/Util/AnnotationFilterExtractorTraitTest.php
Also adds `doctrine/cache` as a dev dependency because of https://github.com/doctrine/DoctrineMongoDBBundle/issues/677.
> chore: bump Symfony next to 5.4

- src/JsonSchema/TypeFactory.php
- tests/JsonSchema/TypeFactoryTest.php
Improve file upload by detecting a binary type property in the OpenAPI documentation when the property class name is a `SplFileInfo`.
> fix(json-schema): consider SplFileInfo class as a binary type

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/argument_resolver.xml
- src/EventListener/DeserializeListener.php
- src/EventListener/ToggleableDeserializationTrait.php
- tests/Bridge/Symfony/Bundle/ArgumentResolver/NotResource.php
- tests/Bridge/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolverTest.php
- tests/Bridge/Symfony/Bundle/ArgumentResolver/ResourceImplementation.php
- tests/Bridge/Symfony/Bundle/ArgumentResolver/ResourceInterface.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| License       | -
When creating a custom controller, the argument which is passed the deserialized payload of the request must be named `$data`. This can be very frustrating, especially when you don't know this requirement and you don't understand why your controller is not working properly.
This PR introduces a controller value resolver that allows to use any argument name, as long as its type declaration matches the resource class.
> feat: add payload controller value resolver

- src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestriction.php
- tests/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestrictionTest.php
| Tickets       | #4182
Cf https://github.com/symfony/symfony/blob/v4.4.25/src/Symfony/Component/Validator/Constraints/CollectionValidator.php#L64
> fix(openapi): handle Collection allowMissingFields=true

- src/OpenApi/Model/Components.php
- src/OpenApi/Model/Paths.php
- src/OpenApi/Serializer/OpenApiNormalizer.php
- tests/OpenApi/Serializer/OpenApiNormalizerTest.php
| Tickets       | #4318
As described in issue #4318 the function recursiveClean does nest one more time and fails, if an ApiResource has a property named `paths`. Updated tests to reproduce the failing parts.
This is version 2, a more general approach, since the logic inside `\ApiPlatform\Core\OpenApi\Serializer\OpenApiNormalizer::recursiveClean` was doing two things:
1. cleaning out `extensionProperties` keys in a recursion and
2. with every recursion, trying to sort the `schemas` and `paths` properties of the OpenApi object
So why not do the sorting in the Object generation directly and fix the double nested `paths`  issue with the normalizing call itself.
Idea is taken from: [Using Callbacks to …
> Fix openapi normalization

- src/OpenApi/Model/Operation.php
This RP allows overriding request body of the documentation of an operation with null (to remove the request body), for example in a decorator:
Before:
```
public function __invoke(array $context = []): OpenApi
{
$openApi = $this->decorated->__invoke($context);
$path = '/users/register';
$pathItem = $openApi->getPaths()->getPath($path);
if (!$pathItem) {
return $openApi;
}
$operation = $pathItem->getPost();
if (!$operation) {
return $openApi;
}
$newOperation = new Operation(
$operation->getOperationId(),
$operation->getTags(),
$operation->getResponses(),
$operation->getSummary(),
$operation->getDescription(),
$operation->getExternalDocs(), …
```
> feat: OpenAPI: Allow null as parameter for Operation->withRequestBody

- src/Core/Serializer/AbstractItemNormalizer.php
- tests/Core/Serializer/AbstractItemNormalizerTest.php
The current behavior is not logic
With the following JSON:
```
{
"triggers": [
{
"type": "url",
"options": {
"url": "http://google.fr"
}
},
"priority": 0,
"description": "description"
}
```
If I put `true` in front of `triggers[0].url`, a `UnexpectedValueException` is raised. 
If I put `true` in front of `priority`, a `InvalidArgumentException` is raised. 
IMHO, the same exception should be thrown in similar situation.
> Throw UnexpectedValueException when value is not valid

- src/Core/Bridge/Symfony/Bundle/DataCollector/RequestDataCollector.php
- src/Core/Bridge/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
- tests/Core/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
- tests/Core/Bridge/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php
| Tickets       | https://github.com/api-platform/core/projects/11#card-66574186
Adds ResourceMetadataCollection compatibility in the profiler.
Displays all possible #[ApiResource()] declarations for the current Resource.
Uses the new "ApiResource" class instead of "ResourceMetadata"
> [WIP] feat: use ResourceMetadataCollection in profiler

- .gitignore
- src/Bridge/Symfony/Identifier/Normalizer/UuidNormalizer.php
- tests/Behat/DoctrineContext.php
The GitHub Actions workflow run PHP-CS-Fixer 3.1.0 now which causes a red build on new PRs. This PR normalizes the codebase and adjusts the `.gitignore` file for the new filenames used by PHP-CS-Fixer 3.
> chore: fix CS

- composer.json
- src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
- src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Common/Util/IdentifierManagerTraitTest.php
- tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php
- tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
API platform references constants from Doctrine DBAL that have been deprecated two years ago (see doctrine/dbal#3356). Those constants have been removed in DBAL 3.0. At the moment, Doctrine ORM blocks the installation of DBAL 3, but this might change soon. This PR fixes all references and should prevent API platform applications from exploding once they bump DBAL beyond 3.0.
> fix: usage of deprecated DBAL type constants

- src/Metadata/ApiProperty.php
- src/Metadata/ApiResource.php
- src/Metadata/Delete.php
- src/Metadata/Get.php
- src/Metadata/GetCollection.php
- src/Metadata/Operation.php
- src/Metadata/Patch.php
- src/Metadata/Post.php
- src/Metadata/Put.php
> fix: improve some types in the new attributes

- src/Metadata/ApiProperty.php
- src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php
Add missing deprecations on `ApiProperty`.
> fix(metadata): add missing deprecations in ApiProperty

- src/Bridge/Symfony/Bundle/Command/DebugResourceCommand.php
- src/Core/Bridge/Symfony/Bundle/Resources/config/debug.xml
- tests/Bridge/Symfony/Bundle/Command/DebugResourceCommandTest.php
- tests/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> feat(debug): add a debug resource command

- features/graphql/mutation.feature
- src/Core/Bridge/Symfony/Bundle/Resources/config/graphql.xml
- src/Core/Serializer/AbstractItemNormalizer.php
- src/GraphQl/Type/FieldsBuilder.php
- src/GraphQl/Type/FieldsBuilderInterface.php
- src/GraphQl/Type/SchemaBuilder.php
- src/GraphQl/Type/TypeBuilder.php
- src/GraphQl/Type/TypeBuilderInterface.php
- src/GraphQl/Type/TypeConverter.php
- src/GraphQl/Type/TypeConverterInterface.php
- tests/Fixtures/TestBundle/Document/RelatedDummy.php
- tests/Fixtures/TestBundle/Entity/RelatedDummy.php
- tests/Fixtures/TestBundle/GraphQl/Type/TypeConverter.php
- tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
- tests/GraphQl/Resolver/Stage/SerializeStageTest.php
- tests/GraphQl/Type/FieldsBuilderTest.php
- tests/GraphQl/Type/SchemaBuilderTest.php
- tests/GraphQl/Type/TypeBuilderTest.php
- tests/GraphQl/Type/TypeConverterTest.php
| Tickets       | #1964 #3258
This PR does two things:
- use only the new `Operation` instead of having both `operation` and `operationName`,
- use denormalization context and groups to transform the required string (IRI) for a relation in a mutation input into an object with an optional ID, in the GraphQL schema.
> feat(graphql): use denormalization groups to allow creation of relation in mutation

- CHANGELOG.md
- features/graphql/collection.feature
- features/graphql/introspection.feature
- features/graphql/mutation.feature
- features/graphql/schema.feature
- src/GraphQl/Type/TypeBuilder.php
- tests/GraphQl/Type/TypeBuilderTest.php
| Branch?       | main?
See if considered as fix or not?
Use case:
```
...
#[QueryCollection(name: 'collectionQueryCursor', resolver: MiscCollectionResolver::class)]
#[QueryCollection(name: 'collectionQueryPage', resolver: MiscCollectionResolver::class, paginationType: 'page', paginationItemsPerPage:12, paginationClientEnabled: true)]
...
```
By the way, there is still an issue about `paginationClientEnabled` that is available in the QueryCollection attribute (or even ApiResource attribute), but inactive per query (or even resource) if not enabled at default configuration level by `api_platform.defaults.pagination_client_items_per_page: true`
But to resolve this …
> fix: use different pagination types for the queries of a resource

- src/GraphQl/Action/EntrypointAction.php
- tests/Api/FilterCollectionFactoryTest.php
- tests/JsonSchema/SchemaFactoryTest.php
- tests/JsonSchema/SchemaTest.php
Fix due to a change in Symfony: https://github.com/symfony/symfony/pull/43017.
Multipart content type is now recognized as `form` and takes over the format defined by API Platform.
> fix(graphql): make sure form content type is recognized as a multipart request

- src/Bridge/Symfony/Bundle/Test/Client.php
- tests/Bridge/Symfony/Bundle/Test/ClientTest.php
| Tickets       | https://github.com/api-platform/core/issues/4352
Header `REMOTE_ADDR` is prefixed with `HTTP_` although [Symfony](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/Request.php#L805) use header without prefix
> fix(testClient): Support REMOTE_ADDR header

- src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
- src/Bridge/Symfony/Bundle/Resources/views/GraphQlPlayground/index.html.twig
- src/Bridge/Symfony/Bundle/Resources/views/Graphiql/index.html.twig
- src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
- src/GraphQl/Action/GraphQlPlaygroundAction.php
- src/GraphQl/Action/GraphiQlAction.php
| Tickets       | fixed #4469
Use the configurable asset_path for every asset, not just in SwaggerUi, also in Graphiql and GraphQlPlayground
> fix: use asset_package for all assets

- src/JsonSchema/SchemaFactory.php
- tests/JsonSchema/SchemaFactoryTest.php
| Tickets       | #4384
This fix makes sure collection key type is saved for collection properties.
Eg. this makes sure an associative array property has type 'object' instead of 'array'.
> Adding collectionKeyType JSON Schema

- CHANGELOG.md
- src/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Core/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Branch?       | current stable version branch
| Tickets       | #4464 
Description of purpose for this PR is written in following issue.
https://github.com/api-platform/core/issues/4464
> fix: Change order of mapping paths being loaded

- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Common/Filter/SearchFilterTestTrait.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
| Branch?       | main because @soyuka told me so, but ideally it should be for the current stable branch
| Tickets       | Same as api-platform/core#2049, but for SearchFilter instead of ExistsFilter
The same problem explained in api-platform/core#2049 also happens for the Doctrine SearchFilter. This PR fixes the SearchFilter, similarly to how api-platform/core#2051 fixed the ExistsFilter.
The issue can be reproduced by adding an Entity `Dummy` that has an owning one-to-one relation to another Entity `RelatedOwnedDummy`, and then adding a `SearchFilter` for that relation:
```php
/**
* @ORM\Entity
*/
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['relatedOwnedDummy'])]
class Dummy {
/**
* …
```
> fix(doctrine): handle inverse side of OneToOne association in Doctrine search filter

- tests/Core/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
| Tickets       | #4547 
| Doc PR        |  n/a
In doctrine/dbal 3.0, types constants are now defined in Doctrine\DBAL\Types\Types.php instead of Doctrine/DBAL/Types/Type.php
References:
- https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/Types/Type.php
- https://github.com/doctrine/dbal/blob/3.1.x/src/Types/Types.php
> fix(doctrine): replace Type class by Types

- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaOneOfRestriction.php
- src/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php
> fix: use `getNestedConstraints()` instead of `getNestedContraints` when available

- src/Symfony/Bundle/Resources/public/init-swagger-ui.js
| Tickets       | #4643 
| Doc PR        | n/a 
----
Considering that:
1. It is allowed to [override the UI template](https://api-platform.com/docs/core/openapi/#overriding-the-ui-template)
2. In the `init-swagger-ui.js` released script, the SwaggerUIBundle that configures the UI should be exported to be used in another script file. 
This PR appends a simple 
```
window.swaggerUI = ui;
``` 
at the end of the `window.onload` function to make this object available for another script.
With the same goal, it also exports the `data` object to avoid any other script to parse the JSON one more time -)
```
window.swaggerData = data;
```
> #4363 - [UI] export the SwaggerUIBundle object to allow extensions

- src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
- tests/Fixtures/TestBundle/Entity/DummyCar.php
- tests/Fixtures/TestBundle/Entity/DummyCarInfo.php
- tests/Util/AnnotationFilterExtractorTraitTest.php
> fix(doctrine): FilterEagerLoadingExtension breaks DQL if property name endings matches with query builder aliases

- CHANGELOG.md
- src/Symfony/Bundle/Test/Client.php
- tests/Symfony/Bundle/Test/ClientTest.php
Adds a helper method to log a user in the tests:
```php
use ApiPlatform\Symfony\Bundle\Test\ApiTestCase;
class MyTest extends ApiTestCase
{
public function testLoginUser(): void
{
$client = self::createClient();
$client->loginUser(
self::getContainer()->get('my_user_repoistory')->findByUsername('kevin')
);
$client->request('GET', '/secured_dummies');
$this->assertResponseIsSuccessful();
}
}
```
> feat(test): add Client::loginUser()

- src/Core/Upgrade/UpgradeApiSubresourceVisitor.php
- tests/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommandTest.php
Use `Link` to declare uriVariables instead of an array.
> fix(upgrade): use Link for uri variables definition

- src/Doctrine/Common/State/Processor.php
- src/State/ChainProcessor.php
- src/State/ProcessorInterface.php
- src/Symfony/Bundle/Processor/TraceableChainProcessor.php
- src/Symfony/Messenger/Processor.php
- tests/Symfony/Messenger/ProcessorTest.php
We'll add it back in another interface if necessary, in the meantime the same behavior can be achieved using decoration and it'll be documented like this.
> fix(processor): remove resumable from the main interface

- features/openapi/docs.feature
- src/Hydra/JsonSchema/SchemaFactory.php
| Tickets       | #4354 #4394 #4667
Hi,
I went ahead and checked what's the reason for this issue.
I can confirm that this is a Redoc issue that when property contains format `"iri-reference"`
<details>
<summary>hydra:view propery</summary>
```javascript
{
"hydra:view": {
"type": "object",
"properties": {
"@id": {
"type": "string",
"format": "iri-reference"
},
"@type": {
"type": "string"
},
"hydra:first": {
"type": "string",
"format": "iri-reference"
},
"hydra:last": {
"type": "string",
"format": "iri-reference"
},
"hydra:previous": {
"type": "string",
"format": "iri-reference"
},
"hydra:next": {
"type": "string",
"format": "iri-reference"
}
}
}
}
```
</details> …
> fix: hydra:view example values

- src/Core/Bridge/Elasticsearch/DataProvider/Filter/AbstractFilter.php
- src/Core/Bridge/Elasticsearch/DataProvider/Filter/AbstractSearchFilter.php
- src/Core/Bridge/Elasticsearch/DataProvider/Filter/MatchFilter.php
- src/Core/Bridge/Elasticsearch/DataProvider/Filter/OrderFilter.php
- src/Core/Bridge/Elasticsearch/DataProvider/Filter/TermFilter.php
- src/Elasticsearch/Filter/AbstractFilter.php
- src/Elasticsearch/Filter/AbstractSearchFilter.php
- src/Elasticsearch/Filter/MatchFilter.php
- src/Elasticsearch/Filter/OrderFilter.php
- src/Elasticsearch/Filter/TermFilter.php
- src/deprecated_interfaces.php
- src/deprecation.php
https://github.com/api-platform/core/issues/4613#issuecomment-1094220949
> fix(elasticsearch): filter autowiring needs typings

- src/JsonSchema/TypeFactory.php
- tests/JsonSchema/TypeFactoryTest.php
| Tickets       | fix #4621 
Fixing a bug that prevents the `ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestAssertionsTrait::assertMatchesResourceItemJsonSchema()` method from validating against JSON-Schema correctly for some nullable properties.
> fix: ensure OpenAPI-specific implementation for nullable types does not influence the other ones

- src/Core/Bridge/Elasticsearch/DataProvider/CollectionDataProvider.php
- src/Core/Bridge/Elasticsearch/DataProvider/ItemDataProvider.php
- src/Elasticsearch/State/CollectionProvider.php
- src/Elasticsearch/State/ItemProvider.php
- src/Elasticsearch/Util/ElasticsearchVersion.php
- tests/Core/Bridge/Elasticsearch/DataProvider/CollectionDataProviderTest.php
- tests/Core/Bridge/Elasticsearch/DataProvider/ItemDataProviderTest.php
- tests/Elasticsearch/State/CollectionProviderTest.php
- tests/Elasticsearch/State/ItemProviderTest.php
- tests/Elasticsearch/Util/ElasticsearchVersionTest.php
| Tickets       | https://github.com/api-platform/core/issues/4628
supersedes https://github.com/api-platform/core/pull/4720
I propose to remove the mapping `type` from the search for certain ES versions, as is deprecated in ES 7 and removed in ES 8 (see [issue](https://github.com/api-platform/core/issues/4628)).
The `type` can still be passed in ES 7 but serves [no purpose](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html#_schedule_for_removal_of_mapping_types) anymore. Thats why the `type` will only be passed on ES 6 and lower so deprecations are not triggered.
> fix(elasticsearch): verify whether mapping type is supported

- src/Core/EventListener/WriteListener.php
- src/Core/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php
- src/Core/Operation/Factory/SubresourceOperationFactory.php
- src/Symfony/Bundle/Resources/config/v3/backward_compatibility.xml
- tests/Core/Bridge/Symfony/Routing/ApiLoaderTest.php
- tests/Core/Metadata/Property/Factory/AnnotationPropertyMetadataFactoryTest.php
- tests/Core/Operation/Factory/SubresourceOperationFactoryTest.php
Also triggers a deprecation only when the legacy resource is found. 
TODO:
> chore(deprecation): missing bc flag parameter

- CHANGELOG.md
- src/JsonLd/ContextBuilder.php
- src/Metadata/ApiProperty.php
- src/Metadata/Extractor/schema/properties.xsd
- src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php
- src/Serializer/AbstractItemNormalizer.php
- tests/Hydra/Serializer/DocumentationNormalizerTest.php
- tests/JsonLd/ContextBuilderTest.php
- tests/Metadata/Extractor/Adapter/XmlPropertyAdapter.php
- tests/Metadata/Extractor/PropertyMetadataCompatibilityTest.php
Implements https://www.w3.org/TR/rdf11-concepts/Overview.html#section-skolemization instead of the previous blank nodes. 
This patch also gives the ability to disable such `@id` using something like:
```
#[ApiProperty(
types: ['http://schema.org/MonetaryAmount'],
iri: false
)]
public MonetaryAmount $totalPrice;
```
> fix(json-ld): use a Skolem IRI instead of blank nodes

- .github/workflows/ci.yml
- src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
- src/Symfony/Bundle/Resources/config/legacy/upgrade.xml
- tests/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommandTest.php
Follows https://github.com/api-platform/core/pull/4738 and tight to https://github.com/api-platform/core/issues/4613#issuecomment-1112189704
> fix(symfony): optional doctrine/annotation for upgrade command

- features/graphql/mutation.feature
- features/graphql/query.feature
- src/Core/GraphQl/Type/TypeBuilder.php
- src/GraphQl/Type/TypeBuilder.php
- tests/Fixtures/TestBundle/DataTransformer/DummyCustomMutationDtoDataTransformer.php
- tests/Fixtures/TestBundle/DataTransformer/DummyCustomQueryDtoDataTransformer.php
- tests/Fixtures/TestBundle/Document/DummyCustomMutation.php
- tests/Fixtures/TestBundle/Document/DummyCustomQuery.php
- tests/Fixtures/TestBundle/Entity/DummyCustomMutation.php
- tests/Fixtures/TestBundle/Entity/DummyCustomQuery.php
- tests/Fixtures/app/config/config_common.yml
- tests/GraphQl/Type/TypeBuilderTest.php
| Tickets       | Fixes #3155, fixes #3647
| Doc PR        | Explicit the need to have a DataTransformer and not do it in the resolver
> fix(graphql): output creates its own type in TypeBuilder

- src/Metadata/Property/Factory/LegacyPropertyMetadataFactory.php
https://github.com/api-platform/core/issues/4613#issuecomment-1130306564
> fix(metadata): property override when value is set

- .php-cs-fixer.dist.php
- phpstan.neon.dist
- src/Symfony/Bundle/Resources/config/maker.xml
- src/Symfony/Maker/MakeStateProcessor.php
- src/Symfony/Maker/MakeStateProvider.php
- src/Symfony/Maker/Resources/help/MakeStateProcessor.txt
- src/Symfony/Maker/Resources/help/MakeStateProvider.txt
- src/Symfony/Maker/Resources/skeleton/StateProcessor.tpl.php
- src/Symfony/Maker/Resources/skeleton/StateProvider.tpl.php
- tests/Fixtures/Symfony/Maker/CustomStateProcessor.php
- tests/Fixtures/Symfony/Maker/CustomStateProviderPhp7.php
- tests/Fixtures/Symfony/Maker/CustomStateProviderPhp8.php
- tests/Symfony/Maker/MakeStateProcessorTest.php
- tests/Symfony/Maker/MakeStateProviderTest.php
| Tickets       | #4414
Here is a maker command to generate a `State\Processor` and a `State\Provider`
It was heavily inspired by existing makers
> feat: add Maker command for state processor and provider

- src/GraphQl/Serializer/ItemNormalizer.php
- src/Hal/Serializer/ItemNormalizer.php
- src/JsonApi/Serializer/ItemNormalizer.php
- src/JsonLd/Serializer/ItemNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
API Platform 3.0 supports Symfony 4.4 (LTS)
Error:
> PHP Fatal error:  Declaration of ApiPlatform\Serializer\AbstractItemNormalizer::supportsDenormalization($data, string $type, $format = null, array $context = []): bool must be compatible with Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer::supportsDenormalization($data, $type, $format = null) in /home/runner/work/CoopTilleulsForgotPasswordBundle/CoopTilleulsForgotPasswordBundle/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php on line 171
> Fix Symfony 4.4.* compatibility

- src/Bridge/Symfony/Bundle/Command/GraphQlExportCommand.php
- src/Bridge/Symfony/Bundle/Command/OpenApiCommand.php
- src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
- src/JsonSchema/Command/JsonSchemaGenerateCommand.php
`Command::setDescription()` method calls can also be removed once Symfony 6.1+ is required
> chore: better BC/FC layer for deprecated `Command::$defaultName`

- src/Bridge/Doctrine/MongoDbOdm/PropertyHelperTrait.php
- src/Bridge/Elasticsearch/DataProvider/Filter/AbstractSearchFilter.php
- src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
- src/Bridge/Symfony/Messenger/DataTransformer.php
- src/Bridge/Symfony/Validator/EventListener/ValidationExceptionListener.php
- src/EventListener/AddFormatListener.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Annotation/ApiFilterTest.php
- tests/Bridge/Symfony/Validator/Exception/ValidationExceptionTest.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/EventListener/RespondListenerTest.php
- tests/Metadata/Property/Factory/ExtractorPropertyMetadataFactoryTest.php
- tests/Operation/Factory/SubresourceOperationFactoryTest.php
Follows up https://github.com/api-platform/core/pull/4889.
> fix: swagger command name

- src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
Fixes: 
>  * 1x: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "ApiPlatform\Core\Bridge\Symfony\Bundle\Command\UpgradeApiResourceCommand" class instead.
> fix: deprecated `UpgradeApiResourceCommand::$defaultName`

- features/main/exception_to_status.feature
- src/Action/ExceptionAction.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/Resources/config/api.xml
- src/Symfony/Bundle/Resources/config/legacy/api.xml
- src/Symfony/Bundle/Resources/config/symfony.xml
- src/Symfony/EventListener/ErrorListener.php
- src/Symfony/EventListener/ExceptionListener.php
- src/Symfony/Routing/ApiLoader.php
- src/Test/DoctrineMongoDbOdmTestCase.php
- tests/Core/Bridge/Symfony/Routing/ApiLoaderTest.php
- tests/Fixtures/TestBundle/Entity/DummyExceptionToStatus.php
- tests/Fixtures/TestBundle/Exception/NotFoundException.php
- tests/Fixtures/TestBundle/State/DummyExceptionToStatusProvider.php
- tests/Fixtures/app/config/config_common.yml
- tests/Symfony/EventListener/ExceptionListenerTest.php
| Tickets       | #4848 
I open this PR to discuss about the possible solution to fix the `exceptionToStatus` feature inside ApiResource attribute and operation
Because of [Symfony ErrorListener](https://github.com/symfony/symfony/blob/f42339552cdeee8aa1e6286c2c97dff1cca3032e/src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php#L166) the request is duplicated without all the attributes needed to fetch the exception to status mapping.
A possible solution (the one I choose) could be to extend this listener to override the `duplicateRequest` method to also duplicate the attributes needed to get the exception to status mapping but I'm not realy satisfied with this solution so I'm really open to suggestions
>  Fix exceptionToStatus in ApiResource and Operation

- CHANGELOG.md
- src/Symfony/Security/ResourceAccessChecker.php
- tests/Symfony/Security/ResourceAccessCheckerTest.php
Just syncing with symfony/security: https://github.com/symfony/symfony/pull/41965.
This argument is useless with the not-so-new authenticator system, and it must be `false` everywhere in Symfony 6.
The plan is to do the same in 3.0: deprecate the parameter entirely and throw if it's passed as `true`, then remove it in 4.0.
The impact of this deprecation is likely to be small since very few or nobody should be extending this class anyway.
> feat(symfony): Deprecate the `$exceptionOnNoToken` parameter in  `ResourceAccessChecker::__construct()`

- CHANGELOG.md
- src/Symfony/Security/ResourceAccessChecker.php
| Doc PR        | nothing to do
Follows #4900
> Remove deprecated `$exceptionOnNoToken` parameter in `ResourceAccessChecker`

- src/Serializer/JsonEncoder.php
- tests/Serializer/JsonEncoderTest.php
Co-Authored-By: AntonioCS <1086401+antoniocs@users.noreply.github.com>
| Tickets       | #4416 
This is a follow-up for #4416 with the added test.
Test for PHP 7.1 failing because of:
```
JSON_INVALID_UTF8_IGNORE (int)
Ignore invalid UTF-8 characters. Available as of PHP 7.2.0.
```
> fix: json encoder invalid utf8 characters

- src/Metadata/ApiProperty.php
| Tickets       | #4911 
In `ApiProperty` the `$example` is currently set to `string|null`, however, as discussed in #4911 the actual type can be mixed because OAI supports arrays, objects, etc. as an example. This is already allowed in `openapiContext.example` but this top level property does not allow it in docblock only. This causes an issue with psalm because it detects this inconsistency.
> fix: #4911 make ApiProperty::$example `mixed` instead of `string|null`

- composer.json
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Serializer/ItemNormalizer.php
| Tickets       | #4924
---
BTW, it'll also speed normalization, since the cache will be re-used!
> [Serializer] Do not use the 'uri' while computing the cache key

- CHANGELOG.md
- features/main/sub_resource.feature
- src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/LinkFactory.php
- src/Metadata/Resource/Factory/PropertyLinkFactoryInterface.php
- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
- src/State/CreateProvider.php
- src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
- src/Symfony/Bundle/Resources/config/doctrine_orm.xml
- src/Symfony/Bundle/Resources/config/elasticsearch.xml
- src/Symfony/Bundle/Resources/config/state.xml
- tests/Fixtures/TestBundle/Entity/Company.php
- tests/Fixtures/TestBundle/Entity/SubresourceEmployee.php
- tests/Fixtures/TestBundle/Entity/SubresourceOrganization.php
- tests/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactoryTest.php
- tests/Metadata/Resource/Factory/LinkFactoryTest.php
- tests/State/CreateProviderTest.php
> feat(metadata): CRUD on subresource

- src/Symfony/Bundle/Resources/config/state.xml
hi,
Similar to <https://github.com/api-platform/api-platform/issues/1265>  
Getting:
``` 
bin/console cache:clear
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!                                                                                 
!!    The service "ApiPlatform\State\CreateProvider" has a dependency on a non-ex  
!!    istent service "api_platform.state.item_provider".                           
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd …
```
> ignore api_platform.state.item_provider when Doctrine is not enabled

- src/Core/Upgrade/UpgradeApiFilterVisitor.php
| Tickets       | #4966
Sorry for the noise.
The `api:upgrade-resource` command is only leaving the last `ApiFilter` attribute of each resource. I did not dig into `nikic/php-parser`but adding an `ApiFilter` removes the previous one.
> fix(symfony): upgrade command removes filters

- src/Metadata/Resource/Factory/NotExposedOperationResourceMetadataCollectionFactory.php
- tests/Fixtures/TestBundle/Metadata/Get.php
- tests/Metadata/Resource/Factory/NotExposedOperationResourceMetadataCollectionFactoryTest.php
> [Metadata] Do not auto-generate NotExposed operation when using custom operation classes

- features/main/exception_to_status.feature
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/Resources/config/api.xml
- src/Symfony/Bundle/Resources/config/symfony/events.xml
- src/Symfony/EventListener/ErrorListener.php
- src/Symfony/EventListener/ExceptionListener.php
- tests/Fixtures/TestBundle/Entity/DummyExceptionToStatus.php
- tests/Fixtures/TestBundle/Exception/NotFoundException.php
- tests/Fixtures/TestBundle/State/DummyExceptionToStatusProvider.php
- tests/Fixtures/app/config/config_common.yml
- tests/Symfony/EventListener/ExceptionListenerTest.php
https://github.com/api-platform/core/pull/4861#issuecomment-1250749050
> fix(symfony): exception_status bad merge

- src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
BC layer for symfony/console <= 5.3 is broken
When running `php bin/console` on a project with `symfony/console` lower than `5.3`, it throws this error :
```
Undefined constant Symfony\Component\Console\Input\InputOption::VALUE_NEGATABLE 
```
> fix(symfony): BC layer broken for symfony/console lower than 5.3

- composer.json
I noticed some errors in the tests of NelmioApiDocBundle after upgrading to 2.7: https://github.com/nelmio/NelmioApiDocBundle/actions/runs/3123031427/jobs/5065374592.
It seems the dependency on symfony/deprecation-contracts is missing.
> Missing dependency on symfony/deprecation-contracts

- src/GraphQl/Resolver/Stage/ReadStage.php
- src/GraphQl/Resolver/Stage/ReadStageInterface.php
- src/GraphQl/Resolver/Stage/SerializeStage.php
- src/GraphQl/Resolver/Stage/SerializeStageInterface.php
- src/State/CallableProvider.php
- src/State/ProviderInterface.php
- src/Symfony/Maker/Resources/skeleton/StateProvider.tpl.php
- tests/Fixtures/Symfony/Maker/CustomStateProvider.php
- tests/Fixtures/TestBundle/State/CustomOutputDtoProvider.php
- tests/Fixtures/TestBundle/State/DummyExceptionToStatusProvider.php
- tests/Fixtures/TestBundle/State/FakeProvider.php
- tests/GraphQl/Resolver/Stage/ReadStageTest.php
- tests/GraphQl/Resolver/Stage/SerializeStageTest.php
Prevents this error:
> Compile Error: Type Traversable|object|array|null contains both object and a class type, which is redundant
Related to https://github.com/php/php-src/issues/9556.
Please note that as described in this issue, this change isn't a BC break and doesn't break existing code even on PHP 8.1.
> fix: compatibility with PHP 8.2

- src/Metadata/ApiProperty.php
- src/Metadata/ApiResource.php
Makes the constructor consistent with `withTypes()`.
> fix(metadata): fix missing `array` cast for RDF types in `ApiResource` & `ApiProperty` constructors

- features/serializer/empty_array_as_object.feature
- src/Hydra/Serializer/CollectionNormalizer.php
- src/Serializer/AbstractCollectionNormalizer.php
- tests/Fixtures/TestBundle/Model/EmptyArrayAsObject.php
- tests/Fixtures/TestBundle/State/EmptyArrayAsObjectProvider.php
- tests/Fixtures/app/config/config_common.yml
- tests/Hal/Serializer/CollectionNormalizerTest.php
- tests/Hydra/Serializer/CollectionNormalizerTest.php
- tests/JsonApi/Serializer/CollectionNormalizerTest.php
Supersedes https://github.com/api-platform/core/pull/4363.
Fixes an issue with the use of `EMPTY_ARRAY_AS_OBJECT` and `PRESERVE_EMPTY_OBJECTS` in the serialization context.
Since the CollectionNormalizer was taking over the serialization of all iterables, the Symfony serializer was not called when normalizing a "raw" collection.
Adding a better supports method fixes the issue.
The supports method is not cacheable anymore since it relies on the context.
> fix: support empty array as object

- src/Core/Bridge/Doctrine/Orm/Util/QueryChecker.php
- src/Doctrine/Orm/Util/QueryChecker.php
- tests/Doctrine/Orm/Util/QueryCheckerTest.php
fixes #4936
| Branch?       | 2.7 - current stable version branch for bug fixes
| Tickets       | #4936
Here is a PR with the changes proposed in the corresponding issue.
From my understanding there is already a way to define this option on per operation basis, but setting that option would result in always using the output walkers, even if they are not needed.
I've described the changes in the issue already, if needed we may discuss here.
I'm submitting this as a bugfix, even though the behavior seems intended, because this change should fix potentially unexpected errors and should not break anything existing.
> Use output walkers when ordering by non-fetched relation

- src/Symfony/EventListener/ErrorListener.php
Forgotten while merging #4861 up. References in ApiLoader tests have been properly removed already
> fix(symfony): remove `_api_exception_to_status` leftovers

- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/Resources/config/state.xml
| Tickets       | #4975
Hi!
Cache seems broken in 3.0.0. Metadatas are not stored in the filesystem nor in APCu, resulting in poor performances (see https://github.com/api-platform/core/issues/4975#issuecomment-1251668523).
Cache services are provided by each metadata XML file located in `src/Symfony/Bundle/Resources/config/`.
- `api_platform.cache.metadata.property` => `metadata/property.xml`
- `api_platform.cache.metadata.resource` => `metadata/resource_name.xml`
- `api_platform.cache.metadata.resource_collection` => `metadata/resource.xml`
- `api_platform.cache.route_name_resolver` => `metadata/api.xml`
- `api_platform.cache.identifiers_extractor` => seems unused
- …
> fix(symfony): metadata cache is broken in dev/prod

- src/Doctrine/Odm/Metadata/Resource/DoctrineMongoDbOdmResourceCollectionMetadataFactory.php
- src/Doctrine/Orm/Metadata/Resource/DoctrineOrmResourceCollectionMetadataFactory.php
- src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
- src/Symfony/Bundle/Resources/config/doctrine_orm.xml
- src/Symfony/Bundle/Resources/config/v3/doctrine_odm.xml
- src/Symfony/Bundle/Resources/config/v3/doctrine_orm.xml
- tests/Doctrine/Odm/Metadata/Resource/DoctrineMongoDbOdmResourceCollectionMetadataFactoryTest.php
- tests/Doctrine/Orm/Metadata/Resource/DoctrineOrmResourceCollectionMetadataFactoryTest.php
> fix(doctrine): ability to use ORM and ODM

- src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
- src/Symfony/Bundle/Command/DebugResourceCommand.php
- src/Symfony/Bundle/Command/GraphQlExportCommand.php
- src/Symfony/Bundle/Command/OpenApiCommand.php
…ALID)
Command constant are only available since Symfony 5.1 (for SUCCESS and FAILURE) and 5.3 (for INVALID).
> fix(symfony): Command constants not available for symfony <5.1

- features/jsonld/non_resource.feature
- src/Hydra/Serializer/CollectionNormalizer.php
- src/JsonLd/ContextBuilder.php
- src/JsonLd/Serializer/ItemNormalizer.php
- src/JsonLd/Serializer/JsonLdContextTrait.php
- src/Metadata/ApiProperty.php
- src/Metadata/Extractor/XmlPropertyExtractor.php
- src/Metadata/Extractor/YamlPropertyExtractor.php
- src/Metadata/Extractor/schema/properties.xsd
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Model/GenId.php
- tests/Fixtures/TestBundle/Model/MonetaryAmount.php
- tests/Hydra/Serializer/CollectionNormalizerTest.php
- tests/Metadata/Extractor/Adapter/XmlPropertyAdapter.php
- tests/Metadata/Extractor/PropertyMetadataCompatibilityTest.php
| Branch?       | bug fix (bc break)
| Tickets       | #5035
On 3.0 this behavior will be the default one, I'll add it only in 3.0 so that one can disable the skolemIri generation. We break the compatibility here, so let's revert for 2.7.
> fix(metadata): no skolem iri by default

- CHANGELOG.md
- src/GraphQl/Action/EntrypointAction.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/Resources/config/graphql.xml
- tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Branch?       | 3.0 
| Tickets       | https://github.com/api-platform/core/issues/4897 
Instead of having an error thrown by the CheckExceptionOnInvalidReferenceBehaviorPass when Twig is not installed or enabled we send a clearer exception and force the user to either disable the GraphQL clients or enable Twig.
If the clients are not enabled we remove the definition as they can't be instantiate and we pass null to the GraphQl action.
Maybe we should not trowing an exception and instead disable silently the the clients if Twig is not enabled but I find better to add an explicit error message.
> [GraphQL] Add a clearer error message when TwigBundle is disable but graphql clients aren't

- src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php
- tests/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolverTest.php
| Tickets       | [#5066](https://github.com/api-platform/core/issues/5066)
<!--
Replace this notice by a short README for your feature/bugfix. This will help people
understand your PR and can be used as a start for the documentation.
Branch: 
- 2.7
> fix(metadata): add class key in payload argument resolver

- src/Doctrine/Orm/Filter/SearchFilter.php
- tests/Doctrine/Common/Filter/SearchFilterTestTrait.php
- tests/Doctrine/Odm/Filter/SearchFilterTest.php
- tests/Doctrine/Orm/Filter/SearchFilterTest.php
When using a search filter with multiple values that have the same lowercase identity, for example:
```
array:2 [▼
0 => "rayon bleu"
1 => "Rayon Bleu"
]
```
SearchFilter will lowercase the value and use it as index key, which makes it send only one parameter to Doctrine when it needs two of them.
I choosed to leave the arbitrary array index so we don't have this kind of issues anymore.
> [Doctrine] SearchFilter - Use abitrary index instead of value

- src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php
- tests/Fixtures/TestBundle/Entity/AttributeOnlyOperation.php
- tests/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactoryTest.php
> fix(metadata): define a name on a single operation

- features/graphql/collection.feature
- features/main/default_order.feature
- src/GraphQl/Type/FieldsBuilder.php
- src/GraphQl/Type/TypeBuilder.php
- src/GraphQl/Type/TypeBuilderInterface.php
- src/Metadata/Extractor/DynamicResourceExtractor.php
- src/Metadata/Extractor/DynamicResourceExtractorInterface.php
- src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/ExtractorResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/FiltersResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/PhpDocResourceMetadataCollectionFactory.php
- src/Metadata/Resource/ResourceMetadataCollection.php
- src/Symfony/Bundle/Resources/config/graphql.xml
- src/Symfony/Bundle/Resources/config/metadata/resource.xml
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/FooDummy.php
- tests/Fixtures/TestBundle/Entity/FooDummy.php
- tests/Fixtures/TestBundle/Entity/SoMany.php
- tests/GraphQl/Type/FieldsBuilderTest.php
- tests/GraphQl/Type/TypeBuilderTest.php
- tests/Metadata/Extractor/DynamicResourceExtractorTest.php
- tests/Metadata/Extractor/ResourceMetadataCompatibilityTest.php
- tests/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactoryTest.php
- tests/Metadata/Resource/Factory/PhpDocResourceMetadataCollectionFactoryTest.php
- tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
See https://github.com/api-platform/core/issues/4613#issuecomment-1210634143.
Supersedes https://github.com/api-platform/core/pull/4930.
Fixes https://github.com/api-platform/api-platform/issues/2296.
The principal issue was mainly because the root operation was used instead of the nested resource one.
This PR also improves how GraphQL handles a nested resource when the query operation does not exist.
Instead of having a fallback on the REST operation (and an exception if it does not exist), it creates a "dynamic" resource having the default operations.
This dynamic resource is created using a new `DynamicExtractor` with an `addResource` method, which can take an optional configuration array.
In the future, I think this could be useful to control how a nested resource is handled by …
> fix(graphql): use right nested operation

- src/deprecation.php
| Tickets       | https://github.com/api-platform/api-platform/issues/2284
When using `opcache.preload` we get the following warnings:
```
PHP message: PHP Warning:  Cannot declare interface ApiPlatform\Core\Api\FilterInterface, because the name is already in use in /var/www/app.10xerp.com/website/vendor/api-platform/core/src/deprecation.php on line 15
PHP message: PHP Warning:  Cannot declare interface ApiPlatform\Core\Api\ResourceClassResolverInterface, because the name is already in use in /var/www/app.10xerp.com/website/vendor/api-platform/core/src/deprecation.php on line 16
```
The solution was to check if the interfaces already exist.
> fix: call class_alias only if interface doesn't exist

- features/graphql/collection.feature
- features/main/default_order.feature
- src/GraphQl/Metadata/Factory/GraphQlNestedOperationResourceMetadataFactory.php
- src/GraphQl/Type/FieldsBuilder.php
- src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/ExtractorResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/FiltersResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/OperationDefaultsTrait.php
- src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
- src/Symfony/Bundle/Resources/config/doctrine_orm.xml
- src/Symfony/Bundle/Resources/config/graphql.xml
- src/Symfony/Bundle/Resources/config/metadata/resource.xml
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/FooDummy.php
- tests/Fixtures/TestBundle/Entity/FooDummy.php
- tests/Fixtures/TestBundle/Entity/RelatedDummy.php
- tests/Fixtures/TestBundle/Entity/SoMany.php
- tests/GraphQl/Metadata/Factory/GraphQlNestedOperationResourceMetadataFactoryTest.php
- tests/GraphQl/Type/FieldsBuilderTest.php
- tests/GraphQl/Type/TypeBuilderTest.php
- tests/Metadata/Extractor/ResourceMetadataCompatibilityTest.php
- tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
Rework of https://github.com/api-platform/core/pull/5102
> fix(graphql): always allow to query nested resources

- features/openapi/docs.feature
- phpstan.neon.dist
- src/Doctrine/Odm/PropertyInfo/DoctrineExtractor.php
- src/JsonSchema/SchemaFactory.php
- src/JsonSchema/TypeFactory.php
- tests/Behat/OpenApiContext.php
- tests/Doctrine/Odm/PropertyInfo/DoctrineExtractorTest.php
- tests/Doctrine/Odm/PropertyInfo/Fixtures/DoctrineEnum.php
- tests/Doctrine/Odm/PropertyInfo/Fixtures/EnumInt.php
- tests/Doctrine/Odm/PropertyInfo/Fixtures/EnumString.php
- tests/Fixtures/TestBundle/Document/Person.php
- tests/Fixtures/TestBundle/Entity/Person.php
- tests/Fixtures/TestBundle/Enum/GenderTypeEnum.php
- tests/JsonSchema/SchemaFactoryTest.php
- tests/JsonSchema/TypeFactoryTest.php
Supersedes https://github.com/api-platform/core/pull/4857.
Partially fixes https://github.com/api-platform/core/issues/2254.
> feat(openapi): add backed enum support

- src/GraphQl/Metadata/Factory/GraphQlNestedOperationResourceMetadataFactory.php
- src/GraphQl/Type/FieldsBuilder.php
- tests/GraphQl/Metadata/Factory/GraphQlNestedOperationResourceMetadataFactoryTest.php
- tests/GraphQl/Type/FieldsBuilderTest.php
Continuing https://github.com/api-platform/core/pull/5112.
See https://github.com/api-platform/core/pull/5112#discussion_r1014898804.
We use the metadata instead of relying on the attributes to handle all cases (XML, YAML...).
> fix(graphql): add filters from the nested resource metadata

- src/Api/IdentifiersExtractor.php
- src/Hydra/Serializer/CollectionFiltersNormalizer.php
- src/Hydra/Serializer/CollectionNormalizer.php
- src/Hydra/Serializer/PartialCollectionViewNormalizer.php
- src/Metadata/Resource/ResourceMetadataCollection.php
- src/Serializer/AbstractCollectionNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
- src/Symfony/Routing/IriConverter.php
- tests/Api/IdentifiersExtractorTest.php
- tests/Hal/Serializer/CollectionNormalizerTest.php
- tests/Hydra/Serializer/CollectionNormalizerTest.php
- tests/JsonApi/Serializer/CollectionNormalizerTest.php
reverts #4999 and re-implement it
> fix(serializer): empty object as array with supports cache 

- src/Api/QueryParameterValidator/Validator/ArrayItems.php
- src/Api/QueryParameterValidator/Validator/Bounds.php
- src/Api/QueryParameterValidator/Validator/CheckFilterDeprecationsTrait.php
- src/Api/QueryParameterValidator/Validator/Enum.php
- src/Api/QueryParameterValidator/Validator/Length.php
- src/Api/QueryParameterValidator/Validator/MultipleOf.php
- src/Api/QueryParameterValidator/Validator/Pattern.php
- src/Api/QueryParameterValidator/Validator/Required.php
- tests/Api/QueryParameterValidator/Validator/ArrayItemsTest.php
- tests/Api/QueryParameterValidator/Validator/BoundsTest.php
- tests/Api/QueryParameterValidator/Validator/EnumTest.php
- tests/Api/QueryParameterValidator/Validator/LengthTest.php
- tests/Api/QueryParameterValidator/Validator/MultipleOfTest.php
- tests/Api/QueryParameterValidator/Validator/PatternTest.php
- tests/Api/QueryParameterValidator/Validator/RequiredTest.php
The filter validators were only using the 'swagger' entry from the filter description. It should also use the 'openapi' entry, as swagger is deprecated.
| Tickets       | NA
| Doc PR        | NA
The filter validators were only using the 'swagger' entry from the
filter description. It should also use the 'openapi' entry, as swagger
is deprecated.
> feat: use openapi array to validate filter parameters

- features/authorization/deny.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/SecuredDummyWithPropertiesDependingOnThemselves.php
| Branch?      | 3.0
| Tickets       | #5054 
Support for `security_post_denormalize` was added in https://github.com/api-platform/core/pull/4184.
At that moment, the clone to populate previousObject was made before denormalization. It worked well.
This [commit](https://github.com/api-platform/core/commit/87b61505d2f719fcf0d8613414d9e6aa436fd61f#diff-d87efa25fbf52904daa06047002652f08645e3ad4a7f4985ffeec5a7c8e39c4f) moved the clone after denormalization.
After upgrading to 3.0, using `security_post_denormalize` on a an `ApiProperty` was not working anymore. Moving the `$previousObject` line to its first position fixed the issue on my project.
I believe [this issue](https://github.com/api-platform/core/issues/5054) will be …
> fix: securityPostDenormalize not working because clone is made after denormalization

- composer.json
- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
- tests/Fixtures/TestBundle/ApiResourceNotLoaded/SymfonyFormatParameterLegacy.php
- tests/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactoryTest.php
See https://github.com/api-platform/core/pull/5080 for details
>  fix(metadata): _format broken bc promise on #5080 

- features/main/relation.feature
- src/Core/Api/LegacyIriConverter.php
- src/Serializer/AbstractItemNormalizer.php
- src/Symfony/Bundle/Resources/config/api.xml
- src/Symfony/Bundle/Resources/config/legacy/api.xml
- src/Symfony/Bundle/Resources/config/v3/api.xml
- tests/Fixtures/TestBundle/DataProvider/Issue5094RelationDataProvider.php
- tests/Fixtures/TestBundle/Entity/Issue5094Relation.php
- tests/Fixtures/TestBundle/Entity/Issue5094Resource.php
- tests/Fixtures/TestBundle/Metadata/ProviderResourceMetadatatCollectionFactory.php
- tests/Fixtures/TestBundle/State/Issue5094RelationProvider.php
- tests/Fixtures/app/config/config_common.yml
- tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
when the backward compatibility layer is `false` we can still use legacy resources while upgrading and therefore the legacy IriConverter is needed as it calls legacy providers.
fixes https://github.com/api-platform/core/issues/5094
> fix: use legacy iri converter for legacy resources

- src/Metadata/Resource/Factory/ExtractorResourceMetadataCollectionFactory.php
- src/Symfony/Bundle/Resources/config/metadata/resource.xml
- src/Symfony/Bundle/Resources/config/metadata/yaml.xml
- tests/Metadata/Extractor/ResourceMetadataCompatibilityTest.php
> fix(metadata): operations must inherit from resource and defaults

- src/Serializer/AbstractItemNormalizer.php
- tests/Serializer/ItemNormalizerTest.php
| Branch?       | 2.x
After delete-item operation I would like to output deleted data, but the normalizer fails on generating `iri` with `PK=null`.
Previously the iri was not generated when passed with in `$context`.
> Don't try to generate iri, if it is already defined in $context

- features/serializer/dynamic_groups.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/RelationGroupImpactOnCollection.php
- tests/Fixtures/TestBundle/Serializer/Normalizer/AddGroupNormalizer.php
- tests/Fixtures/app/config/config_common.yml
> fix(serializer): dynamic groups should not be cached

- src/Metadata/Operations.php
- src/Metadata/Resource/Factory/OperationNameResourceMetadataCollectionFactory.php
- tests/Metadata/Resource/Factory/OperationNameResourceMetadataFactoryTest.php
fixes https://github.com/api-platform/core/issues/5203
> fix(metadata): route prefix in the operation name

- features/main/attribute_resource.feature
- src/Core/Metadata/Resource/ApiResourceToLegacyResourceMetadataTrait.php
- src/Core/Swagger/Serializer/DocumentationNormalizer.php
- src/Doctrine/Odm/State/LinksHandlerTrait.php
- src/Doctrine/Orm/State/LinksHandlerTrait.php
- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
- src/OpenApi/Factory/OpenApiFactory.php
- tests/Fixtures/TestBundle/Entity/Company.php
- tests/Fixtures/TestBundle/Entity/IncompleteUriVariableConfigured.php
> fix(metadata): keep configured uri variables

- src/Symfony/Bundle/DependencyInjection/Compiler/DeprecateMercurePublisherPass.php
- tests/Symfony/Bundle/DependencyInjection/Compiler/DeprecateMercurePublisherPassTest.php
When running functional tests with api-platform 2.7, sylius 1.11 and not using Mercure, I got an error in service definition :
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "api_platform.doctrine.orm.listener.mercure.publish".
> fix: fix a missing service definition in test environment

- src/Symfony/Bundle/Resources/config/jsonld.xml
While trying to decorate the `Symfony\Component\Serializer\Encoder\JsonEncoder` (service `serializer.json.encoder`) we found out that it is not used by `ApiPlatform\Core\Serializer\JsonEncoder` as a service since the argument is not defined and one is created instead https://github.com/api-platform/core/blob/main/src/Serializer/JsonEncoder.php#L36.
So we currently need to wire the argument ourselves in a compiler pass.
Should I add a test for this?
> feat(symfony): wire Symfony JsonEncoder if it exists

- .php-cs-fixer.dist.php
- features/graphql/introspection.feature
- features/graphql/mutation.feature
- features/openapi/docs.feature
- src/GraphQl/Type/FieldsBuilder.php
- src/GraphQl/Type/FieldsBuilderEnumInterface.php
- src/GraphQl/Type/SchemaBuilder.php
- src/GraphQl/Type/TypeBuilder.php
- src/GraphQl/Type/TypeBuilderEnumInterface.php
- src/GraphQl/Type/TypeConverter.php
- src/JsonSchema/SchemaFactory.php
- src/JsonSchema/TypeFactory.php
- src/Metadata/ApiProperty.php
- src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php
- tests/Fixtures/TestBundle/Document/Person.php
- tests/Fixtures/TestBundle/Document/VideoGame.php
- tests/Fixtures/TestBundle/Entity/Person.php
- tests/Fixtures/TestBundle/Entity/VideoGame.php
- tests/Fixtures/TestBundle/Enum/EnumWithDescriptions.php
- tests/Fixtures/TestBundle/Enum/GamePlayMode.php
- tests/Fixtures/TestBundle/Enum/GenderTypeEnum.php
- tests/Fixtures/app/config/config_common.yml
- tests/GraphQl/Type/FieldsBuilderTest.php
- tests/GraphQl/Type/SchemaBuilderTest.php
- tests/GraphQl/Type/TypeBuilderTest.php
- tests/GraphQl/Type/TypeConverterTest.php
- tests/JsonSchema/SchemaFactoryTest.php
- tests/JsonSchema/TypeFactoryTest.php
- tests/Metadata/Property/Factory/AttributePropertyMetadataFactoryTest.php
Fixes (partially) https://github.com/api-platform/core/issues/2254.
Minor changes:
- Attribute property metadata factory is now able to understand enum cases as well.
- It improves the OpenAPI enum support: resource classes are no longer considered as enum (see also [this blog post](https://les-tilleuls.coop/blog/exposez-vos-enums-avec-api-platform)).
> feat: add GraphQL enum support

- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
| Tickets       | #4975
This PR allows to use Symfony default cache pool configuration in development environment instead of forcing ArrayAdapter. 
Change was introduced back in 2016 (#653) when Symfony 2.x required to manually clear cache after every configuration change.
Workaround proposed in #4975 (cache pool definition override) is no longer needed.
> perf: use symfony default cache pool config in development environment

- .github/workflows/ci.yml
Ubuntu 22.04 runner image does not have MongoDB anymore: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md.
> ci: fix mongod startup

- src/Metadata/Resource/Factory/OperationDefaultsTrait.php
- src/Metadata/Resource/Factory/OperationNameResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
- tests/Metadata/Extractor/ResourceMetadataCompatibilityTest.php
- tests/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactoryTest.php
| Tickets       | #5203
Fixes #5203
> fix(metadata): include routePrefix in default operation name (#5203)

- src/Hydra/JsonSchema/SchemaFactory.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
| Tickets       | https://github.com/api-platform/core/issues/5263
| Doc PR       | N/A
If I look in the generated schema for denormalizationContext i can see the required fields for '@id' and '@type'. Why do have this fields required for write operations? We don't need to pass this fields in a write request. If you used this schema on the client with typescript you need to write workarounds because you not sending this fields in the requests.
> fix: do not add linked data for denormalizationContext

- src/GraphQl/Action/EntrypointAction.php
- src/Serializer/SerializerContextBuilder.php
| Tickets       | #5287 
If `getContentTypeFormat` us this instead of `getContentType`, branch 3.0 since I think 2.7 isn't compatible with 6.2? (not sure)
> fix(deprecation): Use getContentTypeFormat when available

- CHANGELOG.md
- features/openapi/docs.feature
- phpstan.neon.dist
- src/Symfony/Bundle/DependencyInjection/Configuration.php
- tests/Fixtures/app/AppKernel.php
- tests/Fixtures/app/config/config_swagger.php
- tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
| Doc PR       | n/a
Please see https://symfony.com/doc/current/configuration.html#using-php-configbuilders and https://symfony.com/doc/current/components/config/definition.html#array-node-options
> fix(symfony): fix swagger config to support Symfony ConfigBuilders

- .github/workflows/ci.yml
- src/Elasticsearch/Paginator.php
- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaLengthRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRangeRestriction.php
> chore(ci): add php 8.2 on CI

- src/Symfony/Bundle/Resources/config/hydra.xml
| Tickets       |  
| Doc PR        |  
Fix any `serializer.default_context` configuration not being passed to the CollectionNormalizer.
For example, because `serializer.default_context.preserve_empty_objects: true` is not passed, the serialization of empty objects is broken.
> Fix default serializer context not passed to CollectionNormalizer

- src/Symfony/Bundle/Resources/config/metadata/yaml.xml
| Branch?       | 3.0 
In that PR https://github.com/api-platform/core/pull/5265 was added `$graphQlEnabled` flag, but it hasn't been considered in `metadata/yaml.xml` config. It results in always false for that flag (as default). This PR fix that.
> fix(graphql): pass graphql enabled flag

- tests/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestrictionTest.php
Follows https://github.com/symfony/symfony/pull/46518
> Switch from deprecated “loose” email validation mode to “html5”

- src/GraphQl/Action/EntrypointAction.php
- src/Serializer/SerializerContextBuilder.php
Follows https://github.com/symfony/symfony/pull/45034
> Replace `Request::getContentType` with `Request::getContentTypeFormat` if available

- src/Symfony/Bundle/Resources/config/api.xml
On branch 2.7, the service `api_platform.error_listener` defines `exception_listener` as parent. https://github.com/api-platform/core/blob/main/src/Symfony/Bundle/Resources/config/api.xml#L170
Twig v4.4 deletes the definition of `exception_listener` and replaces it by `twig.exception_listener` https://github.com/symfony/twig-bundle/blob/4.4/DependencyInjection/Compiler/ExceptionListenerPass.php#L43
So, when using api_platform 2.7 and twig 4.4, the following error occurs at cache clear : 
```
In ResolveChildDefinitionsPass.php line 76:
Service "api_platform.error_listener": Parent definition "exception_listener" does not exist.
```
This PR checks if twig is enabled, and changes the parent of …
> fix: Set twig.exception_listener as service parent

- src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php
`ArgumentValueResolverInterface::resolve` return type always have been `iterable`.
There is no need to make it more specific, especially because we support PHP ≥ 7.1 and full covariance support was added with PHP 7.4.
> Fix `PayloadArgumentResolver::resolve` return type

- src/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
- tests/Fixtures/TestBundle/Entity/User.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
| Doc PR        | #todo
When a JsonSchema needs to be tested over specific serialization context, one has to rewrite it's own methods.
This allows to pass the serializationContext to create the right JsonSchema during testing.
> feat (ApiTestCase): Assert Item|collection JsonSchema with SerializerContext

- .github/workflows/ci.yml
- composer.json
- features/graphql/query.feature
- src/GraphQl/Type/FieldsBuilder.php
- src/Symfony/Bundle/ArgumentResolver/CompatibleValueResolverInterface.php
- src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Entity/TreeDummy.php
As mentioned in #5289 , only use `ValueResolverInterface` if it exists, use the old one otherwise
> chore(deprecation): Only use ValueResolverInterface if it exists

- src/Symfony/Bundle/ArgumentResolver/CompatibleValueResolverInterface.php
- src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php
#5324 but without the other commits
> chore(symfony): ValueResolverInterface deprecation

- CHANGELOG.md
- src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php
- src/Symfony/Bundle/Resources/config/api.xml
Reverts api-platform/core#5337 sqashed by mistake...
> Revert "Merge 2.7"

- src/Metadata/Extractor/XmlResourceExtractor.php
- tests/Metadata/Extractor/XmlExtractorTest.php
Whenever an XML parsing error is found, the error message will be something like:
> [ERROR 1843] Element '{https://api-platform.com/schema/metadata/resources-3.0}operation': Character content other than whitespace is not allowed because the content type is 'element-only'. (in /var/www/ - line 28, column 0) in . (which is being imported from "/var/www/config/routes_api.php"). Make sure there is a loader supporting the "api_platform"
type.
Which is terribly unhelpful. The only file mentioned is in this case is a general routes configuration file, which is absolutely unrelated to the issue at hand.
Yes, ideally one wouldn't be modifying several configuration files at the same time, but sometimes it does happen.
This commit simply adds the path where the error was found to the error message, …
> feat: add context to XML parsing errors

- features/graphql/collection.feature
- src/Doctrine/Orm/Metadata/Resource/DoctrineOrmLinkFactory.php
- src/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Behat/DoctrineContext.php
- tests/Doctrine/Orm/Metadata/Resource/DoctrineOrmLinkFactoryTest.php
- tests/Fixtures/TestBundle/Document/MusicGroup.php
- tests/Fixtures/TestBundle/Entity/MusicGroup.php
| Tickets       | Fixes #5075, fixes #5341
This link factory decorates the one from Metadata.
It automatically adds a Link with a `toProperty` if the Doctrine relation is a `ManyToMany` on the inverse side.
Before it was necessary to add it manually to make a query work in GraphQL.
> feat(doctrine): add link factory

- src/Symfony/Bundle/Resources/config/metadata/resource.xml
The constructor argument for the annotation reader in `FiltersResourceMetadataCollectionFactory` is optional (nullable), but the argument in the service definition is not and therefore fails if the `annotation_reader` service definition does not exist. Defining it as null if invalid should just fix this issue without changing anything when the annotation reader is available.
>  @philipsorst fix: Make annotation reader argument optional

- src/GraphQl/Type/FieldsBuilder.php
- tests/GraphQl/Type/FieldsBuilderTest.php
| Tickets       | #5097 #2736
For all GraphQL mutations except  `create` the `id` field is added automatically. Also for scenarios where an input DTO is used the `id` got added. This PR respects the given input DTO and will not add an additional `id` field. If you need the id your DTO may contain it.
The related Ticker #2736 is not completely solved with this PR but it enables the workaround to have multipe create mutations by using a specifiy input DTO.
Branch: 
- `main`, because not sure if it is a real bugfix or more a tiny new feature.
Note: Failing PHP-cs-fixer is not related to the changes in this PR
> Bugfix: Respect input DTO without adding additional id field

- src/GraphQl/Type/FieldsBuilder.php
- src/GraphQl/Type/TypeBuilder.php
- src/Metadata/Extractor/ResourceExtractorTrait.php
- src/Metadata/Extractor/XmlResourceExtractor.php
- src/Metadata/Extractor/YamlResourceExtractor.php
- src/Metadata/Extractor/schema/resources.xsd
- src/Metadata/GraphQl/Operation.php
- src/Metadata/GraphQl/Query.php
- src/Metadata/GraphQl/QueryCollection.php
- src/Metadata/GraphQl/Subscription.php
- tests/Fixtures/TestBundle/Document/DummyCustomMutation.php
- tests/Fixtures/TestBundle/Entity/DummyCustomMutation.php
- tests/GraphQl/Type/FieldsBuilderTest.php
- tests/Metadata/Extractor/Adapter/XmlResourceAdapter.php
- tests/Metadata/Extractor/ResourceMetadataCompatibilityTest.php
| Tickets       | https://github.com/api-platform/core/issues/5097 https://github.com/api-platform/core/issues/2736
This PR adds an `extraArgs` argument for GraphQL operations.
It also removes the generation of the required ID field in case of a custom query or mutation.
It is a slight BC break if the user relies on this required ID field.
It should be added back with the extra args if needed:
```php
#[ApiResource(graphQlOperations: [
new Mutation(
name: 'custom',
resolver: Resolver::class,
extraArgs: ['id' => ['type' => 'ID!']],
),
])]
```
> feat(graphql)!: add extra args for custom queries or mutations

- src/GraphQl/Type/TypeBuilder.php
- tests/GraphQl/Type/TypeBuilderTest.php
Supersedes https://github.com/api-platform/core/pull/5367.
> fix(graphql): name and key should be the same for an enum without Enum suffix in class name

- src/Symfony/EventListener/RespondListener.php
- tests/Symfony/EventListener/RespondListenerTest.php
Fixes the possibility to use custom http status codes for the PUT methods. Currently, it returns 201 HTTP_CREATED.
> fix(metadata): allow custom http status code for put

- src/HttpCache/SouinPurger.php
- src/HttpCache/SurrogateKeysPurger.php
- src/HttpCache/VarnishPurger.php
- src/HttpCache/VarnishXKeyPurger.php
- tests/HttpCache/VarnishPurgerTest.php
- tests/HttpCache/VarnishXKeyPurgerTest.php
> fix(symfony): wrong purger clients type

- phpstan.neon.dist
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
> fix(symfony): autoconfigure elasticsearch extension

- src/OpenApi/Factory/OpenApiFactory.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
| Tickets       | #5368
Before : When adding a specific requestbody on an openapi declaration, it don't change the swagger/doc : 
After: The openapi doc is decorated :
> fix(openapi): fix openapi requestbody decoration

- src/Api/IdentifiersExtractor.php
- tests/Api/IdentifiersExtractorTest.php
- tests/Fixtures/TestBundle/Entity/DummyWithEnumIdentifier.php
This PR allows backed enums to be used a identifiers
> feat(metadata): IdentifiersExtractor now handles enums

- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
- tests/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactoryTest.php
This PR auto map the `uriVariables` to the `uriTemplate` vars if they exist in the target class
> fix: map uriVariables to uriTemplate vars

- src/OpenApi/Factory/OpenApiFactory.php
- tests/OpenApi/Factory/OpenApiFactoryTest.php
| Branch?       | 3.1 
| Tickets       | #5381
This fix is for overriding the responses in swagger via openapi
> fix(openapi): allow overriding of openapi responses

- src/Symfony/Bundle/Resources/config/api.xml
| Tickets       | https://github.com/api-platform/api-platform/issues/2394
Fixes the `PlaceholderAction` making it usable in operations' `controller` definition  - described here : https://api-platform.com/docs/core/controllers/#using-the-placeholderaction
> fix: missing PlaceholderAction service alias

- features/jsonld/inheritance.feature
- src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/ApiResource/Issue5438/Contractor.php
- tests/Fixtures/TestBundle/ApiResource/Issue5438/Employee.php
- tests/Fixtures/TestBundle/ApiResource/Issue5438/Person.php
> fix(serializer): find parent class operation

- features/filter/property_filter.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/ApiResource/DummyWithArrayOfNotResourceObjects.php
- tests/Fixtures/TestBundle/Dto/DummyNonResource.php
`PropertyFilter` does not presently work with arrays of objects which are not `ApiResource`: it just always serializes these objects as null arrays.
FYI I've tested with `ArrayCollection` of objects which are not `ApiResource` and it works like a charm
> fix(serializer): propertyFilter should apply to arrays as well 

- src/JsonSchema/TypeFactory.php
> fix: avoid ReflectionEnum usage

- features/openapi/docs.feature
- src/Serializer/Filter/PropertyFilter.php
- tests/Fixtures/TestBundle/Entity/DummyWithCollectDenormalizationErrors.php
- tests/Serializer/Filter/PropertyFilterTest.php
| Tickets       | https://github.com/api-platform/core/issues/5415
| Doc PR        |  N/A
PropertyFilter generated description is shown as parameter description in Openapi.
> fix(PropertyFilter): property filter description not shown in openapi

- features/main/custom_put.feature
- src/Symfony/EventListener/RespondListener.php
- tests/Fixtures/TestBundle/Entity/CustomPut.php
| Tickets       | #5417 
Fix #5417
> Added checking of the allowCreate option to set the status

- src/Metadata/HttpOperation.php
Fix rule to accept only string in array like as mentioned in doc.
> fix(metadata): add string[] as allowed param type

- features/openapi/docs.feature
- src/JsonSchema/SchemaFactory.php
- src/Metadata/Resource/ResourceMetadataCollection.php
- tests/Fixtures/TestBundle/Entity/JsonSchemaResource.php
- tests/Fixtures/TestBundle/Entity/JsonSchemaResourceRelated.php
See https://github.com/api-platform/core/pull/5455#issuecomment-1469699042
> fix(jsonSchema): class shortname

- src/Metadata/Extractor/YamlResourceExtractor.php
- src/Metadata/Tests/Extractor/YamlExtractorTest.php
- src/Metadata/Tests/Extractor/yaml/openapi.yaml
| Tickets       | https://github.com/api-platform/core/issues/5484
> fix parameters extractor in openapi with yaml

- src/JsonSchema/SchemaFactory.php
- src/JsonSchema/Tests/TypeFactoryTest.php
- src/JsonSchema/TypeFactory.php
- tests/Fixtures/TestBundle/ApiResource/Issue5501/BrokenDocs.php
- tests/Fixtures/TestBundle/ApiResource/Issue5501/Related.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
fixes #5501
The locations relation inside BrokenDocs is a Resource (named Related) but its only operation is a NotExposed. Still, serializer groups are set, and therefore it is a "readableLink" so we actually want to compute the schema, even if it's not accessible directly, it is accessible through that relation.
> fix(jsonschema): access related subschema on readableLink

- src/Symfony/Bundle/DependencyInjection/Configuration.php
| Branch?       | 3.1 
As discussed with @soyuka, we need to do the verification on the parameters of the operations as well
> fix(symfony): check operations's parameters

- src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php
- tests/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactoryTest.php
Related to https://github.com/api-platform/core/pull/5450. Now fixed for non graphql operations.
> fix(metadata): no deprecation when elasticsearch is null

- features/hydra/error.feature
- features/jsonld/context.feature
- src/Serializer/AbstractItemNormalizer.php
- src/Symfony/Bundle/Resources/config/jsonld.xml
- tests/Serializer/ItemNormalizerTest.php
> Fix SerializedName and name converter

- src/Metadata/FilterInterface.php
- src/Metadata/Operation/PathSegmentNameGeneratorInterface.php
- src/Metadata/ResourceClassResolverInterface.php
- src/OpenApi/Command/OpenApiCommand.php
| Tickets       | [#... ](https://github.com/api-platform/core/issues/5522)
Error with PHP opacache preload :
`Warning: Cannot declare interface ApiPlatform\Api\FilterInterface, because the name is already in use`
> fix: class already declared with preloading

- src/JsonSchema/composer.json
- src/Metadata/composer.json
- src/OpenApi/composer.json
- src/State/composer.json
The link to the contributors' page in some composer.json files is incorrect, changed it for the right one : [https://api-platform.com/community/contributors](https://api-platform.com/community/contributors%60)
> fix: wrong contributors link in composer.json

- src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
The Differ now expects a output builder as mandatory argument.
Fixes #5426
| Branch?       | 2.7 
| Tickets       | #5426 
| Doc PR        | n/a 
Update the `UpgradeApiResourceCommand` for changes in PHPUnit 10.
> fix(symfony): update for PHPUnit 10

- src/Doctrine/Orm/State/LinksHandlerTrait.php
When provided with both a fromProperty and toProperty in a link, the wrong class metadata was used to find the type of the identifier parameters (line 123).
| Branch?       | 3.x
| Tickets       | No
$doctrineClassMetadata was used for both the resource class and the fromClass which was confusing, I renamed the latter to fromClassMetadata in order to clarify things up.
> Fixing issue in ORM/LinkHandlerTrait : Wrong class metadata

- src/Doctrine/Common/State/PersistProcessor.php
- src/Hydra/Serializer/DocumentationNormalizer.php
- src/Metadata/Delete.php
- src/Metadata/HttpOperation.php
- src/Metadata/NotExposed.php
- src/Metadata/Patch.php
- src/Metadata/Post.php
- src/Metadata/Put.php
- src/Metadata/Resource/Factory/FormatsResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/NotExposedOperationResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
- src/Metadata/Resource/ResourceMetadataCollection.php
- src/Metadata/Tests/Fixtures/Metadata/Get.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
- src/Symfony/EventListener/DeserializeListener.php
- src/Symfony/EventListener/ReadListener.php
- src/Symfony/EventListener/RespondListener.php
- src/Symfony/Routing/ApiLoader.php
- src/Symfony/Routing/IriConverter.php
- tests/Fixtures/TestBundle/Metadata/Get.php
As spoken with @chalasr there are string hardcoded operation request which could be replaced with the HttpOperation request const
Maybe this isn't what you want but I thought this would be good to replace those.
I'll gladly take any advice.
I don't know to which branch this should be merged so I'd like your advice.
> refactor(metadata): replace HttpOperation constants by raw strings

- docs/adr/0005-refactor-state-management.md
Proposal to simplify the codebase and give more flexibility to users by leveraging the new  "state processor" and "state provider" concept to get rid of our custom Symfony kernel listeners and of the GraphQL resolvers.
> docs(adr): refactor state management

- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/NonCloneableDummy.php
- tests/Serializer/AbstractItemNormalizerTest.php
| Tickets       | #5561 
Fixes #5561 in the 2.7 branch by using a safer clone approach, and skipping post-normalization attribute revert functionality if the object was never cloned.
> fix(serializer): fix denormalizing to non-cloneable objects

- src/Symfony/Bundle/Test/ApiTestCase.php
Use case: 
```php
$code = CouponCodeFactory::createOne(['code' => 'FOOBAR_123']);
$response = $client->request('POST', '/cart', [
'json' => [
...
'code' => getIriForResource($code->object()), // Instead of findIriBy(['code' => 'FOOBAR_123']) or manually generating IRI                
],
]);
self::assertResponseIsSuccessful();
```
> feat(tests): add a method to generate the IRI from a resource

- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/ApiResource/Issue5584/DtoWithNullValue.php
- tests/Serializer/AbstractItemNormalizerTest.php
> fix(serializer): disable_type_enforcement with null values

- features/jsonld/getter_setter_renaming.feature
- tests/Fixtures/TestBundle/ApiResource/EntityWithRenamedGetterAndSetter.php
This PR tests that no field is added to the resource when renaming the getter and setter of a private property
. (related https://github.com/api-platform/api-platform/issues/2426).
> fix: allows changing getters and setters without breaks

- features/main/put_collection.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/Issue5587/Business.php
- tests/Fixtures/TestBundle/Entity/Issue5587/Employee.php
> fix(serializer): put replaces embed collection

- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
After https://github.com/lexik/LexikJWTAuthenticationBundle/pull/1119, the API Platform integration is not enabled automatically anymore.
Doing this should solve it.
> fix: enable API Platform integration in LexikJWTAuthenticationBundle

- src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
- src/Core/Upgrade/RemoveAnnotationTrait.php
- tests/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommandTest.php
- tests/Fixtures/TestBundle/Entity/DummyToUpgradeWithOnlyAnnotation.php
- tests/Fixtures/TestBundle/Entity/DummyToUpgradeWithOnlyAttribute.php
| Tickets       | #5620 & #4973 
Hello, fixed 2 issues affecting the output of `bin/console api:upgrade-resource`. I know the command is removed in v3, but I think it's an important part of the upgrade path, and it is really hard to use right now because almost the whole file appears in diff, see below.
1. The `PhpParser\PrettyPrinter\Standard::printFormatPreserving` method has 3 requirements to preserve formatting, and one of them was not met.
The AST needs to be traversed by `CloningVisitor` *before* making changes to the AST. This is adding a property on the AST nodes, keeping a reference to the original node, and especially original tokens positions.
This is documented …
> fix: api:upgrade-resource output formatting

- src/Core/Api/IriConverterInterface.php
- src/Core/Api/LegacyIriConverter.php
- src/Core/Bridge/Symfony/Routing/IriConverter.php
- src/Symfony/Bundle/ApiPlatformBundle.php
- src/Symfony/Bundle/DependencyInjection/Compiler/DeprecateLegacyIriConverterPass.php
- src/Symfony/Bundle/Resources/config/api.xml
- src/Symfony/Bundle/Resources/config/legacy/api.xml
- src/Symfony/Bundle/Resources/config/legacy/backward_compatibility.xml
- tests/Symfony/Bundle/ApiPlatformBundleTest.php
- tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Symfony/Bundle/DependencyInjection/Compiler/DeprecateLegacyIriConverterPassTest.php
| Tickets       | #5620 
Hello, proposing a fix for an issue with dependency injection of  `ApiPlatform\Api\IriConverterInterface` & deprecation of `ApiPlatform\Core\Api\IriConverterInterface`. I'm open to discussion if you don't like the proposed solution ofc 🙂 
When BC flag is ON, we receive this deprecation notice
> Since api-platform/core 2.7: The service "ApiPlatform\Core\Bridge\Symfony\Routing\IriConverter" is deprecated, use "ApiPlatform\Symfony\Routing\IriConverter" instead.
There's a few issues with this deprecation imo:
* The message only mentions the concrete class, while user is probably referencing interfaces or service id `api_platform.iri_converter`. Actually both mentioned services does …
> fix: IriConverterInterface DI & deprecation

- src/Metadata/Util/Inflector.php
- src/Metadata/composer.json
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Util/Inflector.php
| Branch       | main
| Tickets       | #5636 
Replace `doctrine/inflector` dependance to pluralize and tableize to `symfony/string`
Introduce new config flag `keep_legacy_inflector` to keep the old inflector or to switch to symfony/string by passing the config to `false`
> feat: replace doctrine/inflector by symfony/string

- features/doctrine/search_filter.feature
- src/Doctrine/Common/Filter/SearchFilterTrait.php
- src/Doctrine/Orm/Filter/SearchFilter.php
- src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
- src/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/ApiResource/Issue5605/MainResource.php
- tests/Fixtures/TestBundle/ApiResource/Issue5605/SubResource.php
- tests/Fixtures/TestBundle/Entity/DummySubEntity.php
- tests/Fixtures/TestBundle/Entity/DummyWithSubEntity.php
- tests/Fixtures/TestBundle/State/Issue5605/MainResourceProvider.php
- tests/Fixtures/TestBundle/State/Issue5605/SubResourceProvider.php
- tests/Fixtures/app/config/config_doctrine.yml
| Tickets       | https://github.com/api-platform/core/issues/5605
This should fix that use case when ids are not composite. 
Composite IDs would still need to be addressed with a custom filter, but that's even more of a fringe case...and would require quite of lot of work as far as i can see. I still left todo comments in case someone wants to tackle that.
> fix: search on nested sub-entity that doesn't use "id" as its ORM id

- src/Symfony/Routing/ApiLoader.php
- tests/Symfony/Routing/ApiLoaderTest.php
Supersedes https://github.com/api-platform/core/pull/5677
> Custom controller with class method

- features/doctrine/search_filter.feature
- src/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- tests/Fixtures/TestBundle/ApiResource/Issue5648/CustomFilter.php
- tests/Fixtures/TestBundle/ApiResource/Issue5648/DummyResource.php
| Branch?       |  3.1
| Tickets       |  https://github.com/api-platform/core/issues/5648
A simple fix to force the joinCondition to a string before using it in preg_replace. 
The related issue actually happens when the query also has a where part (hence the "andWhere('1=1')" in the test), not when there is another SearchFilter. Investigating why this code involving the join condition is not triggered when there is no where may be a good idea too, I didn't dig that far into it.
> fix: ORM filters can use doctrine expressions in join conditions

- src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php
| Tickets       | #5482
This PR fixes #5482.
Because `ExtractorPropertyMetadataFactory::update()` method was updating only some of the properties of the `ApiProperty` class, so in decorated factories, metadata such as `openapiContext` were not being updated.
> fix: enable to update all keys in metadata

- features/doctrine/search_filter.feature
- tests/Fixtures/TestBundle/ApiResource/Issue5648/DummyResource.php
Fix a typo introduced in #5671
> test: fix typo

- src/Doctrine/Odm/Filter/RangeFilter.php
- src/Doctrine/Orm/Filter/RangeFilter.php
- src/Symfony/Routing/ApiLoader.php
> chore: apply a micro-optimization to explode() calls

- tests/Fixtures/TestBundle/State/DummyDtoInputOutputProvider.php
`ApiTestCaseTest::testAssertMatchesResourceItemJsonSchemaOutput` is rightfully failing on my machine. I wonder why it doesn't break the CI.
> test: fix a bug in DummyDtoInputOutputProvider

- src/Core/Api/LegacyIriConverter.php
| Tickets       | #5620 
Hello, a small fix for when using the `\ApiPlatform\Core\Api\LegacyIriConverter`
#5630 Introduced a nice way to fix the IriConverterInterface deprecation before turning off the `metadata_backward_compatibility_layer`. 
One issue I ran into is that `LegacyIriConverter::getIriFromResource` decides if the iri will be Item level or Collection level solely based on if the given `$item` parameter is a string vs an object.
With this methodology, I would have instantiate a new object just to trigger the Item level iri conversion.
(To compare, The new IriConverterInterface handles this decision smartly, using the metadata of the Operation and the given Object).
Previously, the old …
> fix: handle item iri with identifiers in LegacyIriConverter

- src/OpenApi/Factory/OpenApiFactory.php
This PR fixes following bug:
When parameters are set in openapiContext for some operations with some filters applied, the filter parameters are lost and only the parameters set in openapiContext are output to OpenAPI.
The cause of this bug was as follows. Even though the pagination and filter parameters are merged at [here](https://github.com/api-platform/core/blob/24133dfecb584e50e26503d852c654fe2224e45d/src/OpenApi/Factory/OpenApiFactory.php#L275-L283), they are reset to openapiContext parameters value at [here](https://github.com/api-platform/core/blob/24133dfecb584e50e26503d852c654fe2224e45d/src/OpenApi/Factory/OpenApiFactory.php#L369-L374).
> fix(openapi): correctly output OpenAPI parameters

- composer.json
- features/graphql/query.feature
- features/hal/max_depth.feature
- features/jsonapi/collection_attributes.feature
- features/jsonld/max_depth.feature
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/DummyOffer.php
- tests/Fixtures/TestBundle/Document/DummyProduct.php
- tests/Fixtures/TestBundle/Entity/DummyOffer.php
- tests/Fixtures/TestBundle/Entity/DummyProduct.php
| Tickets       | [See here](https://github.com/doctrine/orm/pull/10547) and [here](https://github.com/doctrine/orm/issues/10864)
> fix: change tests to not rely on order of insertion

- src/Serializer/AbstractItemNormalizer.php
- tests/Hal/Serializer/ItemNormalizerTest.php
- tests/Serializer/AbstractItemNormalizerTest.php
- tests/Serializer/ItemNormalizerTest.php
The switch to the new `NormalizerInterface::getSupportedTypes()` system provided by Symfony in #5672 introduced a performance regression.
Symfony 6.2 + API Platform 3.1.12 (faster) VS Symfony 6.3 + API Platform 3.1.13
With this patch fixes the issue: Symfony 6.2 + API Platform 3.11.12 VS Symfony 6.3 + API Platform with this patch
> fix: perf regression with Symfony 6.3 

- src/Metadata/Resource/Factory/NotExposedOperationResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/OperationDefaultsTrait.php
- src/Metadata/Tests/Resource/Factory/NotExposedOperationResourceMetadataCollectionFactoryTest.php
When a NotExposed operation is generated in the metadata, it should inherit the resource options.
> fix(metadata): generated NotExposed operation should inherit resource options

- CHANGELOG.md
With #5609 the integration of API Platform with LexikJWTAuthenticationBundle is automatically enabled. However, if we are not using the default configuration of LexikJWTAuthenticationBundle the documented operation is wrong (wrong path, wrong response in my case) and creates a duplicate. Since the behaviour of API Platform changed in a patch version maybe it's a good idea to explain directly in the changelog how to go back to the previous behaviour.
> docs: Explain how to disable the automatic integration with LexikJWTAuthenticationBundle

- features/doctrine/separated_resource.feature
- features/main/crud_uri_variables.feature
- src/Metadata/Resource/Factory/LinkFactory.php
- tests/Fixtures/TestBundle/ApiResource/EntityClassAndCustomProviderResource.php
- tests/Fixtures/TestBundle/State/EntityClassAndCustomProviderResourceProvider.php
@weaverryan we are already using the correct `fromClass` inside the doctrine Link Factory, therefore I removed the change within the MetadataFactory. Note that we had a test but we were declaring uriTemplates manually, and it wasn't overridden :).
> fix(doctrine): use stateOptions only within doctrine context

- features/main/patch.feature
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/ItemNormalizer.php
- tests/Fixtures/TestBundle/ApiResource/Issue5736/Alpha.php
- tests/Fixtures/TestBundle/ApiResource/Issue5736/Beta.php
> fix(serializer): use data if no uri_variables provided

- features/hydra/item_uri_template.feature
- src/Hydra/Serializer/CollectionNormalizer.php
- src/JsonLd/Serializer/ItemNormalizer.php
- src/Serializer/AbstractCollectionNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/OperationContextTrait.php
- src/Serializer/SerializerContextBuilder.php
- src/Symfony/Routing/IriConverter.php
- tests/Fixtures/TestBundle/ApiResource/Issue5396/CompositeKeyWithDifferentType.php
- tests/Fixtures/TestBundle/ApiResource/Issue5648/DummyResource.php
- tests/Fixtures/TestBundle/Entity/Issue5662/Book.php
- tests/Fixtures/TestBundle/Entity/Issue5662/Review.php
- tests/Fixtures/TestBundle/Entity/ItemReferencedInCollection.php
- tests/Serializer/AbstractItemNormalizerTest.php
- tests/Symfony/Routing/IriConverterTest.php
> Fix Symfony IriConverter with `item_uri_template`

- features/doctrine/search_filter.feature
- src/Doctrine/Common/Filter/SearchFilterTrait.php
- src/Doctrine/Orm/Filter/SearchFilter.php
- src/Doctrine/Orm/State/ItemProvider.php
- src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
- src/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/ApiResource/Issue5605/MainResource.php
- tests/Fixtures/TestBundle/ApiResource/Issue5605/SubResource.php
- tests/Fixtures/TestBundle/Entity/DummySubEntity.php
- tests/Fixtures/TestBundle/Entity/DummyWithSubEntity.php
- tests/Fixtures/TestBundle/Entity/Issue5735/Group.php
- tests/Fixtures/TestBundle/Entity/Issue5735/Issue5735User.php
- tests/Fixtures/TestBundle/State/Issue5605/MainResourceProvider.php
- tests/Fixtures/TestBundle/State/Issue5605/SubResourceProvider.php
- tests/Fixtures/app/config/config_doctrine.yml
| Tickets       | Closes [5735](https://github.com/api-platform/core/issues/5735)
This undoes the revert of https://github.com/api-platform/core/pull/5623 , but (as far as i can see) fixes the part that was causing https://github.com/api-platform/core/issues/5735
> fix: searchfilter with nested custom identifiers

- src/Hydra/Serializer/CollectionNormalizer.php
This fixes a bug introduced by the removal of "private" keyword in 3.1.15 here: https://github.com/api-platform/core/compare/v3.1.14...v3.1.15#diff-865ce957323cd00c97d744721bce982a833cc16edba4d141f0d841277295a02eL41-L48
> Fixes undefined property error in CollectionNormalizer.php, line 46

- src/Elasticsearch/Serializer/ItemNormalizer.php
- tests/Elasticsearch/Serializer/ItemNormalizerTest.php
I have issue using DTO input (https://api-platform.com/docs/core/dto/#implementing-a-write-operation-with-an-input-different-from-the-resource). The state processor doesn't receive the input class as argument. There is a problem with the deserialization process.
This pull request fixes my issue.
With elasticsearch support enabled, the normalizer `api_platform.elasticsearch.normalizer.item` is registered, it decorates the default item normalizer `api_platform.serializer.normalizer.item`. 
I guess that this `ApiPlatform\Elasticsearch\Serializer\ItemNormalizer` class intend to prevent calling the decorated service when using `elasticsearch` format.
Unfortunately, …
> fix(serializer): correct supported types for elasticsearch item normalizer decorator

- src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php
- tests/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommandTest.php
| Tickets       | #5620 
Hello, want to propose a small improvement for the `api:upgrade-resource` command. 
I'm fine if you don't want to merge this since it's not a fix in any way, it's just something that comes very useful in our upgrade scenario, so could probably be useful for others aswell.
Why? Because when upgrading a big application, you most likely want to take small steps, i.e. not running the upgrade on 200 resources in one shot, because there is a lot of things to refactor when upgrading a resource (providers, persisters, etc...).
Usage: `bin/console api:upgrade-resource Foo\\Bar\\Baz`
Let me know if you agree to merge it so I can make a doc PR, thanks!
> feat: allow upgrading single resource

- src/GraphQl/Serializer/ItemNormalizer.php
- tests/GraphQl/Serializer/ItemNormalizerTest.php
| Tickets       | ¤
| Doc PR        | ¤
Hello everyone,
it looks like the localCache in the Serializer is not used for the GraphQL ItemNormalizer, as it's done in the other normalizers.
This small fix reduces the calls to `getAttributes` from the Serializer.
> fix(GraphQL): Add cache_key in item normalizer

- src/Serializer/ItemNormalizer.php
- tests/Serializer/ItemNormalizerTest.php
> fix(serializer): retrieve only first uriVariable from operation

- src/deprecated_interfaces.php
- src/deprecation.php
| Branch?       | 2.7 
Added a few missing deprecations that needs to be fixed when upgrading from the old metadata system.
> fix: Add missing deprecated elasticsearch related interfaces/classes

- features/main/sub_resource.feature
- src/State/CreateProvider.php
- src/Symfony/Bundle/Resources/config/state.xml
- tests/Fixtures/TestBundle/ApiResource/PostWithUriVariables.php
- tests/Fixtures/TestBundle/ApiResource/SubresourceBike.php
- tests/Fixtures/TestBundle/ApiResource/SubresourceCategory.php
- tests/State/CreateProviderTest.php
| Doc PR        | N/A (`@internal` and `@experimental`)
Improve CreateProvider with `parent_uri_template` context option, and remove the `new Get`. If no `parent_uri_template` option is provided, get the first operation found as it's already done in core.
> feat(metadata): improve CreateProvider

- .github/workflows/ci.yml
- behat.yml.dist
- composer.json
- features/graphql/subscription.feature
- features/mercure/discover.feature
- phpunit.xml.dist
- phpunit10.xml.dist
- src/GraphQl/Tests/Subscription/MercureSubscriptionIriGeneratorTest.php
- src/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
- tests/Fixtures/TestBundle/Document/DirectMercure.php
- tests/Fixtures/TestBundle/Entity/DirectMercure.php
- tests/Fixtures/app/config/config_common.yml
- tests/Fixtures/app/config/config_mercure.yml
- tests/Fixtures/app/config/routing_mercure.yml
- tests/Hydra/EventListener/AddLinkHeaderListenerTest.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
> feat(symfony): add mercure asserts

- src/JsonSchema/Metadata/Property/Factory/SchemaPropertyMetadataFactory.php
- src/JsonSchema/Schema.php
- src/JsonSchema/SchemaFactory.php
- tests/Fixtures/TestBundle/Entity/Issue5793/BagOfTests.php
- tests/Fixtures/TestBundle/Entity/Issue5793/TestEntity.php
- tests/Hal/JsonSchema/SchemaFactoryTest.php
- tests/Hydra/JsonSchema/SchemaFactoryTest.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
#5793 related ping @paullallier @vincentchalamon
> fix(jsonschema): allow embed resources

- src/Doctrine/Odm/Filter/BooleanFilter.php
- src/Doctrine/Odm/Filter/DateFilter.php
- src/Doctrine/Odm/Filter/ExistsFilter.php
- src/Doctrine/Odm/Filter/NumericFilter.php
- src/Doctrine/Odm/Filter/OrderFilter.php
- src/Doctrine/Odm/Filter/RangeFilter.php
- src/Doctrine/Odm/Filter/SearchFilter.php
- src/Doctrine/Orm/Filter/BooleanFilter.php
- src/Doctrine/Orm/Filter/DateFilter.php
- src/Doctrine/Orm/Filter/ExistsFilter.php
- src/Doctrine/Orm/Filter/NumericFilter.php
- src/Doctrine/Orm/Filter/OrderFilter.php
- src/Doctrine/Orm/Filter/RangeFilter.php
- src/Doctrine/Orm/Filter/SearchFilter.php
Doctrine filters weren't final in 2.6 but were moved to `final` in 2.7, which is a BC break. This blocks developers to update to 2.7 in case they're extending API Platform Doctrine filters.
If developers cannot update to 2.7, they can't migrate to 3.x.
Mark those filters as `@final` in 2.7.
**Note: there is no need to backport this fix on 3.0 as those filters are already `final`.**
> fix(doctrine): fix BC break about final filters

- src/Elasticsearch/Tests/Filter/MatchFilterTest.php
- src/Elasticsearch/Tests/Filter/TermFilterTest.php
- src/Elasticsearch/Tests/Util/FieldDatatypeTraitTest.php
- src/Elasticsearch/Util/FieldDatatypeTrait.php
This is a resurrection of https://github.com/api-platform/core/pull/5643
| Tickets       | https://github.com/api-platform/api-platform/issues/1375 and https://github.com/api-platform/core/issues/5642
| Doc PR        | WIP
This PR implements the following changes to support filtering on paths like foo.bar.baz:
1. If `foo` is an object, `isNestedField()` now returns `true` instead of `false`
2. If `foo` is an object, `getNestedFieldPath()` now returns `"foo.bar"` instead of `null`
3. If `foo` is a collection, `getNestedFieldPath()` now returns `"foo.bar"` instead of just `"foo"` (matching the behavior if `foo` is an object)
As a result, filtering on deeply-nested paths (with 3 or more levels) now …
> feat(elasticsearch): filtering on nested fields

- src/Elasticsearch/Tests/Filter/MatchFilterTest.php
- src/Elasticsearch/Tests/Filter/TermFilterTest.php
- src/Elasticsearch/Tests/Util/FieldDatatypeTraitTest.php
- src/Elasticsearch/Util/FieldDatatypeTrait.php
Reverts api-platform/core#5820
> Revert "feat(elasticsearch): filtering on nested fields"

- src/Symfony/Bundle/Resources/config/legacy/events.xml
- src/Symfony/EventListener/ErrorListener.php
- src/Symfony/Validator/EventListener/ValidationExceptionListener.php
When an exception occurs the profiler can not serialize a closure. We're using a static function instead.
> fix: profiler can not serialize closure

- src/Symfony/Bundle/ApiPlatformBundle.php
- src/Symfony/Bundle/DependencyInjection/Compiler/TestMercureHubPass.php
- src/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
- tests/Symfony/Bundle/ApiPlatformBundleTest.php
| Doc PR        | **TODO**
Creating fixtures on functional tests may send Mercure Update objects. Before executing the test calls, the developer should be able to reset the Mercure Hub:
```php
public function testAsAdminUserICanUpdateABook(): void
{
FooFactory::createOne();
self::getMercureHub()->reset();    // <== this line resets the Mercure Hub
$this->client->request(...);
self::assertCount(1, self::getMercureMessages());
}
```
> fix: fix Mercure assertions to public to allow Mercure Hub reset

- src/State/Processor/RespondProcessor.php
- src/Symfony/Bundle/Resources/config/state.xml
- tests/State/RespondProcessorTest.php
Add `canonical_uri_template` extra property to be able to specify the URI template of the canonical resource.
Plus, widen the allowed status code for the alternate redirect to 3xx.
> [HTTP] Add canonical_uri_template

- src/JsonSchema/SchemaFactory.php
- tests/Fixtures/TestBundle/Entity/Issue5793/BagOfTests.php
- tests/Fixtures/TestBundle/Entity/Issue5793/NonResourceTestEntity.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
> fix(jsonschema): build non-resource class schema

- features/doctrine/search_filter.feature
- src/Doctrine/Common/Filter/SearchFilterInterface.php
- src/Doctrine/Common/Filter/SearchFilterTrait.php
- tests/Fixtures/TestBundle/Document/DummyCar.php
- tests/Fixtures/TestBundle/Entity/DummyCar.php
| Tickets       |  [5851](https://github.com/api-platform/core/issues/5851)
> fix(FilterContext): add xxx[] hydra:search iexact

- docs/guides/subresource.php
First of all, thanks @soyuka for your amazing work with the wasm integration and the new guide :heart_eyes: 
It seems that the parser is losing the closing of the string. I guess it's because on a new line, so I hope this will fix it !
> docs(subresource): Parser is losing the closing structure on new line

- src/JsonSchema/SchemaFactory.php
- tests/Fixtures/TestBundle/Entity/Issue5793/BagOfTests.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
See https://github.com/api-platform/core/issues/5845#issuecomment-1740478420
> fix(jsonschema): do not override nor complete ApiProperty::schema user value

- src/Elasticsearch/Serializer/ItemNormalizer.php
- tests/Elasticsearch/Serializer/ItemNormalizerTest.php
| Tickets       | #5620 
Hello,
I'm sorry I want to propose a fix for 2.7 🙈 , I found out `ApiPlatform\Elasticsearch\Serializer\ItemNormalizer` is defining an `array` return type, while the decorated service really doesn't return just array.
It is already fixed in 3.0 and 3.1, but I think it is still quite a big issue for 2.7 because this service was introduced as a decorator of `api_platform.serializer.normalizer.item` in https://github.com/api-platform/core/pull/3981 and the return type was added in https://github.com/api-platform/core/pull/4526 , so it basically kicks in everytime as soon as elastic is enabled (and BC flag is off), and then throws a type error when returning anything else than an …
> fix(serializer): Remove ItemNormalizer wrong return type

- tests/Fixtures/TestBundle/Entity/Issue5625/Currency.php
- tests/Symfony/Bundle/Command/OpenApiCommandTest.php
| Tickets       | #5625
Cf. https://swagger.io/docs/specification/authentication/#security
> fix(openapi): dump security properties scheme as object

- features/main/validation.feature
- src/Hal/Serializer/ConstraintViolationListNormalizer.php
- src/Problem/Serializer/ConstraintViolationListNormalizer.php
- src/Serializer/AbstractConstraintViolationListNormalizer.php
- src/Symfony/Bundle/Resources/config/hal.xml
- src/Symfony/Validator/Exception/ValidationException.php
- tests/Fixtures/TestBundle/Document/DummyValidationSerializedName.php
- tests/Fixtures/TestBundle/Entity/DummyValidationSerializedName.php
- tests/Hydra/Serializer/ConstraintViolationNormalizerTest.php
- tests/Problem/Serializer/ConstraintViolationNormalizerTest.php
https://github.com/api-platform/core/issues/5845#issuecomment-1744580590 good catch thanks @dannyvw !
> fix(validation): normalize constraint violation list

- features/main/validation.feature
- src/JsonApi/Serializer/ItemNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/Tests/AbstractItemNormalizerTest.php
| Tickets       | https://github.com/api-platform/core/issues/5843
Completes https://github.com/api-platform/core/pull/5170
> feat: improve `collectDenormalizationErrors`

- src/JsonSchema/SchemaFactory.php
- tests/Fixtures/TestBundle/Entity/Issue5793/BagOfTests.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
| Branch       | main 
https://github.com/api-platform/core/issues/5845#issuecomment-1747726584
> fix(jsonschema): field with unknown_type

- features/jsonld/disable_id_generation.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/DisableIdGeneration.php
>  fix(serializer): allow usage of genId property for collection #5858 

- src/Metadata/Extractor/schema/resources.xsd
> Add itemUriTemplate to resources.xsd

- src/Symfony/Bundle/Resources/public/fonts/open-sans/400.css
- src/Symfony/Bundle/Resources/public/fonts/open-sans/700.css
https://github.com/api-platform/core/issues/5728
> minor: remove reference to .woff fonts-format

- features/openapi/docs.feature
- src/JsonSchema/Tests/TypeFactoryTest.php
- src/JsonSchema/TypeFactory.php
Actually it fixes the same bug as in that [PR](https://github.com/api-platform/core/pull/4681) but for JSON.
> fix(JsonSchema): fix reDoc json sample values

- src/ApiResource/Error.php
- src/Symfony/EventListener/ErrorListener.php
When using xdebug, traces may have arguments, that themselves would go through our normalizers. This isn't needed so we prevent it from happening inside our resources.
I also added a log entry in debug mode to warn that API Platform sends an HTTP Exception.
fixes #5845
> fix: error traces without arguments

- tests/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php
Profiler selector needs fixing after https://github.com/symfony/symfony/pull/47416 that adds `&type=request` to our link.
> chore: symfony dev updates

- src/GraphQl/State/Provider/ReadProvider.php
| Tickets       | Closes #5914
> fix(graphql): use normalization context to get item from IRI

- phpstan.neon.dist
- src/JsonSchema/SchemaFactory.php
- src/JsonSchema/TypeFactory.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/Symfony/Bundle/Resources/config/json_schema.xml
- tests/Fixtures/TestBundle/ApiResource/Issue5896/Foo.php
- tests/Fixtures/TestBundle/ApiResource/Issue5896/LocalDate.php
- tests/Fixtures/TestBundle/ApiResource/Issue5896/TypeFactoryDecorator.php
- tests/Fixtures/app/config/config_common.yml
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
| Tickets       | fixes #5896
We wrongly assumed in #5470 that the TypeFactory would be `@internal` which it is not. We moved the logic related to type computation to our Schema PropertyMetadataFactory so that the schema could get cached. 
This patch restores the TypeFactory behavior.
I think that we should postpone the deprecation of the TypeFactory to 3.3 and provide a way to configure this on non-resources (see #5896) for example:
```php
#[JsonSchema(['type' => 'string', 'format' => 'date'])
class LocalDate {}
```
Overriding the property metadata factory is also an option but requires more code user land.
>  fix(jsonschema): restore type factory usage 

- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> fix(graphql): service missing in debug mode

- features/main/exception_to_status.feature
- src/State/Processor/RespondProcessor.php
- tests/Fixtures/TestBundle/ApiResource/Issue5924/TooManyRequests.php
- tests/State/RespondProcessorTest.php
> fix: use http exception headers

- features/main/exception_to_status.feature
- src/Hydra/Serializer/ErrorNormalizer.php
- src/JsonApi/Serializer/ErrorNormalizer.php
- src/Metadata/Resource/Factory/DeprecationResourceMetadataCollectionFactory.php
- src/Problem/Serializer/ErrorNormalizer.php
- src/Serializer/SerializerContextBuilder.php
- src/Serializer/Tests/SerializerContextBuilderTest.php
- src/State/Processor/RespondProcessor.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/Resources/config/hydra.xml
- src/Symfony/Bundle/Resources/config/jsonapi.xml
- src/Symfony/Bundle/Resources/config/problem.xml
- tests/Fixtures/TestBundle/ApiResource/Issue5921/ExceptionResource.php
- tests/Fixtures/TestBundle/ApiResource/Issue5924/TooManyRequests.php
- tests/Fixtures/TestBundle/Exception/TestException.php
- tests/Fixtures/TestBundle/Serializer/ErrorNormalizer.php
- tests/Fixtures/app/config/config_common.yml
- tests/Problem/Serializer/ErrorNormalizerTest.php
- tests/State/RespondProcessorTest.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
Use defaults.extra_properties.skip_deprecated_exception_normalizers to skip these normalizers.
fixes #5921
> fix: use error normalizers

- src/Doctrine/EventListener/PurgeHttpCacheListener.php
- tests/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
| Branch?       | 3.1 
| Tickets       | -  
| Doc PR        |  -  
**Description**
When a entity has relation to non-resource collection and is flushed, the `PurgeHttpCacheListener` loads each value and checks if it is a resource. This can be a problem with large collections over 10k, it can cause a out-of-memory exception. 
**Solution**
We can check whether the collection contains an entity that is a resource or not before loading each value by checking the class form `$associationMappings[$property]['targetEntity']`
> perf(http_cache): don't load every value for a non-resource collection

- src/GraphQl/Resolver/Factory/ItemResolverFactory.php
- src/GraphQl/Tests/Fixtures/ApiResource/ChildFoo.php
- src/GraphQl/Tests/Fixtures/ApiResource/ParentFoo.php
- src/GraphQl/Tests/Resolver/Factory/ItemResolverFactoryTest.php
| Tickets       |https://github.com/api-platform/core/issues/5750
Please read https://github.com/api-platform/core/issues/5750 to understand and reproduce.
This is the exception I came across while performing a query:
> fix(graphql): item resolver inheritance error 

- features/issues/5926.feature
- src/JsonLd/Serializer/ItemNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/Issue5926/ContentItemCollection.php
- tests/Fixtures/TestBundle/Entity/Issue5926/ContentItemInterface.php
- tests/Fixtures/TestBundle/Entity/Issue5926/Media.php
- tests/Fixtures/TestBundle/Entity/Issue5926/MediaContentItem.php
- tests/Fixtures/TestBundle/Entity/Issue5926/TestIssue5926.php
> fix(serializer): json non-resource intermitent class

- features/main/validation.feature
- src/Symfony/Bundle/Resources/config/symfony/validator.xml
- src/Symfony/Validator/Exception/ValidationException.php
- src/Symfony/Validator/Serializer/ConstraintViolationListNormalizer.php
- tests/Fixtures/TestBundle/Entity/Issue5912/Dummy.php
> fix(serializer): json violation list normalizer

- .github/dependabot.yml
Add dependabot to update github actions.
Configuration is comming from https://github.com/api-platform/api-platform/blob/main/.github/dependabot.yml
> chore(dependabot): add dependabot

- features/graphql/mutation.feature
- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- src/GraphQl/Tests/Resolver/Factory/CollectionResolverFactoryTest.php
- src/GraphQl/Tests/Type/TypeBuilderTest.php
- src/GraphQl/Tests/Type/TypeConverterTest.php
- src/GraphQl/Type/FieldsBuilder.php
- src/GraphQl/Type/TypeBuilder.php
- src/GraphQl/Type/TypeConverter.php
- tests/Fixtures/TestBundle/Entity/Person.php
- tests/Fixtures/TestBundle/Enum/AcademicGrade.php
We have a resource with an array property. The content of this array are enum values. This information can be provided with a doc block. Unfortunatelly on the GraphQL API this was visible as an `iterable`. With the changes in this PR it will be a proper "array of enum", same like i.e. "array of string".
The Behat tests should give you an insight into the details.
> GraphQL: Support Enum collections

- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaGreaterThanRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaLessThanRestriction.php
- tests/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaGreaterThanRestrictionTest.php
- tests/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaLessThanRestrictionTest.php
- tests/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
The generated open api spec is currently invalid for open api 3.1. 
exclusiveMinimum and exclusiveMaximum are still used as boolean, while properties minimum and exclusiveMinimum are merged into one property exclusiveMinimum. 
See https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
The only problem I see now, is that users can configure their open api version. 
But I don't know how I can toggle the logic between 3.0 and 3.1.
Any help is appreciated. Thx!
> Bugfix/exclusive properties dont allow booleans for open api 3.1

- features/json/relation.feature
- src/Doctrine/Orm/Extension/EagerLoadingExtension.php
- tests/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Fixtures/TestBundle/Entity/RelatedDummy.php
- tests/Fixtures/TestBundle/Entity/ThirdLevel.php
| Tickets       | Closes #5847 
In some cases, the EagerLoadingExtension misses some joins it should normally load eagerly. This happens when a *ToOne relationship shares the same inversedBy name than in the parent class. This PR aims to solve this problem and correctly eager join all to-one relationships than should be eager joined.
> fix: missing eager joins on to-one relationships

- features/openapi/docs.feature
- src/JsonSchema/SchemaFactory.php
- tests/Fixtures/TestBundle/Dto/CustomOutputEntityWrapperDto.php
- tests/Fixtures/TestBundle/Entity/WrappedResponseEntity.php
…wrapper
| Tickets       | Closes #https://github.com/api-platform/core/issues/5626
This fixes ar regression introduced in https://github.com/api-platform/core/pull/5469 that caused a recursive openapi schema definition to be generated when using a DTO wrapper as the ApiResource response.
See: https://api-platform.com/docs/core/dto/#implementing-a-read-operation-with-an-output-different-from-the-resource
Ex
```
class CustomOutputEntityWrapperDto
{
/** @var WrappedResponseEntity */
#[Groups(['read'])]
public $data;
}
```
```
#[ApiResource(operations: [new Get(normalizationContext: ['groups' => ['read']], output: CustomOutputEntityWrapperDto::class
)])]
#[ORM\Entity]
class WrappedResponseEntity
{
#[ORM\Id] …
```
> fix(jsonSchema): fix recursive documentation when using a dto entity wrapper

- src/Symfony/Controller/MainController.php
- tests/Symfony/Controller/MainControllerTest.php
> fix(symfony): error in provider without uri variables

- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
| Tickets       | /
The `HydraLinkProcessor` injects links to ApiDocumentation in the response header even when the doc is disabled.
This PR remove the service (like it was the case with the legacy `AddLinkHeaderListener`) when the doc is not enabled.
> fix: remove link to ApiDocumentation when doc is disabled

- src/Symfony/Bundle/Resources/public/init-swagger-ui.js
| Doc PR        | api-platform/docs#1857
I suggest enabling `deepLinking` as a default feature in Swagger UI. This functionality greatly enhances API documentation. WDYT?
With this feature, you can link to specific operations within your API documentation. For example https://petstore.swagger.io/#/user/createUsersWithListInput
> feat: enable Swagger UI deep linking

- src/JsonSchema/Metadata/Property/Factory/SchemaPropertyMetadataFactory.php
- src/JsonSchema/Tests/Fixtures/DummyWithEnum.php
- src/JsonSchema/Tests/Fixtures/Enum/IntEnumAsIdentifier.php
- src/JsonSchema/Tests/Metadata/Property/Factory/SchemaPropertyMetadataFactoryTest.php
Fixes: 6048
| Branch?       | current stable version branch for bug fixes 
| Tickets       | Closes #6048 
> Fix Invalid "type": "int" in openapi/json schema.

- src/Hal/JsonSchema/SchemaFactory.php
- src/Hydra/JsonSchema/SchemaFactory.php
- src/JsonSchema/SchemaFactory.php
- src/JsonSchema/SchemaFactoryAwareInterface.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
> fix(json-schema): keep format subschema generation

- features/hydra/item_uri_template.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/Issue5662/Review.php
> fix: item_uri_template conflict with context on relation

- src/Symfony/EventListener/DeserializeListener.php
- tests/Symfony/EventListener/DeserializeListenerTest.php
I've a custom ConstraintViolationListNormalizer which adds error name to the payload from the constraint error code, but given that listener uses NotNormalizableValueException code which is always 0, getting error name fails, so this sets the correct code
> fix(symfony): use Type constraint violation code instead of exception code

- src/Serializer/ItemNormalizer.php
- tests/Serializer/ItemNormalizerTest.php
| Branch?       | current stable version branch for bug fixes
| Tickets       | Closes [#2594](https://github.com/api-platform/api-platform/issues/2594)
| Doc PR        | 	N/A
I have noticed an inconsistency in the ItemNormalizer.php file regarding the handling of the $context array in the updateObjectToPopulate method.
In the try block, the context is concatenated with ['fetch_data' => true] when calling getResourceFromIri. However, in the corresponding catch block for LegacyInvalidArgumentException|InvalidArgumentException, the same concatenation with fetch_data is not performed when setting the OBJECT_TO_POPULATE in the context:
```php
// In try block
$context[self::OBJECT_TO_POPULATE] = …
```
> Fix: Inconsistency in Context Concatenation with fetch_data

- .php-cs-fixer.dist.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaChoiceRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaGreaterThanOrEqualRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaGreaterThanRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaLengthRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaLessThanOrEqualRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaLessThanRestriction.php
- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaRangeRestriction.php
- tests/Fixtures/DummyCollectionValidatedEntity.php
- tests/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaChoiceRestrictionTest.php
- tests/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestrictionTest.php
- tests/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
| Tickets       | Closes #5414, closes #5413
Supersedes https://github.com/api-platform/core/pull/5505.
> fix(symfony): do not use metadata when merging schema constraints in Collection constraint

- composer.json
| Tickets       | /
| Doc PR        | /
This conflict prevents people from installing 3.2.8
Same commit than cbc803cab81bc6acbe74c4db4eba63bc8539aa16 for 3.2 branch
> fix: Remove comparator conflict in 3.2

- features/graphql/query.feature
- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- src/GraphQl/Resolver/Factory/ResolverFactory.php
- src/GraphQl/Serializer/ItemNormalizer.php
- src/GraphQl/Tests/Resolver/Factory/ResolverFactoryTest.php
- src/GraphQl/Tests/State/Processor/NormalizeProcessorTest.php
- src/Metadata/Resource/ResourceMetadataCollection.php
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/MultiRelationsDummy.php
- tests/Fixtures/TestBundle/Document/MultiRelationsNested.php
- tests/Fixtures/TestBundle/Document/MultiRelationsNestedPaginated.php
- tests/Fixtures/TestBundle/Entity/MultiRelationsDummy.php
- tests/Fixtures/TestBundle/Entity/MultiRelationsNested.php
- tests/Fixtures/TestBundle/Entity/MultiRelationsNestedPaginated.php
We sometimes use JSON arrays to persist a collection of Value Objects which are not an entity. So this collection should be treated like a property of the parent entity. On the GraphQL queries fetching this collection was not an easy task. We had to create some special resolvers which try to fetch the ID of the parent entity out of the `$context`, load it and determine the collection from there.
So I decided to spend this PR that utilizes the `nested` property of the `ApiProperty` and uses the collection already loaded with the entity when no own resolver is given. I added a Behat test that covers that new scenario.
> GraphQL: Nested Collections

- src/Doctrine/Common/State/LinksHandlerLocatorTrait.php
- src/Doctrine/Common/State/LinksHandlerTrait.php
- src/Doctrine/Odm/Metadata/Resource/DoctrineMongoDbOdmResourceCollectionMetadataFactory.php
- src/Doctrine/Odm/State/CollectionProvider.php
- src/Doctrine/Odm/State/ItemProvider.php
- src/Doctrine/Odm/State/LinksHandlerTrait.php
- src/Doctrine/Orm/Metadata/Resource/DoctrineOrmResourceCollectionMetadataFactory.php
- src/Doctrine/Orm/State/CollectionProvider.php
- src/Doctrine/Orm/State/ItemProvider.php
- src/Doctrine/Orm/State/LinksHandler.php
- src/Doctrine/Orm/State/LinksHandlerTrait.php
- src/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
- src/Symfony/Bundle/Resources/config/doctrine_orm.xml
This introduces `ApiPlatform\Doctrine\O(r|d)m\State\LinksHandler` so that users can decorate that service and use default link handling on top of their code.
> feat: allow to extend link handling

- features/http_cache/tag_collector_service.feature
- src/Hal/Serializer/ItemNormalizer.php
- src/JsonApi/Serializer/ItemNormalizer.php
- src/Serializer/TagCollectorInterface.php
- tests/Behat/HttpCacheContext.php
- tests/Fixtures/TestBundle/HttpCache/TagCollectorCustom.php
I tested PR #5753 in a real application after it was merged into main.
I noticed, that while evolving the PR I broke the implementation for HAL and JSONAPI when simplifying the function signature of the TagCollectorInterace (commit https://github.com/api-platform/core/pull/5758/commits/65502080d5a3d7a22dcd30e7a8322104ea0ff531). The context keys `object` and `format` were not properly propagated for HAL and JSONAPI. Unfortunately, there were no test cases for these formats.
This PR:
- fixes implementation for HAL and JSONAPI
- adds additional test coverage for these formats
- cleans up the code in `TagCollectorCustom` to provide more comments and more clarity
> fix(serializer): fix TagCollector for JSONAPI and HAL format

- src/State/Provider/ContentNegotiationProvider.php
- src/State/Provider/DeserializeProvider.php
- src/Symfony/EventListener/DeserializeListener.php
- tests/State/Provider/ContentNegotiationProviderTest.php
- tests/State/Provider/DeserializeProviderTest.php
- tests/Symfony/EventListener/DeserializeListenerTest.php
In PHP, requests without content-type will result in an empty string, not null. This PR modifies several checks for empty content-type in the codebase. They failed because they previously check for a null value, not an empty string.
Also related: https://github.com/symfony/symfony/pull/53380
> fix: In PHP, requests without content-type will result in an empty content-type, not null

- features/openapi/docs.feature
- src/Documentation/Action/DocumentationAction.php
- src/Documentation/Action/EntrypointAction.php
- src/OpenApi/Command/OpenApiCommand.php
- src/OpenApi/Serializer/LegacyOpenApiNormalizer.php
- src/Symfony/Bundle/Resources/config/openapi.xml
- tests/Behat/JsonApiContext.php
- tests/Documentation/Action/DocumentationActionTest.php
| Branch       | 3.2
| Tickets       | Closes #5978
Continue work of #6033
TODO:
> compatibility with OpenAPI 3.0

- composer.json
- src/Test/DoctrineMongoDbOdmFilterTestCase.php
[DoctrineMongoDBBundle v5](https://github.com/doctrine/DoctrineMongoDBBundle/releases/tag/5.0.0-RC1) provides full compatibility with Symfony 7, removing the last deprecation that make the build fail.
(I'm checking compatibility with libraries like API platform before tagging a the stable version)
> Add support for MongoDB ODM Bundle v5 with Symfony 7.0 full compatibility

- src/HttpCache/State/AddHeadersProcessor.php
- src/Hydra/State/HydraLinkProcessor.php
- src/State/CallableProcessor.php
- src/State/Processor/AddLinkHeaderProcessor.php
- src/State/Processor/RespondProcessor.php
- src/State/Processor/SerializeProcessor.php
- src/State/Processor/WriteProcessor.php
- src/State/ProcessorInterface.php
- src/State/ProviderInterface.php
- src/Symfony/State/MercureLinkProcessor.php
- tests/State/RespondProcessorTest.php
In a next PR, the maker command could also be improved to take the name of the provided entity class as an optional parameter.
> fix: better generics support for State\ProcessorInterface

- src/JsonSchema/BackwardCompatibleSchemaFactory.php
- src/Symfony/Bundle/Resources/config/json_schema.xml
- src/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
- tests/Fixtures/TestBundle/Entity/Issue6041/NumericValidated.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
| Tickets       | Closes #6041
I am opening this PR as a starting point to close the issue linked above. From a quick conversation with @soyuka in Symfony Slack workspace I am introducing a top-level decorator that targets `integer` and `number` properties that have range definition in them. The definition is set to Draft 4 of jsonschema since the assertion library the API Platform comes with does not recognize current Draft 6 defintion. 
I want to add tests but I am not sure what are the preferred tests by the team. There are no behat tests for jsonschema checks directly (they are indirectly assessed in openapi feature files). I thought to add a `KernelTestCase` since the schema will append the extra …
> fix(jsonschema): keep integer and number properties draft 4 compliant

- src/GraphQl/Resolver/Stage/SerializeStage.php
- src/GraphQl/State/Processor/NormalizeProcessor.php
- src/GraphQl/Tests/Resolver/Factory/CollectionResolverFactoryTest.php
- src/GraphQl/Tests/Resolver/Stage/SerializeStageTest.php
- src/GraphQl/Tests/State/Processor/NormalizeProcessorTest.php
| Branch?       | current stable version branch for bug fixes
This pull request is a draft to fix a bug discovered on the current graphql implementation.
If the following request is sent:
```
{
nameMetricFirstnameDepartmentOccurrences {
collection {
geoEntityDepartment {
label
}
}
}
}
```
The current implementation executes the count query on the database, to populate `paginationInfo` in the result until this information is dropped by the method `ReferenceExecutor::collectAndExecuteSubFields`.
I would expect the count query to be executed only if the `paginationInfo` is requested, like with the following request:
```
{
nameMetricFirstnameDepartmentOccurrences {
paginationInfo {
itemsPerPage
lastPage
totalCount
}
collection { …
```
> fix(graphql): remove count query if paginationInfo is not requested

- src/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
- tests/Fixtures/TestBundle/Entity/Issue6146/Issue6146Child.php
- tests/Fixtures/TestBundle/Entity/Issue6146/Issue6146Parent.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
| Tickets       | Closes https://github.com/api-platform/core/issues/6146
In https://github.com/api-platform/core/pull/6098 the behavious was changed in the test trait.
Before when you didn't provide a serialization context, the SerializationFactory would initialize it to the normalization context of the operation.
With this change the normalization context is an empty array instead so we loose the normalization context.
Solution: use the normalization context of the operation if the serialization context is null.
> fix: Use normalisation context when none is provided in tests

- src/Doctrine/Common/CollectionPaginator.php
- src/Doctrine/Common/SelectablePaginator.php
- src/Doctrine/Common/SelectablePartialPaginator.php
- src/Doctrine/Common/Tests/CollectionPaginatorTest.php
- src/Doctrine/Common/Tests/SelectablePaginatorTest.php
- src/Doctrine/Common/Tests/SelectablePartialPaginatorTest.php
| Doc PR        | https://github.com/api-platform/docs/pull/1895
Adds three paginators for Doctrine Collection & Selectable.
Some use cases:
```php
use ApiPlatform\Doctrine\Common\SelectablePaginator;
use ApiPlatform\Doctrine\Common\CollectionPaginator;
/** @var BookRepository $repository */
$bookPaginator = new SelectablePaginator($repository, $currentPage, $itemsPerPage);
/** @var Book $book */
/** @var Collection<array-key,Chapter> */
$chapters = $book->getChapters();
$chapterPaginator = new CollectionPaginator($chapters, $currentPage, $itemsPerPage);
```
> feat: Paginators for Doctrine Collection & Selectable

- src/Hydra/Serializer/CollectionFiltersNormalizer.php
This PR purpose is to resolve issue with the splitted version.
`ApiPlatform/Api` is not exported in any components, the `FilterLocatorTrait` cannot be loaded.
This is a quick & dirty workaround that solves the 3.3.0-alpha.1 issue but I think we must find abetter way to solve and provide the filters.
We could describle a FilterRegistryInterface in `ApiPlatform/Metadata` and inject it in the variouscomponents that relies on this feature (Hydra, ParameterValidator) the symfony component could fill an implementation of this registry and inject it.
> fix(hydra): remove dependency from ApiPlatform/Api dependency

- src/GraphQl/State/Provider/ReadProvider.php
- src/GraphQl/Tests/State/Provider/ReadProviderTest.php
| Branch?       | `3.2`
| Tickets       | Closes api-platform/core#6072
After upgrading to 3.2 we noticed a new error `Item from read provider should be a nullable object.` in our projects, when request single resource via GraphQL Query if such resource does not exists with provided id, see api-platform/core#6072.
> fix: return null instead of exception for GraphQL Query operation

- features/graphql/schema.feature
- src/GraphQl/Tests/Type/FieldsBuilderTest.php
- src/GraphQl/Tests/Type/TypeBuilderTest.php
- src/GraphQl/Tests/Type/TypeConverterTest.php
- src/GraphQl/Type/ContextAwareTypeBuilderInterface.php
- src/GraphQl/Type/FieldsBuilder.php
- src/GraphQl/Type/TypeBuilder.php
- src/GraphQl/Type/TypeConverter.php
- tests/Fixtures/TestBundle/Entity/OptionalRequiredDummy.php
| Branch?       | `main`
| Tickets       | https://github.com/api-platform/api-platform/issues/2562
We have a number of cases where we support creating new entities through a relationship with a 'parent' entity. This works fine, but the prop is always marked as 'required' in the GraphQL types that are being generated. This PR addresses this issue and will look for `#[ApiProperty(required: false)]` or `#[ORM\JoinColumn(nullable: true)]` to mark the input as non-required in the GraphQL type.
> fix(graphql): Embedded nullable relations graphql

- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
If the operation has `input: false`, then `OpenApiFactory` should skip adding the `requestBody` for that operation.
> fix(openapi): skip requestBody if input is false

- src/Util/AttributesExtractor.php
This change made relying on AttributesExtractor flawky, let's revert that.
> fix(symfony): revert breaking change on attributes extractor

- src/JsonSchema/BackwardCompatibleSchemaFactory.php
- src/JsonSchema/Tests/BackwardCompatibleSchemaFactoryTest.php
fixes #6041, the `in_array` condition was not working when the `type` is an array (multiple types like `null, number`)
> fix(json-schema): multiple type support (draft4)

- src/OpenApi/Factory/OpenApiFactory.php
I think it is an unexprected behaviour that resource description and summary take the `shortName` parameter into consideration when generating the OpenApi documentation but the identifier parameter description doesn't.
| Branch?       | current stable version
> fix: description of identifier parameter

- features/authorization/deny.feature
- src/Doctrine/Orm/Filter/OrderFilter.php
- src/Metadata/ApiProperty.php
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/Tests/AbstractItemNormalizerTest.php
- tests/Fixtures/TestBundle/Document/SecuredDummy.php
- tests/Fixtures/TestBundle/Entity/SecuredDummy.php
- tests/Fixtures/TestBundle/Security/SecuredDummyAttributeBasedVoter.php
- tests/Fixtures/app/config/config_common.yml
| Tickets       | Closes #5824
| Doc PR        | Inlined
> feat: improve ApiProperty::security using property name

- features/mercure/publish.feature
- src/Doctrine/EventListener/PublishMercureUpdatesListener.php
- tests/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
- tests/Fixtures/TestBundle/Document/MercureWithTopicsAndGetOperation.php
- tests/Fixtures/TestBundle/Entity/MercureWithTopicsAndGetOperation.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
| Doc PR        | **TODO**
When using Mercure on a resource, it's possible to specify multiple topics using Symfony Expression Language:
```php
#[ApiResource(
mercure: [
'topics' => [
'@=iri(object)',
'@=iri(object.getOwner()) ~ "/?topic=" ~ escape(iri(object))',
'@=iri(object, '.UrlGeneratorInterface::ABS_PATH.')', // you can also change the reference type
'https://example.com/books/1',
],
],
)]
```
(source: https://api-platform.com/docs/core/mercure/#dispatching-restrictive-updates-security-mode)
But the `iri` Expression Language function does not allow to send the second argument of [IriConverter::getIriFromResource](https://github.com/api-platform/core/blob/main/src/Metadata/IriC …
> feat(symfony): add `getOperation` Expression Language function on Mercure topics

- composer.json
- src/Doctrine/Common/Tests/State/PersistProcessorTest.php
- src/Doctrine/EventListener/PublishMercureUpdatesListener.php
- src/Doctrine/EventListener/PurgeHttpCacheListener.php
- src/Doctrine/Orm/AbstractPaginator.php
- src/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- src/Doctrine/Orm/Filter/ExistsFilter.php
- src/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php
- src/Doctrine/Orm/State/LinksHandlerTrait.php
- tests/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
- tests/Doctrine/Orm/Extension/OrderExtensionTest.php
- tests/Doctrine/Orm/Extension/PaginationExtensionTest.php
- tests/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactoryTest.php
- tests/Doctrine/Orm/Metadata/Resource/DoctrineOrmLinkFactoryTest.php
- tests/Doctrine/Orm/PaginatorTest.php
- tests/Doctrine/Orm/State/CollectionProviderTest.php
- tests/Doctrine/Orm/State/ItemProviderTest.php
- tests/Doctrine/Orm/Util/QueryBuilderHelperTest.php
- tests/Fixtures/TestBundle/Doctrine/Generator/UuidGenerator.php
- tests/Fixtures/TestBundle/Doctrine/Orm/EntityManager.php
- tests/Fixtures/TestBundle/State/OperationResourceProcessor.php
> fix(doctrine): doctrine/orm:^3.0 support

- src/Metadata/ApiResource.php
- src/Metadata/Operation.php
- src/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/MainControllerResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/OperationNameResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
- src/Metadata/Tests/OperationsTest.php
- tests/Fixtures/TestBundle/ApiResource/OperationPriorities.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
`Operations->sort()` are not called in every metadata factory. Instead of adding this call on each related metadata factory, I think it's better (and safer) to always call it on `withOperations` method call.
> fix(metadata): fix Operations sort

- features/graphql/query.feature
- src/GraphQl/Resolver/Factory/ResolverFactory.php
- src/GraphQl/Serializer/ItemNormalizer.php
- src/GraphQl/State/Provider/NoopProvider.php
- tests/Fixtures/TestBundle/Document/MultiRelationsDummy.php
- tests/Fixtures/TestBundle/Document/MultiRelationsNested.php
- tests/Fixtures/TestBundle/Document/MultiRelationsNestedPaginated.php
- tests/Fixtures/TestBundle/Document/SoMany.php
| Tickets       | Closes #6107 
https://github.com/api-platform/core/pull/6038 was introduced but we had mongodb tests disabled. Though the new scenario has been disabled temporarily for mongo. I activated it again and updated the mongo test fixtures to represent the same case as the ORM ones do.
> fix(graphql): nested collection for mongo

- features/openapi/docs.feature
- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Options.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Symfony/Bundle/Resources/config/openapi.xml
- tests/Fixtures/TestBundle/ApiResource/Issue6151/OverrideOpenApiResponses.php
- tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
> feat(openapi): disable response override

- src/Api/Entrypoint.php
- src/Api/QueryParameterValidator/Validator/Enum.php
- src/Api/QueryParameterValidator/Validator/Length.php
- src/Api/QueryParameterValidator/Validator/MultipleOf.php
- src/Api/QueryParameterValidator/Validator/Pattern.php
- src/Api/QueryParameterValidator/Validator/Required.php
| Tickets       | Closes #6224
> fix: class_exists calls without argument

- src/JsonSchema/SchemaFactory.php
- tests/Fixtures/TestBundle/ApiResource/Issue6212/Bird.php
- tests/Fixtures/TestBundle/ApiResource/Issue6212/Robin.php
- tests/Fixtures/TestBundle/ApiResource/Issue6212/Wren.php
- tests/Fixtures/TestBundle/Entity/Issue6212/Nest.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
| Tickets       | Closes #6212 
As requested by @soyuka  
For the tests I just imported what I had in a sandbox to create the issue. Happy to modify on request.
> fix(jsonschema) don't skip remaining multiple union types

- features/issues/5926.feature
- src/Hal/Serializer/ItemNormalizer.php
- src/JsonApi/Serializer/ItemNormalizer.php
| Branch?       |3.2
| Tickets       | #5926
This is meant as a follow up to #5937, as both the JSON:API & HAL serializers need the context check (c.f. #5937) in the `normalize()` method.
For reference here, without the code change the Behat test will fail with a 400 response that contains a "No resource class found […]" exception emitted from the `ResourceClassResolver`.
> fix(serializer): json non-resource intermittent class (HAL & JSON:API)

- features/openapi/docs.feature
- src/Metadata/Delete.php
- src/Metadata/Error.php
- src/Metadata/Get.php
- src/Metadata/GetCollection.php
- src/Metadata/HttpOperation.php
- src/Metadata/NotExposed.php
- src/Metadata/Patch.php
- src/Metadata/Post.php
- src/Metadata/Put.php
- src/OpenApi/Attributes/Webhook.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
- tests/Fixtures/TestBundle/Entity/DummyWebhook.php
Possible to configure a webhook via an attribute:
`
#[ApiResource(operations: [
new Post(openapi: new Webhook(name: 'a cute name')
)),
new Get(openapi: new Webhook(
name: 'a cute name',
pathItem: new PathItem(
get: new Operation(
summary: 'Something else here',
description: 'Something else here for example',
),
)
)),
]
)]`
and generate documentation
> feat: add webhook - openapi

- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/ApiResource/Issue6211/ArrayPropertyDtoOperation.php
- tests/Fixtures/TestBundle/Dto/ArrayPropertyDto.php
- tests/Functional/ArrayDtoTest.php
> fix(serializer): collection property in an output dto

- src/Hydra/Serializer/DocumentationNormalizer.php
- tests/Hydra/Serializer/DocumentationNormalizerTest.php
Allows to add informations to the `hydra:property` documentation: 
```php
class Dummy {
#[ApiProperty(jsonLdContext: ['hydra:property' => ['rdfs:label' => 'change this value', 'owl:maxCardinality' => 5]]);
public array $foo;
}
```
Previously only `@type` was read from `getIris`, this brings more flexibility.
> feat(hydra): read hydra:property from ApiProperty::jsonLdContext

- src/Hal/JsonSchema/SchemaFactory.php
- src/Hydra/JsonSchema/SchemaFactory.php
- src/JsonSchema/SchemaFactory.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Symfony/Bundle/Resources/config/json_schema.xml
- tests/Hal/JsonSchema/SchemaFactoryTest.php
- tests/Hydra/JsonSchema/SchemaFactoryTest.php
- tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
| Tickets       | Closes #6228
I've not figured out a good way to CI test this, so guidance will be gratefully appreciated.
To reproduce the base issue, apply the following to the `3.2` branch and run `vendor/bin/simple-phpunit --filter JsonSchemaGenerateCommandTest::testSubSchemaJsonLd`
```diff
diff --git a/src/Hydra/JsonSchema/SchemaFactory.php b/src/Hydra/JsonSchema/SchemaFactory.php
index b04ba616b8..43478de74d 100644
--- a/src/Hydra/JsonSchema/SchemaFactory.php
+++ b/src/Hydra/JsonSchema/SchemaFactory.php
@@ -186,7 +186,7 @@ public function buildSchema(string $className, string $format = 'jsonld', string
public function addDistinctFormat(string $format): void
{
-        if ($this->schemaFactory …
```
> fix(jsonschema): generation of non-LD+JSON distinct schema formats

- src/JsonApi/JsonSchema/SchemaFactory.php
- src/Symfony/Bundle/Resources/config/jsonapi.xml
- tests/JsonApi/JsonSchema/SchemaFactoryTest.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
| Tickets       | Closes #3930
~**NOTE:** This depends on recent commits in `3.2` that haven't been merged down to `main` yet. So it is submitted against `3.2` and will be rebased & updated to target `main` after said branch merge.~
> feat(jsonschema): JSON:API schema factory

- features/http_cache/tag_collector_service.feature
- features/jsonapi/absolute_url.feature
- features/jsonapi/jsonapi.feature
- features/jsonapi/network_path.feature
- features/jsonapi/related-resouces-inclusion.feature
- src/JsonApi/Serializer/ItemNormalizer.php
| Tickets       | Closes #6265
Additions to the expectations in the `.feature` files are the missing data property arrays mentioned in the spec/issue.
> fix(jsonapi): return empty data array for empty relation

- features/graphql/query.feature
- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
- src/GraphQl/Resolver/Factory/ItemResolverFactory.php
- src/GraphQl/Resolver/Factory/ItemSubscriptionResolverFactory.php
- src/GraphQl/Resolver/Factory/ResolverFactory.php
- src/GraphQl/Resolver/Factory/ResolverFactoryInterface.php
- src/GraphQl/Tests/Resolver/Factory/ResolverFactoryTest.php
- src/GraphQl/Type/FieldsBuilder.php
- src/Symfony/Bundle/Resources/config/graphql.xml
- src/Symfony/GraphQl/Resolver/Factory/DataCollectorResolverFactory.php
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/MultiRelationsDummy.php
- tests/Fixtures/TestBundle/Document/MultiRelationsResolveDummy.php
- tests/Fixtures/TestBundle/Entity/MultiRelationsDummy.php
- tests/Fixtures/TestBundle/Entity/MultiRelationsResolveDummy.php
- tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryNotRetrievedItemResolver.php
- tests/Fixtures/TestBundle/GraphQl/Resolver/MultiRelationsResolveQueryItemResolver.php
- tests/Fixtures/app/config/config_common.yml
- tests/Fixtures/app/config/config_mongodb.yml
| Tickets       | Closes #6083 
This PR introduces a new the test case especially for properties and Many-To-One-Relations being `null`. It fixes the issues relevant for 3.2. There is another PR https://github.com/api-platform/core/pull/6084 that additionally provides a fix for the nested collection feature which was recently introduced on the main branch.
> GraphQL: Errors with nullish ManyToOne-Relation when using new ResolverFactory (for version 3.2)

- features/openapi/docs.feature
- src/Symfony/Bundle/Resources/config/graphql.xml
> fix(graphql): increment graphql normalizer priority

- src/JsonApi/JsonSchema/SchemaFactory.php
- src/JsonSchema/DefinitionNameFactory.php
- src/JsonSchema/DefinitionNameFactoryInterface.php
- src/JsonSchema/ResourceMetadataTrait.php
- src/JsonSchema/SchemaFactory.php
- src/JsonSchema/Tests/SchemaFactoryTest.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
- src/OpenApi/Tests/Serializer/OpenApiNormalizerTest.php
- src/Symfony/Bundle/Resources/config/json_schema.xml
- src/Symfony/Bundle/Resources/config/jsonapi.xml
- tests/Hal/JsonSchema/SchemaFactoryTest.php
- tests/Hydra/JsonSchema/SchemaFactoryTest.php
- tests/JsonApi/JsonSchema/SchemaFactoryTest.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
- tests/JsonSchema/DefinitionNameFactoryTest.php
| Tickets       | Related #6250
Per https://jsonapi.org/format/#fetching-includes which the serializer already handles beautifully.
> fix(jsonapi): add missing "included" schema parts

- src/Symfony/EventListener/QueryParameterValidateListener.php
- src/Symfony/Tests/EventListener/QueryParameterValidateListenerTest.php
| Tickets       | Closes #6243
> fix: reorder early return QueryParameterValidateListener

- src/JsonSchema/SchemaFactory.php
- tests/Fixtures/TestBundle/ApiResource/Issue6299/Issue6299.php
- tests/Fixtures/TestBundle/ApiResource/Issue6299/Issue6299CollectionDto.php
- tests/Fixtures/TestBundle/ApiResource/Issue6299/Issue6299ItemDto.php
- tests/Fixtures/TestBundle/ApiResource/Issue6299/Issue6299OutputDto.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
| Tickets       | Closes #6299, closes https://github.com/api-platform/api-platform/issues/2634
> fix(jsonschema): don't try to define $ref if set in attributes

- src/Symfony/Messenger/ContextStamp.php
- tests/Symfony/Messenger/ContextStampTest.php
| Tickets       | Closes https://github.com/api-platform/api-platform/issues/2611
In some case, a "Serialization of 'Closure' is not allowed" Exception is thrown when using Messenger. This is due to the fact that the `$context` array is passed to the Envelope via the ContextStamp and that `$context['request']` is set with a not serializable Request object.
Symfony does not guarantee that a Request is serializable so the best solution would be to completely unset `$context['request']` in the ContextStamp. However this would be a breaking change. So, I'm proposing an alternative solution by unsetting `$context['request']` only when the Request object has a session as it seems to be the identified buggy …
> fix(symfony): context not serializable when session

- src/ParameterValidator/FilterLocatorTrait.php
Add return type like exists in ApiPlatform\Api\FilterLocatorTrait.
> fix: add legacy FilterInterface as return type of getFilter function

- .github/workflows/ci.yml
- .github/workflows/guides.yaml
- composer.json
- docs/src/DependencyInjection/Compiler/AttributeFilterPass.php
see https://github.com/api-platform/core/pull/6288#pullrequestreview-1996000452 ping @GwendolenLynch
> ci: use simple-phpunit on lowest

- features/hal/collection_uri_template.feature
- features/jsonapi/collection_uri_template.feature
- src/Hal/Serializer/ItemNormalizer.php
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Document/PropertyCollectionIriOnlyRelation.php
- tests/Fixtures/TestBundle/Document/PropertyCollectionIriOnlyRelationSecondLevel.php
- tests/Fixtures/TestBundle/Entity/PropertyCollectionIriOnlyRelation.php
- tests/Fixtures/TestBundle/Entity/PropertyCollectionIriOnlyRelationSecondLevel.php
This PR fixes a bug introduced with https://github.com/api-platform/core/pull/5675.
For embedded subresources using the new uriTemplate property, components cache is wrongly populated and used for different entities, hence ending in wrong IRIs used in the response.
Note that the IRI-link of the children subresource in the 2nd relation "asb2" is wrongly `"/property_collection_iri_only_relations/1/children"` instead of `"/property_collection_iri_only_relations/2/children"`.
```json
{
"_links": {
"self": {
"href": "/property_collection_iri_onlies/1"
},
"propertyCollectionIriOnlyRelation": {
"href": "/property-collection-relations"
},
"iterableIri": {
"href": …
```
> fix(serializer): uriTemplate wrong cache usage in hal format

- src/Symfony/Messenger/ContextStamp.php
- tests/Symfony/Messenger/ContextStampTest.php
| Tickets       | Closes https://github.com/api-platform/api-platform/issues/2611
Following https://github.com/api-platform/core/pull/6302, here is the PR to completely remove request object from `$context` in the `ContextStamp`. Symfony does not guarantee that the Request object is serializable.
As specified in the commit description, this is a breaking change.
> fix(symfony)!: context stamp not serializable because of request object

- src/JsonApi/JsonSchema/SchemaFactory.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
When using the model I describe in https://github.com/api-platform/core/issues/6212#issuecomment-2019909645, the `$className` variable is overwritten by `null` when an additional (3rd +) type is in the union.
> fix(jsonapi): exit loop when relationship class is found

- src/GraphQl/State/Provider/ResolverProvider.php
- src/GraphQl/Tests/State/Provider/ResolverProviderTest.php
| Branch       | 3.2
With the new `ResolverProvider` some cases with inheritance are broken in our project. It was not a big deal to find out that `ItemResolverFactory` also checked if the resolver provided a subclass of the `resourceClass`. So I added this also to the `ResolverProvider` and everything works like a charm. I am not sure if it should also be extended in `ReadProvider` - there is similar code, but I had no problem with that. Thx for your advice.
> fix(graphql): check inheritance in ResolverProvider

- features/serializer/vo_relations.feature
- src/Serializer/AbstractItemNormalizer.php
Accidentally have closed https://github.com/api-platform/core/pull/5649 PR
This is its copy.
Have found that if validation attributes are specified on DTOs or if the `Valid()` constraint is used on not api-resource property (just an entity in example) then Symfony's [AbstractNormalizer](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php) is used and it has a bit different `MissingConstructorArgumentsException` [exception message that also contains the list of missed arguments](https://github.com/symfony/symfony/blob/9b2ac59e8a373e983157f9a57de8ae951cc1a3ba/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L414).
But in …
> feat(Serializer): update MissingConstructorArgumentsException message

- src/Metadata/Extractor/XmlResourceExtractor.php
- src/Metadata/Extractor/schema/resources.xsd
- src/Metadata/Tests/Extractor/XmlExtractorTest.php
- src/Metadata/Tests/Extractor/xml/valid.xml
| Tickets       | Closes #6031 
Allow using `routeName` Operation property when configuring resources with XML
> fix(metadata): allow extracting routeName from XML config

- src/Doctrine/EventListener/PurgeHttpCacheListener.php
**Waiting for unit tests to pass again on `3.2` so I can test further, just parking it here to make the issue known.**
Remove deprecated ClassUtils from the PurgeHttpListener for doctrine 3, still need to check with due diligence and update tests, but these are failing right now.
> fix(doctrine): Doctrine 3 ApiPlatform\Doctrine\EventListener\PurgeHttpCacheListener uses deprecated ClassUtils class.

- src/Metadata/Parameter.php
- src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
- src/ParameterValidator/Validator/ArrayItems.php
- src/ParameterValidator/Validator/Bounds.php
- src/ParameterValidator/Validator/Enum.php
- src/ParameterValidator/Validator/Length.php
- src/ParameterValidator/Validator/MultipleOf.php
- src/ParameterValidator/Validator/Pattern.php
- src/ParameterValidator/Validator/Required.php
- src/ParameterValidator/Validator/ValidatorInterface.php
- src/State/Provider/ParameterProvider.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/Resources/config/state/provider.xml
- src/Symfony/Bundle/Resources/config/state/state.xml
- src/Symfony/Bundle/Resources/config/symfony/parameter_validator.xml
- src/Symfony/Validator/State/ParameterValidatorProvider.php
- tests/Fixtures/TestBundle/ApiResource/WithParameter.php
- tests/Functional/Parameters/ValidationTests.php
Adds constraint to parameters to allow validation:
> feat(validator): parameter validation

- docs/config/packages/framework.yaml
- docs/guides/http-cache-tags.php
This adds a guide for the functionality added with PR https://github.com/api-platform/core/pull/5758.
I tried to follow the guidelines outlined in https://github.com/api-platform/core/blob/main/docs/README.md.
Managed to run the tests locally, although only when providing `APP_GUIDE` environment variable. Otherwise it would give me a "No guide." error.
I didn't manage to run the WASM//browser version. Could use some help with that.
> docs: add guide for custom TagCollector service

- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
This is hard to test right now as our AppKernel sets that flag up as part of our test matrix, I catched it while updating the distribution https://github.com/api-platform/api-platform/pull/2700
> fix(symfony): use_symfony_listeners before registering services

- features/main/patch.feature
- src/Symfony/EventListener/ReadListener.php
- tests/Fixtures/TestBundle/ApiResource/Issue6355/OrderDto.php
- tests/Fixtures/TestBundle/ApiResource/Issue6355/OrderProductCount.php
- tests/Fixtures/TestBundle/Controller/Issue6355/UpdateOrderProductCountController.php
> fix(symfony): no read should throw on wrong uri variables

- features/jsonld/no_output.feature
- src/Metadata/Resource/Factory/InputOutputResourceMetadataCollectionFactory.php
- src/State/Processor/RespondProcessor.php
- tests/Fixtures/TestBundle/ApiResource/Issue6352/NoIriMessage.php
- tests/State/RespondProcessorTest.php
> fix(state): no location header without output

- features/main/input_output.feature
- src/Serializer/SerializerContextBuilder.php
- src/State/Processor/SerializeProcessor.php
- tests/Fixtures/TestBundle/ApiResource/Issue6358/OutputAndEntityClass.php
- tests/Fixtures/TestBundle/ApiResource/Issue6358/OutputAndEntityClassDto.php
- tests/Fixtures/TestBundle/ApiResource/Issue6358/OutputAndEntityClassEntity.php
- tests/Fixtures/TestBundle/Entity/IdentifierShortcut.php
> fix(symfony): no read should not throw on wrong uri variables

- src/Validator/Exception/ValidationException.php
After update to 3.3.3, `ValidationException` called in custom validators code may cause issued.
For example: If you previously used `ValidationException` with only 1st string argument, after migration to 3.3.3 backward backward compatibility is broken.
```
Failed asserting that exception of type "TypeError" matches expected exception
"ApiPlatform\Validator\Exception\ValidationException". Message was: "Exception::__construct(): Argument #2 ($code) must be of type int, null given" at
/app/vendor/api-platform/core/src/Validator/Exception/ValidationException.php:84
```
> fix(validation): ValidationException causes TypeError exception when called with $code=null

- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Model/RequestBody.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
| Tickets       | Closes #2680 
| Doc PR        | _already existing ([see doc](https://api-platform.com/docs/guides/extend-openapi-documentation/#:~:text=When%20a%20field%20is%20not%20specified%20API%20Platform%20will%20add%20the%20missing%20informations.))_ 
Allow to generate a default request content or description if not defined in the extension of OpenApi using `Model\RequestBody`.
For example, on a `POST /greetings/test` operation on a `Greeting` entity with a `id` and a `name`, the following:
```php
#[ApiResource(
mercure: true,
operations: [
new Post(
uriTemplate: '/greetings/test',
openapi: new Operation(
requestBody: new RequestBody(
description: 'Extended description',
),
),
),
],
)]
```
Will …
> feat(openapi): allow optional request body content

- src/Hal/Serializer/ItemNormalizer.php
- src/JsonApi/Serializer/ItemNormalizer.php
The AbstractItemNormalizer allows for the pre-configuration of the IRI within the context. It is proposed that this feature be extended to both the HAL and JsonApi normalizers for consistency and flexibility.
Example usage:
```php
#[ApiResource(
operations: [
new Get(),
new Post(
uriTemplate: '/search/parse-query',
controller: SearchController::class.'::parseQuery',
normalizationContext: ['groups' => ['api:read'], 'iri' => 'not-existing'],
write: false,
),
new Post(
uriTemplate: '/search/parse-url',
controller: SearchController::class.'::parseUrl',
normalizationContext: ['groups' => ['api:read'], 'iri' => 'not-existing'],
input: SearchParseUrlDto::class,
validate: false,
write: false,
),
],
normalizationContext: ['groups' => ['api:read']],
denormalizationContext: ['groups' => …
```
> Allow IRI to be pre-configured in context when serializing in HAL or JsonApi format

- composer.json
- tests/Fixtures/TestBundle/ApiResource/Issue6264/Availability.php
- tests/Fixtures/TestBundle/ApiResource/Issue6264/AvailabilityStatus.php
- tests/Fixtures/TestBundle/ApiResource/Issue6264/BackedEnumTrait.php
- tests/Functional/BackedEnumPropertyTest.php
- tests/Functional/BackedEnumResourceTest.php
| Tickets       | #6264 #6279 #6283 
@soyuka this is just an updated version of the tests I linked yesterday when discussing #6264 & #6279 … and if I m still wrong please just close this PR. :+1: 
These tests illustrate what *was* working for `json`, `jsonhal`, and `jsonld` formats, but breaks now with the change in https://github.com/symfony/symfony/pull/54315
However, if a fix/workaround is found these tests will still add additional coverage for enum resources.
**Notes:**
- Tests pass when with:
-  core `3.2` as-of `v3.2.19` (i.e. pre #6283)
- `symfony/framework-bundle` `<=7.0.5` (i.e. pre https://github.com/symfony/symfony/pull/54315)
- ~Missing `jsonapi` tests due to target branch~ (Derp! serializer …
> test: Backed enum resource tests

- features/openapi/docs.feature
- src/Metadata/Util/ContentNegotiationTrait.php
- src/OpenApi/Serializer/SerializerContextBuilder.php
- src/OpenApi/State/OpenApiProvider.php
- src/State/Provider/DeserializeProvider.php
- src/State/Provider/ReadProvider.php
- src/State/Tests/Provider/ReadProviderTest.php
- src/Symfony/Action/DocumentationAction.php
- src/Symfony/Bundle/Resources/config/openapi.xml
- src/Symfony/EventListener/DeserializeListener.php
- src/Symfony/EventListener/ReadListener.php
- tests/.ignored-deprecations-legacy-events
- tests/State/Provider/DeserializeProviderTest.php
> fix(symfony): documentation request _format

- src/Doctrine/Orm/Extension/QueryCollectionExtensionInterface.php
- src/Doctrine/Orm/Extension/QueryItemExtensionInterface.php
- src/Doctrine/Orm/Filter/AbstractFilter.php
- src/Doctrine/Orm/Tests/Extension/PaginationExtensionTest.php
| Branch?       |3.3
I've added some more phpdoc annotations. Please let me know if I should add more. I've added just some annotations that are relevant for me own use cases.
> fix(metadata) Added phpdoc to ORM

- src/State/Provider/ReadProvider.php
- src/State/Tests/ReadProviderTest.php
| Tickets       | #6404
Hello, this PR let ReadProvider handle nullable request because `RequestParser::getQueryString($request)` expects a request object to work.
We had this bug when using provider in CLI during async export of a GetCollection operation
> fix(state) handle empty request in read provider

- docs/guides/delete-operation-with-validation.php
| Branch?       | stable
Fixing a typo in constraint message.
> Typo fix in delete-operation-with-validation guide

- src/Doctrine/Orm/Extension/ParameterExtension.php
rebase of https://github.com/api-platform/core/pull/6422/commits
> fix(doctrine): use null-safe operator when retrieving parameters

- features/graphql/mutation.feature
- src/Metadata/GraphQl/Operation.php
- src/Symfony/Bundle/Resources/config/graphql/validator.xml
- src/Symfony/Validator/State/ValidateProvider.php
- tests/Fixtures/TestBundle/ApiResource/Issue6354/ActivityLog.php
- tests/Fixtures/TestBundle/ApiResource/Issue6354/CreateActivityLogResolver.php
- tests/Fixtures/app/config/config_common.yml
> fix(graphql): validate after resolver

- src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php
- src/Metadata/Resource/Factory/BackedEnumResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/LinkFactory.php
- src/Metadata/Resource/Factory/OperationDefaultsTrait.php
- src/State/Provider/BackedEnumProvider.php
- src/Symfony/Bundle/Resources/config/graphql.xml
- src/Symfony/Bundle/Resources/config/metadata/resource.xml
- src/Symfony/Bundle/Resources/config/state/provider.xml
- tests/Fixtures/TestBundle/ApiResource/BackedEnumIntegerResource.php
- tests/Fixtures/TestBundle/ApiResource/BackedEnumStringResource.php
- tests/Fixtures/TestBundle/ApiResource/Issue6264/Availability.php
- tests/Fixtures/TestBundle/ApiResource/Issue6264/AvailabilityStatus.php
- tests/Fixtures/TestBundle/ApiResource/Issue6264/BackedEnumStringTrait.php
- tests/Fixtures/TestBundle/ApiResource/Issue6317/Issue6317.php
- tests/Fixtures/TestBundle/ApiResource/ResourceWithEnumProperty.php
- tests/Functional/BackedEnumResourceTest.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
- tests/State/Provider/BackedEnumProviderTest.php
- tests/Symfony/Bundle/Command/OpenApiCommandTest.php
| Tickets       | Closes #6298, closes #6317
Intended for 3.4, so now it is just for review. 
Depends on #6288 as I want to refactor `BackedEnumPlainResourceTest` test methods into those classes.
- Add a provider for `BackedEnum`s
- Identifier is `value` by default, and implementing `function getId()`, etc, works too
- Resource operations will default to only `Get` & `GetCollection` unless otherwise configured 
```php
#[ApiResource]
enum Status: int
{
case DRAFT = 0;
case PUBLISHED = 1;
}
```
`GET /statuses`
```json
[
{
"name": "DRAFT",
"value": 0
},
{
"name": "PUBLISHED",
"value": 1
}
]
```
`GET /statuses/1`
```json
{
"name": "PUBLISHED",
"value": 1
}
```
> feat: BackedEnum resources

- src/Symfony/Bundle/Resources/config/routing/api.xml
- src/Symfony/Bundle/Resources/config/routing/docs.xml
- src/Symfony/Bundle/Resources/config/routing/errors.xml
- src/Symfony/Bundle/Resources/config/routing/genid.xml
- src/Symfony/Bundle/Resources/config/routing/graphql/graphiql.xml
- src/Symfony/Bundle/Resources/config/routing/graphql/graphql_playground.xml
- src/Symfony/Bundle/Resources/config/routing/jsonld.xml
To prevent weird behaviors like this:
```console
$ curl -vk -X DELETE https://localhost                       392ms  Mer 26 jui 19:14:01 2024
snip
< HTTP/2 204
snip
```
> fix(symfony): check method for readonly routes

- src/OpenApi/Command/OpenApiCommand.php
The OpenAPI specification mandates that all keys in the Responses Object be strings, as outlined here: https://github.com/OAI/OpenAPI-Specification/blob/157a4c81ae537ef793b2bee368bc00d88b461de8/versions/3.0.2.md#patterned-fields-1.
This requirement includes values like '200', which PHP typecasts to integers. Therefore, Yaml should also adhere to this rule.
> fix(openapi): Yaml openapi export should have numeric keys as string

- src/JsonSchema/Metadata/Property/Factory/SchemaPropertyMetadataFactory.php
- src/JsonSchema/Tests/Fixtures/DummyWithCustomOpenApiContext.php
- src/JsonSchema/Tests/Metadata/Property/Factory/SchemaPropertyMetadataFactoryTest.php
| Tickets       | Closes https://github.com/api-platform/core/issues/6391
On a calculated field that returns an array, if we add a ApiProperty to change the type into object, the generated OpenAPI does generate a `"type": "object"` but there is also an extra `"items": {"type": "string"}`.
> fix(metadata): wrong schema generated if openapicontext set on array

- src/JsonSchema/SchemaFactory.php
> [!NOTE]
> Is this a new feature? If so, we can close this PR and go to #6395.
In the schema for the request body of `application/merge-patch+json` PATCH operation, all required properties should be output as optional.
> See here: https://datatracker.ietf.org/doc/html/rfc7386#section-3
This PR fixes the SchemaFactory for the `'json'` format to output required properties as optional only for input context of PATCH operations.
For example, for the following entity, the output of the OpenAPI document will change as follows:
```php
#[ORM\Entity(repositoryClass: TodoRepository::class)]
#[ApiResource]
class Todo
{
#[ORM\Id]
#[ORM\GeneratedValue]
#[ORM\Column] …
```
> fix(jsonschema): make all required properties optional in PATCH operation with 'json' format

- composer.json
- src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
- tests/Fixtures/app/AppKernel.php
To avoid having two errors in case of empty /null values during query parameters validation.
> feat(state): review validation for required parameters

- features/graphql/query.feature
- src/Metadata/GraphQl/Operation.php
- src/Metadata/GraphQl/Query.php
- src/Metadata/GraphQl/QueryCollection.php
- src/Metadata/GraphQl/Subscription.php
- src/Symfony/Bundle/Resources/config/graphql/security.xml
- src/Symfony/Security/State/AccessCheckerProvider.php
- tests/Fixtures/TestBundle/ApiResource/Issue6427/SecurityAfterResolver.php
- tests/Fixtures/TestBundle/ApiResource/Issue6427/SecurityAfterResolverResolver.php
- tests/Fixtures/app/config/config_common.yml
> fix(graphql): security after resolver

- src/Elasticsearch/Metadata/Document/Factory/CatDocumentMetadataFactory.php
- src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php
- src/Elasticsearch/State/CollectionProvider.php
- src/Elasticsearch/State/ItemProvider.php
- src/GraphQl/Type/FieldsBuilder.php
- src/Metadata/InflectorInterface.php
- src/Metadata/Operation/DashPathSegmentNameGenerator.php
- src/Metadata/Operation/UnderscorePathSegmentNameGenerator.php
- src/Metadata/Util/AttributeFilterExtractorTrait.php
- src/Metadata/Util/Inflector.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Symfony/Bundle/Resources/config/api.xml
- src/Symfony/Bundle/Resources/config/elasticsearch.xml
- src/Symfony/Bundle/Resources/config/graphql.xml
- src/Symfony/Bundle/Resources/config/legacy/elasticsearch.xml
- src/Symfony/Tests/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
> feat: inflector as service

- src/Metadata/Link.php
- src/Metadata/Parameter.php
- src/State/Provider/SecurityParameterProvider.php
- src/Symfony/Bundle/Resources/config/state/provider.xml
- src/Symfony/Bundle/Resources/config/state/state.xml
- tests/Fixtures/TestBundle/ApiResource/WithSecurityParameter.php
- tests/Functional/Parameters/SecurityTests.php
This PR adds a security property to `Parameter`, and the corresponding state provider to manage it.
**TODO**
> feat(state): add security to parameters

- .github/workflows/ci.yml
- behat.yml.dist
- features/filter/filter_validation.feature
- features/filter/filter_validation_legacy.feature
- src/Doctrine/Common/Filter/OrderFilterTrait.php
- src/Doctrine/Odm/Tests/Filter/OrderFilterTest.php
- src/Doctrine/Odm/Tests/Filter/OrderFilterTestTrait.php
- src/Doctrine/Orm/Tests/Filter/OrderFilterTest.php
- src/Doctrine/Orm/Tests/Filter/OrderFilterTestTrait.php
- src/Hydra/Serializer/CollectionFiltersNormalizer.php
- src/Metadata/Parameter.php
- src/Metadata/Resource/Factory/DeprecationResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
- src/State/Provider/ParameterProvider.php
- src/Symfony/EventListener/QueryParameterValidateListener.php
- src/Symfony/Validator/State/QueryParameterValidateProvider.php
- tests/.ignored-deprecations
- tests/Fixtures/app/AppKernel.php
The idea here is that we deprecate the QueryParameterValidator in 3.4 in favor of using the new parameter attributes (QueryParameter and HeaderParameter). By doing so, we introduce a backward compatibility flag: 
```
defaults: 
extra_properties:
use_legacy_parameter_validator: true
```
This flag is `true` by default in 3.4 and gets removed in 4.0. When using `false` we add parameters for each declared filter and validation will still be effective (according to `$queryParameterValidationEnabled`). A few changes occur though (hence the flag): 
- status code is 422 instead of 400
- there's no more `collectionFormat` support from swagger, indeed this completely changed in OpenAPI 3.1 and we did not yet add the support of `style` validation on parameters …
> feat: deprecate query parameter validator

- src/Symfony/Bundle/SwaggerUi/SwaggerUiProvider.php
- tests/Fixtures/TestBundle/ApiResource/Issue6384/AcceptHtml.php
- tests/Functional/FormatTest.php
Trying to mitigate https://github.com/api-platform/core/issues/6384 but I probably need to come back to this. The swagger interceptor is here to show http errors inside the swagger ui but after testing manually a 404 did not show the swagger ui... I'm not sure this feature is actually working, I want to see what the CI answers.
> fix: swagger ui provider accept html

- features/main/standard_put.feature
- src/JsonLd/Serializer/ItemNormalizer.php
- src/Symfony/Routing/IriConverter.php
| Branch?       | 3.3  
| Tickets       | Closes https://github.com/api-platform/core/issues/6225 
| Doc PR        | Feature already documented
Allaw `@id`, `@type`, `@context` with JsonLd. With this it's possible to use the `@id` as [described in the documentation ](https://api-platform.com/docs/core/serialization/#denormalization) while using `allow_extra_attributes: false`.
More info in https://github.com/api-platform/core/pull/6402.
> fix(jsonld): allow @id, @context and @type on denormalization 2

- src/Symfony/EventListener/ErrorListener.php
- tests/Fixtures/TestBundle/ApiResource/Issue5921/ExceptionResource.php
- tests/Fixtures/TestBundle/Serializer/ErrorNormalizer.php
- tests/Fixtures/app/config/config_common.yml
Allow to skip the error handler with `extraProperties: ['_api_error_handler' => false]`
> feat(symfony): skip error handler

- src/Serializer/AbstractItemNormalizer.php
- src/Symfony/Routing/IriConverter.php
- tests/Fixtures/TestBundle/Entity/Issue6465/Bar.php
- tests/Fixtures/TestBundle/Entity/Issue6465/CustomInput.php
- tests/Fixtures/TestBundle/Entity/Issue6465/CustomOutput.php
- tests/Fixtures/TestBundle/Entity/Issue6465/Foo.php
- tests/Functional/JsonLd.php
>  fix(jsonld): remove request uri variables when denormalizing output 

- src/Serializer/AbstractItemNormalizer.php
> fix(jsonld): mitigate #6465

- features/openapi/docs.feature
- src/Hydra/JsonSchema/SchemaFactory.php
- tests/Hydra/JsonSchema/SchemaFactoryTest.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
This PR modifies SchemaFactory for JSON-LD to output JSON-LD specific properties such as `@context` `@id` `@type` as REQUIRED.
Below is a simple example.
```php
#[ORM\Entity(repositoryClass: TodoRepository::class)]
#[ApiResource]
class Todo
{
#[ORM\Id]
#[ORM\GeneratedValue]
#[ORM\Column]
private ?int $id = null;
#[ORM\Column(length: 255)]
#[Assert\NotBlank]
#[Assert\Length(max: 255)]
private ?string $title = null;
#[ORM\Column(type: Types::TEXT, nullable: true)]
private ?string $description = null;
#[ORM\Column]
#[Assert\NotNull]
private ?bool $done = null;
```
Currently, the following schema is generated for the above API resource.
JSON-LD specific properties …
> feat(jsonschema): make JSON-LD specific properties required

- src/Metadata/ApiProperty.php
The param annotation for default is set as `string|null` but should be no type, or mixed (like the example property)
| Branch?       | current stable 3.3
| Tickets       | Closes #6471
| Doc PR        | N.A.
In `Metadata/ApiProperty.php` the default property has PHP annotation param type as `null|string`, but that doesn't match the actual type (which is not set). I think it's best to set it to mixed, because that is the same type as the example property.
> fix: property called default in ApiProperty has incorrect type (#6471)

- features/authorization/deny.feature
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Fixtures/TestBundle/ApiResource/Issue6446/SecurityPostValidation.php
> fix(symfony): securityPostValidation when use_symfony_listeners

- CONTRIBUTING.md
- features/http_cache/headers.feature
- src/Doctrine/Odm/Tests/DoctrineMongoDbOdmSetup.php
- src/Elasticsearch/Paginator.php
- src/HttpCache/State/AddHeadersProcessor.php
- src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php
- src/Metadata/Property/Factory/CachedPropertyNameCollectionFactory.php
- src/Metadata/Resource/Factory/CachedResourceMetadataCollectionFactory.php
- src/Metadata/Tests/Property/Factory/CachedPropertyMetadataFactoryTest.php
- src/Metadata/Tests/Property/Factory/CachedPropertyNameCollectionFactoryTest.php
- tests/TestSuiteConfigCache.php
XXH3 is more than 15 times faster than MD5 (https://xxhash.com/).
Symfony made a similar change: https://github.com/symfony/symfony/pull/47094
> perf: use XXH3 instead of MD5

- src/JsonSchema/Command/JsonSchemaGenerateCommand.php
- src/JsonSchema/Tests/SchemaFactoryTest.php
- src/JsonSchema/Tests/SchemaTest.php
- src/Metadata/Tests/Resource/Factory/AttributesResourceMetadataCollectionFactoryTest.php
- src/Serializer/AbstractCollectionNormalizer.php
- src/Serializer/JsonEncoder.php
- src/Symfony/Bundle/DependencyInjection/Compiler/ElasticsearchClientPass.php
- tests/Behat/DoctrineContext.php
- tests/Fixtures/TestBundle/Entity/Content.php
- tests/Hal/JsonSchema/SchemaFactoryTest.php
- tests/Hydra/JsonSchema/SchemaFactoryTest.php
- tests/JsonApi/JsonSchema/SchemaFactoryTest.php
- tests/Symfony/Bundle/DependencyInjection/Compiler/ElasticsearchClientPassTest.php
[This commit](https://github.com/api-platform/core/pull/4851/commits/0ad3439f4d4c91c0586abb14ab6d9c14d6c38ddf) added many `@noRector` comments, but it is strange that the `@noRector` comments remain even though `rector.php` itself was removed in [this commit](https://github.com/api-platform/core/commit/b158de0eb0875310a0daa8bce0d641be64812e5b). This PR removes those unnecessary `@noRector` comments.
Regards.
> docs: remove unnecessary  comments

- src/Symfony/Bundle/Command/DebugResourceCommand.php
| Doc PR        |n/a
Currently when you run command `debug:api-resource` for class, which has multiple resources with same `uriTemplate` (but different `routePrefix`) - you see:
```
There are 2 resources declared on the class Book, which one do you want to debug ? 
[0] /books/{id}{._format}
[1] /books/{id}{._format}
```
but result for `[0]` record is always displayed regardless of your selection, because `$answerResource = $helper->ask($input, $output, $questionResource);` return choice label, not value.
> fix(symfony): fix debug:api-resource command for class with multiple resources with same uriTemplate

- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php
`date` wasn't detected, and immutable and mutable versions were falsely detected.
> fix(laravel): Eloquent date and datetime type detection

- src/GraphQl/Subscription/MercureSubscriptionIriGenerator.php
| Tickets       | Didn't find any, came up with a solution instead of making an issue :)
This is required when publishing and reading host names are not the same, ex: docker environment ("mercure" vs "localhost:port" between server side and client side), having different publishing URL and public access url's, etc. Mercure itself and Mercure bundle have been supporting this for a while.
> Fix(graphql)(mercure): Use public URL for subscription URI creation if it is available

- src/JsonApi/Tests/Fixtures/CustomConverter.php
- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Eloquent/PropertyAccess/PropertyAccessor.php
- src/Laravel/Eloquent/Serializer/SnakeCaseToCamelCaseNameConverter.php
- src/Laravel/Tests/JsonApiTest.php
- src/Laravel/Tests/JsonLdTest.php
- src/Laravel/workbench/app/Models/Book.php
- src/Laravel/workbench/database/factories/BookFactory.php
- src/Laravel/workbench/database/migrations/2023_07_15_231244_create_book_table.php
- src/Metadata/Util/CamelCaseToSnakeCaseNameConverter.php
Currently, model properties containing an underscore aren't written or read because an unneeded case conversion occurs. This patch fixes the issue.
~~A better fix could be to always convert internal snake_case model props to public camelCase API resources props.~~
Now implemented in this PR.
> fix(laravel): snake case props

- src/Laravel/Eloquent/PropertyAccess/PropertyAccessor.php
- src/Laravel/Tests/JsonApiTest.php
- src/Laravel/Tests/JsonLdTest.php
- src/Laravel/workbench/database/factories/BookFactory.php
- src/Laravel/workbench/database/migrations/2023_07_15_231244_create_book_table.php
The current implementation fails to access properties containing the `null` value and likely has other issues.
This patch fixes this issue, simplifies the approach, and increases performance.
> fix(laravel): Eloquent PropertyAccessor

- .php-cs-fixer.dist.php
- src/Laravel/Tests/JsonApiTest.php
- src/Laravel/config/api-platform.php
For improved security (less attack surface by default) and consistency with the Symfony variant.
> chore(laravel): only enable JSON-LD by default

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Tests/JsonLdTest.php
Prevents URLs such as `/api/foobar` to match.
> fix(laravel): api_doc route regex

- src/Laravel/Eloquent/Metadata/ModelMetadata.php
- src/Laravel/Tests/JsonLdTest.php
- src/Laravel/workbench/app/Models/Book.php
- src/Laravel/workbench/app/Models/Comment.php
- src/Laravel/workbench/database/factories/BookFactory.php
- src/Laravel/workbench/database/factories/CommentFactory.php
- src/Laravel/workbench/database/migrations/2023_07_15_231244_create_book_table.php
`Model::$visible` is an allow list. If it is defined, only fields explicitly listed in the array must be visible.
This patch fixes the issue and adds some tests for the feature.
According to [the docs](https://laravel.com/docs/11.x/eloquent-serialization#temporarily-modifying-attribute-visibility), it's also possible to hide the field for an instance by using `makeVisible()` and `makeHidden()`. 
I may be wrong, but this feature doesn't seem to be currently supported. This should be fixed in a follow-up PR.
> fix(laravel): visible and hidden fields support

- src/Documentation/Action/EntrypointAction.php
- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Eloquent/Metadata/ModelMetadata.php
- src/Laravel/Tests/JsonApiTest.php
The `jsonapi` format weren't working. This patch fixes the issue.
> fix(laravel): entrypoint serialization

- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaChoiceRestriction.php
Add support for automatic schema restriction for collection-like properties:
```
/**
* @var string[] $features
*/
#[ApiProperty]
#[Assert\Choice(callback: [Feature::class, 'getCaseValues'], multiple: true)]
private array $features;
```
> fix(symfony): allow schema restriction for collection like property from choice constraint

- src/OpenApi/Factory/OpenApiFactory.php
#6221 introduces options `open_api_override_responses` to toggle default responses generation.
This fix include 404 response generation into `open_api_override_responses` reach.
> feat(openapi): make open_api_override_responses act on default 404 response generation

- src/Doctrine/Common/Filter/BackedEnumFilterTrait.php
- src/Doctrine/Orm/Filter/BackedEnumFilter.php
- src/Doctrine/Orm/Tests/Filter/BackedEnumFilterTest.php
- src/Doctrine/Orm/Tests/Filter/BackedEnumFilterTestTrait.php
- src/Doctrine/Orm/Tests/Filter/ExistsFilterTest.php
- src/Doctrine/Orm/Tests/Filter/OrderFilterTest.php
- src/Doctrine/Orm/Tests/Filter/RangeFilterTest.php
- src/Doctrine/Orm/Tests/Filter/SearchFilterTest.php
- src/Doctrine/Orm/Tests/Fixtures/Entity/Dummy.php
- src/Doctrine/Orm/Tests/Fixtures/Entity/DummyBackedEnum.php
- src/Doctrine/Orm/Tests/Fixtures/Entity/RelatedDummy.php
- src/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Fixtures/app/config/config_doctrine.yml
| Tickets       | Closes #6506
Adding new Doctrine filter for filtering an entity using PHP backed enum
> feat(doctrine): add new filter for filtering an entity using PHP backed enum, resolves #6506

- src/State/Provider/ReadProvider.php
- src/Symfony/Bundle/Resources/config/symfony/events.xml
| Tickets       | Closes #6335
Just adding a simple log to avoid completely hiding the fact that there was a ProviderNotFoundException behind a NotFoundHttpException. 
It could help save time for devs who simply forgot to implement the provider.
> feat(dx): additional log to help locate a potential missing provider

- src/Doctrine/Common/ParameterValueExtractorTrait.php
- tests/Fixtures/TestBundle/Entity/SearchFilterParameter.php
- tests/Functional/Parameters/DoctrineTest.php
This small change uses `Parameter::$property` instead of `Parameter::$key` in filters.
This would allow for "alias" parameters to work out of the box.
Given this api resource:
```php
#[GetCollection(
parameters: [
'fooAlias' => new QueryParameter(filter: 'some_filter', property: 'foo'),
]
)]
class MyClass
{
#[ORM\Column()]
public string $foo = '';
}
```
such calls would search on `foo` property: `/my-classs?fooAlias=bar`
> fix(doctrine): use parameter.property as filter value key

- src/Doctrine/Common/EventListener/PublishMercureUpdatesListener.php
- src/Doctrine/Common/EventListener/PurgeHttpCacheListener.php
- src/Doctrine/Common/Messenger/DispatchTrait.php
- src/Doctrine/Common/Tests/EventListener/PublishMercureUpdatesListenerTest.php
- src/Doctrine/Common/Tests/EventListener/PurgeHttpCacheListenerTest.php
- src/Doctrine/Common/Tests/Fixtures/NotAResource.php
- src/Doctrine/Common/Tests/Fixtures/TestBundle/Entity/ContainNonResource.php
- src/Doctrine/Common/Tests/Fixtures/TestBundle/Entity/DummyCar.php
- src/Doctrine/Common/Tests/Fixtures/TestBundle/Entity/DummyCarInfo.php
- src/Doctrine/Common/Tests/Fixtures/TestBundle/Entity/DummyMercure.php
- src/Doctrine/Common/Tests/Fixtures/TestBundle/Entity/DummyNoGetOperation.php
- src/Doctrine/Common/Tests/Fixtures/TestBundle/Entity/DummyOffer.php
- src/Doctrine/Common/Tests/Fixtures/TestBundle/Entity/MercureWithTopicsAndGetOperation.php
- src/Doctrine/Common/composer.json
- src/GraphQl/Type/FieldsBuilder.php
- src/GraphQl/composer.json
- src/Serializer/SerializerContextBuilder.php
- src/Serializer/composer.json
- src/deprecation.php
Moves the PurgerListener and the CacheListener to the `api-platform/doctrine-common` package to be installed as part of the subtree split.
> fix(doctrine): move event listeners to doctrine/common

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/config/api-platform.php
Prevents a crash when GraphQL isn't installed, which is the default.
> fix(laravel): disable GraphQL by default and fix provider

- src/OpenApi/Model/Paths.php
- src/OpenApi/Serializer/OpenApiNormalizer.php
I've noticed for a while that operations sorting as displayed by tools like swagger-ui or scalar could be confusing at first - they are sorted by path, but displayed by tags first.
This PR sorts them by tags, then by path. As a very small optimization (assuming there are more writes than reads) it also triggers the sorting only when the paths are actually used instead of sorting each time a new path is added.
> feat: better path sorting for openapi UIs

- src/Laravel/ApiPlatformMiddleware.php
- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Controller/ApiPlatformController.php
- src/Laravel/Eloquent/Metadata/ModelMetadata.php
- src/Laravel/Eloquent/Serializer/SerializerContextBuilder.php
- src/Laravel/State/ParameterValidatorProvider.php
- src/Laravel/Tests/EloquentTest.php
- src/Laravel/workbench/app/Models/Book.php
- src/Metadata/Parameter.php
- src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
- src/Serializer/Filter/PropertyFilter.php
- src/Serializer/Parameter/SerializerFilterParameterProvider.php
- src/State/SerializerContextBuilderInterface.php
We don't need this anymore as implementing filters and pagination is done by users using the QueryParameter, and users MAY follow the specification if they want to (as the specification doesn't enforce anything but only recommends)
> fix(laravel): remove json api provider

- src/Doctrine/Orm/Tests/config.yml
- src/GraphQl/Serializer/SerializerContextBuilder.php
- src/GraphQl/Tests/Serializer/SerializerContextBuilderTest.php
- src/Serializer/SerializerContextBuilder.php
- src/Serializer/Tests/SerializerContextBuilderTest.php
#5758 adds a few context data that can take lots of time being serialized in our serialization cache.
> perf: skip context data added in #5758

- src/State/Pagination/TraversablePaginator.php
- tests/State/Pagination/TraversablePaginatorTest.php
Hello,
whenever the `TraversablePaginator` has the same number of items than the `itemsPerPage`, it currently returns `0`, although it should return `totalItems` 
This PR fixes this buggy behavior
It seems strange that nobody has noticed this before :thinking:
> fix: count TraversablePaginator

- features/hydra/collection.feature
- src/State/Processor/RespondProcessor.php
> fix!(state): precise format on content-location

- src/Serializer/SerializerFilterContextBuilder.php
As `ApiPlatform\Serializer\SerializerContextBuilderInterface` is deprecated in favour of `ApiPlatform\State\SerializerContextBuilderInterface` and:
```php
interface ApiPlatform\Serializer\SerializerContextBuilderInterface extends ApiPlatform\State\SerializerContextBuilderInterface
```
it is not possible to use non-deprecated inteface for a ContextBuilder, as the `ApiPlatform\Serializer\SerializerFilterContextBuilder` is still expecting deprecated interface for `$decorated` parameter.
It looks like this deprecated interface has not been removed also in v4, where I should expect it to be gone.
Hope it makes sense.
> fix(serializer): allow state's SerializerFilterContextBuilderInterface

- composer.json
- src/Doctrine/Odm/composer.json
- src/Doctrine/Orm/composer.json
> fix: composer.json config

- src/Symfony/Bundle/Resources/config/api.xml
> fix(symfony): missing alias to serializer context builder interface

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Console/InstallCommand.php
Fix group names for pulishing config and assets.
Closes #6645
| Tickets       | Closes #6645 
| Doc PR        | https://github.com/api-platform/docs/pull/1989
> Add installation command, fix config overwrites

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/State/SwaggerUiProcessor.php
- src/Laravel/config/api-platform.php
| Tickets       | Closes #6662
| Doc PR        | [#1991](https://github.com/api-platform/docs/pull/1991)
> [Laravel]: Fix authorization swagger ui

- src/Laravel/Eloquent/State/LinksHandler.php
The function [`Model::qualifyColumn()`](https://github.com/laravel/framework/blob/abf86b08b08c5ea5c9247877bc8b6ea259805f80/src/Illuminate/Database/Eloquent/Model.php#L586-L593) does exactly the same as the existing code. But for MongoDB, we had to [override this method](https://github.com/mongodb/laravel-mongodb/blob/716d8e166809502a22017b476979678a57d5d91d/src/Eloquent/DocumentModel.php#L564-L567) as the column name (field name) cannot be prefixed with the table name (collection name). So we need this method to be used instead of having the logic hard coded.
For relations, we use the `getQualifiedForeignKeyName` that has the same mechanism for …
> Laravel: Use `Model::qualifyColumn()` instead of `$table.$column`

- docs/guides/validate-incoming-data.php
- features/hydra/error.feature
- features/jsonld/input_output.feature
- features/main/attribute_resource.feature
- features/main/not_exposed.feature
- features/main/relation.feature
- features/main/union_intersect_types.feature
- features/main/validation.feature
- features/serializer/vo_relations.feature
- src/JsonLd/ContextBuilder.php
- src/State/ApiResource/Error.php
- src/Validator/Exception/ValidationException.php
Additionally, [api-platform/admin](https://github.com/api-platform/admin) must be updated because of the following error (with `hydra_prefix: false`):
> fix: remove "hydra:" remaining prefix

- src/Laravel/ApiPlatformProvider.php
| Tickets       | Closes #2767
If GraphQL is enabled and API Platform's route prefix is configured to be an empty string instead of the default `/api` then the `/graphql` route is incorrectly handled by `\ApiPlatform\Laravel\Controller\EntrypointController` instead of `ApiPlatform\Laravel\GraphQl\Controller\EntrypointController`.
This is because the routes being handled by the former controller are registered before the GraphQL routes. Instead, they should be registered last.
> Fix: route registration of EntrypointController should be after GraphQL's EntrypointController

- src/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Symfony/Bundle/Resources/config/validator/events.xml
| Tickets       | Closes #6670
Currently, the standalone `api-platform/symfony` package crashes when installed. This patch fixes the issue.
>  fix(symfony): config and DI 

- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php
- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyNameCollectionMetadataFactory.php
- src/Laravel/Tests/EloquentTest.php
- src/Laravel/workbench/app/Models/WithAccessor.php
- src/Laravel/workbench/database/factories/WithAccessorFactory.php
- src/Laravel/workbench/database/migrations/2024_09_24_065934_create_with_accessors_table.php
- src/Laravel/workbench/database/seeders/DatabaseSeeder.php
| Tickets       | Closes #6644
Fixes https://github.com/api-platform/core/issues/6644 @toitzi may you review?
> fix(laravel): eloquent accessors

- src/State/Provider/ParameterProvider.php
- src/State/Tests/ParameterProviderTest.php
In case of using long running http workers (Roadrunner for example), query parameters and in general parameters functionality tends to persist previous request value due to aggressive [caching of resource metadata ](https://github.com/api-platform/core/blob/main/src/Metadata/Resource/Factory/CachedResourceMetadataCollectionFactory.php)
Fixing by clearing extra data before parsing new one
Targeting 3.4, but the issue reproducible at 4.0 as well
> fix: parameter provider in a long running http worker

- src/JsonSchema/DefinitionNameFactory.php
- tests/JsonSchema/DefinitionNameFactoryTest.php
- tests/JsonSchema/Dummy/NamespaceA/Module/DummyClass.php
- tests/JsonSchema/Dummy/NamespaceB/Module/DummyClass.php
- tests/JsonSchema/Dummy/NamespaceC/Module/DummyClass.php
| Branch?       | 3.3 
It fixes documentation models reference in the case where there are 2 or more classes with the same name but in different namespaces.
Previously the very first class model was created and used in all places in documentation.
Now if the name is the same but namespace is different, a previous one element of a namespace is prepended to the name until the name is unique
> fix(jsonapi): fixed definition name to allow using the same class names in different namespaces

- src/Elasticsearch/composer.json
When installing api-platform/core (3.4) elasticsearch 7 and 8 is supported (https://github.com/api-platform/core/blob/v3.4.1/composer.json#L144) but when installing the same version (3.4) with api-platform/elasticsearch only 8 is supported https://github.com/api-platform/core/blob/v3.4.1/src/Elasticsearch/composer.json#L30.
> fix(elasticsearch): Allow ES 7

- src/Metadata/Extractor/XmlResourceExtractor.php
- src/Metadata/Extractor/YamlResourceExtractor.php
| Tickets       | related to https://github.com/api-platform/core/pull/6659
Currently there is no possibility to pass the class as a parameter in `fromClass` and `toClass` uriVariables' options and this PR adds this missed possibility.
> fix: using parameters in fromClass and toClass uriVariables' options

- src/Hydra/Serializer/ConstraintViolationListNormalizer.php
- src/Symfony/Bundle/Resources/config/hydra.xml
Hydra prefix is not removed in ConstraintViolationListNormalizer
> fix: remove hydra prefix

- src/GraphQl/Type/TypeConverter.php
- src/Laravel/Tests/AuthTest.php
- src/Laravel/Tests/EloquentTest.php
- src/Laravel/Tests/GraphQlAuthTest.php
- src/Laravel/Tests/GraphQlTest.php
- src/Laravel/Tests/HalTest.php
- src/Laravel/Tests/JsonApiTest.php
- src/Laravel/Tests/JsonLdTest.php
- src/Laravel/Tests/Policy/PolicyAllowTest.php
- src/Laravel/Tests/Policy/PolicyDenyTest.php
- src/Laravel/workbench/app/Models/Vault.php
Because the `shouldSeed` (https://github.com/orchestral/testbench-core/commit/57954ccc46e9a1824bbce2d3984cf9ec897684cf) is now false by default we didn't executed the DatabaseSeeder every time. I choose to load just what we need for each test to speed up tests. Also, I noted that we may have side effects using the file storage as `app.debug` looks to be `false` by default for testing (not sure what brought this update) and therefore when adding a format inside tests we need to use the MemoryCache, or to clear laravel's cache (couldn't make it work through the workbench command).
> test(laravel): call factories, debug is now false by default

- src/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPass.php
- tests/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php
Since https://github.com/symfony/symfony/commit/ce228d3a7a6448e5f214033a0cd2710177085f29#diff-f53370286252d2326a377eafd4bba05112518e0c8bf3aedda670fd76a254e9fa the serializer.name_converter.metadata_aware is extending an abstract service. Therefore there are no arguments by default. We relied on the number of arguments to inject API Platform's configured name converter.
> fix(symfony): metadata aware name converter has 0 arguments by default

- src/Laravel/ApiPlatformProvider.php
| Tickets       | #6713
If the settings are not passed, the UI elements required for login will not appear on the API documentation page.
> fix(laravel): openapi Options binding

- src/JsonLd/Serializer/ErrorNormalizer.php
- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyNameCollectionMetadataFactory.php
- src/Laravel/Tests/JsonApiTest.php
- src/Laravel/Tests/JsonLdTest.php
- src/Laravel/workbench/app/Models/WithAccessor.php
- src/Laravel/workbench/app/Models/WithAccessorRelation.php
- src/Laravel/workbench/database/factories/WithAccessorRelationFactory.php
- src/Laravel/workbench/database/migrations/2024_09_24_065934_create_with_accessors_table.php
- src/Metadata/ApiProperty.php
- src/Metadata/Tests/Extractor/Adapter/XmlPropertyAdapter.php
- src/Serializer/Mapping/Loader/PropertyMetadataLoader.php
- src/Serializer/Tests/Fixtures/Model/HasRelation.php
- src/Serializer/Tests/Fixtures/Model/Relation.php
- src/Serializer/Tests/Mapping/Loader/PropertyMetadataLoaderTest.php
- src/Symfony/Bundle/ApiPlatformBundle.php
- src/Symfony/Bundle/DependencyInjection/Compiler/SerializerMappingLoaderPass.php
- src/Symfony/Bundle/Resources/config/api.xml
- tests/Symfony/Bundle/ApiPlatformBundleTest.php
| Branch?       | 4.0 (new metadata feature but a bug fix for laravel)
| Doc PR        | required?
```php
#[ApiResource(normalizationContext: ['groups' => ['read']])]
class Resource
{
#[ApiProperty(serialize: [new Groups(['read'])])]
public function relation(): Relation
{
return new Relation(id: 1, name: 'test');
}
}
#[Groups(['read'])]
#[ApiResource(operations: [])]
class Relation
{
public function __construct(public int $id, public string $name) {}
}
```
```json
{
"@context": "/api/contexts/SomeClass",
"@id": "/api/some_classes/1",
"@type": "SomeClass",
"relation": {
"@id": "/api/relations/1",
"@type": "Relation",
"id": 1,
"name": "test"
}
}
```
> fix(laravel): allow serializer attributes through ApiProperty

- src/JsonSchema/SchemaFactory.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
turn off inserting @id into a schema that is not a resource and has @id autogeneration turned off
> fix(jsonschema): handle @id when genId is false 

- src/Laravel/Console/Maker/AbstractMakeStateCommand.php
- src/Laravel/Tests/Console/Maker/Utils/PathResolver.php
| Branch?       | `4.0` (fix for a feature available since `4.0`)
Updates directory paths from 'src/State/' to 'app/State/' in AbstractMakeStateCommand and PathResolver. This aligns with the standard Laravel directory structure conventions.
Before the files were generated in `src/State` instead of `app/State`.
> fix(laravel): make command writes to app instead of src

- src/GraphQl/Type/FieldsBuilder.php
- src/Laravel/Tests/GraphQlTest.php
- src/Laravel/workbench/app/Models/Book.php
Fixes #6698 
I'll backport this fix to 3.4 afterwards.
>  fix(graphql): register query parameter arguments with filters 

- src/Symfony/Bundle/DataCollector/RequestDataCollector.php
- tests/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
> fix(symfony): fetch api-platform/symfony version debug bar

- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php
| Tickets       | Closes #6736 
Fixes the issue on collection relations other than HasMany not working for Laravel
> fix(laravel): collection relations other than HasMany

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/workbench/app/Providers/WorkbenchServiceProvider.php
Make use of the default laravel cache setting, makes it possible for developers to configure where data should be cached
Closes: #6735
| Branch?       | main?
| Tickets       | Closes #6735 
| Doc PR        | [#2048](https://github.com/api-platform/docs/pull/2048)
Not sure if you consider this a feature or a bugfix, let me know if you want this to be merged against the 4.x branch instead.
> feat(laravel): use laravel cache setting

- src/Validator/Metadata/Resource/Factory/ParameterValidationResourceMetadataCollectionFactory.php
- tests/Fixtures/TestBundle/ApiResource/WithParameter.php
- tests/Fixtures/TestBundle/Filter/PatternFilter.php
- tests/Functional/Parameters/ValidationTest.php
| Tickets       | Closes #6685 
> fix(symfony): ECMA-262 pattern with RegExp validator

- src/Validator/Metadata/Resource/Factory/ParameterValidationResourceMetadataCollectionFactory.php
Hello,
According to the documentation https://api-platform.com/docs/core/filters/#parameter-validation, we can read:
```
You can also use your own constraint by setting the constraints option on a Parameter. In that case we won’t setup the automatic validation for you and it’ll replace our defaults.
```
Then, given the following simplified resource definition:
```
#[Api\ApiResource(
// ...
parameters: [
'channel' => new QueryParameter(required: true, constraints: [new ChannelConstraint()]),
],
)]
```
I would expect that the `NotNull` constraint automatically provided by the `required` parameter is not provided anymore as I define custom constraint.
If you mind why …
> fix(metadata): providing parameter constraints skips automatic ones

- src/Laravel/config/api-platform.php
- src/Laravel/resources/views/swagger-ui.blade.php
| Tickets       | Fixes https://github.com/api-platform/api-platform/discussions/2781
| Doc PR        | https://github.com/api-platform/docs/pull/2044
Symfony users are not the only people subjects to arachnophobia. Despite spiders being much more classy in their Lambo, Laravel users still might suffer from fear of them.
Let's fix this issue and re-introduce the `show_webby` parameter!
To remove Webby, add the following to the `config/api-platform.php` file:
```php
return [
// ...
'show_webby' => false,
// ...
];
```
> fix: reintroduce the `show_webby` parameter in Laravel config

- composer.json
Hi, in the PR #6468, which was updating minimum dependencies from Symfony 7.0 to 7.1, the line for symfony/framework-bundle in conflict section was mistakenly updated too.
Since Symfony 7.0 as be re-allowed in #6628, I've only revert the change made in previous PR to keep the conflict on v7.0.6 and allow v7.1.6.
> chore(symfony): conflict with symfony/framework-bundle 7.1.6

- features/main/validation.feature
- src/Serializer/AbstractItemNormalizer.php
See https://github.com/symfony/symfony/pull/53959
> fix(serializer): fetch type on normalization error when possible

- src/Validator/Exception/ValidationException.php
- src/Validator/Tests/Exception/ValidationExceptionTest.php
| Tickets       |  
When a `ApiPlatform\Validator\Exception\ValidationException` is created with a `ConstraintViolationList` and a `$previous` exception, the current constructor breaks on https://github.com/api-platform/core/blob/67fbe51c570abe1ece6651ae6a037662e9012881/src/Validator/Exception/ValidationException.php#L76
with the following error:
```
TypeError: Exception::__construct(): Argument #2 ($code) must be of type int, Exception given
```
> fix(validator): allow to pass both a ConstraintViolationList and a previous exception

- src/Doctrine/Orm/Extension/ParameterExtension.php
I noticed there are many places where APIP fails silently. This make our code harder to debug.
I don't know if this is a feature, or just a mistake. If it's a mistake, I'll try to send more PR.
> fix(doctrine): throw an exception when a filter is not found in a parameter

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Tests/LinkHeaderTest.php
- src/Laravel/Tests/LinkHeaderWithoutJsonldTest.php
| Branch       | 4.0
| Tickets       | https://github.com/api-platform/core/issues/6738 (second part)
Do not inject HydraLinkProcessor if the jsonld format is not activated in the config.
> fix(laravel): remove link header when jsonld is not enabled

- src/Symfony/Bundle/DependencyInjection/Configuration.php
The default format should be `json-ld` not `openapi` by default.
> fix(symfony): default formats order

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Tests/JsonLdTest.php
- src/Laravel/workbench/app/ApiResource/Staff.php
- src/Laravel/workbench/app/ApiResource/StaffPositionHistory.php
> fix(laravel): overlaping route format

- src/Laravel/ApiPlatformProvider.php
| Tickets       | https://github.com/api-platform/api-platform/discussions/2791
> fix(laravel): declare normalizer list as a service

- src/State/Pagination/ArrayPaginator.php
- tests/State/Pagination/ArrayPaginatorTest.php
Hello,
When using Doctrine or Elastic paginator, it behaves by giving an empty array when the page is out of bounds but when using the Array paginator, it throws an `OutOfBoundsException`.
This PR align this behavior accross all paginators.
> fix(state): empty result when the array paginator is out of bound

- src/Hal/Serializer/ItemNormalizer.php
- tests/Fixtures/TestBundle/ApiResource/Issue4358/ResourceA.php
- tests/Fixtures/TestBundle/ApiResource/Issue4358/ResourceB.php
- tests/Functional/HALCircularReference.php
| Tickets       | https://github.com/api-platform/core/issues/4358
The Hal serializer didn't detect circular references, creating an infinite json.
Now Hal's `ItemNormalizer` can detect and handle this case.
> fix(hal): detecting and handling circular reference

- src/State/Provider/ContentNegotiationProvider.php
- tests/State/Provider/ContentNegotiationProviderTest.php
Problem appears after https://github.com/api-platform/core/pull/6102
> fix(state): do not check content type if no input

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Eloquent/State/LinksHandler.php
- src/Metadata/Resource/ResourceMetadataCollection.php
| Tickets       | https://github.com/api-platform/api-platform/discussions/2795, #6791 
This is still work in progress and needs feedback
> fix(laravel) graphQl Relationship loading

- src/Symfony/Routing/Router.php
- tests/.ignored-deprecations
- tests/Symfony/Routing/RouterTest.php
This got fixed into symfony and the way we did it was hackish anyways. Now the behavior will be the one of symfony, which is just fine.
> chore: symfony dev tests

- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php
- src/Laravel/Tests/GraphQlTest.php
- src/Laravel/workbench/app/Models/Book.php
- src/Laravel/workbench/database/factories/BookFactory.php
- src/Laravel/workbench/database/migrations/2023_07_15_231244_create_book_table.php
| Tickets       | Closes #6807
> fix(laravel): allow boolean cast

- src/Symfony/EventListener/ErrorListener.php
- tests/Fixtures/TestBundle/ApiResource/Issue6718/Organization.php
- tests/Functional/ItemUriTemplateTest.php
> fix(symfony): unset item_uri_template when serializing an error

- src/Metadata/ApiResource.php
| Doc PR        | https://github.com/api-platform/docs/pull/2054
YAML is now a RFC and has an official media type: https://www.rfc-editor.org/rfc/rfc9512.html#name-media-type-application-yaml
> doc: use newly registered YAML media type

- src/State/Provider/ContentNegotiationProvider.php
- tests/State/Provider/ContentNegotiationProviderTest.php
| Tickets       | Closes #6831 
Proposed fix for bug where in long-running worker processes e.g. FrankenPHP, the `Request` formats are overwritten and can lose their default associations such as `json` --> `application/json`.
> fix(symfony): retain existing associations of formats to MIME types when adding new MIME types

- src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestriction.php
- tests/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaCollectionRestrictionTest.php
- tests/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
in case of `Collection` constraint with empty `fields` key (this is valid value for it):
```
/**
* @var array<string, mixed>
*/
#[Assert\Collection(fields: [])]
public array $options = [];
```
`properties` field is generated as plain array, which is incorrect (must be always object):
```
options:
type: object
properties: [] <--------
additionalProperties: false
```
> fix(symfony): object typed property schema collection restriction

- src/Doctrine/Orm/Filter/DateFilter.php
| Tickets       | None
DateFilter applies an inner join on nested property relations even when no values to filter on are provided. This update adds a check ensuring the values array is not empty before applying the join.
Without this fix, simply defining a DateFilter on nullable relations in GraphQL excludes all records lacking related entities, due to the nature of INNER JOIN.
> fix(doctrine): Fixed ORM DateFilter applying inner join when no filtering values have been provided

- .php-cs-fixer.dist.php
| Branch?       | `4.0`
Enable parallel execution by configuring PHP-CS-Fixer with automatic detection of optimal parallel settings using the `ParallelConfigFactory::detect` method. This improves performance in environments that support parallel processing.
> ci(php-cs-fixer): add parallel execution

- src/JsonSchema/Metadata/Property/Factory/SchemaPropertyMetadataFactory.php
- src/JsonSchema/SchemaFactory.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/Symfony/Bundle/Resources/config/json_schema.xml
- tests/Fixtures/TestBundle/ApiResource/Issue6800/Foo.php
- tests/Fixtures/TestBundle/ApiResource/Issue6800/TestApiDocHashmapArrayObjectIssue.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
| Branch?       | `3.4`
| Tickets       | Closes #6800 
Key changes:
- Fix OpenAPI schema generation for hashmap properties
- Add tests to verify the correct schema generation for hashmap properties and different syntax for arrays of objects
> fix(jsonschema): hashmaps produces invalid openapi schema

- src/Laravel/ApiPlatformProvider.php
| Branch?       | 4.x
| Tickets       | Closes #6854
> [Laravel] Fix GraphQL Resolver Discovery

- src/Doctrine/Odm/Extension/ParameterExtension.php
- src/Doctrine/Orm/Extension/ParameterExtension.php
> fix: test empty parameter against null

- features/filter/filter_validation.feature
- src/Metadata/Parameter.php
- src/Metadata/Parameters.php
- src/Metadata/Tests/ParameterTest.php
- src/Metadata/Tests/ParametersTest.php
- src/Symfony/Validator/State/ParameterValidatorProvider.php
- tests/Fixtures/TestBundle/ApiResource/WithParameter.php
- tests/Functional/Parameters/ValidationTest.php
- `Parameter::getValue()` now takes a default value as argument `getValue(mixed $default = new ParameterNotFound()): mixed`
- `Parametes::get(string $key, string $parameterClass = QueryParameter::class)` (but also `has` and `remove`) now has a default value as second argument to `QueryParameter::class`
- Constraint violation had the wrong message when using `property`, fixed by using the `key` instead: 
```
#[QueryParameter(property: 'id', key: 'int', constraints: [new Assert\Type('integer')], provider: [self::class, 'toInt']))]
```
```diff
-id: This value should be of type integer.
+int: This value should be of type integer.
```
<details>
<summary>See the `toInt` provider.</summary>
```php
public static function …
```
> fix(metadata): various parameter improvements

- src/GraphQl/State/Processor/NormalizeProcessor.php
- src/GraphQl/Type/TypeBuilder.php
- src/Laravel/Eloquent/Paginator.php
- src/Laravel/Tests/GraphQlTest.php
- src/Laravel/workbench/app/Models/Book.php
| Branch?       | 4.x
| Tickets       | Closes #6856
Also adds "currentPage" to graphql.
> [Laravel] Graphql simple pagination fix "hasNextPage"

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Eloquent/Extension/FilterQueryExtension.php
- src/Laravel/Eloquent/Filter/BooleanFilter.php
- src/Laravel/Metadata/ParameterValidationResourceMetadataCollectionFactory.php
- src/Laravel/Tests/Eloquent/Filter/BooleanFilterTest.php
- src/Laravel/Tests/EloquentTest.php
- src/Laravel/workbench/app/Models/Book.php
- src/Laravel/workbench/database/factories/BookFactory.php
- src/Laravel/workbench/database/migrations/2023_07_15_231244_create_book_table.php
Adding new boolean filter in order to filter by boolean attributes
> feat(laravel): boolean filter

- src/Laravel/Eloquent/State/LinksHandler.php
| Tickets       | closes #6861 
> feat(laravel): Fixing BelongsToManyThrough

- src/Doctrine/Common/State/LinksHandlerLocatorTrait.php
Currently, when there is a typo in the callable array passed as `handleLinks`, the error message is unclear:  
```
Warning: Array to string conversion
```
This error does not indicate that the issue lies in `handleLinks`, making debugging difficult and causing unnecessary confusion for developers.  
- Added explicit validation to check that the specified method exists in the given class when a `[ClassName, MethodName]` array is passed as `handleLinks`.  
- If the method does not exist, a clear exception is thrown, indicating the missing method and its associated class.  
- Included a suggestion for a similar method name …
> feat(doctrine): enhance getLinksHandler with method validation and typo suggestions

- src/JsonApi/Filter/SparseFieldset.php
- src/JsonApi/Filter/SparseFieldsetParameterProvider.php
- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Eloquent/Filter/JsonApi/SortFilter.php
- src/Laravel/Eloquent/Filter/JsonApi/SortFilterParameterProvider.php
- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyNameCollectionMetadataFactory.php
- src/Laravel/JsonApi/State/JsonApiProvider.php
- src/Laravel/Tests/JsonApiTest.php
- src/Laravel/workbench/app/Models/Book.php
- src/Metadata/Parameter.php
- src/Metadata/ParameterProviderFilterInterface.php
- src/Metadata/PropertiesAwareInterface.php
- src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
| Branch?       | 4.0 (this feature should be supported by Laravel)
| Tickets       | Closes #6841
> fix(laravel): jsonapi query parameters (page, sort, fields and include)

- src/Laravel/ApiPlatformProvider.php
| Branch?       | `main`
The `BooleanFilter` was most certainly deleted by mistake in `Laravel/ApiPlatformProvider.php`, in this [merge commit](https://github.com/api-platform/core/commit/716a43b825f9c569971ac57a889338134959f2e1#diff-1f34d8685c9bbcc2037ef47c41cb6dac916a0fe6fc06e2047b9635e35fa13527L426-R440). 
This is why the CI is failing in the `main` branch:
I propose a patch to reintroduce it.
> fix(laravel): restore accidentally removed BooleanFilter

- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
- src/OpenApi/Tests/Fixtures/Issue6872/Diamond.php
| Branch?       | `3.4`
| Tickets       | Closes #6872 
Add OpenAPI documentation for the forbidden responses (see issue #6872 for more details).
> fix(openapi): not forbidden response on openAPI doc

- src/Symfony/Bundle/SwaggerUi/SwaggerUiAction.php
The original deprecation was introduced at [#5657](https://github.com/api-platform/core/commit/afb739b392d337159f6475f7c3144cbac74b1067#diff-10997c2eea998f54ae8b684cf439f54183156dd825abc92dfd68cb37cc63e399R30) and initially released under the [v3.2.0-alpha.1
](https://github.com/api-platform/core/releases/tag/v3.2.0-alpha.1) tag.
Then, the release [3.3.0](https://github.com/api-platform/core/blob/3b8a0068beb23acbf7a9a0da19e4b9638bf883e4/src/Symfony/Action/DocumentationAction.php#L37) introduced the `DocumentationAction` class, which IMO is a much natural replacement for the deprecated class.
Additionally, the referenced class …
> fix(symfony): suggest `DocumentationAction` as replacement for deprecated `SwaggerUiAction`

- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php
- src/Laravel/workbench/app/Models/Book.php
- src/Laravel/workbench/app/Models/Vault.php
| Tickets       | Closes #6875 
> fix!(laravel): fix use laravel fillable for writable props

- src/Laravel/Eloquent/Filter/DateFilter.php
- src/Laravel/Eloquent/Filter/OrFilter.php
- src/Laravel/Eloquent/Filter/OrderFilter.php
- src/Laravel/Eloquent/Filter/RangeFilter.php
- src/Laravel/Eloquent/Paginator.php
- src/Laravel/Eloquent/PartialPaginator.php
- src/Laravel/Routing/IriConverter.php
- src/Laravel/Routing/SkolemIriConverter.php
- src/Laravel/Tests/Console/Maker/MakeStateProcessorCommandTest.php
- src/Laravel/Tests/Console/Maker/MakeStateProviderCommandTest.php
- src/Laravel/composer.json
Hi,
I'm trying to install `api-platform/laravel` on a codebase with larastan 3 which failed as it throw error saying phpstan/phpdoc-parser must be at least 2.0. So I edited composer.json to allow 2.0 too
Then i also allow larastan 3.0 since phpstan/phpdoc-parser 2.0 require phpstan 2.0 (larastan 3.x use phpstan 2.x, larastan 3.x use phpstan 1.x)
> Allow phpstan/phpdoc-parser 2 (which in turns allow PHPstan 2, Larastan 3) for api-platform/laravel

- src/GraphQl/Type/FieldsBuilder.php
- src/Laravel/Tests/GraphQlTest.php
Workarround for registering parameter filter types within graphql
| Tickets       | Closes #6746 
WIP
> fix(graphql): register types for parameter args

- features/hydra/collection.feature
- features/main/crud.feature
- features/main/crud_abstract.feature
- features/main/crud_uri_variables.feature
- src/State/Processor/RespondProcessor.php
| Branch?       | `4.0`
| Tickets       | Closes #6750
Eliminates the unnecessary `Content-Location` header from GET responses to prevent potential issues, such as with temporary or preview resources lacking an ID. 
While compliant with RFC 9110, this header is redundant and not required. For more details, refer to #6750.
> fix(state): skip Content-Location header for GET requests

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Tests/EloquentTest.php
- src/Laravel/Tests/GraphQlTest.php
- src/Laravel/workbench/app/Enums/BookStatus.php
- src/Laravel/workbench/app/Models/Book.php
- src/Laravel/workbench/database/factories/BookFactory.php
- src/Laravel/workbench/database/migrations/2023_07_15_231244_create_book_table.php
Closes: #6906
| Tickets       | Closes #6906 
> feat(laravel): add support for backed enums

- src/JsonSchema/Metadata/Property/Factory/SchemaPropertyMetadataFactory.php
- src/JsonSchema/Tests/Fixtures/DummyWithCustomOpenApiContext.php
- src/JsonSchema/Tests/Metadata/Property/Factory/SchemaPropertyMetadataFactoryTest.php
When specify an `openapiContext` in #`[ApiProperty]`, the typing of the same property is no longer used, and force to explicitly specify it within the `openapiContext` array.
| Branch       | 3.4
| Tickets       | Closes https://github.com/api-platform/core/issues/6893 
> fix(openapi): typing issue with `openapiContext` in `#[ApiProperty]`

- src/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php
- tests/Fixtures/DummyValidatedEntity.php
- tests/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
| Branch?       | 4.0 
```php
#[ApiResource(
validationContext: [
'groups' => [self::class, 'getValidationGroups'],
],
)]
class Foo
```
If root resource has dynamic validation groups - validation groups for it in `ValidatorPropertyMetadataFactory` are evaluated as plain array `['\App\Entity\Fee', 'getValidationGroups']` and as a result no constraint is found for these validation groups.
> fix(symfony): fix property restrictions for root resource with dynamic validation groups

- src/JsonApi/JsonSchema/SchemaFactory.php
- src/JsonSchema/ResourceMetadataTrait.php
- src/Laravel/Eloquent/Metadata/Factory/Property/EloquentPropertyMetadataFactory.php
- src/Metadata/ApiProperty.php
- src/Metadata/ApiResource.php
- src/Metadata/HttpOperation.php
- src/Metadata/Operation.php
- src/Metadata/Parameter.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
- src/OpenApi/Tests/Serializer/OpenApiNormalizerTest.php
- src/State/ApiResource/Error.php
- src/Validator/Exception/ValidationException.php
- tests/Fixtures/TestBundle/ApiResource/Crud.php
- tests/Functional/OpenApiTest.php
- tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
| Branch?       | not sure yet
| Tickets       | Closes #6918
This fixes many issues related to how errors and constraint violations are documented, it was reported in #6918 and is a follow up of #6748 (therefore I'd be up to add this on 4.1 instead of 4.0 as without the patch there are still inconsistencies).
A few screenshots:
I still need to add a few tests as this was hard to implement we need to cover regressions...
> fix(openapi): document error outputs using json-schemas

- composer.json
- src/Doctrine/Odm/Extension/PaginationExtension.php
- src/Doctrine/Odm/State/CollectionProvider.php
- src/Doctrine/Odm/State/ItemProvider.php
- src/Doctrine/Odm/State/LinksHandlerTrait.php
- src/Doctrine/Odm/Tests/Extension/PaginationExtensionTest.php
- src/Doctrine/Odm/Tests/State/CollectionProviderTest.php
- src/Doctrine/Odm/Tests/State/ItemProviderTest.php
The method `AggregationBuilder::execute()` is [deprecated](https://github.com/doctrine/mongodb-odm/blob/2.10.0/lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php#L176).
This requires updating the minimum version of MongoDB ODM for testing, as the new result class have been added in v2.10.0 by https://github.com/doctrine/mongodb-odm/pull/2702, so we can mock it.
> feat(mongodb): Replace usage of deprecated method `AggregationBuilder::execute()`

- src/Doctrine/Odm/composer.json
- src/Doctrine/Orm/composer.json
- src/Symfony/composer.json
- src/Validator/composer.json
https://github.com/api-platform/core/pull/6775 introduced a new interface `ApiPlatform\Doctrine\Common\Filter\ManagerRegistryAwareInterface` that is implemented by `ApiPlatform\Doctrine\{Orm,Odm}\Filter\AbstractFilter`, making `api-platform/doctrine-{orm,odm}: 4.1` require `api-platform/doctrine-common: 4.1`.
I hit this error while requiring only the dev version of `api-platform/doctrine-odm`.
```
!!    Invalid service "api_platform.doctrine_mongodb.odm.search_filter": class "A  
!!    piPlatform\Doctrine\Common\Filter\ManagerRegistryAwareInterface" not found   
!!    while loading "ApiPlatform\Doctrine\Odm\Filter\SearchFilter".       
``` …
> fix: Fix cross-package version dependencies

- src/Laravel/public/style.css
> fix(laravel): SwaggerUI custom CSS

- src/Metadata/ApiProperty.php
- src/Serializer/Mapping/Loader/PropertyMetadataLoader.php
| Tickets       | Closes https://github.com/api-platform/core/issues/6929
The array cast is faulty (it converts the properties of the object) in an array and the attribute must be repeatable when used on a class.
This fixes https://github.com/api-platform/core/issues/6929
> fix: ApiProperty::$serialize array conversion and make ApiProperty repeatable

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Tests/ApiTest.php
- src/Laravel/config/api-platform.php
- src/Laravel/routes/api.php
**Problem**
When the API Platform service provider is not auto-discovered, and manually added as a provider, the SP would overwrite any route that had been registered up until that point. 
Because of the Eloquent ORM introspection that happens when discovering metadata, a DB service is required to perform the introspection. This happens whenever composer `php artisan package:discover` is run. This is not optimal for CI/CD environments where you often don't have those services running to perform chores like linting and static analysis. 
**Solution**
By allowing the developer to add API Platforms SP to composer's `dont-discover` array and manually registering the SP at a later time, we can prevent the needs of the DB specifically when `php artisan package:discover` is run. We then register …
> fix(laravel): Prevent overwriting existing routes on the router

- .github/workflows/ci.yml
- composer.json
- src/Elasticsearch/State/CollectionProvider.php
- src/Elasticsearch/State/ItemProvider.php
- src/Elasticsearch/composer.json
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/DependencyInjection/Compiler/ElasticsearchClientPass.php
- src/Symfony/Bundle/DependencyInjection/Configuration.php
- tests/Behat/ElasticsearchContext.php
- tests/Symfony/Bundle/DependencyInjection/Compiler/ElasticsearchClientPassTest.php
| Tickets       | closes https://github.com/api-platform/core/issues/6788
This PR re-introduces ES7 support, by simply introducing the v7 client namespaces.
> feat(elasticsearch): re-introduce v7 support

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Eloquent/Metadata/ModelMetadata.php
- src/Metadata/Resource/Factory/ConcernsResourceNameCollectionFactory.php
- src/Metadata/Resource/Factory/LinkFactory.php
- src/Metadata/Util/ReflectionClassRecursiveIterator.php
Few changes:
- ModelMetadata was not a singleton in Laravel and we had 2 different instances
- ModelMetadata clean up (some methods were dead code) + added memory cache for better speed in dev mode
- defining uriVariables (for example: `uriVariables: ['id']`) is always faster then letting us compute them as we go through every property, added a local memory cache for that too
-  ReflectionClassRecursiveIterator is now used in 3 classes (compared to only one in API Platform 3.4), 2 of them are used with Symfony and 3 with Laravel, I added a simple local memory cache for that too as it loops over all declared classes in the project. 
https://github.com/api-platform/core/pull/6943 is a great start to remove that ReflectionClassRecursiveIterator but we need time to do it properly, and it also …
> perf: various optimizations for Laravel/Symfony

- src/Symfony/composer.json
In https://github.com/api-platform/core/pull/6952, the class `ApiPlatform\State\ErrorProvider` have been updated, with its DI configuration.
Fixes this error:
> Invalid service "api_platform.state.error_provider": method "ApiPlatform\State\ErrorProvider::__construct()" has no argument named "$resourceMetadataCollectionFactory". Check your service definition.
> fix(symfony): Update bundle dependency to state package

- src/Laravel/Tests/ApiTest.php
- src/Laravel/routes/api.php
- src/Laravel/workbench/app/Models/PrefixedOperation.php
- src/OpenApi/Factory/OpenApiFactory.php
> fix(laravel): handle route prefix

- src/Symfony/Bundle/Test/ApiTestCase.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
> fix: boot kernel only if it's necessary in `createClient()` method

- src/Symfony/Bundle/Test/ApiTestAssertionsTrait.php
| Doc PR        | Tell me if it's necessary and I'll create it.
By default, the json schema format is validated when the use the `assertMatchesResourceCollectionJsonSchema` and the `assertMatchesResourceItemJsonSchema`. This is a problem when we change the default DateTime format because we MUST no longer use the format Json Schema validation. We should rely on the 'pattern' attribute instead.
```php
#[Context([DateTimeNormalizer::FORMAT_KEY => 'Y-m-d\TH:i:s'])]
#[ApiProperty(
// As the format of date-time is not standard, we need to change the
// JsonSchema accordingly.
jsonSchemaContext: [
'type' => 'string',
// Unfortunately, there is no built-in way here to remove the `format` …
```
> feat(jsonschema): Add `checkMode` parameter to control json schema validation in tests

- src/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Doctrine/Orm/Tests/Extension/EagerLoadingExtensionTest.php
| Tickets       | Closes https://github.com/api-platform/core/pull/6973.
Fixes the following deprecation: "Using ArrayAccess on Doctrine\ORM\Mapping\JoinColumnMapping is deprecated and will not be possible in Doctrine ORM 4.0. Use the corresponding property instead."
> fix: Doctrine mapping ArrayAccess deprecation

- src/Symfony/Bundle/Test/ApiTestCase.php
- tests/Functional/ArrayDtoTest.php
- tests/Functional/BackedEnumPropertyTest.php
- tests/Functional/BackedEnumResourceTest.php
- tests/Functional/ErrorTest.php
- tests/Functional/FormatTest.php
- tests/Functional/HALCircularReference.php
- tests/Functional/HydraTest.php
- tests/Functional/Issues/Issue6926Test.php
- tests/Functional/ItemUriTemplateTest.php
- tests/Functional/JsonLdTest.php
- tests/Functional/OpenApiTest.php
- tests/Functional/Parameters/BooleanFilterTest.php
- tests/Functional/Parameters/DateFilterTest.php
- tests/Functional/Parameters/DoctrineTest.php
- tests/Functional/Parameters/ExistsFilterTest.php
- tests/Functional/Parameters/HydraTest.php
- tests/Functional/Parameters/NumericFilterTest.php
- tests/Functional/Parameters/OrderFilterTest.php
- tests/Functional/Parameters/ParameterProviderTest.php
- tests/Functional/Parameters/ParameterTest.php
- tests/Functional/Parameters/QueryParameterStateOptionsTest.php
- tests/Functional/Parameters/RangeFilterTest.php
- tests/Functional/Parameters/SecurityTest.php
- tests/Functional/Parameters/StrictParametersTest.php
- tests/Functional/Parameters/ValidationTest.php
- tests/Symfony/Bundle/Test/ApiTestCaseTest.php
- tests/Symfony/Bundle/Test/ClientTest.php
> fix(symfony): add a `alwaysBootKernel` property for BC layer

- .commitlintrc
- src/HttpCache/State/AddHeadersProcessor.php
- src/HttpCache/Tests/State/AddHeadersProcessorTest.php
- src/Metadata/HttpOperation.php
Some cache directives were missing from the `AddHeadersProcessor`, like `no-store`, this PR adds them.
> feat(httpcache): add more cache directives to AddHeadersProcessor

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Tests/AutoconfigureTest.php
- src/Laravel/testbench.yaml
- src/Laravel/workbench/app/ApiResource/ServiceProvider.php
- src/Laravel/workbench/app/Models/PrefixedOperation.php
- src/Laravel/workbench/app/State/CustomProvider.php
- src/Metadata/Util/ReflectionClassRecursiveIterator.php
| Branch?       | 4.1 (feature is available inside symfony)
| Doc PR        | needs to be done
> feat(laravel): auto configure our tagged interfaces

- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Tests/JsonApiTest.php
- src/Laravel/workbench/app/Models/Book.php
This PR doesn't change much we just moved the parameters to our `defaults` section to test if it works properly. 
We can definitely close #6841 with the documentation commit at https://github.com/api-platform/docs/commit/c7892af178736840d6f93b60192f7c246098ac3e
> fix(laravel): json api default parameters

- src/State/Provider/ParameterProvider.php
- tests/Fixtures/TestBundle/ApiResource/WithParameter.php
- tests/Functional/Parameters/ParameterTest.php
| Branch?       | 3.x
The type-hint on `ApiPlatform\Metadata\Parameter` suggest a `ParameterProviderInterface` can be passed to `provider` property, but this won't work as expected in this case. This PR ensures it works.
Example:
```php
#[Api\ApiResource(
operations: [
new Api\GetCollection(
parameters: [
'foo' => new Api\QueryParameter(
provider: new FooParameterProvider(),
),
],
),
]
)]
class Resource
{
}
```
> fix: allow parameter provider as object

- src/Laravel/testbench.yaml
- src/Laravel/workbench/app/Modules/ExampleModule/tests/Feature/DoNothingTest.php
- src/Metadata/Util/ReflectionClassRecursiveIterator.php
Fixes https://github.com/api-platform/core/issues/7023
> fix(laravel): do not require files while autoconfiguring

- src/Laravel/ApiPlatformDeferredProvider.php
- src/Laravel/ApiPlatformProvider.php
- src/Laravel/Controller/ApiPlatformController.php
- src/Laravel/Exception/ErrorHandler.php
fixes https://github.com/api-platform/core/issues/7048
> fix(laravel): error handler only on api routes

- src/Metadata/Extractor/YamlResourceExtractor.php
- src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php
| Tickets       | Closes #6598
Link security was ignored in YAML. This PR fix this.
> fix(subresource): Link Security YAML

- src/Hydra/Serializer/DocumentationNormalizer.php
- src/Hydra/Tests/Serializer/DocumentationNormalizerTest.php
- src/Laravel/ApiPlatformProvider.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/Resources/config/hydra.xml
- src/Symfony/Routing/ApiLoader.php
This PR aims to fix definitively a recurring issue: **JSON-LD documentation is mandatory** but users don't want to expose their endpoints when the API is private: https://github.com/api-platform/core/issues/1568
The `enable_docs` configuration parameter removes the `api_doc` route: the documentation is not exposed anymore, but the URL is needed in some parts of the API Platform code: JSON-LD context, Hydra links, etc.
It regularly causes some bugs.
A relating PR was done in 2018:
https://github.com/api-platform/core/pull/1731
This PR was removing the code adding the Hydra headers when the docs is disabled.
IMO @dunglas's …
> fix(hydra): use correctly enable_docs

- composer.json
- src/Metadata/Resource/Factory/OperationDefaultsTrait.php
| Tickets       | Closes #7072
> fix(symfony): internal resources should not inherit global defaults

- .github/patches/phpunit.patch
- .github/workflows/ci.yml
- phpunit.xml.dist
- src/Doctrine/Common/phpunit.xml.dist
- src/Doctrine/Odm/phpunit.xml.dist
- src/Doctrine/Orm/phpunit.xml.dist
- src/Elasticsearch/phpunit.xml.dist
- src/GraphQl/phpunit.xml.dist
- src/HttpCache/phpunit.xml.dist
- src/Hydra/phpunit.xml.dist
- src/JsonApi/phpunit.xml.dist
- src/JsonSchema/phpunit.xml.dist
- src/Laravel/phpunit.xml.dist
- src/Metadata/phpunit.xml.dist
- src/OpenApi/phpunit.xml.dist
- src/RamseyUuid/phpunit.xml.dist
- src/Serializer/phpunit.xml.dist
- src/State/phpunit.xml.dist
- src/Symfony/phpunit.xml.dist
- src/Validator/phpunit.xml.dist
>  chore: phpunit missing deprecation triggers 

- src/State/ProviderInterface.php
| Tickets       | #5303
The actual phpDoc `@template` definition does not allow the provider to return arrays (like Doctrine mixed results).
This tiny PR avoid PHPStan (and probably Psalms too) to throw some errors like the following
```
@param for parameter \$collectionProvider is not subtype of template type T of object of interface
```
This was initially a feedback by @nesl247 for Psalm and not really fixed by #5024
> fix(state): update generic template type variable in ProviderInterface

- src/Serializer/AbstractItemNormalizer.php
| Branch?       | 4.1 
Backport union/intersection types support in item normalizer from @mtarld work done in #6979
> fix(serializer): backport handling of union/intersection type in item normalizer

- src/Metadata/Parameter.php
- src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
- src/Metadata/Tests/Fixtures/ApiResource/WithLimitedPropertyParameter.php
- src/Metadata/Tests/Resource/Factory/ParameterResourceMetadataCollectionFactoryTest.php
| Branch?       | 4.1 (may be considered as a feature, experimental classes + really improves usability) 
When using a parameter on multiple properties it's common usage to want to use only a specific range of properties (only dates, etc.).
> fix(state): specify :property parameter properties

- src/State/ProviderInterface.php
Reverts api-platform/core#7083
> Revert "fix(state): update generic template type variable in ProviderInterface"

- src/Metadata/Util/AttributeFilterExtractorTrait.php
| Branch?       | 4.1 
| Tickets       | N/A 
| Doc PR        | N/A 
When specifying properties on a `SearchFilter`, it does not use the `strategy` if the `properties` is only an array of property names and does not specify a per property strategy.
```
#[ApiFilter(filterClass: SearchFilter::class, strategy: 'ipartial', properties: ['link.name'])]
```
Without this PR, the strategy for `link.name` is `exact`.
> fix: filtering not using strategy set in attribute when strategy not set per property

- src/Doctrine/Common/Filter/BackedEnumFilterTrait.php
- tests/Fixtures/TestBundle/Entity/Issue7126/DummyForBackedEnumFilter.php
- tests/Fixtures/TestBundle/Entity/Issue7126/IntegerBackedEnum.php
- tests/Fixtures/TestBundle/Entity/Issue7126/StringBackedEnum.php
- tests/Functional/BackedEnumFilterTest.php
| Tickets       | #7126
Currently BackedEnumFilter displays integer backed enums on the docs page but does not filter them.
This is because the $value received by `filterProperty` is a string and not an integer.
I solved this by adding this short code snippet at the start of the `normalizeValue` function in the `BackedEnumFilterTrait` to attempt to convert the value to an integer if the enum is a backed integer enum.
```php
$firstCase = $this->enumTypes[$property]::cases()[0] ?? null;
if (
is_int($firstCase?->value)
&& false !== filter_var($value, FILTER_VALIDATE_INT)
) {
$value = (int) $value;
}
```
Alternatively, we could use ReflectionEnum::getBackingType(), but this avoids the …
> fix(doctrine): support integer-backed enums in BackedEnumFilter

- phpunit.xml.dist
- src/Laravel/Exception/ErrorHandler.php
- src/Symfony/EventListener/ErrorListener.php
- tests/Fixtures/TestBundle/Entity/Issue7135/Bar.php
- tests/Fixtures/TestBundle/Entity/Issue7135/Foo.php
- tests/Functional/Issues/Issue7135Test.php
Hello...
when i send POST request with body
```
"items": [
{
"quantity": 0,
"product": "/api/catalog/products/invalid-uuid"
}
]
```
then i have error 500 response.
But GET method with wrong UUID identifier is Invalid uri variables with 404 status code.
This chage return better status e400 code.
> fix(symfony,laravel): InvalidUriVariableException status code (e400)

- src/State/Provider/DeserializeProvider.php
- src/State/SerializerContextBuilderInterface.php
- src/State/Tests/Provider/DeserializeProviderTest.php
- src/Symfony/Controller/MainController.php
- src/Symfony/EventListener/DeserializeListener.php
| Tickets       | alternative to #7123
I have a use case where I need to send a "code" (2FA code) when deleting a resource.
With this PR, I'm able to send the code along with a DELETE request:
```
curl --request DELETE \
--url https://redirection-io.test/app_dev.php/api/users/424e19b0-0db9-4595-bc43-f03632b3fe65/two-factor/devices/4d9853c3-f53c-422d-80cd-6c4c4fa64650 \
--header 'Authorization: Bearer .....'
--header 'Content-Type: application/json' \
--header 'accept: application/ld+json' \
--data '{
"code": "610432"
}'
```
I use a custom DTO to do so:
```php
#[ApiResource(
operations: [
new Delete(
uriTemplate: '/users/{id}/two-factor/devices/{deviceId}',
provider: …
```
> feat(serializer): set the object-to-populate in deserializer context as soon as data !== null

- src/Metadata/Extractor/XmlResourceExtractor.php
Building HTTP cache headers in `XmlResourceExtractor` does not cast read values, which means all values will be strings. In case of eg. `s-maxage` header, that will result in error since Symfony's `Response::setSharedMaxAge(int $value): object` expects it to be an integer.
```xml
<cacheHeaders>
<cacheHeader name="shared_max_age">7200</cacheHeader>
</cacheHeaders>
```
> Fix: PHPize HTTP cache headers

- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Symfony/Bundle/Resources/config/openapi.xml
- tests/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
> feat(symfony): Add error classes options to OpenAPI config

- composer.json
- src/Laravel/Eloquent/Extension/FilterQueryExtension.php
- src/Laravel/Eloquent/Filter/JsonApi/SortFilterParameterProvider.php
- src/Metadata/Parameter.php
- src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
- src/Metadata/composer.json
- src/State/Util/ParameterParserTrait.php
- src/Symfony/Validator/State/ParameterValidatorProvider.php
- src/Validator/Metadata/Resource/Factory/ParameterValidationResourceMetadataCollectionFactory.php
- src/Validator/composer.json
- tests/Fixtures/TestBundle/ApiResource/Issue6673/MutlipleParameterProvider.php
- tests/Fixtures/TestBundle/ApiResource/WithParameter.php
- tests/Fixtures/TestBundle/ApiResource/WithSecurityParameter.php
- tests/Fixtures/TestBundle/Document/FilteredBooleanParameter.php
- tests/Fixtures/TestBundle/Document/FilteredExistsParameter.php
- tests/Fixtures/TestBundle/Document/FilteredOrderParameter.php
- tests/Fixtures/TestBundle/Entity/FilteredBooleanParameter.php
- tests/Fixtures/TestBundle/Entity/FilteredExistsParameter.php
- tests/Fixtures/TestBundle/Entity/FilteredOrderParameter.php
- tests/Functional/Parameters/ParameterTest.php
- tests/Functional/Parameters/ValidationTest.php
| Tickets       | Closes #7111
Adds a nativeType to parameters, defaults to `list<string>|string` as this is the default with Symfony query parameters parsing and for HTTP Headers. It also fixes the value extraction accordingly and the validation that may have work partially on a value that's extracted as an array.
TODO:
> refactor(metadata): type parameters to list<string>|string

- src/Symfony/EventListener/ErrorListener.php
- src/Symfony/Routing/ApiLoader.php
- tests/Fixtures/TestBundle/ApiResource/XmlWithJsonError.php
- tests/Functional/ErrorTest.php
- tests/Symfony/Routing/ApiLoaderTest.php
todo: test (input XML, errors JSON whith no accept header)
> fix: error formats

- src/Metadata/Parameter.php
- src/State/Util/ParameterParserTrait.php
- tests/Fixtures/TestBundle/ApiResource/WithParameter.php
- tests/Functional/Parameters/ParameterTest.php
| Tickets       | Closes #7157
This fixes a breaking change into how parameters are parsed when a string is expected. This also fixes an inconsistency where the default `string|string[]` type for a query parameter should allow both types.
> fix(metadata): parameter cast to array flag

- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/Tests/AbstractItemNormalizerTest.php
| Tickets       | Closes #7149
> fix(serializer): Fix exception message to not expose resource FQCN

- src/Laravel/routes/api.php
- src/Symfony/Routing/ApiLoader.php
> fix: skip openapi webhooks when generating routes

- .github/workflows/ci.yml
- .github/workflows/subtree.yml
- composer.json
- src/Doctrine/Common/composer.json
- src/Doctrine/Odm/composer.json
- src/Doctrine/Orm/composer.json
- src/Documentation/composer.json
- src/Elasticsearch/composer.json
- src/GraphQl/composer.json
- src/Hal/composer.json
- src/HttpCache/composer.json
- src/Hydra/composer.json
- src/JsonApi/composer.json
- src/JsonLd/composer.json
- src/JsonSchema/composer.json
- src/Metadata/composer.json
- src/OpenApi/composer.json
- src/RamseyUuid/composer.json
- src/Serializer/composer.json
- src/State/composer.json
- src/Symfony/composer.json
- src/Validator/composer.json
The solution to test lower branches implemented at https://github.com/api-platform/core/commit/0a1a1eac0ed8b04a32e724fe324937a70b3cc5f5 actually has an impact on the release process and I didn't anticipated that... 
This should do the same although it'll be harder to reproduce a lower-branch control locally (as you need this environment variable).
> ci: remove version from composer to avoid release side effects

- src/Laravel/Eloquent/State/PersistProcessor.php
- src/Laravel/Tests/EloquentTest.php
- src/Laravel/workbench/app/Models/CommentMorph.php
- src/Laravel/workbench/app/Models/PostWithMorphMany.php
- src/Laravel/workbench/database/migrations/2025_06_13_130000_create_posts_with_morph_many_table.php
> fix(laravel): persist HasMany and MorphMany relationships

- tests/Symfony/Bundle/Command/DebugResourceCommandTest.php
> test(symfony): mock uses Application::addCommand instead of add

- src/Laravel/Eloquent/State/LinksHandler.php
- src/Laravel/Tests/EloquentTest.php
- src/Laravel/workbench/app/Models/CommentMorph.php
- src/Laravel/workbench/database/factories/CommentFactory.php
- src/Laravel/workbench/database/factories/CommentMorphFactory.php
- src/Laravel/workbench/database/factories/PostWithMorphManyFactory.php
| Tickets       | #7227 
This PR adds support for polymorphic relationships from within the `LinksHandler`.
Previously:
This would result in bad query formation where the model type was not taken into account and you could have multiple model types returned with the same IDs:.
```select * from `attachments` where `attachments`.`model_id` = ?```
```
new GetCollection(
uriTemplate: '/projects/{id}/attachments',
uriVariables: [
'id' => new Link(
fromProperty: 'attachments',
fromClass: Project::class,
),
],
),
```
Now:
```
select * from `attachments` where `attachments`.`model_type` = ? and `attachments`.`model_id` = ? and `attachments`.`model_id` is not null
```
We …
> fix(laravel): Allow `LinksHandler` to handle polymorphic relationships

- src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
Considering the following configuration:
```php
new GetCollection(
// ...
parameters: [
'archivedOnly' => new QueryParameter(
key: 'archivedOnly',
schema: ['type' => 'boolean'],
required: true,
openApi: new Model\Parameter(
name: 'archivedOnly',
in: 'query',
required: true,
),
),
],
),
```
The current code only supports `array` or `string` types, then fallback to `an array of strings` (cf. `ParameterResourceMetadataCollectionFactory` line 160), which seems then considered to an iterable by the validator (`All` validator is applied, which expects an `array` as value), leading to the following error:
> Symfony\Component\HttpClient\Exception\ClientException: An …
> fix: fix boolean parameters type detection

- src/Metadata/Extractor/XmlResourceExtractor.php
Fix OpenApi attribute extraction from ApiResource Xml files.
In the first place `XmlResourceExtractor` was only extracting the `deprecated` attribute.
After fixing, a bug in SimpleXml lib led to infinite loop (at least on php 8.1/8.3) when OpenApi has multiple attributes (eg. `<openapi operationId="myOperationId" description="my description" />`)
Introduced by #5254
> fix(metadata): build Open Api attributes in XmlResourceExtractor

- src/Doctrine/Odm/Metadata/Resource/DoctrineMongoDbOdmResourceCollectionMetadataFactory.php
- src/Doctrine/Odm/Tests/Metadata/Resource/DoctrineMongoDbOdmResourceCollectionMetadataFactoryTest.php
- src/Doctrine/Orm/Metadata/Resource/DoctrineOrmResourceCollectionMetadataFactory.php
- src/Doctrine/Orm/Tests/Metadata/Resource/DoctrineOrmResourceCollectionMetadataFactoryTest.php
- src/Hydra/Serializer/EntrypointNormalizer.php
- src/JsonApi/Serializer/EntrypointNormalizer.php
- src/Metadata/ApiResource.php
- src/Metadata/CascadeFromResource.php
- src/Metadata/CascadeToOperationsTrait.php
- src/Metadata/Operation.php
- src/Metadata/Operations.php
- src/Metadata/Resource/Factory/FormatsResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/NotExposedOperationResourceMetadataCollectionFactory.php
- src/Metadata/Resource/Factory/OperationDefaultsTrait.php
- src/Metadata/Resource/ResourceMetadataCollection.php
- src/Metadata/Tests/Resource/Factory/AttributesResourceMetadataCollectionFactoryTest.php
- src/Metadata/WithResourceTrait.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/Symfony/Routing/ApiLoader.php
- tests/Fixtures/TestBundle/Entity/AttributeResource.php
Also related to https://github.com/api-platform/core/pull/7213 
Adds a way to update your operations without having to do it manually (only when values are null but are set on the api resource).
This code would also make a refactoring possible inside our current metadata factories.
>  refactor(metadata): cascade resource to operation 

- src/JsonSchema/SchemaFactory.php
| Tickets       | Closes #7162
> fix(jsonschema): rebuild sub-schema definition without @id property when `genId` is `false` (#7162)

- composer.json
- src/State/Processor/ObjectMapperProcessor.php
- src/State/Provider/ObjectMapperProvider.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Bundle/Resources/config/state/object_mapper.xml
- tests/Fixtures/TestBundle/ApiResource/MappedResource.php
- tests/Fixtures/TestBundle/ApiResource/MappedResourceOdm.php
- tests/Fixtures/TestBundle/Document/MappedDocument.php
- tests/Fixtures/TestBundle/Entity/MappedEntity.php
- tests/Functional/MappingTest.php
Still a few things left to be done but this is a first approach. This makes API Platform compatible with the Object Mapper component: https://github.com/symfony/symfony/pull/51741
Demo: 
```
composer create-project symfony/skeleton test-objectmapper2
cd test-objectmapper2
composer req debug api-platform/symfony api-platform/doctrine-orm make orm symfony/asset 
nvim .env # uncomment sqlite
nvim composer.json # change extra.symfony to 7.3.*
composer config minimum-stability RC
composer req symfony/object-mapper:^7.3.0-RC1 symfony/type-info:v7.3.0-RC1 symfony/framework-bundle:v7.3.0-RC1 -W 
composer link ../core-6801 # if link is not available `composer global require soyuka/pmu`
bin/console make:entity # …
```
> feat(symfony): object mapper with state options

- phpstan.neon.dist
- src/Doctrine/Odm/State/LinksHandlerTrait.php
- src/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php
- src/Doctrine/Orm/State/CollectionProvider.php
- src/Doctrine/Orm/State/ItemProvider.php
- src/Elasticsearch/State/ItemProvider.php
- src/Metadata/ApiResource.php
- src/Metadata/Tests/Resource/OperationTest.php
- src/OpenApi/Factory/OpenApiFactory.php
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/Tests/AbstractItemNormalizerTest.php
- src/State/Provider/DeserializeProvider.php
- src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Symfony/Controller/MainController.php
- src/Symfony/EventListener/DeserializeListener.php
- src/Symfony/EventListener/ReadListener.php
- src/Symfony/EventListener/WriteListener.php
I was fixing the `identifier: instanceof.alwaysTrue` errors and ends up with code like 
```
if (null === $parameter->getOpenApi() && ($openApi = $description[$key]['openapi'] ?? null) && $openApi instanceof OpenApiParameter) {
```
=> Here the  `$openApi instanceof OpenApiParameter` check is reported as useless but the type is coming from phpdoc and there is a test which check what happen if the phpdoc is not respected
or 
```
$repository = $manager->getRepository($documentClass);
if (!$repository instanceof DocumentRepository) {
```
Same here, instanceof …
> chore: disable treat phpdoc type as certain for phpstan

- src/JsonLd/Serializer/ItemNormalizer.php
- src/Serializer/OperationContextTrait.php
- tests/Fixtures/TestBundle/ApiResource/GenIdFalse/LevelFirst.php
- tests/Fixtures/TestBundle/ApiResource/GenIdFalse/LevelSecond.php
- tests/Fixtures/TestBundle/ApiResource/GenIdFalse/LevelThird.php
- tests/Functional/JsonLdTest.php
| Tickets       | Closes #7258 #7261
I failed reproducing the users bc breaks, I think I isolated the behavior though, @norkunas @GSadee may you please check this patch and tell me if it solves your issues? Also would it be possible to have a look at my test fixtures and let me know how your configuration differs from my test?
> fix(jsonld): reset gen_id configuration

- phpstan.neon.dist
- src/Doctrine/Odm/PropertyHelperTrait.php
- src/Doctrine/Orm/Util/QueryBuilderHelper.php
- src/GraphQl/Subscription/SubscriptionManager.php
- src/GraphQl/Tests/Type/FieldsBuilderTest.php
- src/GraphQl/Tests/Type/TypeBuilderTest.php
- src/GraphQl/Tests/Type/TypeConverterTest.php
- src/GraphQl/Type/TypeConverter.php
- src/HttpCache/Tests/SouinPurgerTest.php
- src/HttpCache/Tests/VarnishPurgerTest.php
- src/HttpCache/Tests/VarnishXKeyPurgerTest.php
- src/Laravel/Eloquent/Paginator.php
- src/Laravel/Eloquent/PartialPaginator.php
- src/Metadata/ApiProperty.php
- src/Metadata/IdentifiersExtractorInterface.php
- src/Metadata/IriConverterInterface.php
- src/Metadata/IsApiResource.php
- src/State/Pagination/Pagination.php
- src/State/Provider/ContentNegotiationProvider.php
- src/Symfony/Doctrine/EventListener/PublishMercureUpdatesListener.php
- src/Symfony/Routing/ApiLoader.php
- tests/Behat/JsonApiContext.php
- tests/Behat/OpenApiContext.php
- tests/Fixtures/TestBundle/Security/SecuredDummyAttributeBasedVoter.php
- tests/OpenApi/Command/OpenApiCommandTest.php
- tests/State/RespondProcessorTest.php
> chore: more phpstan fixes

- src/Metadata/ApiProperty.php
- src/Serializer/composer.json
- src/Symfony/Tests/Validator/Metadata/Property/Restriction/PropertySchemaFormatTest.php
> fix: symfony deprecations

- src/Metadata/Metadata.php
| Tickets       | Closes #...
Hi @soyuka,
When using `Operation::getExtraProperties`, phpstan report
```
Call to method getExtraProperties() of internal class          
ApiPlatform\Metadata\Metadata from outside its root namespace  
ApiPlatform
```
This is because those getter are defined in Metadata which is marked as internal.
You can see a reproducer on phpstan.org with https://phpstan.org/r/ec5a2ab4-eac7-4814-836d-0edf97ccee25
Since all Metadata setter/getter shouldn't be considered as internal ; I feel like the simplest solution would be to remove the `@internal` tag from the abstract class.
Would be nice if it could be added before the 4.2 release. 🙏
> Remove internal from Metadata

- src/Doctrine/Common/Filter/BackedEnumFilterTrait.php
- src/Doctrine/Orm/Filter/BackedEnumFilter.php
- src/Doctrine/Orm/Tests/Filter/BackedEnumFilterTest.php
- src/Doctrine/Orm/Tests/Filter/BackedEnumFilterTestTrait.php
| Tickets       | #7128
| Doc PR        |  
Allows multiple values for BackedEnumFilter to make it work similar to SearchFilter[exact].
There currently is no section for BackedEnumFilter in https://github.com/api-platform/docs/blob/main/core/doctrine-filters.md I can create a PR to add one if needed.
Before:  
After:
> feat(doctrine): BackedEnumFilter allow multiple values similar to SearchFilter[exact]

- src/Metadata/Resource/Factory/PhpDocResourceMetadataCollectionFactory.php
- src/Metadata/composer.json
| Tickets       | Closes #7275
Not fully sure about this one @soyuka but
- I assume the issue https://github.com/api-platform/core/issues/7275 is related to https://github.com/api-platform/core/pull/7204/files#diff-a74b749ab4aa559ca58d9087c4f2c9193ca78bc87ac65ab9a6a09f2d8b799581 which does not require phpstan/doc-parser since 4.18.
- Lot of PHPStan\PhpDocParser classes are used in PhpDocResourceMetadataCollectionFactory. (like https://github.com/api-platform/core/blob/d3b98b5354213937f96143c5d8819f98e2e66640/src/Metadata/Resource/Factory/PhpDocResourceMetadataCollectionFactory.php#L141)
So since phpDocParser/lexer will be null when PhpDocParser is not installed, a …
> Do not fail if phpstan/phpdoc-parser is missing

- features/openapi/docs.feature
- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
Currently, even if we set `pagination_client_enabled` to `true`, the `partial` query parameter is not automatically output to the OpenAPI document.
This PR makes it so that it is automatically output.
e.g.
```diff
api_platform:
title: Hello API Platform
version: 1.0.0
defaults:
stateless: true
cache_headers:
vary: ['Content-Type', 'Authorization', 'Origin']
+         pagination_client_enabled: true
+         pagination_client_items_per_page: true
+         pagination_client_partial: true
```
| Before | After |
| --- | --- |
| ![](https://github.com/user-attachments/assets/8c3cfb78-f442-45ad-889d-8392f822ed6c) | …
> fix(openapi): output `partial` query parameter to OpenAPI when `pagination_client_enabled` is true

- src/State/Processor/ObjectMapperProcessor.php
- src/State/Provider/ObjectMapperProvider.php
- tests/Fixtures/TestBundle/ApiResource/FirstResource.php
- tests/Fixtures/TestBundle/ApiResource/SecondResource.php
- tests/Fixtures/TestBundle/Entity/SameEntity.php
- tests/Functional/MappingTest.php
| Tickets       | Closes #7310 
Small fix to force the correct target mapping when an entity is mapped to multiple resources.
> fix(symfony): explicitly set the target when mapping entities to resources

- src/Serializer/ItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/Issue6225/Bar6225.php
- tests/Fixtures/TestBundle/Entity/Issue6225/Foo6225.php
- tests/Functional/NestedPatchTest.php
| Tickets       | Resolves https://github.com/api-platform/core/issues/6225
The linked issue was resolved for JSON LD format with https://github.com/api-platform/core/pull/6451 but not for standard JSON, so this PR implements the same change in the standard ItemNormalizer.
The included test file demonstrates the expected behaviour, it should be possible to alter the Bar entity's `someProperty` via a PATCH request to edit its parent `Foo` object.
This test passes with the ItemNormalizer change, but fails without it due to `Extra attributes are not allowed (\"id\" is unknown).`.
First contribution so let me know if I've done things correctly or if I've missed anything needed for approval!
> fix(serializer): Allow nested denormalization when allow_extra_attributes=false

- composer.json
- src/State/ObjectMapper/ClearObjectMapInterface.php
- src/State/ObjectMapper/ObjectMapper.php
- src/State/Processor/ObjectMapperProcessor.php
- src/Symfony/Bundle/Resources/config/state/object_mapper.xml
- tests/Fixtures/TestBundle/ApiResource/MappedResourceWithRelation.php
- tests/Fixtures/TestBundle/ApiResource/MappedResourceWithRelationRelated.php
- tests/Fixtures/TestBundle/Entity/MappedResourceWithRelationEntity.php
- tests/Fixtures/TestBundle/Entity/MappedResourceWithRelationRelatedEntity.php
- tests/Functional/MappingTest.php
Fixes an issue where we keep fetched relations so that we don't create new entities instead of persisting the existing one. Check the test and the issue at https://github.com/symfony/symfony/issues/61119. 
This needs https://github.com/symfony/symfony/pull/61145 to work.
> fix(state): object-mapper reuse related entity

- src/JsonApi/Serializer/ConstraintViolationListNormalizer.php
- src/JsonApi/Tests/Serializer/ConstraintViolationNormalizerTest.php
| Tickets       | Closes https://github.com/api-platform/api-platform/issues/2920
| Doc PR        | doesn't apply
> fix(jsonapi): handle type error when handling validation errors

- src/State/ApiResource/Error.php
| Tickets       | Closes 
Currently, when setting the details, it set both the description and the details since the `getDescription` returns 
```
public function getDescription(): ?string
{
return $this->detail;
}
```
So I feel like we're missing a `setDescription`, this way:
- To override both description and detail, we use `setDetails`
- To just override the description, we use `setDescription` 
And both field now might have a different value.
> Add Error:setDescription

- src/Symfony/Bundle/Resources/config/doctrine_orm_http_cache_purger.xml
- src/Symfony/Doctrine/EventListener/PurgeHttpCacheListener.php
Could you check this @mrossard ?
> fix(httpcache): only map entites that are persisted

- src/State/SerializerAwareProviderInterface.php
- src/State/SerializerAwareProviderTrait.php
- src/Symfony/Bundle/ApiPlatformBundle.php
- src/Symfony/Bundle/DependencyInjection/Compiler/DataProviderPass.php
- tests/Fixtures/TestBundle/State/SerializableProvider.php
- tests/Symfony/Bundle/ApiPlatformBundleTest.php
| Branch?       | `4.2`
Made the deprecation before the removal made in #7314.
**Reason**: Direct access to private services is discouraged because this practice:
-  Violates the dependency injection principle, which is at the heart of Symfony's architecture.
- Creates a strong coupling between your code and the container, making it less modular.
- Makes your application more fragile and much more difficult to maintain and test.
That's why PHPStan reported an error, which is ignored by our PHPStan config here: https://github.com/vinceAmstoutz/api-platform-core/blob/9e382e01bb4529d4ae63dbbeda01839d1da2994a/phpstan.neon.dist#L107-L110.
**Historic reason**:
After looking at its history, it looks like a legacy …
> fix(serializer): deprecate SerializerAwareProviderInterface and SerializableProvider

- src/Symfony/Doctrine/EventListener/PurgeHttpCacheListener.php
- src/Symfony/Tests/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
- src/Symfony/Tests/Fixtures/MappedEntity.php
- src/Symfony/Tests/Fixtures/MappedResource.php
- src/Symfony/composer.json
- tests/Behat/HttpCacheContext.php
| Tickets       | Closes #7347
Followup on #7345. This version waits for the doctrine flush() before trying to map the inserted entites to resources, which should ensure we invalidate the related resource collections correctly.
The related test was also reworked, it didn't do what it should. On that point i'm not sure whether it's correct to prophesize the ObjectMapper...the test would be better with a real instance IMO, but i can't (yet?) figure out how to do that easily.
> fix(httpcache): collection iri invalidation for mapped entities

- src/Symfony/Bundle/ApiPlatformBundle.php
- src/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPass.php
- tests/Symfony/Bundle/ApiPlatformBundleTest.php
- tests/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php
| Tickets       | Closes #6101 
If set, the name_converter in api_platform was being applied to any serializer defined in framework.yaml. The PR moves MetadataAwareNameConverterPass before Symfony's own SerializerPass and configures the container parameters as Symfony would expect.
Tested only with SF 7.3.
/cc @soyuka
> Only set name_converter for the default serializer

- src/Metadata/HttpOperation.php
- src/Metadata/Tests/Resource/OperationTest.php
When adding an operation to an ApiResource, setting `paginationViaCursor` has no effect because the parent constructor of `HttpOperation` is missing the`paginationViaCursor` parameter.
```
#[ApiResource(
// this works
paginationViaCursor: [ 
[
'field' => 'newId',
'direction' => 'DESC',
]
],
operations: [
new GetCollection(
uriTemplate: '/users',
// this does not
paginationViaCursor: [
[
'field' => 'id',
'direction' => 'DESC',
]
],
),
],
)]
```
> fix: pagination via cursor on ApiResource operations

- src/State/ParameterProvider/ReadLinkParameterProvider.php
- tests/Fixtures/TestBundle/ApiResource/LinkParameterProviderResource.php
- tests/Fixtures/TestBundle/Entity/Employee.php
- tests/Functional/Parameters/LinkProviderParameterTest.php
```php
#[Get(
uriTemplate: '/link_parameter_provider_resources/{id}',
uriVariables: [
'id' => new Link(
provider: ReadLinkParameterProvider::class,
fromClass: Dummy::class
),
],
provider: [self::class, 'provide']
)]
class LinkParameterProviderResource
{
public string $id;
public Dummy $dummy;
public Dummy $dummyFromOperation;
/**
* @param HttpOperation $operation
*/
public static function provide(Operation $operation, array $uriVariables = [])
{
$d = new self();
$d->id = '1';
$d->dummyFromOperation = $operation->getUriVariables()['id']->getValue();
$d->dummy = $uriVariables['id'];
return $d;
}
}
```
> fix(state): transform uri variable using ReadLinkParameterProvider

- composer.json
- src/Symfony/composer.json
Since the version was removed in : https://github.com/api-platform/core/pull/7054
> fix(symfony): remove suggest ocramius/package-versions

- src/Symfony/Tests/Validator/State/ParameterValidatorProviderTest.php
- src/Symfony/Validator/State/ParameterValidatorProvider.php
> fix(symfony): openapi property path for validation

- src/JsonSchema/SchemaFactory.php
- src/JsonSchema/Tests/Fixtures/GenericChild.php
- src/JsonSchema/Tests/Fixtures/NotAResource.php
- src/JsonSchema/Tests/SchemaFactoryTest.php
Fix schema generic generation with new `TypeInfo`component introduced in 4.2
> fix: handle generic schema in JsonSchema

- src/OpenApi/Factory/OpenApiFactory.php
- src/OpenApi/Model/Response.php
- src/OpenApi/Tests/Factory/OpenApiFactoryTest.php
| Branch?       | 4.2 like https://github.com/api-platform/core/pull/7412 ?
cc @soyuka This is a followed up of https://github.com/api-platform/core/pull/7412 to have a 100% consistent behavior with the RequestBody override.
When you override the RequestBody:
- Without description, it use the default one
- With a `''` description, it use `''`
After https://github.com/api-platform/core/pull/7412
- If you override the response without a description, it use `''`
- If you override the response with an explicit `''`, it use `''`
So you cannot rely on the default description provided by the OpenAiFactory.
On the opposite, just adding
```
if …
```
> fix(openapi): Improve response override

- features/filter/filter_validation.feature
- features/http_cache/headers.feature
- src/Validator/Util/ParameterValidationConstraints.php
- tests/Fixtures/TestBundle/ApiResource/TranslateValidationError.php
- tests/Fixtures/app/AppKernel.php
- tests/Functional/Parameters/ParameterTest.php
- tests/Functional/Parameters/ValidationTest.php
> fix(validator): custom message was not translated

- src/Doctrine/Orm/Filter/FreeTextQueryFilter.php
- tests/Functional/Parameters/OrFilterTest.php
| Tickets       | Closes  #7441
TODO: do the same on the ODM filter ?
> fix(doctrine): group or filter in an AndWhere

- src/Symfony/Bundle/Test/Client.php
| Tickets       | Related to #6976 and #7007
As of #6976 and #7007, calling `createClient()` no longer boots the kernel when `$alwaysBootKernel = false` is set, as recommended.
If we use `Client::loginUser()` when the kernel has not been booted, no error will occur and we will simply remain in a non-logged in state.
So, this PR ensure that the kernel is booted before using `KernelBrowser::loginUser()`, and that `Client::loginUser()` always succeeds.
> fix(symony): ensure the kernel is booted before using `KernelBrowser::loginUser()`

- src/State/Processor/ObjectMapperProcessor.php
- src/State/Tests/Processor/ObjectMapperProcessorTest.php
- src/State/composer.json
> fix(state): object mapper on delete operation
