- JsonLd/ContextBuilder.php
- Resources/config/api.xml
- Serializer/JsonLdNormalizer.php
- Tests/Behat/TestBundle/Entity/Dummy.php
- features/collection.feature
- features/context.feature
- features/crud.feature
- features/fixtures/TestApp/bootstrap.php
- features/relation.feature
- features/vocab.feature
This PR add `DateTime` objects deserialization.
> Add \DateTime deserialization support

- .travis.yml
If there is hhvm-nightly, there should be hhvm as well.
Also changed spaces to more readable and standard ones.
> travis: hhvm added, clear structure

- .travis.yml
- Annotation/Iri.php
- DependencyInjection/DunglasJsonLdApiExtension.php
- Mapping/AttributeMetadata.php
- Mapping/ClassMetadata.php
- Mapping/ClassMetadataFactory.php
- Mapping/Loader/AnnotationLoader.php
- Mapping/Loader/AttributesLoader.php
- Mapping/Loader/LoaderChain.php
- Mapping/Loader/LoaderInterface.php
- Mapping/Loader/PhpDocLoader.php
- Mapping/Loader/ValidatorMetadataLoader.php
- Resources/config/metadata.xml
- Tests/Behat/TestBundle/Entity/Dummy.php
- Util/Reflection.php
- composer.json
- features/fixtures/TestApp/config/config.yml
- features/vocab.feature
Better design. More extensible.
> Extract loaders from ClassMetadataFactory

- README.md
> Fixed indentation in doc.

- Hydra/ApiDocumentationBuilder.php
- JsonLd/ContextBuilder.php
- JsonLd/Serializer/DateTimeNormalizer.php
- JsonLd/Serializer/ItemNormalizer.php
- Mapping/AttributeMetadata.php
- Mapping/Loader/AttributesLoader.php
- README.md
- Tests/Behat/TestBundle/Entity/RelatedDummy.php
- Tests/Behat/TestBundle/Entity/RelationEmbedder.php
- features/context.feature
- features/error.feature
- features/fixtures/TestApp/config/config.yml
- features/relation.feature
- features/vocab.feature
Works like for normalization. cc @marcw
> Embeded objects for denormalization

- Api/IriConverter.php
- Api/IriConverterInterface.php
- DependencyInjection/Compiler/ResourcePass.php
- Doctrine/Orm/DataProvider.php
- Doctrine/Orm/Filter.php
- Hydra/Serializer/CollectionNormalizer.php
- JsonLd/EntrypointBuilder.php
- JsonLd/Serializer/ItemNormalizer.php
- Model/DataProviderChain.php
- Model/DataProviderInterface.php
- Resources/config/api.xml
- Resources/config/doctrine_orm.xml
- Resources/config/hydra.xml
- Resources/config/json_ld.xml
- Routing/Router.php
- composer.json
* Introduce a new `IriConverter` class.
* Lazy loads some services.
Close #38.
> Fix filters

- Controller/ResourceController.php
- Hydra/Serializer/CollectionNormalizer.php
- Resources/config/hydra.xml
- features/collection.feature
- features/relation.feature
Generate proper URI (`@id` in JSON-LD) for collections.
Fix a bug reported by @amenophis in https://github.com/dunglas/DunglasApiBundle/pull/52#discussion-diff-29930863.
> Fix collection @id IRI

- Controller/ResourceController.php
- Doctrine/EventSubscriber.php
- Event/DataEvent.php
- FosUser/EventSubscriber.php
Because the data can be an object or an array (lists).
> Rename ObjectEvent to DataEvent

- Mapping/ClassMetadataFactory.php
Didn't test, but looks like a typo
> Fix validation group in getMetadataFor

- Doctrine/Orm/SearchFilter.php
- Resources/config/doctrine_orm.xml
- Resources/doc/filters.md
- features/fixtures/TestApp/config/config.yml
> Rename Filter to SearchFilter

- Api/Resource.php
- Api/ResourceCollection.php
- Api/ResourceCollectionInterface.php
- DependencyInjection/Compiler/ResourcePass.php
- Resources/doc/filters.md
- Resources/doc/operations.md
- features/fixtures/TestApp/config/config.yml
- Fix errors when using built-in resources (fix #82, ping @MLKiiwy)
- Better API (fix #63, ping @theofidry)
> Enhance filters and operations API

- README.md
- Resources/doc/fosuser-bundle.md
cf. #71. Could not find much to say but it's better than nothing. Waiting for you feedback on this because I'm pretty sure you will find something to say^^
> Added doc for FOSUserBundle integration.

- Doctrine/Orm/Filter/AbstractFilter.php
- Doctrine/Orm/Filter/DateFilter.php
- Resources/doc/filters.md
- Tests/Doctrine/Orm/DateFilterTest.php
- Tests/Doctrine/Orm/OrderFilterTest.php
- features/crud.feature
- features/doctrine/date-filter.feature
- features/doctrine/order-filter.feature
- features/fixtures/TestApp/config/config.yml
- features/hydra/collection.feature
- features/relation.feature
> Refactor filters

- Resources/config/hydra.xml
- Resources/config/json_ld.xml
- Routing/Router.php
> Simplify router decorator & use real router where not needed

- Resources/doc/controllers.md
- Resources/doc/data-providers.md
- Resources/doc/external-vocabularies.md
- Resources/doc/filters.md
- Resources/doc/getting-started.md
Fix #105 little observation too (not the main subject)
> [Doc] fix links

- Resources/doc/nelmio-api-doc.md
cf https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.md#sandbox
> [doc] Fix nelmio config path

- Resources/doc/the-event-system.md
> Fix class names in the-event-system.md

- Controller/ResourceController.php
- features/circular-reference.feature
- features/crud.feature
> Fix status code for PUT operation

- features/hydra/error.feature
> Fix behat tests suite when running with ext-jsonc

- JsonLd/ContextBuilder.php
- JsonLd/Event/ContextBuilderEvent.php
- JsonLd/Event/Events.php
- JsonLd/EventListener/ResourceContextBuilderListener.php
- Resources/config/json_ld.xml
- Resources/doc/the-event-system.md
We need to add some informations to the context dynamically, like the '@language' (http://www.w3.org/TR/json-ld/#string-internationalization).
I propose to use an event dispatcher to provide this functionality.
> Add an event dispatcher to the context builder

- Mapping/ClassMetadata.php
- Mapping/Loader/AttributesLoader.php
- Tests/Behat/TestBundle/Entity/CustomNormalizedDummy.php
- features/custom_normalized.feature
- features/fixtures/TestApp/config/config.yml
- features/hydra/vocab.feature
I discover an issue in normalization / denormalization process due to my previously feature.
Here is a complete fix with a functionnal test that show the bug.
I think the class "AttributeLoader" is actually very complex and can be refactored ...
> attribute-loader-groups-bug : fix : normalization by groups; add : TF for the bug

- Controller/ResourceController.php
- DependencyInjection/Compiler/DoctrineQueryExtensionPass.php
- Doctrine/Orm/DataProvider.php
- Doctrine/Orm/Extension/FilterExtension.php
- Doctrine/Orm/Extension/OrderExtension.php
- Doctrine/Orm/Extension/PaginationExtension.php
- Doctrine/Orm/Filter/DateFilter.php
- Doctrine/Orm/Filter/OrderFilter.php
- Doctrine/Orm/Filter/SearchFilter.php
- Doctrine/Orm/QueryCollectionExtensionInterface.php
- Doctrine/Orm/QueryItemExtensionInterface.php
- Doctrine/Orm/QueryResultExtensionInterface.php
- Model/DataProviderChain.php
- Model/DataProviderInterface.php
- Resources/config/doctrine_orm.xml
- Tests/Doctrine/Orm/DateFilterTest.php
- Tests/Doctrine/Orm/OrderFilterTest.php
> Extend query extensions usage to item queries

- Resources/doc/operations.md
I think this was a mistake, any feedback welcomed :-)
> Correct/Update operations.md

- README.md
- Resources/doc/content-negotiation.md
- Resources/doc/external-vocabularies.md
- Resources/doc/performance.md
- Resources/doc/security.md
> Added doc for security

- Resources/config/api.xml
- Resources/config/doctrine_orm.xml
- Resources/config/jsonld.xml
This allows to use our own `PropertyAccessor` more easily.
cc @sroze
> Added alias for PropertyAccessor

- Resources/config/api.xml
- Resources/config/hydra.xml
- Resources/config/jsonld.xml
- features/fixtures/TestApp/config/config.yml
This allows us to use our own Serializer more easily.
cc @sroze
> Add Serializer alias

- Resources/doc/content-negotiation.md
Fix #210 according to the discussion conclusion.
> Fix "custom format in Negotiation library" doc

- README.md
> Added use case with JMSSerializer

- Resources/doc/content-negotiation.md
> Doc: fix missing master request check removal

- Doctrine/Orm/Filter/SearchFilter.php
- Tests/Doctrine/Orm/SearchFilterTest.php
This PR follows #209 and fixes OneToMany associations
> Fix Missing collection association alias

- Resources/doc/angular-integration.md
- Resources/doc/security.md
> Fix documentation links on performance

- JsonLd/Serializer/ItemNormalizer.php
> Close #264

- Doctrine/Orm/Extension/EagerLoadingExtension.php
- Resources/config/doctrine_orm.xml
- features/unknown_attributes.feature
* Merge 1.0 in master
* Moved the eager loading system of @csarrazi to the extension system.
> Merge 1.0 in master

- DependencyInjection/DunglasApiExtension.php
- Tests/DependencyInjection/DunglasApiExtensionTest.php
> Fix prepend condition

- JsonLd/EntrypointBuilder.php
Following #205 
Sometimes, it might happen to have resources without any GET collection operation. However, those resources might have a POST operation in order to create a new item or submit a payload.
This is currently impossible, as the resource IRI is generated from the first GET collection operation.
However, this fix is more a workaround than a real solution.
On another hand, I easily understand why the resource and item IRIs are related to the Route, but doesn't this system have some limitations as it is ?
A resource only exposing GET item operation but not a GET collection operation shouldn't being part of the EntryPoint anyway ? 
The POST collection operation might be available, we'll see it under the Entrypoint `hydra:supportedProperty` on the hydra `apidoc`, but not on the …
> Fix EntryPointBuilder when no GET operation

- CHANGELOG.md
Since there never was a 1.0.0 beta 4
> Correct changelog entry for #201

- DependencyInjection/Configuration.php
I made typo to be able to correct it.
It's the only way to be quicker than @pborreli! ;)
> Correct typo

- JsonLd/Serializer/ItemNormalizer.php
> Fix wrong denormalization context for related resources

- Hydra/Action/ExceptionAction.php
- Hydra/EventListener/RequestExceptionListener.php
- Hydra/EventListener/ValidationExceptionListener.php
- Hydra/Serializer/ErrorNormalizer.php
- Resources/config/hydra.xml
- Tests/DependencyInjection/DunglasApiExtensionTest.php
| BC breaks?    | maybe
| Fixed tickets | #302 
Adapt #302 to master.
> Adapt the new exception system (#302) for master

- JsonLd/Serializer/ItemNormalizer.php
I don't see or is used in this version
> PropertyInfo\Type Not used

- .travis.yml
- composer.json
> Merge #323 in master

- .styleci.yml
Here's the config, there is just enabling StyleCI on the repository and adding the header check (in the StyleCI interface).
```
This file is part of the DunglasApiBundle package.
(c) Kévin Dunglas <dunglas@gmail.com>
For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.
```
> Add StyleCI config

- Routing/Router.php
- Tests/Routing/RouterTest.php
> Fix some router bugs. Close #333.

- composer.json
Closes #263.
Merge to master (#344)
> Exclude test classes from classmap

- .travis.yml
- Tests/Routing/RouterTest.php
- composer.json
> Update dependencies and fix tests

- Doctrine/Orm/Filter/SearchFilter.php
- Tests/Doctrine/Orm/Filter/SearchFilterTest.php
- features/crud.feature
... regardless of association cardinality
Fixes #365
> SearchFilter: Allow single/multiple values for any relation

- composer.json
> Move the `doctrine/orm` dependency to `require-dev`

- .travis.yml
> Fix an Insight complaint about .travis.yml

- Doctrine/Orm/DataProvider.php
> Use defined variable for entityClass instead of calling getEntityClass

- Doctrine/Orm/Filter/SearchFilter.php
| Fixed tickets | #379
ping @csarrazi
> Added support for non-hardcoded identifiers (follow up #379)

- appveyor.yml
- features/fixtures/TestApp/AppKernel.php
- features/fixtures/TestApp/config/config.yml
- features/fixtures/TestApp/config/routing.yml
> Configure AppVeyor

- features/fixtures/TestApp/config/config.yml
> Escape @ in YAML

- appveyor.yml
> Fix Behat on AppVeyor

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Add GitHub pull-request template

- composer.json
> Support HttpFoundation >= 3.0

- composer.json
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/EventListener/FormatRequestListener.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
- tests/EventListener/FormatRequestListenerTest.php
- tests/Fixtures/app/config/config.yml
Upgrade to Negotiation v2 and add a unit test.
> Upgrade to @willdurand's Negotiation v2

- .travis.yml
- composer.json
- src/Metadata/Resource/Factory/ItemMetadataPhpDocFactory.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
- tests/Fixtures/ClassWithNoDocBlock.php
- tests/Metadata/Resource/Factory/ItemMetadataPhpDocFactoryTest.php
> Support for reflection-docblock 3

- composer.json
> Rename composer package

- Doctrine/Orm/Filter/SearchFilter.php
- Tests/Behat/TestBundle/Entity/Dummy.php
- Tests/Doctrine/Orm/Filter/SearchFilterTest.php
- features/bootstrap/FeatureContext.php
- features/crud.feature
- features/doctrine/search-filter.feature
- features/fixtures/TestApp/config/config.yml
| Doc PR        | api-platform/doc#30
> Implement searchFilter case sensitivity

- README.md
| Fixed tickets | ø
| Doc PR        | ø
> Update the badge addresses

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
- src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
- src/Bridge/Symfony/Bundle/Resources/config/metadata.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Fixtures/app/config/config.yml
This is a follow-up on #436 - see https://github.com/api-platform/core/pull/436#issuecomment-193784818
> Rename metadata services

- composer.json
As per https://github.com/api-platform/core/issues/463#issuecomment-197802099
> Require symfony/property-info

- .styleci.yml
Override [StyleCI default configuration](https://styleci.readme.io/docs/configuration) to include tests. They should be checked as well shouldn't they?
> Check code style of tests

- src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php
- src/Metadata/Property/Factory/CachedPropertyNameCollectionFactory.php
- src/Metadata/Resource/Factory/CachedResourceMetadataFactory.php
Wrong conclusion in https://github.com/api-platform/core/pull/469#discussion_r56747097
> Switch from sha1 to md5 for hashing (cache key) of metadata parameters

- .styleci.yml
> Revert "Check code style of tests"

- src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
- tests/Metadata/Property/Factory/SerializerPropertyMetadataFactoryTest.php
* Set readable / writable based on serializer groups of target property
* Set readableLink / writableLink based on serializer groups of properties on related resource
> Fix SerializerPropertyMetadataFactory

- Api/Operation/OperationFactory.php
Allow to override globally the base controller.
ping @salahm
> Allow to configure the default controller

- .travis.yml
- appveyor.yml
- composer.json
> Make test green with Symfony 3

- composer.json
Fix Composer dependencies. Builds were failing...
> Require symfony/http-kernel 3.1

- composer.json
Again, our build has become broken. Such is life on the bleeding edge.
> Require symfony/dependency-injection 3.1

- features/crud.feature
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
As requested in https://github.com/api-platform/core/issues/365#issuecomment-168909612
> Allow multiple values for a property in search filter when using "exact" strategy

- features/json-ld/context.feature
Fix https://travis-ci.org/api-platform/core/jobs/124759303#L3011
> Fix order issue on context feature

- composer.json
> Update dependencies and normalize composer.json

- src/Bridge/Symfony/Routing/IriConverter.php
> Fix IriConverter parameters sent to ItemDataProvider

- tests/Bridge/Symfony/Routing/IriConverterTest.php
Add unit tests for #532
| Fixed tickets | #531
> Add tests for #532

- .travis.yml
Travis now does a self-update himself during the setup.
> Remove unneeded composer self-update

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
Automatically rebuild the container if an entity is modified.
> Rebuild the container when an entity is modified

- features/overriding-attribute.feature
- tests/Fixtures/TestBundle/Entity/CustomAttributeDummy.php
In order to show directly in the core how do to on each method custom normalization/denormalization we  add tests.
ping @dunglas @AlexandreHagen .
> hotfix(add-test): Related to #582

- src/JsonLd/Serializer/ItemNormalizer.php
> Fix typo in ItemNormalizer

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
Tell me if I should add a behat test (I have no time for now but in few days I can add a test if needed).
> [Bug] Wrong class in api.xml

- src/Bridge/Doctrine/EventListener/WriteListener.php
- src/Bridge/FosUser/EventListener.php
- src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
- src/EventListener/DeserializeListener.php
- src/EventListener/ReadListener.php
> Use Request::isMethodSafe() when possible

- src/Documentation/ApiDocumentationBuilderInterface.php
- src/Hydra/ApiDocumentationBuilder.php
- src/Serializer/SerializerContextBuilder.php
- src/Swagger/ApiDocumentationBuilder.php
- tests/Swagger/ApiDocumentationBuilderTest.php
> Fix Swagger implementation and tests

- features/hydra/collection.feature
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
ping @dunglas is the test good enough ?
> fix: pagination events issue

- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
| Bug fix?      | yno
Mandatory to make Swagger UI working.
> Enable JSON to have Swagger support by default

- src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
> Don't override parent parameter in the Swagger command

- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- src/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php
- src/Bridge/Doctrine/Orm/Util/QueryChecker.php
- src/Bridge/Doctrine/Orm/Util/QueryNameGenerator.php
- src/Bridge/FosUser/EventListener.php
- src/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProvider.php
- src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
- src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php
- src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyNameCollectionFactory.php
- src/Bridge/Symfony/Routing/ApiLoader.php
- src/Bridge/Symfony/Routing/IriConverter.php
- src/Hydra/DocumentationNormalizer.php
- src/JsonLd/ContextBuilder.php
- src/Swagger/DocumentationNormalizer.php
- src/Util/Reflection.php
- tests/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProviderTest.php
- tests/Swagger/DocumentationNormalizerTest.php
> Fix some Scrutinizer issues

- .travis.yml
@dunglas Can we introduce an `.editorconfig` file, so that we may rid ourselves of problems like this going forward?
> Fix indentation in Travis CI config

- tests/Serializer/AbstractItemNormalizerTest.php
> feat:add test to sereliazer

- src/Hydra/DocumentationNormalizer.php
- src/Swagger/DocumentationNormalizer.php
> feat: refactor documentations

- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Bridge/Doctrine/Orm/Extension/FilterExtensionTest.php
- tests/Bridge/Doctrine/Orm/Extension/OrderExtensionTest.php
Adding coverage to the doctrine extension namespace.
> feat: add test to doctrine ext namespace

- tests/Api/EntrypointTest.php
- tests/Api/ResourceClassResolverTest.php
Adding code corverage to the api namespace
> feat: add test for api namespace

- .editorconfig
- CONTRIBUTING.md
- features/composite.feature
- features/content_negotiation.feature
- features/crud.feature
- features/doctrine/numeric_filter.feature
- features/hal.feature
- features/overridden_operation.feature
- features/problem.feature
- features/relation.feature
- src/Bridge/Doctrine/EventListener/WriteListener.php
- src/Hydra/DocumentationNormalizer.php
- src/schema/metadata.xsd
- tests/Hydra/DocumentationNormalizerTest.php
- tests/Swagger/DocumentationNormalizerTest.php
> Add .editorconfig and fix some indentation issues

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
Minimalist replacement for #653 and #657
Thanks @Ener-Getick!
> [Symfony] Use ArrayAdapter for metadata cache in dev

- tests/DataProvider/ChainCollectionDataProviderTest.php
- tests/DataProvider/ChainItemDataProviderTest.php
Improve code coverage from 83% to 84% (Thanks to PHPStorm & PhpUnit for the percentage)
> feat: add test for DataProvider Namespace

- tests/Action/EntrypointActionTest.php
- tests/Action/ExceptionActionTest.php
- tests/Documentation/Action/DocumentationActionTest.php
- tests/JsonLd/Action/ContextActionTest.php
This PR increase the code coverage from 83 to 87% (Thanks to PhpUnit and PhpStorm for the percentage)
> feat: complete Action tests

- src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
- src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
- src/Bridge/Symfony/Bundle/Resources/config/hal.xml
- src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
- src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
- src/Hal/Serializer/ItemNormalizer.php
- src/Hydra/Serializer/DocumentationNormalizer.php
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php
- tests/Fixtures/TestBundle/Action/ConfigCustom.php
- tests/Fixtures/TestBundle/Resources/config/api_resources.yml
- tests/Fixtures/app/config/config.yml
- tests/Hal/Serializer/ItemNormalizerTest.php
- tests/Hydra/Serializer/DocumentationNormalizerTest.php
- tests/Swagger/Serializer/DocumentationNormalizerTest.php
> Improve the code quality (SensioLabs Insight)

- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Swagger/Serializer/DocumentationNormalizerTest.php
> Fix Swagger

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
> Fix wrong comment on kernel.request priority

- .travis.yml
- behat.yml
- features/bootstrap/CoverageContext.php
| Doc PR        |n/a
Add code coverage support for both Behat and PHPUnit suites. The report should be available at https://coveralls.io/github/api-platform/core
ping @Simperfit
> Add Coveralls support

- features/content_negotiation.feature
- src/EventListener/AddFormatListener.php
> Fix priorities

- src/Bridge/Symfony/Routing/RouterOperationPathResolver.php
> Fix typo in RouterOperationPathResolver

- tests/Fixtures/app/config/routing.yml
These should not be set anyway.
> Remove outdated defaults in test routing.yml

- src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
Update the template to be compatible with the Swagger UI 2.2.0.
> Fix Swagger UI

- src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
- src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
- src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
- src/Bridge/Doctrine/Orm/Filter/RangeFilter.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- src/Bridge/Doctrine/Orm/Util/QueryNameGenerator.php
- src/Bridge/Doctrine/Orm/Util/QueryNameGeneratorInterface.php
- tests/Bridge/Doctrine/Orm/Filter/BooleanFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/NumericFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/RangeFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
- tests/Bridge/Doctrine/Util/QueryNameGeneratorTest.php
> feat: add the name/association in the queryNameGenerator

- src/Bridge/Doctrine/Orm/CollectionDataProvider.php
- src/Bridge/Doctrine/Orm/ItemDataProvider.php
- tests/Api/FilterCollectionTest.php
- tests/Bridge/Doctrine/Orm/CollectionDataProviderTest.php
> Add 2 more tests and fix some quality issues

- composer.json
- features/security/validate_response_types.feature
- src/EventListener/AddFormatListener.php
- tests/EventListener/AddFormatListenerTest.php
https://github.com/willdurand/Negotiation/pull/84
> Compatbility with Negotiation 2.0.3

- Hydra/ApiDocumentationBuilder.php
| Fixed tickets | #1234, #5678
> bug @ 'hydra:Link'

- src/Hydra/Serializer/DocumentationNormalizer.php
> Fix case in the hydra prefix. Closes #719 for v2.

- src/Api/IriConverterInterface.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Routing/IriConverter.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> Improve quality of ApiPlatformExtension

- src/Swagger/Serializer/DocumentationNormalizer.php
> fix swagger denormalization groups

- composer.json
- features/bootstrap/FeatureContext.php
- features/doctrine/range_filter.feature
- src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
- src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
- src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- src/Bridge/Doctrine/Orm/Filter/RangeFilter.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
- tests/Bridge/Doctrine/Orm/Filter/BooleanFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/NumericFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/RangeFilterTest.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
> Refactor Doctrine ORM filters

- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Fixtures/app/config/config.yml
> Fix missing use statement for LoggerInterface

- src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Swagger/Serializer/DocumentationNormalizerTest.php
| Fixed tickets | #725, #722
Alternative fix to #725. It is done the same way than in the Hydra doc.
ping @Ener-Getick
> Fix Swagger base path

- src/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php
> Improve the quality of some other methods

- src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
- src/Bridge/Doctrine/Orm/Filter/BooleanFilter.php
- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
- src/Bridge/Doctrine/Orm/Filter/NumericFilter.php
- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- src/Bridge/Doctrine/Orm/Filter/RangeFilter.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
For better extensibility.
Duplicate function extracted up to AbstractFilter::apply
> Add AbstractFilter::filterProperty

- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
> Fix SearchFilter case sensitivity for IN values

- src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
Displays current filters in Swagger UI.
> Display current filters in Swagger UI.

- features/composite.feature
- features/configurable.feature
- features/content_negotiation.feature
- features/crud.feature
- features/crud_abstract.feature
- features/custom_identifier.feature
- features/custom_writable_identifier.feature
- features/hal.feature
- features/overridden_operation.feature
- features/relation.feature
- features/security/strong_typing.feature
- features/security/unknown_attributes.feature
- features/uuid.feature
- src/Hal/Serializer/ItemNormalizer.php
- src/JsonLd/Serializer/ItemNormalizer.php
- src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
- src/Serializer/ItemNormalizer.php
- tests/Serializer/ItemNormalizerTest.php
> ID should not be an IRI when not using an hypermedia format, don't hide the raw ID property by default

- .php_cs
- .travis.yml
> Update PHP-CS-Fixer config and run on Travis build

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
https://github.com/api-platform/core/pull/796#discussion_r83216003 see @teohhanhui comment
> better variable name for options in EagerLoadingExtension

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
Just removed a useless method call.
> Improve EagerLoadingExtension by using the associationMappings array

- tests/Fixtures/app/config/config.yml
> Update tests for the last version of FOSUser

- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
> Remove duplicate code in DateFilter

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Fixed tickets | https://github.com/api-platform/core/pull/822#discussion_r86358789
And now the 0.001 % are back \o/
> Don't inject the eager extension service if it's disabled

- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyEntityValidator.php
Maybe we can make our "advent" tests calendar and get 100% coverage for the end of the year...
> Add tests for the ValidatorPropertyMetadataFactory class

- src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
- tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |
> feat: issues

- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyValidatedEntity.php
> Rename validated entity

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
| Fixed tickets | https://github.com/api-platform/core/pull/825#discussion_r86934680
> Remove duplicate call to the extension

- tests/Api/ResourceClassResolverTest.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/FilterPassTest.php
- tests/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php
- tests/Bridge/Symfony/Routing/IriConverterTest.php
> Fix exception check in tests

- features/custom_identifier.feature
- features/custom_normalized.feature
- features/custom_writable_identifier.feature
- features/hydra/docs.feature
- features/jsonld/context.feature
- features/swagger/docs.feature
- src/Bridge/Symfony/Bundle/Resources/config/routing/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/routing/jsonld.xml
| Bug fix?      | yes (sort of)
Correct a typo in the docs's URL.
> Rename /doc to /docs

- .travis.yml
Download PHP-CS-Fixer v2.0.0-RC in Travis build.
> Fix Travis lint (PHP-CS-Fixer)

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
- tests/Fixtures/TestBundle/Entity/CircularReference.php
This PR forces eager by default and adds the ability to configure it in the attributes of a resource.
> Force eager by default

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
The configuration was processed in the wrong order.
> Fix disabling EagerLoadingExtension

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
> Refactor EagerLoadingExtension to use QueryNameGenerator

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
| Fixed tickets | api-platform/api-platform#179
https://github.com/api-platform/api-platform/issues/179
> Do not eager join properties or associations that are not linked to a resource

- src/JsonLd/Serializer/ItemNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/ItemNormalizer.php
| Fixed tickets | https://github.com/api-platform/core/commit/62264a5f4c0ce24b640e2b0bd68be69a06f1f069#commitcomment-19969198
> fix override fetch_data context

- src/Bridge/Doctrine/EventListener/WriteListener.php
- src/Bridge/FosUser/EventListener.php
- src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
- src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
- src/EventListener/DeserializeListener.php
> Fix symfony 3.2 warning isMethodSafe

- composer.json
> Fix minimal version of PHPUnit

- .travis.yml
> Use the stable version of PHP CS Fixer 2

- src/Serializer/JsonEncoder.php
> Fix the PHPDoc of JsonEncoder

- composer.json
> Fix builds

- src/EventListener/EventPriorities.php
- tests/EventListener/EventPrioritiesTest.php
> Fix the priority of POST_RESPOND

- src/Swagger/Serializer/DocumentationNormalizer.php
Fix a bug when generating swagger documentation when using two groups
> fix an issue in swagger generator when using two groups

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/hal.xml
- src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
- src/JsonLd/Serializer/ItemNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
| Fixed tickets | #890
@digilist, can you please test this patch to see if it's fix the problem you reported? Thanks!
> Inject serializer's class metadata factory

- features/hydra/docs.feature
- src/Hydra/Serializer/DocumentationNormalizer.php
Also include a small code cleanup (related to https://blog.blackfire.io/php-7-performance-improvements-encapsed-strings-optimization.html).
> Fix range in the Hydra doc when the relation has an IRI

- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
> Add nulls comparison to OrderFilter

- src/Serializer/JsonEncoder.php
> feat: change JsonResponse::DEFAULT_ENCODING_OPTIONS with real value

- src/Serializer/JsonEncoder.php
Following of #910, changed according to the advices.
> hotfix: change hardcoded value to php constant

- src/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactory.php
- tests/Fixtures/TestBundle/Entity/Dummy.php
- tests/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactoryTest.php
> Exclude static methods in AnnotationPropertyNameCollectionFactory

- .travis.yml
- tests/JsonLd/ContextBuilderTest.php
Add a test to improve code coverage on contextBuilder
> minor: add missing test for contextBuilder

- .travis.yml
> Prevent phpcov segfault on PHP 7.0 (Travis)

- features/main/non_resource.feature
- tests/Fixtures/NotAResource.php
- tests/Fixtures/TestBundle/DataProvider/ContainNonResourceItemDataProvider.php
- tests/Fixtures/TestBundle/Entity/ContainNonResource.php
- tests/Fixtures/app/config/config.yml
| Bug fix?      | not yet
This a try to reproduce #924 and #916 but it seems to work well... @fbourigault @ufik do you have an idea of how to reproduce your issue?
> Add a test for non-resource object normalization

- src/Bridge/Doctrine/Orm/ItemDataProvider.php
- src/Bridge/Doctrine/Orm/Util/IdentifierManagerTrait.php
- tests/Bridge/Doctrine/Util/IdentifierManagerTraitTest.php
Makes SensioLabs Insight happy.
> Move properties in IdentifierManagerTrait and fix CS.

- CHANGELOG.md
> hotfix: update changelog

- src/Hydra/Serializer/DocumentationNormalizer.php
- tests/Hydra/Serializer/DocumentationNormalizerTest.php
> [Hydra] ConstraintViolationList documentation fix

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> Fix prepend configuration

- behat.yml
- composer.json
- features/bootstrap/FeatureContext.php
- features/bootstrap/HydraContext.php
- features/bootstrap/SwaggerContext.php
- features/doctrine/date_filter.feature
- features/doctrine/numeric_filter.feature
- features/doctrine/order_filter.feature
- features/doctrine/range_filter.feature
- features/doctrine/search_filter.feature
- features/hydra/collection.feature
- features/main/relation.feature
Let's see if this works (sorry about the spam)
> Master branch is protected

- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
> Fix private service deprecation in SearchFilterTest

- .travis.yml
> [WIP] Fix Travis setup

- .travis.yml
- features/bootstrap/FeatureContext.php
- features/doctrine/boolean_filter.feature
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
> Merge 2.0 on master

- .travis.yml
Trying the dunglas magic thing on deps=low
PR #1000 is for this 😢
> Attempt to fix tests (segfault php 7)

- .travis.yml
- features/bootstrap/FeatureContext.php
- features/doctrine/date_filter.feature
- features/doctrine/search_filter.feature
- features/main/crud.feature
- features/main/relation.feature
- src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Fixtures/TestBundle/Entity/DummyCar.php
- tests/Fixtures/TestBundle/Entity/DummyCarColor.php
- tests/Fixtures/TestBundle/Entity/DummyFriend.php
- tests/Fixtures/TestBundle/Entity/ParentDummy.php
- tests/Fixtures/TestBundle/Entity/RelatedDummy.php
- tests/Fixtures/TestBundle/Entity/RelatedToDummyFriend.php
- tests/Fixtures/app/config/config.yml
> Merge 2.0 in master

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
Fix bug introduced in #950
/cc @soyuka
> Remove FilterEagerLoadingExtension when eager loading is disabled

- tests/Fixtures/TestBundle/Entity/UpperCaseIdentifierDummy.php
- tests/Fixtures/TestBundle/Entity/UuidIdentifierDummy.php
> Move @author to the correct file

- composer.json
> Explicitly add missing dependency to PropertyAccess

- src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
| Tests pass?   | ?
| Fixed tickets | #763 
I think it has to do with the entity that uses table inheritance.
> fix undefined index: subType in NelmioApiDoc/ApiPlatformParser

- composer.json
> Use the stable version of FOSUserBundle

- src/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactory.php
- src/Metadata/Property/Factory/ExtractorPropertyNameCollectionFactory.php
- src/Metadata/Property/Factory/InheritedPropertyNameCollectionFactory.php
- tests/Metadata/Property/Factory/InheritedPropertyNameCollectionFactoryTest.php
| Fixed tickets | https://github.com/api-platform/api-platform/issues/282
> Fix strict typing exception when the propertyName is a number

- composer.json
> Remove the templating dependency from require-dev

- composer.json
- features/hal/problem.feature
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/metadata/annotation.xml
- src/Bridge/Symfony/Bundle/Resources/config/metadata/metadata.xml
- src/Bridge/Symfony/Bundle/Resources/config/metadata/php_doc.xml
- src/Bridge/Symfony/Bundle/Resources/config/metadata/xml.xml
- src/Bridge/Symfony/Bundle/Resources/config/metadata/yaml.xml
- src/Bridge/Symfony/Bundle/Resources/config/validator.xml
- src/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
This PR fixes some edge cases. It's require to be compatible with Symfony Flex.
> Fix the bundle when soft deps aren't installed

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/security.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> Make the dependency to SecurityBundle optional

- features/main/table_inheritance.feature
- src/JsonLd/Serializer/ItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/DummyTableInheritance.php
- tests/Fixtures/TestBundle/Entity/DummyTableInheritanceChild.php
- tests/Fixtures/TestBundle/Entity/DummyTableInheritanceDifferentChild.php
- tests/Fixtures/TestBundle/Entity/DummyTableInheritanceRelated.php
- tests/Hydra/Serializer/ItemNormalizerTest.php
| Fixed tickets | #1025
As I am having the same issues as #1025, I figured I'd contribute a failing test case to help move things along on PR #1046. 
@nik-lampe @dunglas @soyuka Can you take a look at this test case and make sure it matches your failing use case?
> Multiple inheritance collection serialization

- phpstan.neon
- src/Metadata/Extractor/XmlExtractor.php
- tests/Bridge/Doctrine/Orm/Filter/ExistsFilterTest.php
- tests/Bridge/Doctrine/Util/IdentifierManagerTraitTest.php
> Fix PHPStan errors in master

- .styleci.yml
> Delete the StyleCI config

- src/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php
- tests/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactoryTest.php
> Fix inheritance of property metadata for the Doctrine ORM property metadata factory

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
| Fixed tickets | #1069, #1071
Tried to fix this issue "Eager Loading Extension partial objects causing properties to not be available" #1069 So I basically select all fields for entities that have subclasses.
> EagerLoadingExtension: Disable partial fetching if entity has subclasses

- src/Hydra/Serializer/ErrorNormalizer.php
- src/Problem/Serializer/ErrorNormalizer.php
See https://github.com/api-platform/core/pull/1036#discussion_r113320718
> Remove useless code for error normalizers

- features/doctrine/date_filter.feature
- features/jsonld/context.feature
- tests/Fixtures/FileConfigurations/legacyoperations.xml
- tests/Fixtures/FileConfigurations/nocollectionoperations.xml
- tests/Fixtures/FileConfigurations/noitemoperations.xml
| Fixed tickets | https://github.com/api-platform/core/pull/1080#issuecomment-297960415
> Fix xsd uri schema

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Util/ShouldEagerLoad.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
> Refactor should eager load

- src/Bridge/Symfony/Routing/ApiLoader.php
- tests/Fixtures/TestBundle/Entity/Answer.php
Just to prepare documentation needed to check if it actually worked with groups on subresources (it does \o/).
> Add groups to subresource

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Util/ShouldEagerLoad.php
> Improve the ShouldEagerLoad

- src/Hal/Serializer/ItemNormalizer.php
> HAL: Ignore cache when the key is false

- features/main/uuid.feature
- src/Bridge/Symfony/Routing/IriConverter.php
- tests/Fixtures/TestBundle/Doctrine/Generator/Uuid.php
- tests/Fixtures/TestBundle/Doctrine/Generator/UuidGenerator.php
- tests/Fixtures/TestBundle/Entity/CustomGeneratedIdentifier.php
> fix stringifyable identifier

- composer.json
> Do not restrict negotiation library to 2.3.1

- src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php
> Remove a useless constructor

- src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
- src/Bridge/Doctrine/Orm/Util/QueryChecker.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
| Fixed tickets | https://github.com/api-platform/core/pull/789#issuecomment-302324794
see https://github.com/api-platform/core/pull/789#issuecomment-296218102
> specify left join for filter associations if there was a previous left join

- .travis.yml
* Bump all versions
* Restore colors
* Improve memory usage (run all `.feature` file separately)
> Improve the Travis setup

- features/doctrine/order_filter.feature
- features/main/crud.feature
ping @meyerbaptiste never too late :p
> Fix small behat test issues

- src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
- tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php
> hotfix: add an exception for item per page equal 0

- tests/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php
- tests/Bridge/Symfony/Routing/RouteNameResolverTest.php
> Improve legacy testing on RouteNameResolver

- src/DataProvider/ItemDataProviderInterface.php
I'm making another PR because rebasing against 2.0 was a pain in the ass, so you can close the [old one](https://github.com/api-platform/core/pull/1180)
| Bug fix?      | NO
| New feature?  | NO
| BC breaks?    | NO
| Deprecations? | NO
| Tests pass?   | YES
> Switch docBlock order

- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Swagger/Serializer/DocumentationNormalizerTest.php
> Swagger: change the type of IDs in URL to string

- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> Fix tests for the master branch

- src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
- tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php
Strange that no one saw this earlier.
credit @hercemer42
> fix nelmio parser recursive relation

- src/EventListener/ReadListener.php
| Fixed tickets | https://github.com/api-platform/core/pull/1221
> Do not duplicate exceptions in read listener

- features/bootstrap/HydraContext.php
- features/hydra/collection.feature
- features/hydra/docs.feature
- features/main/relation.feature
- src/Hydra/Serializer/DocumentationNormalizer.php
- src/JsonLd/ContextBuilderInterface.php
- tests/Hydra/Serializer/DocumentationNormalizerTest.php
Reverts api-platform/core#1235
> Revert "Fix Hydra documentation"

- features/bootstrap/HydraContext.php
- features/hydra/collection.feature
- features/hydra/docs.feature
- features/main/relation.feature
- src/Hydra/Serializer/DocumentationNormalizer.php
- src/JsonLd/ContextBuilderInterface.php
- tests/Hydra/Serializer/DocumentationNormalizerTest.php
> Fix Hydra documentation

- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
| Fixed tickets | #1250
I'm not quite sure that there will not be any side effects from this
> Do not make extra join while filter ManyToOne by id

- features/main/recursive.feature
- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Fixtures/TestBundle/Entity/Recursive.php
- tests/Fixtures/TestBundle/Entity/RecursiveChild.php
> Implement maxDepth in eager loading extension

- src/Security/EventListener/DenyAccessListener.php
> Fix insight notice

- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Routing/RouterOperationPathResolver.php
- tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
| Bug fix?      |  no
Follows #1256.
> Remove deprecation notices

- .travis.yml
> Fold Behat output in Travis

- src/EventListener/ReadListener.php
- src/Swagger/Serializer/DocumentationNormalizer.php
> Fix Insight issues

- src/Api/CachedIdentifiersExtractor.php
> Rename memoryCache to localCache in CachedIdentifiersExtractor

- .travis.yml
- tests/Bridge/Doctrine/Orm/Filter/ExistsFilterTest.php
> Ensure PHPStan version stability

- src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php
- tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
> fix #1310 join condition aliases in FilterEagerLoadingExtension

- src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Swagger/Serializer/DocumentationNormalizerTest.php
| Fixed tickets | https://github.com/api-platform/api-platform/issues/381 (partially)
Add pagination parameter to the swagger doc for get (collection) operation
> Update swagger doc with pagination parameter

- .travis.yml
- tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
> Upgrade to PHP CS Fixer 2.4

- features/main/recursive.feature
> Remove useless "print last JSON response" in a Behat feature

- src/Security/ExpressionLanguage.php
> Remove extra copyright doc

- src/Bridge/Symfony/Routing/IriConverter.php
- tests/Bridge/Symfony/Routing/IriConverterTest.php
> Fix a faulty trigger_error call

- appveyor.yml
Similar to #1261 but for AppVeyor.
> Speedup AppVeyor build

- features/main/relation.feature
- src/Serializer/ItemNormalizer.php
- tests/Serializer/ItemNormalizerTest.php
| Fixed tickets | #1338
thanks @pierre-H
Added tests.
> Fix json normalizer to fetch relations #1338

- features/bootstrap/FeatureContext.php
- features/main/relation.feature
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/ContextTrait.php
- tests/Fixtures/TestBundle/Entity/Person.php
- tests/Fixtures/TestBundle/Entity/PersonToPet.php
- tests/Fixtures/TestBundle/Entity/Pet.php
| BC breaks?    | ?
| Deprecations? | ?
| Tests pass?   | n/a
| Fixed tickets | #1222
possible fix for #1222, for discussions pls refer to that issue
> Fix serialization of nested non-resource objects

- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
> Enable FOSUser support if the bundle is installed

- src/Api/OperationTypeDeprecationHelper.php
- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- src/Bridge/Symfony/Routing/OperationMethodResolver.php
- src/Bridge/Symfony/Routing/RouteNameResolver.php
- src/Hydra/Serializer/CollectionNormalizer.php
- src/Metadata/Property/PropertyMetadata.php
- src/PathResolver/OperationPathResolver.php
- src/Serializer/AbstractItemNormalizer.php
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
> fix yoda style conditions

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
> Fix the config for the path_segment_name_generator key

- src/Serializer/AbstractItemNormalizer.php
> In memory cache for supportsDenormalization types

- src/Bridge/Doctrine/EventListener/WriteListener.php
| Fixed tickets | #
| Doc PR        | #
Bridge/Doctrine/EventListener/WriteListener.php doesn't return anything
> Remove wrong doc

- src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DoctrineQueryExtensionPass.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DoctrineQueryExtensionPassTest.php
| Fixed tickets | #1412
Replaces #1413
> Reuse PriorityTaggedServiceTrait from symfony

- src/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php
> Remove an unused var

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/Hydra/Serializer/DocumentationNormalizer.php
> Fix some quality issues

- README.md
We don't use Gitter anymore and we support a lot of other formats than JSON-LD.
> Remove useless badges

- src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DataProviderPass.php
- src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/FilterPass.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/FilterPassTest.php
> Throw on abstract data providers / filters

- features/graphql/query3.feature
> Fix indentation for GraphQL features

- .travis.yml
- features/bootstrap/CoverageContext.php
- features/bootstrap/FeatureContext.php
- features/bootstrap/HydraContext.php
- features/bootstrap/SwaggerContext.php
- features/hydra/docs.feature
- features/main/custom_identifier.feature
- features/main/custom_normalized.feature
- features/main/custom_writable_identifier.feature
- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Fixtures/TestBundle/Entity/RelatedToDummyFriend.php
> Clean Behat tests

- phpstan.neon
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtensionTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Fixtures/TestBundle/Entity/CompositeItem.php
- tests/Fixtures/TestBundle/Entity/CompositeLabel.php
- tests/Fixtures/TestBundle/Entity/CompositeRelation.php
- tests/Fixtures/TestBundle/Entity/DummyFriend.php
- tests/Fixtures/TestBundle/Entity/RelatedDummy.php
- tests/Fixtures/app/bootstrap.php
- tests/Hydra/Serializer/ErrorNormalizerTest.php
- tests/Metadata/Resource/Factory/ExtractorResourceMetadataFactoryTest.php
- tests/Problem/Serializer/ErrorNormalizerTest.php
- tests/Util/IriHelperTest.php
- Remove deprecations
- Remove dead code
- Clean PHPDoc
- Various fixes
> Clean PHPUnit tests

- src/Api/FilterInterface.php
… and where to find them should there be newer ones.
| Tests pass?   | yes well at least I hope
| Doc PR        | https://github.com/api-platform/docs/pull/322
> Document swagger-specific description options

- .php_cs.dist
- src/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProvider.php
- src/DataProvider/ChainCollectionDataProvider.php
- src/DataProvider/ChainItemDataProvider.php
- src/Hal/Serializer/ItemNormalizer.php
- src/Hydra/Serializer/DocumentationNormalizer.php
- tests/Bridge/NelmioApiDoc/Extractor/AnnotationsProvider/ApiPlatformProviderTest.php
- tests/DataProvider/ChainCollectionDataProviderTest.php
> Fix missing return statement

- src/Metadata/Resource/Factory/ShortNameResourceMetadataFactory.php
- tests/Fixtures/FileConfigurations/resourceswithoutnamespace.yml
- tests/Metadata/Resource/Factory/ExtractorResourceMetadataFactoryTest.php
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |yes   |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |
> Add support for resource names without namespace

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
- src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
As of sf 4.0, controllers must be explicitly made public.
> [SF 4.0] Make actions explicitly public

- features/hal/hal.feature
- src/Hal/Serializer/CollectionNormalizer.php
- src/JsonApi/Serializer/CollectionNormalizer.php
- src/Serializer/AbstractCollectionNormalizer.php
- tests/JsonApi/Serializer/CollectionNormalizerTest.php
Try to make SensioLabsInsight happy...
> Create a base collection normalizer

- src/Hydra/Serializer/DocumentationNormalizer.php
- tests/Hydra/Serializer/DocumentationNormalizerTest.php
> Fix owl:allValuesFrom when using IRIs

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php
- src/EventListener/DeserializeListener.php
- src/Hydra/Serializer/DocumentationNormalizer.php
- src/JsonLd/Serializer/ItemNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/Filter/GroupFilter.php
- src/Serializer/Filter/PropertyFilter.php
- src/Serializer/ItemNormalizer.php
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Bridge/NelmioApiDoc/Parser/ApiPlatformParserTest.php
- tests/EventListener/DeserializeListenerTest.php
- tests/Metadata/Property/Factory/SerializerPropertyMetadataFactoryTest.php
- tests/Metadata/Resource/Factory/FileConfigurationMetadataFactoryProvider.php
- tests/Serializer/Filter/GroupFilterTest.php
- tests/Swagger/Serializer/DocumentationNormalizerTest.php
> Replace context keys by constants

- src/Bridge/Graphql/Resolver/CollectionResolverFactory.php
- src/Bridge/Graphql/Resolver/CollectionResolverFactoryInterface.php
- src/Bridge/Graphql/Resolver/ItemResolverFactory.php
- src/Bridge/Graphql/Resolver/ItemResolverFactoryInterface.php
- src/Bridge/Graphql/Type/SchemaBuilder.php
- src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
- tests/Bridge/Graphql/Resolver/CollectionResolverFactoryTest.php
- tests/Bridge/Graphql/Resolver/ItemResolverFactoryTest.php
Use case: take into account serialization groups for example.
> Pass serialization context to GraphQL

- .travis.yml
- phpunit.xml.dist
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Metadata/Extractor/YamlExtractor.php
- tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
- tests/Fixtures/FileConfigurations/resources.yml
- tests/Fixtures/app/config/config.yml
| New feature?  |  no
| Fixed tickets | #1497
> Run Travis with Symfony 4

- README.md
> [docs] Updated link in README.md

- src/Api/FilterInterface.php
| Fixed tickets | ø
So IDEs are happy with the `@see` and we can Ctrl+Click :)
> Update typo in interface

- composer.json
- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/data_provider.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Fixed tickets | #1450
Make the bundle working with autowiring's strict mode (enabled by default in Flex).
> Autowiring strict mode compatibility

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
> Fix disabling of cache pools with the dev environment

- src/Annotation/ApiResource.php
- src/Bridge/Symfony/Routing/ApiLoader.php
- src/Metadata/Extractor/XmlExtractor.php
- src/Metadata/Extractor/YamlExtractor.php
- src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
- src/Metadata/Resource/Factory/ExtractorResourceMetadataFactory.php
- src/Metadata/Resource/ResourceMetadata.php
- src/Metadata/schema/metadata.xsd
- src/Operation/Factory/SubresourceOperationFactory.php
- tests/Fixtures/FileConfigurations/resources.xml
- tests/Fixtures/FileConfigurations/resources.yml
- tests/Fixtures/FileConfigurations/single_resource.yml
- tests/Metadata/Resource/Factory/AnnotationResourceMetadataFactoryTest.php
- tests/Metadata/Resource/Factory/FileConfigurationMetadataFactoryProvider.php
- tests/Metadata/Resource/ResourceMetadataTest.php
- tests/Operation/Factory/SubresourceOperationFactoryTest.php
https://github.com/api-platform/core/pull/1483 should've been merged on 2.1 not on master
Will fix https://github.com/api-platform/api-platform/issues/440
> Backport Fix subresource override operation

- .travis.yml
- behat.yml.dist
> Skip behat postgres tagged features by default

- src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
- src/Graphql/Action/EntrypointAction.php
- src/Graphql/Executor.php
- src/Graphql/ExecutorInterface.php
- src/Graphql/Resolver/AbstractResolverFactory.php
- src/Graphql/Resolver/CollectionResolverFactory.php
- src/Graphql/Resolver/CollectionResolverFactoryInterface.php
- src/Graphql/Resolver/ItemMutationResolverFactory.php
- src/Graphql/Resolver/ItemMutationResolverFactoryInterface.php
- src/Graphql/Resolver/ItemResolverFactory.php
- src/Graphql/Resolver/ItemResolverFactoryInterface.php
- src/Graphql/Type/SchemaBuilder.php
- src/Graphql/Type/SchemaBuilderInterface.php
- tests/Graphql/Action/EntrypointActionTest.php
- tests/Graphql/Resolver/CollectionResolverFactoryTest.php
- tests/Graphql/Resolver/ItemMutationResolverFactoryTest.php
- tests/Graphql/Resolver/ItemResolverFactoryTest.php
- tests/Graphql/Type/SchemaBuilderTest.php
> Move the Grahpql namespace to the root. Switch some internal annots to experimental

- .travis.yml
- behat.yml.dist
- composer.json
- features/integration/nelmio_api_doc.feature
~~**Do not merge yet**.~~
Follows: nelmio/NelmioApiDocBundle#1134
> Fix nelmio

- composer.json
- features/bootstrap/JsonApiContext.php
> Remove JsonSchema 1 support (dev only)

- features/doctrine/date_filter.feature
- features/filter/property_filter.feature
- features/main/crud.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/Dummy.php
- tests/Fixtures/app/config/config_test.yml
> Allow to select nested attributes when using PropertyFilter

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
> Style fixes in EagerLoadingExtension

- .travis.yml
- appveyor.yml
> [2.0] Fix tests

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
> Some code style fixes in EagerLoadingExtension

- src/HttpCache/EventListener/AddHeadersListener.php
> Fix a case typo in HeaderListener

- composer.json
> fix tests, enforce doctrine/orm < 2.6

- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
- src/GraphQl/Resolver/ItemResolver.php
- src/GraphQl/Resolver/ResourceAccessCheckerTrait.php
> GraphQL: pass the operation name to the access checker

- tests/EventListener/AddFormatListenerTest.php
| Fixed tickets | #1631
Alternative to #1631.
> Fix unit tests

- brigade.js
> Fix Coveralls

- src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
- tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php
> Allow to set maximum items per page at operation/resource level

- features/bootstrap/FeatureContext.php
- features/doctrine/date_filter.feature
- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
- tests/Fixtures/TestBundle/Entity/DummyImmutableDate.php
- tests/Fixtures/app/bootstrap.php
- tests/Fixtures/app/config/config_test.yml
> Fix DateFilter for datetime_immutable

- src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
> Prevent the @ApiFilter annotation of triggering deprecation notices

- composer.json
- features/bootstrap/FeatureContext.php
- features/graphql/introspection.feature
- features/graphql/mutation.feature
- features/graphql/query.feature
- features/hal/hal.feature
- features/main/content_negotiation.feature
- features/main/crud.feature
- features/main/default_order.feature
- features/main/relation.feature
- features/security/strong_typing.feature
- features/security/unknown_attributes.feature
- src/GraphQl/Type/Definition/IterableType.php
- src/GraphQl/Type/SchemaBuilder.php
- tests/Fixtures/TestBundle/Entity/Dummy.php
- tests/GraphQl/Type/Definition/IterableTypeTest.php
- tests/GraphQl/Type/SchemaBuilderTest.php
| Fixed tickets | #1576
Add an IterableType to manage for example array types in Doctrine (http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#array-types).
TODO:
> [GraphQL] Iterable type

- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
> bugfix: Add the missing : for DX

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> Fix service declaration deprecation for api_platform.router

- src/Bridge/Symfony/Validator/EventListener/ValidateListener.php
- src/Metadata/Resource/ResourceMetadata.php
- src/Security/EventListener/DenyAccessListener.php
- src/Serializer/SerializerFilterContextBuilder.php
- src/Validator/EventListener/ValidateListener.php
- tests/Metadata/Resource/ResourceMetadataTest.php
https://github.com/api-platform/core/pull/1678 followup 
ping @norkunas
> Simplify some calls to getOperationAttribute

- src/Security/EventListener/DenyAccessListener.php
- tests/Security/EventListener/DenyAccessListenerTest.php
> Implement access_control_message attribute

- src/Documentation/Action/DocumentationAction.php
- src/EventListener/SerializeListener.php
- tests/Documentation/Action/DocumentationActionTest.php
> Fix Swagger.basePath

- src/Documentation/Action/DocumentationAction.php
See nelmio/NelmioApiDocBundle#1225.
> Fix a BC break impacting NelmioApiDoc

- composer.json
> Try to fix the tests (Behatch)

- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
- tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php
> Fix date filter

- tests/GraphQl/Action/EntrypointActionTest.php
> Attempt to fix transient tests

- tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php
> Fix date filter tests with immutable dates

- tests/Bridge/Doctrine/Orm/Filter/DateFilterTest.php
> Adapt tests for the date filter

- src/Bridge/Symfony/Routing/CachedRouteNameResolver.php
> fix route name resolver cache with subresources

- tests/Fixtures/FileConfigurations/parse_exception.yml
The Yaml Parser had a regression, I'll try to contribute a fix to symfony/symfony
> Fix testsuite

- tests/Fixtures/FileConfigurations/parse_exception.yml
> Fix testsuite (2.1)

- features/graphql/mutation.feature
@dunglas this fixes my tests locally
> Bug graphql feature?

- .php_cs.dist
- tests/Annotation/AnnotatedClass.php
- tests/Fixtures/TestBundle/Entity/AbstractDummy.php
- tests/Fixtures/TestBundle/Entity/CircularReference.php
- tests/Fixtures/TestBundle/Entity/Container.php
- tests/Fixtures/TestBundle/Entity/CustomActionDummy.php
- tests/Fixtures/TestBundle/Entity/DummyCar.php
- tests/Fixtures/TestBundle/Entity/DummyTableInheritance.php
- tests/Fixtures/TestBundle/Entity/DummyTableInheritanceRelated.php
- tests/Fixtures/TestBundle/Entity/Foo.php
- tests/Fixtures/TestBundle/Entity/FourthLevel.php
- tests/Fixtures/TestBundle/Entity/JsonldContextDummy.php
- tests/Fixtures/TestBundle/Entity/OverriddenOperationDummy.php
- tests/Fixtures/TestBundle/Entity/RelatedToDummyFriend.php
- tests/Fixtures/TestBundle/Entity/RelationEmbedder.php
- tests/Fixtures/TestBundle/Entity/ThirdLevel.php
> Add the DoctrineAnnotation ruleset to the PHP-CS-Fixer config

- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Filter/DateFilter.php
- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
- src/GraphQl/Resolver/ResourceAccessCheckerTrait.php
- src/GraphQl/Type/Definition/IterableType.php
> Fix some more quality issues

- features/bootstrap/JsonApiContext.php
this was broken accidentally at some point i imagine.
> fix getting value of a node

- phpstan.neon
> Fix PHPStan

- tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
> fixed typo

- behat.yml.dist
- brigade.js
> Fix coverage

- .travis.yml
- behat.yml.dist
- phpunit.xml.dist
- tests/Fixtures/app/AppKernel.php
- tests/Fixtures/app/config/config_test_phpunit.yml
The coverage now takes 10 minutes instead of 15 minutes before.
> Speed-up Travis

- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
> Change default priority on autoconfiguration Doctrine DataProvider extensions

- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
Reverts api-platform/core#1847
> Revert "Change default priority on autoconfiguration Doctrine DataProvider extensions"

- src/Bridge/Symfony/Routing/IriConverter.php
- tests/Bridge/Symfony/Routing/IriConverterTest.php
> Forward operation name in the iri converter

- src/Hal/Serializer/ItemNormalizer.php
- tests/Hal/Serializer/ItemNormalizerTest.php
> use name converter for relations in hal item normalizer

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/hydra.xml
- src/Bridge/Symfony/Routing/IriConverter.php
- src/DataProvider/OperationDataProviderTrait.php
- src/GraphQl/Serializer/ItemNormalizer.php
- src/Hal/Serializer/ItemNormalizer.php
- src/Hydra/Serializer/DocumentationNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Bridge/Symfony/Routing/IriConverterTest.php
- tests/EventListener/ReadListenerTest.php
- tests/GraphQl/Serializer/ItemNormalizerTest.php
- tests/Hal/Serializer/ItemNormalizerTest.php
- tests/Hydra/Serializer/DocumentationNormalizerTest.php
- tests/Hydra/Serializer/ItemNormalizerTest.php
- tests/JsonApi/Serializer/ItemNormalizerTest.php
- tests/Serializer/AbstractItemNormalizerTest.php
- tests/Serializer/ItemNormalizerTest.php
Not easy but I think we're back to square 1 :D
> Merge 2.2 in master

- src/Swagger/Serializer/DocumentationNormalizer.php
> Fixed typos in DocumentationNormalizer.php

- features/bootstrap/JsonContext.php
- features/jsonld/context.feature
- tests/Fixtures/app/AppKernel.php
- tests/Fixtures/app/config/config_test.yml
- tests/Fixtures/app/config/routing.yml
> Make tests green with Symfony 4.1

- src/EventListener/EventPriorities.php
- tests/EventListener/EventPrioritiesTest.php
| Doc PR        | api-platform/doc#489
> Feat: add constants for PRE and POST serialize

- src/Hydra/Serializer/CollectionFiltersNormalizer.php
- src/Hydra/Serializer/PartialCollectionViewNormalizer.php
I found some trait unused into hydra class
> Remove unused trait into Hydra Serializer

- features/main/validation.feature
I was about to comment in #2014 and it was merged meanwhile...
> Remove useless steps after #2014

- src/Operation/Factory/SubresourceOperationFactory.php
- tests/Operation/Factory/SubresourceOperationFactoryTest.php
| Fixed tickets | #1711 
Hey,
I find time to fix the problem with subresource maxDepth. here is a fix + a working test case!
Ask any questions!
> Fix issue #1711 - Subresource Depth bug

- composer.json
| Fixed tickets | #2043, #2047
Temporary use the dev branches of HttpFoundation, until a new tag is created (because symfony/symfony#27714 fixes our test suite).
> Temporary fix for the tests

- src/Bridge/Doctrine/Orm/Filter/ContextAwareFilterInterface.php
> Remove duplicated license header

- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
> Initialize the 'totalCount' property to the default value to 0.0

- appveyor.yml
Simplify the AppVeyor setup a bit.
> Improve the AppVeyor config

- phpstan.neon
- src/DataProvider/OperationDataProviderTrait.php
- src/JsonApi/Serializer/ItemNormalizer.php
- tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
- tests/Bridge/Doctrine/Orm/Util/IdentifierManagerTraitTest.php
- tests/Bridge/Symfony/Routing/IriConverterTest.php
- tests/Fixtures/TestBundle/DataProvider/ContainNonResourceItemDataProvider.php
> Fix PHPStan issues

- features/bootstrap/FeatureContext.php
- features/main/subresource.feature
- src/Serializer/AbstractItemNormalizer.php
- tests/Fixtures/TestBundle/Entity/Greeting.php
- tests/Fixtures/TestBundle/Entity/Person.php
> fix #2073 do not populate subresource inverse side

- src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js
| Fixed tickets | n:a
This feature was broken again because of a Swagger UI update. This really need to be contributed upstream.
> Fix Swagger UI init

- src/Bridge/Symfony/Routing/IriConverter.php
- tests/Bridge/Symfony/Routing/IriConverterTest.php
> improve exeption message

- features/bootstrap/FeatureContext.php
- features/jsonapi/related-resouces-inclusion.feature
- src/JsonApi/Serializer/CollectionNormalizer.php
| Bug fix?      | yes, but the fix is in #2087 
| Tests pass?   | yes once #2087 will be merged
Just add non regression test for #2087
> Remove duplicate data from JSON API include

- composer.json
https://github.com/api-platform/core/pull/2098/files#r202432943
> Inflector as a hard dependency

- .travis.yml
- appveyor.yml
- features/bootstrap/FeatureContext.php
- features/graphql/filters.feature
- features/jsonapi/related-resouces-inclusion.feature
- src/Annotation/AttributesHydratorTrait.php
- src/Bridge/Symfony/Routing/RouteNameGenerator.php
- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- src/GraphQl/Type/SchemaBuilder.php
- src/HttpCache/EventListener/AddTagsListener.php
- src/JsonApi/Serializer/CollectionNormalizer.php
- src/Operation/DashPathSegmentNameGenerator.php
- src/Operation/UnderscorePathSegmentNameGenerator.php
- tests/GraphQl/Type/SchemaBuilderTest.php
- tests/HttpCache/EventListener/AddTagsListenerTest.php
> Merge 2.3 into master

- composer.json
- tests/Fixtures/TestBundle/Controller/CustomActionController.php
- tests/Fixtures/TestBundle/Controller/DummyValidationController.php
- tests/Fixtures/app/config/config_test.yml
| Fixed tickets | #2062
i updated `framework-extra-bundle` and keep 3.x/4.x available
See https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/562 and https://github.com/symfony/symfony/pull/23044
> [Route] Update framework-extra-bundle annotation

- src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
- tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
| Fixed tickets | https://github.com/api-platform/api-platform/issues/767
ping @maaxxicarvalho
> Fix doctrine subresource identifier parameter type detection

- src/DataProvider/OperationDataProviderTrait.php
>  fix #2094 by improving error message

- features/graphql/mutation.feature
- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- src/GraphQl/Type/SchemaBuilder.php
| Fixed tickets | #2093
Fix collection fields not returned when a mutation is done.
> [GraphQL] Fix collection field mutation

- src/Bridge/Doctrine/Orm/Extension/FilterExtension.php
- src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
- src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
- tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
> OrderFilter with nullable relation uses LEFT JOIN fix #2109

- src/DataPersister/ChainDataPersister.php
- tests/DataPersister/ChainDataPersisterTest.php
Reverts api-platform/core#2064
> Revert "fix skipped data persisters on persist"

- tests/Action/ExceptionActionTest.php
See https://ci.appveyor.com/project/dunglas/dunglasapibundle/build/1.0.6261
> Fix a flacky test

- src/Bridge/Symfony/Routing/Router.php
| Fixed tickets | #1006
fixes #1006
> [Router bridge] Keep host context

- src/DataPersister/ChainDataPersister.php
- tests/DataPersister/ChainDataPersisterTest.php
Constistency with persist, see https://github.com/api-platform/docs/issues/540#issuecomment-425410622
> Fix data persister remove stops after 1st match

- .github/PULL_REQUEST_TEMPLATE.md
> Add branch information to the pull request template

- src/Util/RequestAttributesExtractor.php
Allow utility to be used outside internal - https://github.com/api-platform/core/issues/1193#issuecomment-430890223
| Bug fix?      | No
| New feature?  | No
> Remove internal annotation

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
> ApiPlatformExtension cleanup

- composer.json
> Remove a now useless composer hack

- phpstan.neon
- src/Serializer/AbstractItemNormalizer.php
- tests/EventListener/RespondListenerTest.php
- tests/Metadata/Extractor/ExtractorTestCase.php
This PR will allow to bump PHPStan level on master too once #2272 will be merged.
> Bump PHPStan analysis to level 6

- src/Bridge/Symfony/Bundle/Resources/public/graphiql-style.css
> Improve graphiql CSS

- src/Bridge/Symfony/Bundle/DataCollector/RequestDataCollector.php
- tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
Fixes the panel display. Truly sorry about that I probably forgot to push this change after improving the context display by using `profiler_dump()`, actually causing the issue 😞
> [Bugfix] Remove type Error in the Debug Toolbar

- src/JsonLd/ContextBuilderInterface.php
> Remove unnecessary line in phpdoc

- src/GraphQl/Serializer/ItemNormalizer.php
> Remove duplicate header

- src/Api/ExtendedFormatsProviderInterface.php
- src/Api/FormatsProvider.php
- src/Api/OperationAwareFormatsProviderInterface.php
- src/Bridge/Symfony/Bundle/Resources/config/swagger.xml
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Api/FormatsProviderTest.php
- tests/Swagger/Serializer/DocumentationNormalizerTest.php
| Fixed tickets | api-platform/api-platform#886
> Correctly expose overridden formats in Swagger

- .gitignore
- composer.json
- phpstan.neon
- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/JsonEncoder.php
- tests/Action/ExceptionActionTest.php
- tests/Fixtures/TestBundle/Controller/CustomActionController.php
- tests/Fixtures/TestBundle/Controller/CustomController.php
- tests/Fixtures/app/AppKernel.php
- tests/Hal/Serializer/ItemNormalizerTest.php
- tests/JsonApi/Serializer/ItemNormalizerTest.php
- tests/Serializer/AbstractItemNormalizerTest.php
* Make the code compatible with Symfony 4.2
* Remove (most) deprecation warnings
> Symfony 4.2 compatiblity

- .travis.yml
The container-based environment is being removed.
See:
- https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
- https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Remove `sudo: false` from .travis.yml

- composer.json
- features/graphql/introspection.feature
- features/graphql/mutation.feature
- features/graphql/query.feature
- features/hal/collection.feature
- features/hal/max_depth.feature
- features/jsonld/max_depth.feature
- features/main/exposed_state.feature
- features/main/operation.feature
- features/main/relation.feature
- features/main/subresource.feature
- features/main/validation.feature
- phpstan.neon
- src/GraphQl/Action/EntrypointAction.php
- src/GraphQl/Type/SchemaBuilder.php
- tests/GraphQl/Action/EntrypointActionTest.php
- tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
- tests/GraphQl/Resolver/Factory/ItemMutationResolverFactoryTest.php
- tests/GraphQl/Resolver/ItemResolverTest.php
- tests/GraphQl/Resolver/ResourceFieldResolverTest.php
~~waiting for https://github.com/symfony/symfony/pull/29350~~
| Bug fix?      | kind of
Allow the test suite to run normaly.
> Add webonyx/graphql-php version 0.13 compatibility

- .circleci/config.yml
> Fix update-composer in CircleCI configuration

- features/jsonld/context.feature
- src/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php
- tests/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactoryTest.php
- tests/Fixtures/DummyIriWithValidationEntity.php
| Fixed tickets | ~ 
| Doc PR        | https://github.com/api-platform/docs/pull/680
> feat (symfony-validator-bridge): guess IRI from validation constraints

- src/Hydra/Serializer/DocumentationNormalizer.php
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Swagger/Serializer/DocumentationNormalizerTest.php
> Manage advanced name converters for documentation generation

- src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
| Fixed tickets | https://github.com/api-platform/core/pull/2347#issuecomment-448621821
> Improve the detection of MercureBundle

- src/Api/FilterInterface.php
- src/Serializer/Filter/PropertyFilter.php
- tests/Serializer/Filter/PropertyFilterTest.php
| New feature?  | not really
follow up on #2391 that would also add the property filter in the newly supported OpenAPI spec version
> Added OpenAPI description to property filter

- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
> Add support for the status attribute in OpenAPI

- features/openapi/docs.feature
- features/swagger/docs.feature
- src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
- src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php
- src/Documentation/Action/DocumentationAction.php
- tests/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
- tests/Documentation/Action/DocumentationActionTest.php
> OpenAPI: default to v2

- src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js
Currently, the hack to display the current API URL in Swagger UI doesn't work anymore. This PR fixes it.
> Fix init-swagger-ui.js

- src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Fixtures/TestBundle/Entity/InputDto.php
- tests/Fixtures/TestBundle/Entity/OutputDto.php
- tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
> OpenAPI: add support for input and output classes

- src/Bridge/Symfony/Messenger/DataPersister.php
- tests/Bridge/Symfony/Messenger/DataPersisterTest.php
> Messenger: add support for HandledStamp

- src/Swagger/Serializer/DocumentationNormalizer.php
- tests/Swagger/Serializer/DocumentationNormalizerV3Test.php
| New feature?  | ye
| Fixed tickets | #2414
This PR add OpenAPI v3 [Links](https://swagger.io/docs/specification/links/)
I'm not really sure of what is expected in case of composite identifers, but that's a start
> [OpenAPI] Add support for Links

- .travis.yml
This was forgotten in #2408 @dunglas
> Validate exported files against OpenAPI V3

- .travis.yml
- src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
- src/Bridge/Elasticsearch/DataProvider/CollectionDataProvider.php
- src/Bridge/Symfony/Bundle/Resources/config/data_provider.xml
- src/DataProvider/Pagination.php
- src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
- src/JsonApi/EventListener/TransformPaginationParametersListener.php
- tests/Bridge/Doctrine/Orm/Extension/PaginationExtensionTest.php
- tests/Bridge/Elasticsearch/DataProvider/CollectionDataProviderTest.php
- tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
- tests/JsonApi/EventListener/TransformPaginationParametersListenerTest.php
| Fixed tickets | https://github.com/api-platform/core/pull/1999#discussion_r245734689
> Refactoring of the pagination to get ride of HttpFoundation

- src/Hydra/Serializer/CollectionFiltersNormalizer.php
- src/Hydra/Serializer/CollectionNormalizer.php
- src/Serializer/AbstractCollectionNormalizer.php
- tests/Fixtures/Foo.php
- tests/Fixtures/NotAResource.php
- tests/Hydra/Serializer/CollectionFiltersNormalizerTest.php
- tests/Hydra/Serializer/CollectionNormalizerTest.php
| Fixed tickets | possibly related to #1222
We have to support raw collections, since we have already returned `true` in `supportsNormalization` (we have no way to tell).
TODO:
> Fix normalization of raw collections (not API resources)

- src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig
I understand that there is a way to overwrite the twig bundle templates through Symfony but there no block element, proposing to add blocks to allow custom stylesheet and javascript. Let me know if I am thinking wrong.
| Tests pass?   | unkown
> Allow custom stylesheets to be appended or replaced.

- CHANGELOG.md
- src/Bridge/Doctrine/MongoDbOdm/PropertyHelperTrait.php
- src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
- src/Bridge/Doctrine/Orm/Util/EagerLoadingTrait.php
- src/Bridge/Symfony/Routing/RouteNameResolver.php
- src/EventListener/WriteListener.php
- src/Exception/InvalidIdentifierException.php
- src/Identifier/CompositeIdentifierParser.php
- tests/Bridge/Doctrine/Orm/Extension/EagerLoadingExtensionTest.php
- tests/Bridge/Doctrine/Orm/Util/QueryNameGeneratorTest.php
- tests/DataPersister/ChainDataPersisterTest.php
- tests/DataProvider/ChainSubresourcedataProviderTest.php
- tests/Filter/QueryParameterValidateListenerTest.php
- tests/Hydra/Serializer/PartialCollectionViewNormalizerTest.php
- tests/Metadata/Extractor/ExtractorTestCase.php
- tests/Swagger/Serializer/DocumentationNormalizerV2Test.php
- tests/Util/RequestParserTest.php
> Fixed typos

- composer.json
> Fix deps=lowest

- src/Bridge/Symfony/Routing/IriConverter.php
- src/Bridge/Symfony/Routing/Router.php
- tests/Bridge/Symfony/Routing/IriConverterTest.php
- tests/Bridge/Symfony/Routing/RouterTest.php
> Alternative fix to #2298

- src/Api/IdentifiersExtractor.php
- src/Bridge/Doctrine/Common/Filter/RangeFilterTrait.php
- src/Bridge/Doctrine/MongoDbOdm/Filter/RangeFilter.php
- src/Bridge/Doctrine/MongoDbOdm/ItemDataProvider.php
- src/Bridge/Doctrine/MongoDbOdm/PropertyInfo/DoctrineExtractor.php
- src/Bridge/Doctrine/Orm/Filter/RangeFilter.php
> Fix Insight violations

- CHANGELOG.md
- src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
- src/GraphQl/Type/SchemaBuilder.php
- tests/GraphQl/Type/SchemaBuilderTest.php
Fixes a bug introduced by #2492.
> GraphQL: Prevent an error when the type factory is null

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Tests pass?   | waiting for...
> Add autoconfiguration for tag 'api_platform.data_transformer'

- src/Serializer/ItemNormalizer.php
| Fixed tickets | #2537
Fixes broken PR #2538
> Fix normalization output Data Transformer for Json format

- src/JsonApi/Serializer/ItemNormalizer.php
alternative to https://github.com/api-platform/core/issues/2539 
Maybe that a trait would've been better then repeating the code, even though I tried and it's bad because of the inheritance pattern between the normalizers. Ref to https://github.com/api-platform/core/issues/2355 which will definitely improve the code base and maintenance.
> Fix jsonapi datatransformer

- src/Bridge/Symfony/Routing/Router.php
see https://github.com/api-platform/core/pull/2519#pullrequestreview-205805499
> Respect the RouterInterface by using a ResourceNotFoundException

- src/JsonLd/AnonymousContextBuilderInterface.php
- src/JsonLd/ContextBuilder.php
- src/JsonLd/Serializer/JsonLdContextTrait.php
- tests/JsonLd/ContextBuilderTest.php
| Fixed tickets | #2551 
Add tests.
> Test ContextBuilder with anonymous objects

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/hal.xml
- src/Bridge/Symfony/Bundle/Resources/config/jsonapi.xml
- src/Bridge/Symfony/Bundle/Resources/config/metadata/xml.xml
- src/Bridge/Symfony/Bundle/Resources/config/metadata/yaml.xml
To avoid "XML tag has empty body" warnings in IDE
> Cleanup configuration

- src/Metadata/schema/metadata.xsd
- tests/Fixtures/Metadata/schema/invalid.xml
- tests/Fixtures/Metadata/schema/valid.xml
- tests/Metadata/schema/XmlSchemaTest.php
> fix graphql operation xsd

- src/Bridge/Symfony/Messenger/DataPersister.php
- src/DataPersister/ContextAwareDataPersisterInterface.php
- src/EventListener/WriteListener.php
- tests/Bridge/Symfony/Messenger/DataPersisterTest.php
- tests/EventListener/WriteListenerTest.php
Allow messenger attribute by operation.
> Allow per-operation messenger configuration

- src/Bridge/Symfony/Bundle/Resources/config/api.xml
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> Configure formats provider interface autowiring alias

- src/Bridge/Doctrine/MongoDbOdm/Filter/RangeFilter.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/RangeFilterTest.php
| Bug fix?      |     yes
| Fixed tickets | #2595 
> Fix inversion of parameters gte et lte

- features/doctrine/date_filter.feature
- features/doctrine/multiple_filter.feature
- features/doctrine/numeric_filter.feature
- features/doctrine/range_filter.feature
- phpstan.neon
- src/Bridge/Doctrine/Common/Filter/NumericFilterTrait.php
- src/Bridge/Doctrine/Common/Filter/RangeFilterTrait.php
- src/Bridge/Doctrine/MongoDbOdm/Filter/NumericFilter.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/NumericFilterTest.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/RangeFilterTest.php
- tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
- tests/Fixtures/TestBundle/Document/Dummy.php
> [MongoDB] Fix numeric and range filters coercion

- src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
- src/Bridge/Symfony/Bundle/EventListener/SwaggerUiListener.php
- src/Bridge/Symfony/Bundle/Resources/config/routing/api.xml
- src/Bridge/Symfony/Bundle/Resources/config/routing/docs.xml
- src/Bridge/Symfony/Bundle/Resources/config/routing/jsonld.xml
- src/EventListener/AddFormatListener.php
- src/EventListener/ExceptionListener.php
- src/EventListener/RespondListener.php
- src/EventListener/SerializeListener.php
- src/EventListener/WriteListener.php
- src/Util/AttributesExtractor.php
- tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
- tests/EventListener/AddFormatListenerTest.php
- tests/EventListener/DeserializeListenerTest.php
- tests/EventListener/ExceptionListenerTest.php
- tests/Serializer/SerializerFilterContextBuilderTest.php
- tests/Util/RequestAttributesExtractorTest.php
> Make sure listeners are opt-in when not handling API Platform operations

- features/main/input_output.feature
- src/GraphQl/Serializer/ItemNormalizer.php
- src/Hal/Serializer/ItemNormalizer.php
- src/JsonApi/Serializer/ItemNormalizer.php
- src/JsonLd/Serializer/ItemNormalizer.php
- src/Serializer/AbstractItemNormalizer.php
- src/Serializer/ItemNormalizer.php
- tests/Serializer/ItemNormalizerTest.php
| Fixed tickets | https://github.com/api-platform/api-platform/issues/1045
Needs work, just published it so that @phryneas can try.
> WIP: Fix output normalization

- src/GraphQl/Type/SchemaBuilder.php
> Remove unused variable (fix PHPStan build)

- features/jsonld/context.feature
- features/main/input_output.feature
- src/GraphQl/Serializer/ItemNormalizer.php
- src/JsonLd/ContextBuilder.php
- src/JsonLd/Serializer/ItemNormalizer.php
- src/JsonLd/Serializer/JsonLdContextTrait.php
- tests/JsonLd/ContextBuilderTest.php
| Fixed tickets | na 
This fixes the JSON-LD embeded context when using outputs.
> json-ld: correct embeded context

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Fixtures/app/config/config_common.yml
Reverts api-platform/core#2629
See discussion in #2644
> Revert "Do not disable cache in dev"

- phpstan.neon.dist
- src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- src/HttpCache/EventListener/AddHeadersListener.php
- src/Metadata/Property/Factory/InheritedPropertyMetadataFactory.php
- src/Metadata/Property/Factory/InheritedPropertyNameCollectionFactory.php
- src/Metadata/Resource/ResourceNameCollection.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
- tests/Fixtures/app/config/config_common.yml
- tests/HttpCache/EventListener/AddHeadersListenerTest.php
> Merge 2.4 to fix phpstan

- src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
- tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
| Fixed tickets | https://github.com/api-platform/core/issues/2593#issuecomment-476737312
The test was incorrect.
> Don't load graphql services when disabled in config

- src/Swagger/Serializer/DocumentationNormalizer.php
> reuse $baseUrl in computeDoc

- src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php
- src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm_mercure_publisher.xml
- tests/Bridge/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
> publish to mercure using the default format and also respect the entity's serializer context

- src/Bridge/Doctrine/Common/Filter/OrderFilterTrait.php
| Fixed tickets | https://github.com/api-platform/core/pull/2144#discussion_r269624985
/cc @bastnic
> Fix BC break in Doctrine ORM OrderFilter

- src/Annotation/AttributesHydratorTrait.php
- src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
| Fixed tickets | follow up on #2685
> ApiResource attributes default value to null

- CONTRIBUTING.md
Improve the contributing documentation.
> Better contributing documentation

- src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
Issue when 2.4 has been merged.
> [GraphQL] Fix denormalizationContext

- src/Hydra/Serializer/PartialCollectionViewNormalizer.php
> Fix PartialCollectionViewNormalizer for subresources

- src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
- tests/Fixtures/TestBundle/Document/CustomNormalizedDummy.php
- tests/Fixtures/TestBundle/Entity/CustomNormalizedDummy.php
Reverts api-platform/core#1974
See discussion in api-platform/core#1974, specifically https://github.com/api-platform/core/pull/1974#issuecomment-495940604 and https://github.com/api-platform/core/pull/1974#issuecomment-495940684
> Revert "Be more intelligent in determining property writable/readable link."

- .circleci/config.yml
- phpstan.neon.dist
> Add temporary false positives for phpstan
